### ISSUE TITLE
Chunkhash of JS file changes when CSS file is changed

### ISSUE THREAD

**Issue by ustun** [webpack-contrib/extract-text-webpack-plugin#105]
I'm using contenthash for extracting CSS file, and chunkhash for the JS file.

Here is what happens:
- If I change JS file, the CSS file hash does not change, and the name is the same.
- If I change the CSS file, both file hashes for CSS and JS change. I expect only the CSS hash to change.

Is there an equivalent of contenthash to be used for the JS file?

**Comment by farism** [comment]
https://github.com/webpack/webpack/issues/672

**Comment by shanggqm** [comment]
i met the same question, is this issue any progress？

**Comment by e-cloud** [comment]
would it be possible that removing the module from the chunk before hashing the chunk? by removing the the extracted assets, the chunk hashing ought to be identical.

**Comment by bebraw** [comment]
Can you open a new issue with a standalone example to run? Easier to debug.
