### ISSUE TITLE
fix: source maps for various devtool modes

### ISSUE THREAD

**Issue by jeron-diovis** [webpack-contrib/extract-text-webpack-plugin#107]
Webpack has a lot of possible values for `devtool` option: 
http://webpack.github.io/docs/configuration.html#devtool

Some of them are much more preferred in development then just default `source-map` (like `cheap-module-eval-source-map`), due to rebuild speed, for example.

But, this plugin requires exactly `source-map` option to be set to make source maps for css work.
Why?

**Comment by jeron-diovis** [comment]
Anybody alive here?

**Comment by gsklee** [comment]
cc @sokra

**Comment by noradaiko** [comment]
Same here, this is painful.

**Comment by joezimjs** [comment]
In my experience, "source-map" doesn't even work correctly. This is all I see in my source map:

```
{"version":3,"sources":[],"names":[],"mappings":"","file":"app.css","sourceRoot":""}
```

**Comment by albertogasparin** [comment]
+1

**Comment by kensnyder** [comment]
+1

**Comment by GabbeV** [comment]
+1

**Comment by kevinwhoffman** [comment]
It still doesn't appear possible to generate source maps using anything other than `devtool: 'source-map'`. Any update on this?

**Comment by evilebottnawi** [comment]
Closing this issue as duplicate if favor https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/663 (yep this issue older than link, but we have good description and reproducible repo there). We remember about this problem, do not worry.
