### ISSUE TITLE
Extract text doesn't work with multiple CommonsChunk plugins

### ISSUE THREAD

**Issue by adrianca** [webpack-contrib/extract-text-webpack-plugin#109]
Trying to build multiple static vendors bundle + multiple entry points + common entry points logic bundle.
I want to achieve a css file per entry point + common styles bundle.

webpack config:

``` js
var webpackConfig = {
  resolve: {
    alias: {
      'react': 'react/dist/react.min.js', 
      'reflux': 'reflux/src/index.js'
    },
    root: path.join(__dirname, 'src'),
    extensions: ['', '.ts', '.js', '.jsx', '.json', '.scss', '.css']
  },
  entry: {
    vendors: ['react', 'reflux'],
    home: './home.js',
    admin: './admin.js'
  },
  output: {
    path: './assets',
    filename: '[name].js',
  },
  module: {
    loaders: [
      {
        test: /\.js[x]?$/,
        include: path.join(__dirname, 'src'),
        exclude: /node_modules/,
        loaders: ['babel'],
      },
      {
        test: /\.s?css$/,
        include: path.join(__dirname, 'src/client'),
        exclude: /node_modules/,
        loader: ExtractTextPlugin.extract('style-loader', 'css!postcss!sass')
      },
      {
        test: /\.(png|woff|jpg|jpeg|gif|svg)$/,
        include: path.join(__dirname, 'src'),
        exclude: /node_modules/,
        loader: 'url-loader?limit=50000',
      }
    ]
  },
  postcss: [require('autoprefixer-core')()],
  plugins: [
    new ExtractTextPlugin('[name].css', {allChunks:true}),
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendors'
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: 'common',
      chunks: ['home', 'admin']
    }),
  ],
};
```

The result of this is a single `vendors.css` file with common styles shared by the entry points. 

If I remove the `common` CommonsChunkPlugin, then it creates a file per each entry, in addition to the vendors bundle.

Can `ExtractText` not handle multiple CommonChunks ?

**Comment by arturkin** [comment]
Same problem, took me half a day but no luck :(

**Comment by adrianca** [comment]
I ended up using gulp to achieve this and running webpack with it to build the individual bundles. I found that approach to be more manageable and flexible too.

**Comment by arturkin** [comment]
Thanks for sharing, i'm thinking to do the same. Webpack was built for JS bundling, but we want it to bundle HTML/CSS/etc...

**Comment by max-mykhailenko** [comment]
Oh no :( @sokra will you improve this behavior? I need separate css extract for several groups of entries. Maybe you have some advice.

**Comment by borisirota** [comment]
The order of the plugins matters so place the commons before the vendors.

In addition take a look [at this](http://stackoverflow.com/questions/30329337/how-to-bundle-vendor-scripts-separately-and-require-them-as-needed-with-webpack)

**Comment by cchinaka** [comment]
I noticed i applied this to make seperate css files work, as well as capturing all css files in imports - 
```javascript
entry: {
	bundle: "./app/index.js",
	app: "./app/index.js"
},
output: {
	filename: "[name].js",
	path: path.resolve(__dirname, 'app/dist')
},
plugins:[
	new ExtractTextPlugin("[name].css"),\n
	new webpack.optimize.CommonsChunkPlugin({
		name: "vendors",
		minChunks: module => module.context && module.context.indexOf("node_modules") !== -1
	}),
	new webpack.optimize.CommonsChunkPlugin({
		name: 'manifest'
	})
]
```

**Comment by evilebottnawi** [comment]
Seems duplicate https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/58, close here. If you think it is not duplicate feel free to reopen issue, thanks!
