### ISSUE TITLE
TypeError: r.forEach is not a function

### ISSUE THREAD

**Issue by onemanstartup** [webpack-contrib/extract-text-webpack-plugin#110]
Tried every combinations.

``` js
/Users/onemanstartup/Code/awesome/insaneapp/node_modules/webpack/node_modules/webpack-core/lib/LoadersList.js:81
        r.forEach(function(r) {
          ^

TypeError: r.forEach is not a function
  at /Users/onemanstartup/Code/awesome/insaneapp/node_modules/webpack/node_modules/webpack-core/lib/LoadersList.js:81:5
  at Array.reduce (native)
  at LoadersList.match (/Users/onemanstartup/Code/awesome/insaneapp/node_modules/webpack/node_modules/webpack-core/lib/LoadersList.js:80:27)
```

**Comment by xabikos** [comment]
The sane for me here. Even with the simplest configuration.

**Comment by CtrlZvi** [comment]
I ran into this as well, and it turns out that it was because I was using the `loaders` key in my webpack.config.js instead of the `loader` config.

**Comment by xabikos** [comment]
Thank you @CtrlZvi that was the error in my case

**Comment by Cleod9** [comment]
So I ran into this as well when trying to use resolveLoader aliases with this plugin, and the problem seemed to be related to this line here:

https://github.com/webpack/extract-text-webpack-plugin/blob/master/loader.js#L100

I threw some logs there and it seems the possible values for `text` should normally be either a `string` or an `Array`. But for some reason while the chunks are being processed, the first value for `text` is an empty object `{}`. When I added this code before `text.forEach` the problem went away:

```js
if (!text.forEach) {
  text = [];
}
```
Obviously this is not an ideal fix, but maybe someone with more knowledge might now why an empty object would be getting passed this function in the first place?

**Comment by Cleod9** [comment]
I'm going to open up a separate issue actually, since my error message is slightly different:

**New issue:** https://github.com/webpack/extract-text-webpack-plugin/issues/114

**Comment by joshgillies** [comment]
Bitten by this also!

Note: loader **not** loader**s**

ref: #100

**Comment by jpeg729** [comment]
Loaders expects a list, so I tried giving it a list
```js
loaders: [ ExtractTextPlugin.extract('style-loader', sassLoaders.join('!')) ]
```
but then I get
```
ERROR in ./src/styles/app.scss
Module parse failed: /projdir/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!style-loader!css-loader!sass-loader!/projdir/src/styles/app.scss Line 2: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| 
| @import "base.scss";
| 
```
Using ```loader``` works as expected. **Very strange!**

At some point the code makes itself the following list...
```js
[ '/projdir/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}',
  'style-loader',
  'css-loader',
  'sass-loader' ]
```
as though the extract-text plugin's loader part simply gets added to the front of the chain of loaders.

*Wouldn't it be simpler to be able to declare it as such in the config?* ```['extract-text','style','css','sass']``` Of course, we'd also have to declare the plugin part too, in the relevant part of the configuration.

Then again, that might not be possible for reasons unknown to me.

**Comment by sheerun** [comment]
Anyone resolved it?

**Comment by 0x80** [comment]
:+1:  loader / loaders is really easy to mess up!

**Comment by sheerun** [comment]
As for this issue the fix was to change "loaders" to "loader". But after this change I still get similar, but different error: #131 Please help :)

**Comment by pgilad** [comment]
I have a fix for this in terms of better error message here: (as PR)
https://github.com/webpack/webpack/pull/1889

**Comment by petermikitsh** [comment]
'loaders' should still work even if you only supply one... but this is a problem w/ webpack-core

**Comment by gavingolden** [comment]
To eliminate any confusion regarding the *loader* in question
```js
module: {
  loaders: [ // Not talking about this
    { 
      test: /\.css$/, 
      loaders: ['style', 'css'] // !!!! Expects array
    },
    { 
      test: /\.tsx?$/, 
      loader: 'ts-loader' // !!!! Expects single string
    }
  ]
}
```

**Comment by ziyuchengit** [comment]
Thanks @CtrlZvi

**Comment by JetQin** [comment]
```
module.exports = {
    entry:'./src/app.js',
    output:{
        path:'./bin',
        filename:'app.bundle.js'
    },
    module:{
        loaders:[{
            test: /\.js$/,
            exclude: /node_modules/,
            loaders: ['babel-loader']
        }]
    }
};
```
you should check the loaders,is it an array or a string? I meet the same error because of I write like this
```
module.exports = {
    entry:'./src/app.js',
    output:{
        path:'./bin',
        filename:'app.bundle.js'
    },
    module:{
        loaders:[{
            test: /\.js$/,
            exclude: /node_modules/,
            loaders: 'babel-loader'
        }]
    }
};
```

**Comment by KarandikarMihir** [comment]
@CtrlZvi You're a life-saver.

**Comment by charmingmel** [comment]
@gavingolden: Thanks for enlightening one on the distinction.
@JetQin:  Your example was the same as mine. I can see the issue clearly now. Thanks for sharing.


Ideally, one should use: `Array` when using `loaders` and `String` when using `loader`.

**Comment by Couto** [comment]
I just want to add that if you're using Webpack 2 with its new syntax `use` it will also result in problems.
I had to change `use` to `loader` to fix it.

**Comment by njjackzhong** [comment]
I have  the problem,and solve it like this.
 `module.exports = {
    entry:"./entry.js",
    output:{
        path:__dirname,
        filename:"bundle.js"
    },
    module:{
        loaders:[
            {test:/\.css$/,loaders:['style','css']} //expect loader array
           //error : {test:/\.css$/,loaders:"style!css"}
        ]
    }
};`

**Comment by sham-hq** [comment]
Solved. issue is in syntex of my **webpack.config.dev.js** file.

**Comment by scottdj92** [comment]
Closing due to age. If your issue persists, feel free to re-open.

**Comment by MissCuriosity** [comment]
thanks  @Cleod9 
I have this problem too.What you commented on 6 Oct 2015 is exactly why my problem created

**Comment by abhinavsingi** [comment]
I'm using webpack-2 and using `use`, I'm still getting this error.
part of the config:
```{
        test: /\.scss$/,
        exclude: [
          /node_modules/,
          /\.mod\.scss$/,
        ],
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            'dynamic-style-loader',
            {
              loader: 'css-loader',
              options: CSS_LOADER_OPTIONS,
            },
            {
              loader: 'postcss-loader',
              options: POSTCSS_LOADER_OPTIONS,
            },
            {
              loader: 'sass-loader',
              options: SASS_LOADER_OPTIONS,
            },
          ],
        }),
      },```

**Comment by jknight12882** [comment]
I am still getting this issue as well
