### ISSUE TITLE
forEach Error When Using resolveLoader Aliases

### ISSUE THREAD

**Issue by Cleod9** [webpack-contrib/extract-text-webpack-plugin#114]
Was hoping to use a simple alias like this so that I could just `require('sass-extract!./file.scss')` in my code:

``` js
resolveLoader: {
  alias: {
    "sass-extract": sassPlugin.extract("raw-loader!sass-loader")
  }
}
```

But I get the following error:

```
Module build failed: TypeError: Object #<Object> has no method 'forEach'
    at Object.<anonymous> (/Users/...../node_modules/extract-text-webpack-plugin/loader.js:103:11)
```

The problem seemed to be related to this line here:

https://github.com/webpack/extract-text-webpack-plugin/blob/master/loader.js#L100

I threw some logs there and it seems the possible values for `text` should normally be either a `string` or an `Array`. But for some reason while the chunks are being processed, the first value for `text` is an empty object `{}`. When I added this code before `text.forEach` the problem went away:

``` js
if (!text.forEach) {
  text = [];
}
```

Obviously this is not an ideal fix, but maybe someone with more knowledge of this plugin might now why an empty object would be getting passed this function in the first place?

Getting this fixed would be HUGE, I'd happy to submit a PR but would really love some additional insight first.

**Comment by jpeg729** [comment]
You could also try giving it a list in the first place.
```
"sass-extract": [ sassPlugin.extract("raw-loader!sass-loader") ]
```
In other places that can help.

**Comment by Cleod9** [comment]
@jpeg729 No good, same exact error. I can fix it by making that change in `loader.js`, but at this point I'm probably going to just avoid using aliases with this plugin. Feel free to close this if no one is going to look into it

**Comment by bebraw** [comment]
The problem with `"sass-extract": sassPlugin.extract("raw-loader!sass-loader")` is that it invokes `extract`. It's already too late after that for aliasing.

We would have to treat `extract` somehow really differently to make aliasing work. At worst webpack core would need some work.
