### ISSUE TITLE
Plugin overwrites source maps generated by other plugins

### ISSUE THREAD

**Issue by sebald** [webpack-contrib/extract-text-webpack-plugin#119]
I am using `ts-loader` and it generates the correct source maps. But when I add `ExtractTextPlugin` as a plugin somthing goes horribly wrong with the creation of the source maps.

Here is the relevant part of my setup:

``` javascript
module: {
    loaders: [

        // Support for Typescript
        { test: /\.ts$/, loader: 'ts' },

        // Support for Styles (CSS/Sass)
        {
            test:   /\.s(c|a)ss$/,
            loader: ExtractTextPlugin.extract(
                'style',
                `css?sourceMap!sass?sourceMap&includePaths[]=${bourbon.includePaths}`
            )
        }
    ]
},

plugins: [
    new ExtractTextPlugin('style.css', {
        allChunks: true
    })
]
```

With the `ExtraTextPlugin` enabled I get links to the TypeScript source like `test.scss:7`. Which is obviously not really the correct file ;-D If I disable the plugin (via `disable: true`) everything works fine (as long as I am using the `source-map` option).

I also removed the `sourceMap` param from the css and sass loader. But even then the source files are broken. With this setting they link to the compiled JS instead to the TypeScript files.

Did anyone encounter the same problem?

**Comment by sebald** [comment]
I check the generated code and there is actually no TypeScript source map anymore. But Chrome seems to find one!?

**Comment by plopinou** [comment]
I have the same problem using stylus for css and babel with es6.
When I have a js error, it shows that it's in `app.styl:10`
When looking at the map file, the whole chunk referencing the javascript is not there anymore.

Everything's fine if I disable the plugin.

**Comment by cwmoo740** [comment]
Same issue with babel-loader and ExtractTextPlugin. Enabling extract-text outputs this as the sourcemap:

{"version":3,"sources":[],"names":[],"mappings":"","file":"styles.css","sourceRoot":""}

**Comment by lanocturne** [comment]
+1

**Comment by elsigh** [comment]
+1

**Comment by eirikurn** [comment]
+1

**Comment by willemstuursma** [comment]
+1

**Comment by sokra** [comment]
Could you please create a small repro repo so I can test it?

**Comment by elsigh** [comment]
@paulshen and I just did this and discovered that it was our use of `sourceMapFilename` which was the culprit. Makes sense that the CSS source map overwrites the JS one when `sourceMapFilename` doesn't include `[file]` or something to generate a dynamic output name.

**Comment by duncangrist** [comment]
@elsigh - confirmed that was my issue too. Thanks for posting that :+1:

**Comment by jamesthurley** [comment]
Thanks @elsigh, this fixed it for me as well.. I changed `sourceMapFilename: '[name].[chunkhash].map'` to `sourceMapFilename: '[file].map'` and it sorted the problem out.

**Comment by biblesyme** [comment]
+1

**Comment by richdyang** [comment]
+1  confusing!

**Comment by colthreepv** [comment]
This one is _so_ hard to track down on a big webpack config.
I just made [an empty repo](https://github.com/colthreepv/extract-text-plugin-error) to isolate the plugin and I was ready to create an issue :/

It should be big over the README.md

**Comment by tconroy** [comment]
Thank you so much @jamesthurley && @elsigh ! this was indeed the issue and the shared fix worked perfectly for me. Cheers! 🍻

**Comment by scamden** [comment]
omg thank you!!!!!!

**Comment by amitava82** [comment]
wasted few hours on this. Thanks @elsigh

**Comment by chrisvasz** [comment]
More kudos to @elsigh -- that was our issue too!

**Comment by SeunLanLege** [comment]
I still have this issue and none of the above solutions work for me

**Comment by SeunLanLege** [comment]
ok so i fixed it by adding:

```js
...
output: {
    sourceMapFilename: '[file].map'
}
...
```

now it outputs `bundle.js.map` and `index.css.map`

**Comment by dvakatsiienko** [comment]
The same behavior with empty css source map:

`{"version":3,"sources":[],"names":[],"mappings":"","file":"styles.css","sourceRoot":""}`

Happens because of [purifycss-webpack](https://github.com/webpack-contrib/purifycss-webpack) plugin, spent about 30 mins demystifying. Hope it helps someone.

**Comment by liamse** [comment]
Thanks @dvakatsiienko, I have the same problem and after omitting purifycss-webpack (move to  production), problem solved.

**Comment by jkachhia** [comment]
The same behavior with empty css source map:

{"version":3,"sources":[],"names":[],"mappings":"","file":"styles-less.css","sourceRoot":"webpack:///"}

/*# sourceMappingURL=styles-less.css.map*/

Happens because of `angular-router-loader`  plugin.

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
