### ISSUE TITLE
Have to manually include the ouputted css file.

### ISSUE THREAD

**Issue by andrew-w-ross** [webpack-contrib/extract-text-webpack-plugin#127]
Hi I just wanted to ask if I am being stupid. If I use extract text plugin my css is no longer included with my bundle and I now have to include it manually in the page. I assume this is the normal use case.

Is there a way to have the css extracted to a separate file but still loaded by only including the bundle?

**Comment by Levino** [comment]
I personally think this is NOT the correct way to use. But maybe I am mistaken...

**Comment by michael-ciniawsky** [comment]
@andrew-w-ross You can specify two different loader configs, one for CSS that should stay in the bundle and one that gets extracted by `ExtractTextPlugin`

**webpack.config.js**
```js
...
rules: [
  { 
     test: /\.css$/,
     use: [ 'style-loader', 'css-loader' ],
     exclude: 'styles/vendor'
  },
  {
     test: /\.css$/,
     loaders: ExtractTextPlugin.extract({
        fallbackLoader: 'style-loader',
        loaders: [ 'css-loader' ]
    }),
    exclude: 'styles/components'
  }
]
...
plugins: [
   new ExtractTextPlugin('style.css')
]
...
```

What is the usecase here?

**Comment by Levino** [comment]
With this I probably can solve my issue. Thank you.
