### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by sapegin** [webpack-contrib/extract-text-webpack-plugin#128]
Because [it’s important](http://keepachangelog.com/).

**Comment by warrenrumak** [comment]
@sokra genuinely doesn't care about informing people of what he's doing with webpack.  You'll be waiting a long time for this.

**Comment by bebraw** [comment]
@d3viant0ne I guess this will be solved once we get this project to follow the standard structure, right?

**Comment by michael-ciniawsky** [comment]
yep standard version generates a CHANGELOG.md following `git tags` and extract them based on the angular commit convention, so at mininum commits starting from the last (current)  tag must be reworded to follow the convention

**Comment by bebraw** [comment]
@michael-ciniawsky Is it possible to lint PRs against the commit convention? I think that would help a lot.

**Comment by michael-ciniawsky** [comment]
@bebraw https://github.com/marionebl/conventional-changelog-lint [+ https://gitcop.com/]

**Comment by bebraw** [comment]
@michael-ciniawsky 👍 Thanks.

**Comment by d3viant0ne** [comment]
We have a standard setup for this, i'll PR it in shortly. See webpack/webpack#4104

**Comment by evilebottnawi** [comment]
Already fixed [changelog](https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/master/CHANGELOG.md)
