### ISSUE TITLE
Add another maintainer for extract-text-webpack-plugin

### ISSUE THREAD

**Issue by ChrisCinelli** [webpack-contrib/extract-text-webpack-plugin#138]
I think there are a bunch of issue that need to be addressed. 
There are also some pull requests 6+ months old that probably should be merged.
@sokra if you do not have the bandwidth to take care do this, do you mind, do add another maintainer?

**Comment by sokra** [comment]
> @sokra if you do not have the bandwidth to take care do this, do you mind, do add another maintainer?

Do you want to volunteer?

**Comment by bebraw** [comment]
@ChrisCinelli Let me know if you want to pitch in still. We have more active effort going on and we can support more developers.
