### ISSUE TITLE
feat: add logs for debugging and performance monitoring

### ISSUE THREAD

**Issue by ChrisCinelli** [webpack-contrib/extract-text-webpack-plugin#139]
The plugin does not have any debug options to check what the plugin is doing and no way to see how long it takes. I wonder if it is possible to make it a little more verbose with a debug option turned on.

**Comment by evilebottnawi** [comment]
@ChrisCinelli webpack already output all messages what etwp do. Also in v4 webpack will ship with profiling plugins for this purpose. Thanks for issue!
