### ISSUE TITLE
Error when including sass mixin from node_modules (susy sass)

### ISSUE THREAD

**Issue by Kurniawandering** [webpack-contrib/extract-text-webpack-plugin#149]
When I try to import susy from my manifest.scss

```
@import '~susy/sass/susy';

```

I get the following error:

```

Module build failed: CssSyntaxError

```

It is as if the file is not compiled by webpacks sass loader first, when it goes through the ExtractTextPlugin. However, my other scss files are getting compiled corretly. Only this one from the node_modules is giving me error.

My webpack.config looks like this

``` javascript

    module: {
        loaders: [
            {
                test: /\.scss$/,          
                loader: ExtractTextPlugin.extract('style', 'css', 'sass')                
            }
        ]
    }

```

Anyone have an idea about this?

**Comment by tkirill** [comment]
@Kurniawandering Have you tried pass loaders as array?

    module: {
        loaders: [
            {
                test: /\.scss$/,          
                loader: ExtractTextPlugin.extract(['style', 'css', 'sass'])
            }
        ]
    }

**Comment by wolves** [comment]
I am running into this same issue

**Comment by michael-ciniawsky** [comment]
The file extname is missing and therefore the rule in `webpack.config.js` isn't matching, please try again by adding it and feel free to reopen if still any regressions :)

```diff
- @import '~susy/sass/susy';
+ @import '~susy/sass/susy.scss';
``` 

⚠️ Please ensure to have to correct path to the file, since I didn't tested this 😛

**Comment by frankn11** [comment]
I have a similar issue with susy. 
```
ERROR in ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./node_modules/import-glob-loader!./src/scss/main.scss
...
No mixin named container
```

I can't really use any Susy features, but if you're wondering what is my importation:

```
@import '~susy/sass/susy';

$susy: (
  columns: 12,
  container: $maxWidth,
  debug: (image: hide)
);
.container {
  @include container;
}
```
