### ISSUE TITLE
Enable source-maps for extracted text only

### ISSUE THREAD

**Issue by rosenfeld** [webpack-contrib/extract-text-webpack-plugin#152]
When using code splitting, I don't want to use source-maps for lazily loaded code because it uses blobs and this way I wouldn't be able to provide relative paths. I can't set the full public path because the same application may be loaded through two different domains and I would prefer to maintain the same domain when loading images referenced in url()...

Would it be possible to provide some option to enable source-maps only for extracted CSS?

**Comment by michael-ciniawsky** [comment]
The source map is generated by the respective loaders per file/chunk when `{ sourceMap: true }`, tbh I don't know how to tackle this based on the CSS being a asnyc chunk or not

**Comment by michael-ciniawsky** [comment]
ETWP entered maintenance mode and won't receive any feature updates, please open an issue in [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) instead
