### ISSUE TITLE
What is the difference between hash, chunkhash and contenthash?

### ISSUE THREAD

**Issue by ahmed1490** [webpack-contrib/extract-text-webpack-plugin#153]
Also I dont understand what is a chunk. Can this be made clearer in readme as well?

**Comment by sbussard** [comment]
Is no one able to answer this question?

**Comment by Poky85** [comment]
hash is calculated for a build, chunkhash is calculated for chunk (entry file), contenthash is special hash generated in ExtractTextPlugin and is calculated by extracted content, not by whole chunk content

**Comment by PhiLhoSoft** [comment]
The question is good (I had the same), but it is asked at the wrong location: it is a question about Webpack itself, not about this plugin...
Additional references: https://webpack.github.io/docs/code-splitting.html explains chunks (not very clear...), and http://survivejs.com/webpack/building-with-webpack/splitting-bundles/ (and other chapters) can bring more information.

**Comment by coderars** [comment]
It's old, but If anyone came here and still confused, see my answer on Stackoverflow with examples:
https://stackoverflow.com/a/52786672/5263363
