### ISSUE TITLE
Can somebody explain to me what's going here

### ISSUE THREAD

**Issue by t0lkman** [webpack-contrib/extract-text-webpack-plugin#162]
why this syntax is working:

`loader: ExtractTextPlugin.extract('style-loader', 'css-loader!postcss-loader')`

and all vendor prefixes are being added

and this one is not:

loader: ExtractTextPlugin.extract('style-loader', 'css-loader', 'postcss-loader')`

from any documentations available online, I couldn't find why NOT all loaders could be separated by comma

**Comment by Mtnt** [comment]
`ExtractTextPlugin.extract([notExtractLoader], loader, [options])`, did you actually read the documentation? =)

**Comment by ishan28mkip** [comment]
The first parameter is to be used with all the chunks not handled by ExtractTextPlugin, the second parameter specifies the actual loaders.

**Comment by IanVS** [comment]
FWIW, nowhere in the readme does the term `notExtractLoader` appear.

**Comment by Kovensky** [comment]
@IanVS it's now (and has been for the past few months?) called the `fallbackLoader`.

**Comment by IanVS** [comment]
Except for in the example: https://github.com/webpack/extract-text-webpack-plugin/blob/master/example/webpack.config.js#L17

**Comment by bebraw** [comment]
Hi,

The syntax has been updated so it should be a little clearer now.
