### ISSUE TITLE
Option not to save a file?

### ISSUE THREAD

**Issue by wzup** [webpack-contrib/extract-text-webpack-plugin#164]
I use the plugin for React server-site rendering. And I don't actually need to create a file with styles. Is there an option to disable creating and saving a file?

**Comment by PhiLhoSoft** [comment]
Given that the plugin's purpose is to "extract text" to a file, I wonder why you use it at all. Perhaps other plugins or loaders are more suited for your purpose, no?
Or maybe I don't understand your needs (I am only a beginner at Webpack usage). Why do you use it?

**Comment by bebraw** [comment]
Can you expand on your use case? The idea of this plugin is to extract a file. Why to use it otherwise?

**Comment by michael-ciniawsky** [comment]
see @bebraw's comment, anything else is another plugin (fork etc)
