### ISSUE TITLE
Post Processing final extract

### ISSUE THREAD

**Issue by nhavar** [webpack-contrib/extract-text-webpack-plugin#167]
I'm trying unsuccessfully so far to find an example of how to do post processing on the final output of ExtractTextPlugin. After I run webpack ExtractTextPlugin successfully merges all of the CSS into a main.css, but there's still cleanup required (like merging/removing dupes). But I haven't seen any examples of how to achieve this. Piping to !postcss just seems to run those plugins on the individual chunks and not the whole. Has anyone identified a solution for manipulating the output file?

**Comment by Grafikart** [comment]
Got the same problem with mqpacker (to merge media queries) 
At the moment the only solution is to use postcss outside of webpack after the build succeed

**Comment by kisenka** [comment]
@nhavar @Grafikart you can extend extract-text-webpack-plugin and write you own. Take look at [ExtractSVGPlugin](https://github.com/kisenka/svg-sprite-loader/blob/master/lib/extract-svg-plugin.js#L18) which postprocess extracted chunk with wrapping it with `<svg>` tags. Hope that helps.

**Comment by kisenka** [comment]
Related issue https://github.com/webpack/extract-text-webpack-plugin/issues/161

**Comment by bebraw** [comment]
I do this at [purifycss-webpack](https://github.com/webpack-contrib/purifycss-webpack). Please see the plugin for the approach.
