### ISSUE TITLE
Any way to prevent .js file written?

### ISSUE THREAD

**Issue by fairbairn** [webpack-contrib/extract-text-webpack-plugin#175]
We have a simple scenario where we're using webpack to build out a separate global minified .css file from .less that we're using on a large site.

```
    entry: {
        main: ['./app/main'],
        style: ['./theme/react.less'],
        common: Object.keys(require("./package.json").dependencies)
    },
```

..this all works, and we get our .css file created, but in the process it also writes out a style.js file, which we don't seem to need at all.

So two questions, what would  remain in style.js if kept around, and in our case where it doesn't seem to have any value, can we provide an option to ExtractTextPlugin to prevent that style.js from being written at all (along with it's .map file in the event we have source maps enabled?).

We have these loaders...

```
   module: {
        loaders: [
            {
                test: /\.jsx?$/,
                include: path.join(__dirname, 'app'),
                exclude: /node_modules/,
                loaders: ['react-hot', 'babel']
            },
            {
                test: /\.css$/,
                loader: ExtractTextPlugin.extract("style-loader", 'css-loader?' + css_mode)
            },
            {
                test: /\.less$/,
                loader: ExtractTextPlugin.extract("style-loader", 'css-loader?' + css_mode + '!less-loader')
            },

            {test: /\.woff(2)?/, loader: "url-loader?mimetype=application/font-woff"},
            {test: /\.(ttf|eot|svg)/, loader: "url-loader"},
            {test: /\.(png|jpg|gif)/, loader: "url-loader"}
        ]
    },
```

Thanks for the insight!

**Comment by mandx** [comment]
I have the same problem. The only workaround I have found is to **not** include the `*.less` entry in the webpack config and import that `less` file in the main JS entrypoint (in this case that would be the `./app/main.jsx` file).

**Comment by bebraw** [comment]
Related issue, https://github.com/webpack/webpack/issues/1967 .

**Comment by bebraw** [comment]
This is a core issue. Not much we can do here.
