### ISSUE TITLE
How to extract HTML and JS?

### ISSUE THREAD

**Issue by ccorcos** [webpack-contrib/extract-text-webpack-plugin#177]
I had this idea that you should be able to specify html, css, or js as entry points and webpack should just work. Something like this:

``` js
const files = {
  // ex1: two pages to our website
  home: {
    src: './src/index.html',
    dest: 'index.html',
  },
  dashboard: {
    src: './src/dashboard/index.html',
    dest: 'dashboard/index.html'
  },
  // ex2: an npm package we want to publish
  package: {
    src: './src/package.js',
    dest: 'package.js'
  },
  // ex3: some css theme we want to publish
  theme: {
    src: './src/theme.css',
    dest: 'theme.css'
  },
}
```

All other assets get hashed and linked up appropriately.

I've been working on it [here](https://github.com/ccorcos/extract-everything) but I'm having issues. 

My distribution html files end up like this:

``` html
  <link rel="stylesheet" href="[object Object]">
  <script src="[object Object]"></script>
```

Perhaps the `html-loader` does things differently from `css-loader`

I'm also having trouble understanding how the js output works -- webpack complains with no output, but I'm extracting everything with this plugin.

Anyways, I think it would be really cool if webpack was easy as the specifying the entry points. I'd appreciate any help.

**Comment by kisenka** [comment]
The same issue #470

**Comment by evilebottnawi** [comment]
@ccorcos problem still exists?

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
