### ISSUE TITLE
feat: support [path] in output

### ISSUE THREAD

**Issue by resistdesign** [webpack-contrib/extract-text-webpack-plugin#178]
That's it, I just think this plugin should support `[path]` in the output path in case you want to keep your assets where they came from.

**Comment by honchy** [comment]
I just come into the same situation that I would like the css file being generated in another folder

sorry for my poor English

**Comment by michael-ciniawsky** [comment]
ETWP entered maintenance mode and won't receive any feature updates, please open an issue in [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) instead

It's not possible to support anyways :)
