### ISSUE TITLE
Why function extract requires before argument?

### ISSUE THREAD

**Issue by mocheng** [webpack-contrib/extract-text-webpack-plugin#191]
If scss loader is specified as below, it works.

```
ExtractTextPlugin.extract("style-loader", "css-loader!sass-loader");
```

However, if it is as below, it doesn't work.

```
ExtractTextPlugin.extract("style-loader!css-loader!sass-loader");
```

It costs me quite some time to figure out that a `before` argument is necessary to have `{extract: true}` take effect.
https://github.com/webpack/extract-text-webpack-plugin/blob/master/index.js#L128-L141

It would be better to have the API more friendly. I don't understand what ExtractTextPlugin can do if {extract: false} is set.

**Comment by bebraw** [comment]
Hi,

This has been changed. The API should be clearer now. Thanks for the report.
