### ISSUE TITLE
refactor: remove async library

### ISSUE THREAD

**Issue by jimmywarting** [webpack-contrib/extract-text-webpack-plugin#193]
I only see [one place](https://github.com/webpack/extract-text-webpack-plugin/blob/a5996652713ce9804575993b45cbae8dbbdfcf1a/index.js#L237) where async is being used that it feels idiotic to include a such large lib just for that, it also adds a dependency of other...

I would suggest implementing that small pice of code yourself preferable by using [Array.prototype@@iterator()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/@@iterator)

**Comment by bebraw** [comment]
Hi,

We can accept a PR for this. Either a lighter dep or what you described would work.

**Comment by insin** [comment]
Does `async.forEach()` run in parallel?

I usually reach for one of the versions someone has extracted if I need those, e.g. https://github.com/feross/run-parallel

**Comment by bebraw** [comment]
If I'm reading right, that could be written as a regular `forEach`. There's nothing async going on.

**Comment by insin** [comment]
I was assuming `compilation.rebuildModule(module, function(err) {` is async due to the errback.

**Comment by bebraw** [comment]
Ah, yeah. I missed that. Good point.

**Comment by bebraw** [comment]
That errback handling is a little weird, though, as it doesn't pass `err` further to terminate. It does just `compilation.errors.push(err);`.
