### ISSUE TITLE
Above the Fold CSS (Critical CSS)

### ISSUE THREAD

**Issue by mjsisley** [webpack-contrib/extract-text-webpack-plugin#194]
Is there an established way to have (criticalCSS) above the fold CSS placed inline in the html file and the rest in a separate CSS file? 

Isomorphic does this for templating done in React templating. But what if templating is done outside of javascript?

I could run the output of extract-text-webpack-plugin through another build tool, but was wondering if it exists within the webpack ecosystem.

**Comment by psimyn** [comment]
Same question as https://github.com/webpack/extract-text-webpack-plugin/issues/187 ?

**Comment by bebraw** [comment]
Let's close in favor of #187. Better discuss there.
