### ISSUE TITLE
problem of filename of extract stylesheets file

### ISSUE THREAD

**Issue by cesiya23** [webpack-contrib/extract-text-webpack-plugin#197]
``` javascript

var ExtractTextPlugin = require('extract-text-webpack-plugin');
var config = {
  entry: './app/app.js',
  output: {
    publicPath: '/app/',
    path: './build/app/',
    filename: 'js/bundle.js',
    chunkFilename: 'js/[name].chunk.js?[hash]'
  },
  module: {
    loaders: [
      {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract('style-loader', 'css-loader!autoprefixer?{browsers:["last 2 version"]}!sass-loader')
      }
      // ... 
    ]
  }
  plugins: [
    new ExtractTextPlugin('css/[name].css');
  ]
}
```

My stylesheets file : style.scss

Why the file name of stylesheet file is 'main.css' , not 'style.css' ????

**Comment by bebraw** [comment]
Can you add your `entry` configuration?

**Comment by cesiya23** [comment]
@bebraw I have update the issue with entry and output

**Comment by bebraw** [comment]
I guess you are referring to the CSS at `./app/app.js` then. If you wanted `style.css`, you could set up an entry like this:

```javascript
entry: {
  main: './app/app.js',
  style: [... paths to your css ...]
}
```

This should generate what you expect.

**Comment by cesiya23** [comment]
@bebraw In this case you adviced, how to assign different filename for multipule entries?
 `filename: [name].js` will generate files named `style.js` and `main.js`.
How can I generate a file named `style.css`

**Comment by bebraw** [comment]
You can discard the `style.js` it generates. That `'css/[name].css'` postion at `ExtractTextPlugin` generates the CSS file you want (`css/style.css`). That entry configuration is needed to get that `name` right.

**Comment by cesiya23** [comment]
@bebraw Thanks a lot.

 I have just tried to  replace `new ExtractTextPlugin('css/[name].css')` with `new ExtractTextPlugin('css/style.css', {allChunks: true})`, and this works successfully.

I don't know why `css/[name].css` does not generate `app.css`.

All of my stylesheets are imported into `app.scss` finally.

**Comment by bebraw** [comment]
> I don't know why css/[name].css does not generate app.css (actually it generated main.css).

That might have to do with your entry configuration. Instead of `main: './app/app.js',` you could try `app: './app/app.js',` since that key maps to `[name]`.

**Comment by cesiya23** [comment]
@bebraw 
```
entry: './app/app.js',
...,
new ExtractTextPlugin('css/[name].css')
``` 

This leads to `css/main.css`.

Is that to say webpack will change one-point-entry into `entry: {main: filename}` ?

And stylesheets will extend this name of entry `main`, which finally leads to `css/main.css` ?

**Comment by bebraw** [comment]
> Is that to say webpack will change one-point-entry into entry: {main: filename} ?

Yeah, I think it defaults to `main` by default. So if you want control over the resulting name, use the object syntax instead.

> All [name] actually means the name of entry ?

It figures out the output `[name]` based on the entry name, yup.

**Comment by cesiya23** [comment]
@bebraw Thanks a lot :)
