### ISSUE TITLE
Add timestamp to generated comment in stub module (behind an option flag?)

### ISSUE THREAD

**Issue by ddelbondio** [webpack-contrib/extract-text-webpack-plugin#20]
I am trying to get HMR working for css files generated by the plugin. I have a solution which isn't the most prettiest, but which would work if the generated stub module would be marked in as changed in the HMR frontend. The easiest solution i can think of there is actually modifying the stub module by adding the current timestamp to the generated comment. If there is another solution even better :)

**Comment by carlosepp** [comment]
@ddelbondio any success on getting HMR work with ExtractTextPlugin, if so could you share your implementation, this would be the holly grail of a better front-end workflow, @sokra any update on this?

Thanks in advance :pray:

**Comment by michael-ciniawsky** [comment]
HMR will not be supported by this plugin in te near future since it's sole purpose it to extract css files when running webpack in production mode
