### ISSUE TITLE
How can I keep the css order in the css file when I use extract-text-webpack-plugin？

### ISSUE THREAD

**Issue by cage1618** [webpack-contrib/extract-text-webpack-plugin#200]
How can I keep the css order in the css file when I use extract-text-webpack-plugin？

```
// app.js
import '../scss/index.scss';
import AnComponent from './components/AnComponent/index';
```

```
// ./components/AnComponent/index.js
import './src/scss/index.scss';

export default class AnComponent Component {
    render() {
        return (
            <div class="component">
               I am a example component
            </div>
        );
    }
}
```

```
// ../scss/index.scss
body{
    background-color:red;
}
```

```
// ./components/AnComponent/src/scss/index.scss
body{
    background-color:green;
}
```

How can ensure `./scss/index.scss` is before `./components/AnComponent/src/scss/index.scss` in the output css file when I use extract-text-webpack-plugin?

**Comment by FabioAntunes** [comment]
Same problem here, my sass file:
```sass
$icon-font-path: "~bootstrap-sass/assets/fonts/bootstrap/";
@import "~bootstrap-sass/assets/stylesheets/bootstrap";
@import "~angular-ui-grid/ui-grid.css";
@import "~angular-ui-select/select.css";
@import "~startbootstrap-sb-admin-2/dist/css/sb-admin-2.css";
@import "dashboard";
@import "editable-grid";
@import "flash-msgs";
@import "manual-link";
@import "popular";
@import "product-list";
@import "sidebar";
@import "slider";
@import "widgets";
```

My webpack config:
```javascript
{
      test: /\.scss$/,
      loader: ExtractTextPlugin.extract('style-loader', 'css-loader?sourceMap!postcss-loader!sass?sourceMap')
}
```

And then on my browser:
![screenshot from 2016-08-05 10 49 03](https://cloud.githubusercontent.com/assets/2544673/17433052/6c124914-5afa-11e6-9fb1-6bae77d33f88.png)


Note: _panels.scss is a bootstrap component

**Comment by Kovensky** [comment]
Try doing your order-dependent imports in JS, or adding the `@import`s inside the files that actually depend on those files happening before them. AFAIK, webpack doesn't care about the order dependencies appear in, since the ordering is enforced by the order `require` calls are encountered; but that has issues with CSS, as it doesn't have a "runtime" order.

Doing as many imports in JS as possible also should help with incremental build performance.

**Comment by VincyLouis** [comment]
I have a workaround but wasn't pretty...
```
const extractLibStyle = new ExtractTextPlugin("[name].lib.[hash].css");
const extractProjectStyle = new ExtractTextPlugin("[name].[hash].css");
```
```
module: {
        loaders: [ { ... }, {
            test: /\.(css|scss|sass)$/,
            loader: extractLibStyle.extract("style-loader", "css-loader!sass-loader?sourceMap"),
            include: [path.resolve(ROOT, "bower_components/"), path.resolve(ROOT, "node_modules/")],
            exclude: path.resolve(ROOT, "app/")
        }, {
            test: /\.(css|scss|sass)$/,
            loader: extractUserStyle.extract("style-loader", "css-loader?localIdentName=[folder]__[local]&modules&importLoaders=1!postcss-loader!sass-loader?sourceMap"),
            include: path.resolve(ROOT, "app/"),
            exclude: [path.resolve(ROOT, "bower_components/"), path.resolve(ROOT, "node_modules/"), path.resolve(ROOT, "build/")]
        }, { ... } ]
    }
}
```
```
plugins: [
        extractLibStyle,
        extractProjectStyle,
]
```
So library styling will come first before my project styling, by using this approach...
**Pro**
 - able to seperate out two styling into two file
 - absolute control of which stylesheet being extracted and insert into `<head>` tag, even if I purposely require the bower file after my project file like this
```
// app.js
require("../stylesheets/main.scss");
require("~/bower_components/mdi/scss/materialdesignicons.scss");
```
output:
```
<!-- index.html -->
<link href="/app.lib.6c157af1e450e9782aca.css" rel="stylesheet">
<link href="/app.6c157af1e450e9782aca.css" rel="stylesheet">
```
**Con** is
 - there is a lot of writing going on...
 - more http request, this might be a concern to some people...

Still, hope there is an option to control the order

**Comment by jhnns** [comment]
The order of the extracted text is based on the order of `require()` calls inside the bundle. If you want to ensure that the output of `index.scss` is before all the other rules, you need to `require("./index.scss")` before requiring all the components.

**Comment by nlitwin** [comment]
@jhnns I can get the ordering to work properly if I follow your instructions and put `require('./index.scss')` before requiring other components, but if I remove `{ "modules": false }` from my `.babelrc`'s es2015 preset, the ordering is wrong again. Any idea on why that would cause it to change?

**Comment by jhnns** [comment]
`require()` and `import()` are very different constructs. `require()` is a regular function and will always execute in the given order. `import()` is not a function, but syntactic sugar for a native language feature. ES2015 will hoist all imports and resolve them **before** any code is executed. And babel emulates that behavior by first hoisting all imports and then turning them into `require()`. That's why your other components will be required first when you remove `"modules": false`.

**Comment by wen96** [comment]
Same issue as @FabioAntunes. It sames like, when you `@import` from `.css` and `SASS` files, it keep order between `css` and `scss` but not both together. For example:


```
// main.scss

// It works
@import "../../node_modules/bootstrap/dist/css/bootstrap.css";
@import "../../node_modules/admin-lte/dist/css/AdminLTE.css";

// Wrong order
@import "../../node_modules/bootstrap-sass/assets/stylesheets/bootstrap";
@import "../../node_modules/admin-lte/dist/css/AdminLTE.css";
```

@FabioAntunes have you find any solution to this?

**Comment by FabioAntunes** [comment]
@wen96 Not really, I had to re-write the rules on my scss, fortunately they were just a couple, which might not be your case.

**Comment by Gtosta96** [comment]
someone have solutions for this one?

**Comment by secondstreetmedia** [comment]
It's difficult to tell from the code snippets posted above if this will help others, but my issue was that I only had ***some*** of my styling related loaders utilizing the **`extract-text-webpack-plugin`** rather than ***all*** of them. Once I ensured all of them utilized the plugin, my styles were loading consistently in the order I wanted them to, at least in development. (See my more detailed response here: https://github.com/webpack/webpack/issues/215)

**config** (original)

    {
      test: /\.css$/,
      use: ['style-loader', 'css-loader']
    },
    {
      test: /\.*(sass|scss)$/,
      use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: ['css-loader', 'sass-loader']
      })
    },

**config** (revised)

    {
      test: /\.css$/,
      use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: ['css-loader']
      })
    },
    {
      test: /\.*(sass|scss)$/,
      use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: ['css-loader', 'sass-loader']
      })
    },

**Comment by bebraw** [comment]
Can someone provide a standalone example illustrating this issue? That would help a lot. Thanks.

**Comment by GitSage** [comment]
I had the same issue as @wen96: load order isn't respected with mixed css and scss.

**Comment by julmot** [comment]
@bebraw You can reproduce it in my repository [here](https://github.com/julmot/form-components/blob/v0.1.0/src/components/_common/index.js#L1-L2). The normalize.css is generated after the other required components.

Relative issues I've found:
- https://github.com/webpack/webpack/issues/1343
- https://github.com/babel/babel/issues/2061
- https://github.com/webpack/webpack/issues/215

**Comment by FelschR** [comment]
I'm using `@import`s in my css files (without using CSS modules) and I'm experiencing this issue.
Moving the imports to js didn't change anything about that.

Is this really still and issue? Am I missing something?

**Comment by evilebottnawi** [comment]
@FelschR bug exists, feel free to PR

**Comment by pbarbiero** [comment]
This started happening for me with webpack 3.11.0, 3.10.0 does NOT exhibit this issue.

**Comment by gtournie** [comment]
@vincent-louis I did the same but I used the `file-merge-webpack-plugin` to get only css file at the end (it messes up the source map tho...)

This is a real issue in my case. I import Bootstrap via css-modules (with reactstrap) and have also some custom stylesheets:
```
import bs from 'bootstrap'
import styles from './styles'
[...]
  <div styleName="bs.bg-primary styles.bg"></div>
```
For now there is no way to ensure that all bootstrap styles will be placed first. The only workaround is to use 2 ExtractTextWebpackPlugin instances and to generate 2 css files.

It would be nice to have a priority option, like:
```
{ test: ..., loader: ExtractTextPlugin.extract({ use: ..., priority: 1 }) }, // Bootstrap
{ test: ..., loader: ExtractTextPlugin.extract({ use: ..., priority: 2 }) }, // App
```

**Comment by sherlock1982** [comment]
Started to happen for me in Webpack 4.0.1.

**Comment by th3fallen** [comment]
im still getting this on 3.0.2 anyone know a fix for it, it is maddening

**Comment by pboos** [comment]
Just upgraded to Webpack 4.1.1 and this is happening to me it seems.

Strange thing: It changes the order depending on the build. Sometimes it is ok. Sometimes it is wrong. So ordering seems random?

**Comment by sherlock1982** [comment]
I swtiched to mini-css-extract-plugin and the order is ok now. Looks like extract-text-webpack-plugin will be left for Webpack3

**Comment by pboos** [comment]
As @sherlock1982 said, extract-text-webpack-plugin is for webpack3 and older (will not support webpack 4 it seems). They say to move to mini-css-extract-plugin.

For more information see here: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/701#issuecomment-374551300

**Comment by luojianet** [comment]
use `extract-text-webpack-plugin` webpack plugin.

write like this, can not keep css order.
```
import "../css/normalize.css";
import "../css/animate.css";
import "../css/style.css";
```
----------------------splite line----------------------
* you can write like this.
```
import "../css/first.css";
```
```first.css
@import url(normalize.css);
@import url(animate.css);
@import url(style.css);
```

**Comment by julmot** [comment]
Could fix it finally by switching to https://github.com/webpack-contrib/mini-css-extract-plugin

**Comment by evilebottnawi** [comment]
@julmot PR welcome

**Comment by x-yuri** [comment]
I can't reproduce it. See [this post][1].

[1]: https://github.com/webpack/webpack/issues/215#issuecomment-422092704

**Comment by zacherkkila** [comment]
I am able to get this problem anytime I have a "." in the file name. This seems to push it to the bottom of the import list

For example

    @import "./bootstrap.min.css";
    @import "./common.css"

Results in `common.css` above `bootstrap.css` on import.

However,

    @import "./bootstrap.css";
    @import "./common.css"

Results in the correct order. 

I can consistenly make this happen just by having a ".something" in the filename

    @import "./test.awesome.css";
    @import "./common.css"

and

    @import "./test.css";
    @import "./common.css"

Yields the same result

I just renamed the files in my program but that would be a place to look

**Comment by x-yuri** [comment]
@zacherkkila I tried to reproduce it but [failed](https://github.com/x-yuri/example-webpack-css-order/tree/double-extension) (branch `double-extension`). Can you help us figure out how to reproduce it? Like, an archive or repository with an example (preferably simple) that reproduces the issue?

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
