### ISSUE TITLE
Extract text plugin with code splitting

### ISSUE THREAD

**Issue by toddw** [webpack-contrib/extract-text-webpack-plugin#208]
When I'm using code splitting via `require.ensure` is it possible to get .css files generated from those chunks? Even though I'm using the extract text plugin, it seems like the stylesheets are getting embedded in the chunks created from `require.ensure`

**Comment by cage1618** [comment]
I have the same issue

**Comment by Kovensky** [comment]
Give the `allChunks: true` option to the `ExtractTextPlugin` instance. But then it'll pull the CSS from all chunks for the entry points it works on, even if you want to preserve it in some of them...

**Comment by cage1618** [comment]
I already give allChunks options, But it still don't work for me !

**Comment by Tom910** [comment]
Yes, some problem

**Comment by damassi** [comment]
@sokra, does this fix here: https://github.com/webpack/webpack/issues/2450 apply to Webpack 1 as well? Or do I need to upgrade my app?

**Comment by whitecolor** [comment]
@sokra can be accomplished somehow currently?

**Comment by coreylarson** [comment]
Same desire here.

**Comment by george3447** [comment]
+1

**Comment by matheusml** [comment]
+1

**Comment by fhqdgv** [comment]
Same desire here. wii support?

**Comment by NogsMPLS** [comment]
Running into the same problem. I'd really *really* like to be able to do something like:

```javascript
require.ensure([], function (require) {
    require('./someFile.css');
}, 'chunkName')
```

And have it output a css file.

**Comment by michael-ciniawsky** [comment]
This feature request continues in #455 :)
