### ISSUE TITLE
load sass and can't resolve the file of @import

### ISSUE THREAD

**Issue by Pines-Cheng** [webpack-contrib/extract-text-webpack-plugin#209]
I use this plugin to loader sass,the part of config is below:

```
plugins:
new ExtractTextPlugin('css/index.[contenthash].css', {
            allChunks: true
        })
loaders:
{
            test: /\.scss$/,
            exclude: /node_modules/,
            loader: ExtractTextPlugin.extract( "style-loader","css-loader","sass-loader") //注意loader和laoders的区别
        }
```

and  I meet a error.

```
ERROR in ./~/css-loader!./css/common.scss
    Module not found: Error: Cannot resolve 'file' or 'directory' ./variables in /Users/spider/Work/ydh/git/yy-ydh-agent-pc-kill/css
     @ ./~/css-loader!./css/common.scss 3:10-72

    ERROR in ./~/css-loader!./css/common.scss
    Module not found: Error: Cannot resolve 'file' or 'directory' ./normalize in /Users/spider/Work/ydh/git/yy-ydh-agent-pc-kill/css
     @ ./~/css-loader!./css/common.scss 5:10-72
..... 
.....
.....
```

It sames that the loader can't resolve the @import in the common.scss

```
@import "variables";
@import "mixins";
```

and I don't why.

**Comment by Pines-Cheng** [comment]
fine ,It takes me almost half a day to resolve this problem .at last ,I found the solution,

it is just change the line of `loader: ExtractTextPlugin.extract( "style-loader","css-loader","sass-loader") ` to `loader: ExtractTextPlugin.extract('style','css!sass')`

ok ,It looks easy ,aha ,but I still not know why.

Is someone  can explain it?

**Comment by zallek** [comment]
Thank you so much :)

**Comment by Kovensky** [comment]
`ExtractTextPlugin.extract` doesn't take a list of loaders in its `arguments`, but a stylesheet-loading loader (almost always `style-loader`) and a stylesheet-producing loader (`css!sass` in your case; could also have been `['css', 'sass']`).

**Comment by tylik1** [comment]
@Pines-Cheng i'm using the same method but my mixins are not working. They are outputted in destination css file, the same way i defined them in mixin.scss.  Does it work for you. If so, could you please share webpack.config.js. Thanks!
