### ISSUE TITLE
Duplicates entries appended to webpack records on each build

### ISSUE THREAD

**Issue by wbobeirne** [webpack-contrib/extract-text-webpack-plugin#217]
I've got a webpack records file as a part of my config, and since I rolled CSS compilation in to my webpack config, I'm finding that the following snippet of code gets appended to the "extract-text-wepack-plugin" array in my records.json file every time I build, even if there is no change (I'm up to about 75 of these in there):

```
diff --git a/cupid/okcontent/flat/js/webpack.records.json b/cupid/okcontent/flat/js/webpack.records.json
index 3ca8b7e..eeaaf80 100644
--- a/cupid/okcontent/flat/js/webpack.records.json
+++ b/cupid/okcontent/flat/js/webpack.records.json
@@ -1908,6 +1908,20 @@
         "byName": {},
         "byBlocks": {}
       }
+    },
+    {
+      "nextFreeModuleId": 2,
+      "modules": {
+        "byIdentifier": {
+          "node_modules/css-loader/index.js!node_modules/sass-loader/index.js!css/mycss.scss": 0,
+          "node_modules/css-loader/lib/css-base.js": 1
+        }
+      },
+      "nextFreeChunkId": 1,
+      "chunks": {
+        "byName": {},
+        "byBlocks": {}
+      }
```

The relevant parts of my webpack config are as follows:

```
return {
  plugins: [
    new StyleLintPlugin({
      configFile: cssDir + "/.stylelint.yml",
      syntax: "scss",
      context: cssDir,
    }),
    new ExtractTextPlugin("../css/[name]" + min + ".css"),
  ],

  loaders: [
    // ES6
    {
      test: /\.jsx?$/,
      loader: "babel",
    },
    // SCSS
    {
      test: /\.scss$/,
      include: [
        cssDir,
      ],
      loader: ExtractTextPlugin.extract(["css", "sass"]),
    },
  ],

  sassLoader: {
    includePaths: [
      cssDir,
    ]
    .concat(bourbon.includePaths)
    .concat(neat.includePaths)
  },

  recordsPath: path.join(jsBuildPath, "webpack.records.json"),
}
```

**Comment by francoisromain** [comment]
I had the same kind of problem, and I solved it setting the `allChunks` option to `true`. 

`new ExtractTextPlugin('css/styles.css', { allChunks: true })`

The doc says: _options.allChunks: boolean extract from all additional chunks too (by default it extracts only from the initial chunk(s))_

I don't really understand what this means though. What are _additional_ chunks vs _initial_ chunks ?

**Comment by wbobeirne** [comment]
Hmmm, that option did not fix this for me. But I'm also not entirely sure what that flag means either.

**Comment by stipsan** [comment]
Hey, I had this problem as well.

I solved it by adding an id to the plugin, like this:
```js
new ExtractTextPlugin('style', 'css/styles.css', { allChunks: true })
```
I discovered this option when reading the API docs here https://github.com/webpack/extract-text-webpack-plugin/blob/webpack-1/README.md#api
Since it says it automatically generates the id by default I thought it was worth trying to make it static to see if that resolved the problem 😄

**Comment by wbobeirne** [comment]
This didn't appear to work for me, and it might be because I output one css file per entry point, so I use `[name]` in my output file. I tried putting `[name]` as the ID, but that didn't work either.

**Comment by wbobeirne** [comment]
I can confirm that this is still happening in Webpack 2, using version 2.0.0-beta4. Had hoped it would have gone away with all of the changes in there.

**Comment by pawelpabich** [comment]
Setting `allchunks` to `true` fixed it for me.

**Comment by evilebottnawi** [comment]
@wbobeirne @francoisromain @stipsan can you provide minimum reproducible test repo?

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
