### ISSUE TITLE
How to extract specific async chunk style file?

### ISSUE THREAD

**Issue by JounQin** [webpack-contrib/extract-text-webpack-plugin#219]
For example, I don't want the bootstrap.css loaded in every page, and I use the bootstrap module and import it in some chunk module.

If I set the allChunks option to false, the styles of chunks will be bundled in the _chunk.js_ file. So, is there anyway to extract it to another .css file?

Actually I found out a solution:

``` javascript
const extractBootstrap = new ExtractTextPlugin('bootstrap', 'bootstrap.[contenthash].css', {allChunks: true});

const [first, ...rest] = lessLoaders;

webpackConfig.module.loaders.push({
    test: /bootstrap\.less$/,
    loader: extractBootstrap.extract(first, rest.join('!'))
  });

webpackConfig.plugins.push(extractBootstrap);
```

However, it still will be included in the index.html automatically. : (

Hoping for your help, thx!

**Comment by scottdj92** [comment]
Closing due to age. If your issue persists, feel free to re-open.
