### ISSUE TITLE
No Hot Module Replacement

### ISSUE THREAD

**Issue by baby2011** [webpack-contrib/extract-text-webpack-plugin#222]
Is there any solutions to resolve the problem?

**Comment by justo** [comment]
In the readme it says that is one of the caveats of this plugin 😞

**Comment by FabioAntunes** [comment]
I want separate files when I build, but I don't need them necessarily when I'm developing so what I did was adding this:

```javascript
const ENV = process.env.npm_lifecycle_event;
const isProd = ENV === 'build';
const ccsLoaderSettings = 'css-loader?sourceMap!postcss-loader!sass?sourceMap';

{
      test: /\.scss$/,
      loader: isProd ? ExtractTextPlugin.extract('style-loader', ccsLoaderSettings) : 'style-loader!' + ccsLoaderSettings
},

```

This way the HMR for my sass and css works

**Comment by evillemez** [comment]
If you are passing any sort of environment variable to webpack when you run it, you can use that to disable the plugin while in development.  For example, in my `webpack.config.js`, I have this:

```js

//...
module: {
  rules: [
          { test: /\.scss$/, loader: ExtractTextPlugin.extract({loader: 'css-loader!postcss-loader!sass-loader', fallbackLoader: 'style-loader'}), exclude: /node_modules/ },

  ]
}
//...
plugins: [
//...
    new ExtractTextPlugin({
      filename: '[name].css',
      disable: 'development' === process.env.NODE_ENV
    }),

//...
```
Thus, in development, the plugin is disabled and falls back to just using the style loader.  But, in production, the template is expecting to find a stylesheet it can import.  Your `index.html` will need to know not to try and load the stylesheet if it's in dev too though.

**Comment by bebraw** [comment]
See https://github.com/webpack/extract-text-webpack-plugin/pull/89 .

**Comment by shepherdwind** [comment]
I just write a loader([css-hot-loader](https://github.com/shepherdwind/css-hot-loader)), which supprot hot module replacement for an extracted css file.

If you don't want use style-loader, maybe you should have a try.

**Comment by scottdj92** [comment]
Closing due to age. If your issue persists, feel free to re-open.
