### ISSUE TITLE
SASS loader & ExtractTextPlugin 2.0.0: Cannot read property 'node_modules/extract-text-webpack-plugin' of null

### ISSUE THREAD

**Issue by ranchoX** [webpack-contrib/extract-text-webpack-plugin#226]
The same with #211 , but my extract-text-webpack-plugin version is 2.0.0-beta.3.
`
0 active/node_modules/loader-runner/lib/LoaderRunner.js:90 throw e;
TypeError: Cannot read property '/node_modules/extract-text-webpack-plugin' of null
    at /node_modules/extract-text-webpack-plugin/index.js:257:27
    at /node_modules/webpack/lib/Compilation.js:462:4
    at Array.forEach (native)
    at callback (/node_modules/webpack/lib/Compilation.js:461:14)
    at Compilation.<anonymous> (/node_modules/webpack/lib/Compilation.js:482:4)
    at /node_modules/webpack/lib/Compilation.js:326:10
    at /node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/node_modules/async/lib/async.js:209:22)
    at Compilation.addModuleDependencies (/node_modules/webpack/lib/Compilation.js:192:8)
    at Compilation.processModuleDependencies (/node_modules/webpack/lib/Compilation.js:177:7)
    at Compilation.<anonymous> (/node_modules/webpack/lib/Compilation.js:469:8)
`

**Comment by thenoseman** [comment]
Same here when used in the context of Angular2@beta:

When using this demo component:
````
import { Component } from "@angular/core";

@Component({
  selector: "another-component",
  template: require("./another.component.pug"),
  styles: [ require("./another.component.scss") ]
})
export class AnotherComponent {
  title = "Tour of Heroes!";
}
````
The resulting bundle looks like this (only the relevant parts):
```
var AnotherComponent = (function () {
    function AnotherComponent() {
        this.title = "Tour of Heroes!";
    }
    AnotherComponent = __decorate([
        __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_0__angular_core__["Component"])({
            selector: "another-component",
            template: __webpack_require__(502),
            styles: [__webpack_require__(500)]
        }), 
        __metadata('design:paramtypes', [])
    ], AnotherComponent);
    return AnotherComponent;
}());
```

Note the ``styles`` require which is id 500:
```
/***/ 500:
/***/ function(module, exports) {

// removed by extract-text-webpack-plugin

/***/ },
```

When I patch ``loader.js#39`` to look like this it works:
```
		var resultSource;
		if(query.remove) {
			resultSource = "// removed by extract-text-webpack-plugin\nmodule.exports='';";
		} else {
			resultSource = undefined;
		}
```

Angular2 at least requires the `styles` options to returns a array of strings.

Don't know if that helps.

Cheers,
Frank

**Comment by ranchoX** [comment]
i had found the reason.
my file-loader
`
 {
            test: /\.png|jpe?g|ico|bmp|gif$/,
            loader: "file-loader?name=imgs/[name]-[hash].[ext]"
        }
`
 is not work.
and my css has
`
body{
background:url(bg.png)
}
`
so have error
`
{ ModuleBuildError: Module build failed: ModuleParseError: Module parse failed: bg.png Unexpected character '�'
`

perhaps ExtractText try parse bg.png file.

**Comment by anorudes** [comment]
+1 i have the same problem

**Comment by derpoho** [comment]
+1 Same here

**Comment by rpoitras** [comment]
I have the same problem with 2.1.0-beta.20.  It was working on another machine.  So it may be a newer version of some other lib.  I'm still using '^'s everywhere in my package.json.

```
building modules 1114/1114 modules 0 active/home/rpoitras/dev/components-material-ui/node_modules/loader-runner/lib/LoaderRunner.js:104                                                                                                                        
                if(isError) throw e;
                            ^

TypeError: Cannot read property '/home/rpoitras/dev/components-material-ui/node_modules/extract-text-webpack-plugin' of null
    at /home/rpoitras/dev/components-material-ui/node_modules/extract-text-webpack-plugin/index.js:257:27
    at /home/rpoitras/dev/components-material-ui/node_modules/webpack/lib/Compilation.js:462:4
    at Array.forEach (native)
    at callback (/home/rpoitras/dev/components-material-ui/node_modules/webpack/lib/Compilation.js:461:14)
    at Compilation.<anonymous> (/home/rpoitras/dev/components-material-ui/node_modules/webpack/lib/Compilation.js:482:4)
    at /home/rpoitras/dev/components-material-ui/node_modules/webpack/lib/Compilation.js:326:10
    at /home/rpoitras/dev/components-material-ui/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/home/rpoitras/dev/components-material-ui/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/home/rpoitras/dev/components-material-ui/node_modules/async/lib/async.js:209:22)
    at Compilation.addModuleDependencies (/home/rpoitras/dev/components-material-ui/node_modules/webpack/lib/Compilation.js:192:8)
    at Compilation.processModuleDependencies (/home/rpoitras/dev/components-material-ui/node_modules/webpack/lib/Compilation.js:177:7)
    at Compilation.<anonymous> (/home/rpoitras/dev/components-material-ui/node_modules/webpack/lib/Compilation.js:469:8)
    at /home/rpoitras/dev/components-material-ui/node_modules/webpack/lib/Compilation.js:124:4
    at Array.forEach (native)
    at callback (/home/rpoitras/dev/components-material-ui/node_modules/webpack/lib/Compilation.js:123:12)
    at /home/rpoitras/dev/components-material-ui/node_modules/webpack/lib/Compilation.js:147:10
    at setError (/home/rpoitras/dev/components-material-ui/node_modules/webpack/lib/NormalModule.js:214:3)
    at /home/rpoitras/dev/components-material-ui/node_modules/webpack/lib/NormalModule.js:178:18
    at /home/rpoitras/dev/components-material-ui/node_modules/webpack/lib/NormalModule.js:137:11
    at /home/rpoitras/dev/components-material-ui/node_modules/loader-runner/lib/LoaderRunner.js:328:11
    at /home/rpoitras/dev/components-material-ui/node_modules/loader-runner/lib/LoaderRunner.js:150:20
    at context.callback (/home/rpoitras/dev/components-material-ui/node_modules/loader-runner/lib/LoaderRunner.js:87:13)
    at Object.<anonymous> (/home/rpoitras/dev/components-material-ui/node_modules/extract-text-webpack-plugin/loader.js:89:12)
    at Compiler.<anonymous> (/home/rpoitras/dev/components-material-ui/node_modules/webpack/lib/Compiler.js:251:10)
    at /home/rpoitras/dev/components-material-ui/node_modules/webpack/lib/Compiler.js:442:12
    at next (/home/rpoitras/dev/components-material-ui/node_modules/tapable/lib/Tapable.js:81:11)
    at Compiler.<anonymous> (/home/rpoitras/dev/components-material-ui/node_modules/extract-text-webpack-plugin/loader.js:82:4)
    at next (/home/rpoitras/dev/components-material-ui/node_modules/tapable/lib/Tapable.js:83:14)
    at Compiler.<anonymous> (/home/rpoitras/dev/components-material-ui/node_modules/webpack/lib/CachePlugin.js:61:4)
    at Compiler.applyPluginsAsync (/home/rpoitras/dev/components-material-ui/node_modules/tapable/lib/Tapable.js:85:13)
```
webpack.config.js
```
const path = require('path')
const webpack = require('webpack')
const validate = require('webpack-validator')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const ExtractTextPlugin = require('extract-text-webpack-plugin')

const PATHS = {
  app: './app/index.js',
  html: './app/index.html',
  lib: './lib/index.js',
  src: path.join(__dirname, 'app'),
  libDir: path.join(__dirname, 'lib'),
  dist: path.join(__dirname, 'dist'),
  routes: path.join(__dirname, 'app/routes'),
  eslintrc: path.join(__dirname, './.eslintrc')
}

const HtmlWebpackPluginConfig = new HtmlWebpackPlugin({
  template: PATHS.html,
  filename: 'index.html',
  inject: 'body'
})

module.exports = env => {
  return validate({
    entry: {
      hmr: [
        'webpack-dev-server/client?http://localhost:4000',
        'webpack/hot/only-dev-server'
      ],
      js: PATHS.app,
      route: PATHS.routes + '/routes',
      lib: PATHS.lib,
      vendor: [
        'react', 'react-router', 'react-dom', 'material-ui', 'babel-polyfill'
      ]
    },
    output: {
      filename: '[name].bundle.js',
      chunkFilename: '[id].bundle.js',
      path: PATHS.dist,
      publicPath: env.prod ? '/' : 'http://localhost:4000/dist/',
      pathinfo: !env.prod
    },
    context: __dirname,
    devtool: env.prod ? 'eval' : 'inline-source-map',
    bail: env.prod,
    externals: {
      'cheerio': 'window',
      'react/lib/ExecutionEnvironment': true,
      'react/lib/ReactContext': true
    },
    module: {
      loaders: [
        {
          test: /(\.js|\.jsx)$/,
          exclude: /node_modules/,
          loaders: ['react-hot', 'babel?presets[]=react,presets[]=es2015,presets[]=stage-0', 'eslint']
        },
        {
          test: /(\.scss|\.css)$/,
          loader: ExtractTextPlugin.extract({
            fallbackLoader: 'style-loader',
            loader: ['css', 'sass']
          })
        }
      ]
    },
    plugins: [
      HtmlWebpackPluginConfig,
      new webpack.optimize.CommonsChunkPlugin({
        name: 'vendor',
        minChunks: Infinity,
        filename: 'vendor.bundle.js'
      }),
      new ExtractTextPlugin({
        filename: '[name].[id].style.css',
        allChunks: false
      })
    ],
    devServer: {
      contentBase: PATHS.dist,
      port: 4000,
      historyApiFallback: true
    }
  })
}
```

**Comment by rpoitras** [comment]
Also I do *not* have any images in .css or .scss

**Comment by Kovensky** [comment]
That error... doesn't make much sense o_O

The code crashes on the last line of this simplified snippet:

```js
var meta = module.meta && module.meta[NS];
if (meta && ...) {
  ...
  compilation.rebuildModule(module, function (err) {
    meta = module.meta[NS];
```

The second time `module.meta[NS]` is only reachable if `module.meta[NS]` was successfully read from before, and that can only happen if `module.meta` is an object; but you are seeing the crash because, inside `rebuildModule`, `module.meta` is suddenly `null`.

I wonder if the sass-loader is mistakenly resetting the `module.meta`?

**Comment by joyychang** [comment]
I found out I was running node 4 when this happened. I reinstalled everything with node 6+npm 3 and it all went back to working.

**Comment by tleunen** [comment]
I had the same issue when I forgot to remove the style loader from the "loader" property, so make sure to remove it to only keep it as a "fallback".

**Comment by Kovensky** [comment]
It looks like the callback to `compilation.rebuildModule` is not receiving an error value when there is an error in the compilation. After encountering this issue, I could determine that, when `module.meta[NS]` was, for some reason, suddenly `null`, `module.errors` was not empty and had compilation errors from previous loaders.

**Comment by as-com** [comment]
For some reason, the following commands fixed the issue for me:
```sh
rm -rf node_modules
npm i
npm dedupe
```

**Comment by guilhermechiara** [comment]
I'm having the same issue.. When I try to load font-awesome, it doesn't work:

My vendor.scss file:
`//# Bootstrap CSS
@import '../../node_modules/bootstrap/dist/css/bootstrap.min.css';

//# Font-Awesome
@import '../../node_modules/font-awesome/css/font-awesome.min.css';`

When I comment the font-awesome import line, it works.. I checked the folder and everything is there.. So, I don't know whats happening..

**Comment by jaylaw81** [comment]
The issue i found with the same error message, was that ExtractTextPlugin did not like SASS / CSS rules that looked like this

errored
```css
width: (1 / 3 * 100)%;
```

errored
```css
width: calc(1 / 3 * 100)%;
```

ok
```css
width: 33.33333%;
```

**Comment by reupen** [comment]
I can confirm @Kovensky's findings. 

I used the node-inspector to debug webpack and set a breakpoint at `extract-text-webpack-plugin/index.js:257`. `module.errors` was indeed not empty when there was a problem with module.meta. 

In my case it was a combination of missing packages (url-loader/file-loader) and invalid paths in `url(...)` values in some of the (S)CSS. Fixing those problems got everything working.

**Comment by rpoitras** [comment]
@Kovensky that's interesting at the time I don't think I had `url-loader` as a devDependency. If I can a chance I try this again and see if that helps.  It may help others that are still stuck if you could post your package.json and webpack.config.js.

@as-com I'm pretty sure `npm` does the `dedupe` by default as of version 3.0

**Comment by as-com** [comment]
@rpoitras `npm dedupe` was still able to remove and symlink some packages.

**Comment by rpoitras** [comment]
Thanks @as-com that's good to know.

**Comment by bebraw** [comment]
@Kovensky Safe to close?

**Comment by bebraw** [comment]
Let's close.
