### ISSUE TITLE
Rename `ExtractTextPlugin` to `ExtractCssPlugin` for webpack@2

### ISSUE THREAD

**Issue by nodkz** [webpack-contrib/extract-text-webpack-plugin#230]
I suggest for webpack v2 create a separate module for extracting css to files. Rather than create 2.0.0 version for `ExtractTextPlugin` and get tons of questions (why my old config does not works, why I got `Chunk.entry was removed. Use hasRuntime()` error and others).

By the way `ExtractCssPlugin` is a more obvious name for such kind of plugin.

**Comment by nodkz** [comment]
Cross issues:
https://github.com/webpack/webpack/issues/2764#issuecomment-232371501
https://github.com/webpack/extract-text-webpack-plugin/issues/210
https://github.com/Hashnode/mern-starter/issues/200

About unclear naming, I can cite as an example my first thoughts:
- hm, will styles work with them?
- is this exactly better solution? maybe exist another plugin?
- what else it can extract, except styles?

**Comment by valmirjunior0088** [comment]
I would also suggest renaming the npm module name to "webpack-plugin-extract-text", or "webpack-plugin-extract-css" as to follow naming conventions followed by other packages.

**Comment by bebraw** [comment]
I think the main argument for the current name is that the plugin can do more than extract just CSS. Extracting HTML is another use case although the readme doesn't advertise this.

**Comment by bebraw** [comment]
This change isn't going to happen.
