### ISSUE TITLE
Not working with postCSS

### ISSUE THREAD

**Issue by MoeSattler** [webpack-contrib/extract-text-webpack-plugin#231]
it does not work with postcss. I don't get any error messages, it just doesn't output a bundle. 

``` javascript
{
   test: /\.p?css/, loader: ExtractTextPlugin.extract({fallbackLoader: 'style-loader', loader: 'style-loader!css-loader!postcss-loader'}),
}
```

Versions:

``` JavaScript
    "webpack": "2.1.0-beta.20",
    "extract-text-webpack-plugin": "2.0.0-beta.3",
    "postcss": "^5.1.2",
    "postcss-loader": "^0.10.0",
    "css-loader": "0.23.1",
    "style-loader": "0.13.1",
```

**Comment by Kovensky** [comment]
Sounds like the same issue as #218

**Comment by agileago** [comment]
it is the same with me. anyone solve it?

**Comment by monolithed** [comment]
Having the same problem

**Comment by abouthiroppy** [comment]
This works for me(extract-text-webpack-plugin@2.0.0-beta.4, webpack@2.1.0-beta.25)
```
{
  loader: ExtractTextPlugin.extract({
    fallbackLoader: 'style',
    loader: [{
      loader: 'css',
      query: {
        modules       : true,
        localIdentName: '[path]___[name]__[local]___[hash:base64:5]'
      }
    }, {
      loader: 'postcss',
      query: {
        sourceMap: 'inline'
      }
    }]
  })
}
```

**Comment by monolithed** [comment]
There's another solution:

```
[
	{
		test: /\.css$/,
		loader: ExtractTextPlugin.extract('style', 'css?importLoaders=1&-autoprefixer!postcss')
	}
]
```

**Comment by QuantumInformation** [comment]
I tried this https://github.com/postcss/postcss-loader/issues/144

**Comment by QuantumInformation** [comment]
@monolithed how would you write it if you use .pcss file extensions?

**Comment by monolithed** [comment]
> how would you write it if you use .pcss file extensions?
```
test: /\.pcss$/,
```

**Comment by QuantumInformation** [comment]
I made an issue here:
https://github.com/webpack/webpack/issues/3414

**Comment by bebraw** [comment]
Can you try against rc0? Note that you need to go with `use` instead of `loader` when extracting.

@MoeSattler Would you mind setting up a demo project if that fails?

**Comment by MoeSattler** [comment]
@bebraw due to the problems with postCSS and extract-text-webpack-plugin we moved to other solutions (namely styled-components). I am not sure if this is still an issue.

**Comment by QuantumInformation** [comment]
@bebraw I'll try it later today.

**Comment by QuantumInformation** [comment]
this worked fine: )

https://github.com/quantumjs/solar-popup/blob/master/webpack.config.js#L30
