### ISSUE TITLE
Disable caching per module

### ISSUE THREAD

**Issue by arasmussen** [webpack-contrib/extract-text-webpack-plugin#233]
I override some CSS per entry like so:

``` javascript
// main.js
window.__widget__ = false;
require('component.js');
```

``` javascript
// widget.js
window.__widget__ = true;
require('component.js');
```

``` javascript
// component.js
require('main.css');
if (__widget__) {
  require('widget.css');
}
```

Where my entries are main and widget. This works great when I don't use ExtractTextPlugin. However, once I use ExtractTextPlugin, my widget CSS shows up in my main bundle...

I'm guessing this is because which CSS files are associated with a JS file is being cached somewhere? Not completely sure. Any ideas?

**Comment by Kovensky** [comment]
`require` is specified to only execute modules once. That this happened to work at all in your first try sounds more like a bug, unless you are making completely separate builds; if you are, you should never include them in the same page, as the two webpack runtimes would silently conflict with each other.

webpack does conditional requires through constant propagation. It has no way of knowing that `__widget__` is not changed by, say, `require('main.css')`, or any other code in the page, so it has to assume `require('widget.css')` can run, and in the case of ExtractTextPlugin, it has to assume that it _will_ run.

You have to either use `DefinePlugin` to define `__widget__` to `true` or `false` (where they become "real constants" that can be used to eliminate the `if`'s body), or just better separate your code.

**Comment by arasmussen** [comment]
> That this happened to work at all in your first try sounds more like a bug, unless you are making completely separate builds

In this case `main` and `widget` are two separate entries so they are separate builds if I understand correctly. The problem with DefinePlugin is you cannot specify a different constant for different entries... Separating the code isn't a great option because they're the exact same JS components with additional styling.

I'll keep thinking / looking and report back if I find a good solution. Any ideas you have would be appreciated!

**Comment by evilebottnawi** [comment]
@arasmussen problems still exists? Can we close issue?

**Comment by arasmussen** [comment]
Not sure, feel free to close though
