### ISSUE TITLE
Possibility to disable css source maps

### ISSUE THREAD

**Issue by VladShcherbin** [webpack-contrib/extract-text-webpack-plugin#235]
I'm using webpack with config:

``` js
module.exports = {
  devtool: 'hidden-source-map',
  ...
  module: {
    loaders: [
      {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract({
          loader: ['css?minimize', 'postcss', 'sass?{precision:10}'],
          publicPath: '/static/'
        })
      }
    ]
  },
  postcss: [autoprefixer({ browsers: ['last 2 versions'] })]
}
```

Source map is created automatically, but I don't need it. Besides, produced `css` file has no path for source map in it and produced source map is useless:

``` css
{"version":3,"sources":[],"names":[],"mappings":"","file":"css/file.css","sourceRoot":""}
```

Is there an option to disable its creation?

**Comment by jiayihu** [comment]
I was able to disable sourcemaps for CSS files using `devtool: false`, whereas `nosources-source-map` had the same problem.

**Comment by michael-ciniawsky** [comment]
This is an issue we will fix soon within `css-loader` PR is [here](https://github.com/webpack-contrib/css-loader/pull/478)

**Comment by mnpenner** [comment]
@evilebottnawi But I *want* them off because the [sourcemaps don't work anyways](https://stackoverflow.com/q/49330996/65387).
