### ISSUE TITLE
Add attribute to `link` tag?

### ISSUE THREAD

**Issue by FezVrasta** [webpack-contrib/extract-text-webpack-plugin#240]
I need to define a `data-id` attribute on the `link` tags created by this loader, is it possible?

I'd look for a syntax like `require('./test.css?dataId=foobar')` which would output:

```
<link href="assets/test.css" data-id="foobar" />
```

**Comment by scottdj92** [comment]
Closing due to age. If your issue persists, feel free to re-open.

**Comment by FezVrasta** [comment]
I don't see why you should close an issue just because you never replied to it, do as you want.

**Comment by scottdj92** [comment]
Apologies. I was cleaning up the older issues. As far as I know, I don't think there's support for something like this. Could there be a different loader that does what you're trying to do?

**Comment by FezVrasta** [comment]
I wasn't able to find one and I think it would be quite useful.

**Comment by scottdj92** [comment]
Sure @sokra are there plans to support this?

**Comment by rogyvoje** [comment]
It would be a very good enhancement, example would be if I want to access some stylesheet with JavaScript and add some new rules to it, and I would like to be able to attach at least an id attrubute to that **link** tag

something like this:

```
new ExtractTextPlugin({ id: 'some-id-i-want-to-see-when-extracted',  filename: 'page.css' });
```

and then output would be:

```
<link href="page.css" rel="stylesheet" id="some-id-i-want-to-see-when-extracted">
```

**Comment by michael-ciniawsky** [comment]
I'm confused by this request since ETWP doesn't add a link tag anywhere, it's sole purpose is to extract the CSS from the bundle and emit a CSS file. It's up to the user to reference the CSS file via a `<link id="1" data-id="1" href="path/to/extracted.css">` in the HTML. It's out of scope for this plugin to load the HTML file and parse it and add the links. Feel free to reopen in case I missed something :)

**Comment by rogyvoje** [comment]
@michael-ciniawsky yeah you are right, it was my mistake, this should be considered inside this library [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin)

I got confused with all these libraries for webpack 😄
