### ISSUE TITLE
Option to not emit the CSS files

### ISSUE THREAD

**Issue by bensampaio** [webpack-contrib/extract-text-webpack-plugin#247]
Would it be possible to add an option to not emit the generated CSS? The reason I ask this is because I have a React app with client and server rendering. For the client I need all assets to be emitted but for the server I only need the JS files to be emitted.

I tried to use the `css-loader/locals`loader (as mentioned [here](https://github.com/webpack/css-loader/issues/59)) but I came across the problem I mentioned [here](https://github.com/webpack/css-loader/issues/333). I don't know what the correct solution would be, but for now not emitting the CSS files would fix my problem. Although that might not be the most performant solution...

**Comment by antwan1986** [comment]
Good shout; I've the same requirement. I output two code bundles in my particular use case, and only want the plugin to run on one of them:

```
    entry: {
        'core': './src/components/core/scripts/index.js',
        'core.min': './src/components/core/scripts/index.js'
    },
    module: {
        loaders: [
            {
                test: /\.scss$/,
                exclude: /(node_modules|bower_components)/,
                loader: ExtractTextPlugin.extract('css!postcss!sass')
            }
        ]
    },
    plugins: [
        new ExtractTextPlugin('css/[name].css', {
            allChunks: true
        }),
        new webpack.optimize.UglifyJsPlugin({
            include: /\.min\.js$/,
            compress: {
                'drop_console': false,
                'drop_debugger': false,
                'warnings': false
            }
        })
    ],
```

Ideally there was some regex option like the UglifyJS plugin has, to skip over particular bundles via their name.

**Comment by michael-ciniawsky** [comment]
Would an ENV variable solve this ? It basically negates the whole purpose of this plugin and adding therefore adding it as an options to the plugin isn't a good idea imho

```
use: ENV === 'server' ? [...loaders] :  ExtractTextPlugin. extract(...)
```

It basically negates the whole purpose of this plugin and therefore changing anything within the plugin itself isn't a good idea imho. This is better solve on webpack config level somehow
