### ISSUE TITLE
feat: replace content with path to the extracted file

### ISSUE THREAD

**Issue by donaldpipowitch** [webpack-contrib/extract-text-webpack-plugin#268]
Hello, this is more a feature request instead of a bug.

**Goal**

Instead of removing imported styles directly the path to the extracted files should be inserted.

**Use case**

I want to develop web components which are easy to consume by others. Say I have a complicated webpack config to load styles (e.g. Less, Sass, Stylus or something more exotic, process this with post-css with several plugins and so on...), but others shouldn't need to know about my config. They should just require my app which references the compiled and extracted css file.

**Example**

Say I've set `new ExtractTextWebpackPlugin('style.css')`.  Instead of having this:

```
/***/ },
/* 1 */
/***/ function(module, exports) {

// removed by extract-text-webpack-plugin

/***/ },
```

I'd like to have this:

```
/***/ },
/* 1 */
/***/ function(module, exports) {

module.exports = "style.css";

/***/ },
```

**Comment by Yona-Appletree** [comment]
I'm doing a dynamic css loading thing as well, and I have the same problem. I need to know the name of the extracted file as a return value from require(), like the file-loader-plugin works.

**Comment by vinpac** [comment]
I need this too for my universal app. Maybe a query param could be defined to return the result filename.

`new ExtractTextWebpackPlugin('static/css/[name].[contenthash:8].css]', { exportFilename: true })`

```
function(module, exports) {
     module.exports = 'static/css/main.65468796.css'
}
```

**Comment by michael-ciniawsky** [comment]
The `module.exports = 'path/to/extracted.css'` would be needed I guess or could this be a comment aswell to minify it away in production ?

**Comment by evilebottnawi** [comment]
@donaldpipowitch @Yona-Appletree @vinpac friendly ping

**Comment by michael-ciniawsky** [comment]
ETWP entered maintenance mode and won't receive any feature updates, please open an issue in [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) instead
