### ISSUE TITLE
No way to combine less and sass in one css.

### ISSUE THREAD

**Issue by trsh** [webpack-contrib/extract-text-webpack-plugin#271]
I have adminLTE styles written in sass, and then some of our company written styles in sass. I want combine those in same outputs css. How could I do that?

**Comment by trsh** [comment]
My setup: 

```
entry: {
      'polyfills': './src/common/bundles/polyfills.browser.ts',
      'vendor':    './src/common/bundles/vendor.browser.ts',
      'index':     [
        './src/index/bundles/main/main.browser.ts',
        './src/index/themes/admin-lte/adminlte.pack.less',
        './src/index/themes/default/styles/combine.pack.scss'
      ]
    },
```

```
module: {
      loaders: [
        {
          test: /\.pack.less$/,
          exclude: /node_modules/,
          loaders: ExtractTextPlugin.extract({ loader: ['raw-loader', 'less-loader'] })
        },
        {
          test: /\.pack.scss$/,
          exclude: /node_modules/,
          loaders: ExtractTextPlugin.extract({ loader: ['raw-loader', 'sass-loader'] })
        }
      ]
    },
```

```
plugins: [
      new ExtractTextPlugin({
        filename: 'assets/css/[name].css?[hash]-[chunkhash]-[contenthash]'
      }),
```

And it always just includes styles from less. :/

**Comment by jamelt** [comment]
Try using the style loader.

**Comment by bebraw** [comment]
I think you could pull this off using a post-process plugin. It would have to pick up the initially generated files, concat as you like, and emit a new one. I've done something related at [purify plugin](https://github.com/webpack-contrib/purifycss-webpack) and you may want to study it to understand the technical side better.

ExtractTextPlugin doesn't support this behavior itself.
