### ISSUE TITLE
Relative paths to CSS in HTML files on github.io point to wrong location

### ISSUE THREAD

**Issue by Nearoo** [webpack-contrib/extract-text-webpack-plugin#279]
I can't get couscous to work properly, possibly because _I_ am doing something wrong. Testing a project locally using `couscous preview` works fine, but putting it online using `couscous deploy` doesn't - the links to the css files at the top of my html page are faulty. Instead of pointing to `/my-project/css/cssfile.css`, they point to `/css/cssfile.css/`, which results in my page loading without any styling information at all.

**Comment by SpaceK33z** [comment]
Do you still have this issue? If so, you'll need to provide way more information. A repository reproducing the issue would be nice.
