### ISSUE TITLE
Possibly a bug using options vs query. 

### ISSUE THREAD

**Issue by amir20** [webpack-contrib/extract-text-webpack-plugin#281]
Documentation suggests to use `options` to configure loaders but I had to use `query`. 

```js
ExtractTextPlugin.extract({
                fallbackLoader: 'style-loader',
                loader: [
                     {
                         loader: 'css-loader',
                         query: { importLoaders: 1}, // <--- should this be options? 
                     },
                     {
                         loader: 'postcss-loader',
                     }
                 ]
            })
```

This could be a bug. I couldn't figure out how to get `css-loader` configured with `importLoaders` otherwise.

**Comment by flying-sheep** [comment]
definitely true.

this still only supports webpack 1 style `query`, not `options`

**Comment by bebraw** [comment]
The plugin has been updated to use `options`. Instead of `loader` you should go with `use` now.
