### ISSUE TITLE
Should error on invalid ExtractTextPlugin config object

### ISSUE THREAD

**Issue by rgrwkmn** [webpack-contrib/extract-text-webpack-plugin#284]
The new version of ExtractTextPlugin helpfully told me to update the arguments when calling `new ExtractTextPlugin()`, but it did not error when I provided an object with the property `fileName` instead of `filename`. This led to some unusual errors in webpack and the cause was hard to track down.

**Comment by bebraw** [comment]
This should be done now with the schema.
