### ISSUE TITLE
How to setup the plugin with dynamic chunks (System.import)?

### ISSUE THREAD

**Issue by tleunen** [webpack-contrib/extract-text-webpack-plugin#285]
I have a loader which use ExtractTextPlugin to create a css file, but I don't really know how to setup all this with dynamic chunks based on System.import.

For these chunks, the css is not extracted in an external file.

Does anyone have an example to achieve this?

**Comment by clayne11** [comment]
I have managed to get this working. I have written about it a bit [here](https://github.com/webpack/extract-text-webpack-plugin/issues/263#issuecomment-260780404).

**Comment by tleunen** [comment]
I don't see how you resolved it... It seems the css from the chunks are still appended into the head without using an external file

**Comment by fdaciuk** [comment]
Same issue using dynamic `import()` on webpack2. Someone has any solution?

**Comment by monkindey** [comment]
When I setup react-router code splitting

* **The webpack.config.js** 

```js
rules: [{
	test: /\.less$/,
	use: ExtractTextPlugin.extract({
		fallback: 'style-loader',
		use: [{
			loader: 'css-loader'
		}, {
			loader: 'less-loader'
		}]
	})
}]

plugins: [
	new ExtractTextPlugin({
		filename: '/css/[name].css'
	})
]
```

* **react-router config** 

```js
const loadRoute = (done) => (module) => done(null, module.default)

const routes = {
	path: '/',
	component: App,
	childRoutes: [{
		path: '/inbox',
		getComponents(nextState, done) {
			System.import('./inbox').then(loadRoute(done, false));
		}
	}, {
		path: '/about',
		getComponents(nextState, done) {
			System.import('./about').then(loadRoute(done, false));
		}
	}]
}
```

   So you can lazy load the component when you switch its route.

* **one of routes `About` Component**

```js
import './about.less' 
import React, { Component } from 'react'

const About = props => (
	<div>
		<h3>About</h3>
		<p className="detail">I am inbox</p>
	</div>
);

export default About
```

When I click the `about` Link, will download the about chunk js and inject the `about` css into the head of the html by style tag. So it won't have different external css file by configuring these above, we can achieve lazy load css with the help of style-loader.

hope it helps.

**Comment by fdaciuk** [comment]
@monkindey in my case, I have a SPA without routes, but I'm using dynamic `import()`, so, I want to separate _critical_ styles - to load inline - and all others styles, to load on a `main.css` file.

I create a [simple internal plugin](https://gist.github.com/fdaciuk/d9dcb7ed11163477724bd3087292c181) on my application to deal with it. This approach have worked fine for me.

**Comment by monkindey** [comment]
Good job! Thanks for sharing, learn a lot from it. But can we collect critical styles automatically ?

Related [webpack-plugin-critical](https://github.com/nrwl/webpack-plugin-critical)

**Comment by fdaciuk** [comment]
I didn't try `webpack-plugin-critical` yet.. Let's see how it works =)

**Comment by michael-ciniawsky** [comment]
Emit a CSS file per split point (chunk) isn't supported atm, feature request for this is [here](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/455)
