### ISSUE TITLE
Extract text webpack plugin extracts css-base.js from css-loader from my bundle

### ISSUE THREAD

**Issue by vjancik** [webpack-contrib/extract-text-webpack-plugin#287]
Example from plugin output:
```
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 1.46 kB {0} [built]
       [1] ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/client/containers/LanguageSwitch/LanguageSwitch.scss 550 bytes {0} [built]
```
Line about css-base in `--display-modules` output:
```
 [711] ./~/css-loader/lib/css-base.js 1.46 kB [built]
```
It's missing a `{0}` because this plugin extracts it and it doesn't get emitted. 

However, in production I am using both extract text plugin, for extracting CSS and SCSS **AND isomorphic style loader** for inlining critical CSS and extracting it into HTML in SSR.
And thus, I need the `css-base.js` in my production bundle.

Is there any way to prevent this plugin from extracting the file?

Versions:
`extract-text-webpack-plugin@2.0.0-beta.4`
`webpack@2.1.0-beta.27`

Thank you!

**Comment by vjancik** [comment]
For whom it may concern, I got around the issue by a silly hack. I copied the `css-loader`, changed it's name, and referenced it in my `isomorphic-style-loader` under the different name. That way it doesn't get extracted by this plugin.

Specifically, using a postinstall npm script:

```bash
rm -rf ./node_modules/css-loader-clone
cp -r ./node_modules/css-loader ./node_modules/css-loader-clone
sed -e 's/css-loader/css-loader-clone/g' < ./node_modules/css-loader/package.json > ./node_modules/css-loader-clone/package.json
```

**Comment by scottdj92** [comment]
Closing due to age. If your issue persists, feel free to re-open.
