### ISSUE TITLE
webpack2: chunks styles are not loaded

### ISSUE THREAD

**Issue by sgratzl** [webpack-contrib/extract-text-webpack-plugin#290]
**environment**:
 * webpack@2.1.0-beta.27
 * extract-text-webpack-plugin@2.0.0-beta.4

I have a multi chunk environment based on `System.import` calls, i.e., webpack splits in multiple chunks for these modules. Some of the modules have styles referenced. 

**observation**:
While for the main module the styles are extracted, the styles should be inlined for dynamically loaded ones which works fine. However, the dynamic styles are not inserted into the DOM. Moreover, I can't find the style loading code in any bundle. 

**workaround**:
As a workaround I enabled the `allChunks: true` option to extract all styles

**Comment by yolo2013** [comment]
Have a similar problem.

**Comment by nowaalex** [comment]
+1

**Comment by scottdj92** [comment]
Closing due to age. If your issue persists, feel free to re-open.
