### ISSUE TITLE
Include original chunk comment into result file

### ISSUE THREAD

**Issue by yrtimiD** [webpack-contrib/extract-text-webpack-plugin#291]
Webpack can add annotation with original file name before each chunk:
```
/* 33 */
/*!**********************************************************!*\
  !*** ./~/angular-ui-bootstrap/dist/ui-bootstrap-csp.css ***!
  \**********************************************************/
/***/ function(module, exports) {

```

It will be extremely helpful to include this comment along with extracted css

**Comment by bebraw** [comment]
I think `BannerPlugin` could do this with small tweaks. Track https://github.com/webpack/webpack/issues/4252 .
