### ISSUE TITLE
Not all styles included in extracted css

### ISSUE THREAD

**Issue by KELiON** [webpack-contrib/extract-text-webpack-plugin#294]
How can I debug why not all css modules are included in final css bundle?

I've migrated to webpack 2 and rewrote my production config:

```js
module: {
  loaders: [
    ...baseConfig.module.loaders,

    {
      test: /global\.css$/,
      loader: ExtractTextPlugin.extract(
        'style-loader',
        'css-loader'
      )
    },

    {
      test: /^((?!global).)*\.css$/,
      loader: ExtractTextPlugin.extract(
        'style-loader',
        'css-loader?modules&importLoaders=1&!postcss-loader'
      )
    }
  ]
}
...
plugins: [
  ...
  new ExtractTextPlugin('style.css', { allChunks: true }),
  ...
]

```

And now:

```js
module: {
  rules: [
    ...baseConfig.module.rules,

    {
      test: /global\.css$/,
      loader: ExtractTextPlugin.extract({
        fallbackLoader: 'style-loader',
        loader: 'css-loader'
      })
    },
    {
      test: /^((?!global).)*\.css$/,
      loader: ExtractTextPlugin.extract({
        fallbackLoader: 'style-loader',
        loader: 'css-loader?modules&importLoaders=1!postcss-loader'
      })
    }
  ]
}
...
plugins: [
  ...
  new ExtractTextPlugin({
    filename: 'style.css',
    allChunks: true
  }),
  ...
]
```

First config works in webpack 1, but with new config and webpack 2 I see that a lot of styles are not in styles.css. How can I debug why it happens? 

Also, if I use rules from development (without ExtractCss) it works:

```js
{
  test: /global\.css$/,
  use: [
    'style-loader',
    {
      loader: 'css-loader',
      options: {
        sourceMap: true
      }
    }
  ]
},

{
  test: /^((?!global).)*\.css$/,
  use: [
    {
      loader: 'style-loader',
      options: {
        sourceMap: true
      }
    },
    {
      loader: 'css-loader',
      options: {
        modules: true,
        sourceMap: true,
        importLoaders: 1
      }
    },
    'postcss-loader'
  ]
}
```

**Comment by TNT-Likely** [comment]
i also have this problem

**Comment by TNT-Likely** [comment]
wish one guy help me resolve this problem

**Comment by devvdi** [comment]
+1, same problem here

**Comment by bebraw** [comment]
Could someone set up a standalone project to study?

**Comment by bebraw** [comment]
@KELiON Any luck with getting a little demo to study?

**Comment by Sharlaan** [comment]
Not sure, maybe related to [this (found in wp2 docs)](https://webpack.js.org/guides/migrating/#extracttextwebpackplugin-breaking-change) ?

**Comment by KELiON** [comment]
Sorry, missed few notifications here. 

I'll try to check what happens with the latest versions of webpack and extract text plugin and set up a demo if it still happens, but if you want to check before I had this issue [here](https://github.com/KELiON/cerebro/tree/feature/webpack2) (branch feature/webpack2)

**Comment by breeswish** [comment]
+1. In my project, it is only able to extract CSS in one rule. Outputs from other rules using the plugin are ignored.

**Comment by bebraw** [comment]
@breeswish Unless someone can provide a project to study, this won't get fixed.

**Comment by breeswish** [comment]
@bebraw Completely agree with you. Just got free time to create a small demo for this bug. Please check it out here: https://github.com/breeswish/demo

```bash
cd demo/My.Project
npm install
npm run build
```

According to the `webpack.config.js`, some part of [foundation-sites](https://github.com/zurb/foundation-sites) scss should be compiled and placed into `dist/vendors.css`, which is not happening. It only contains css from `../My.UI/pkg1/style.css`.

However, by commenting out the `CommonsChunkPlugin`, or by commenting L45 and uncommenting L46 (change to another ExtractTextPlugin), it works.

**Comment by bebraw** [comment]
@breeswish Great example. Thank you. 👍 

I traced it down to `minChunks`. If you replace it with `minChunks: module => module.context && module.context.indexOf('node_modules') >= 0,`, it seems to fix the issue.

Now the question is, is it the same bug as for the others? And is this a bug even or just the way `CommonsChunkPlugin` works?

**Comment by breeswish** [comment]
Thank you for the quick workaround! Really helpful for my current crying needs. 👍

**Comment by bebraw** [comment]
Please re-open with a small project study if still relevant.
