### ISSUE TITLE
Module not found: Error: Can't resolve './\""'

### ISSUE THREAD

**Issue by milkmidi** [webpack-contrib/extract-text-webpack-plugin#298]
package.json
    "webpack": "^2.1.0-beta.25",
    "webpack-dev-server": "^2.1.0-beta.0"
  "extract-text-webpack-plugin": "^2.0.0-beta.4",

webpack.config.js
var htmlExtractText = new ExtractTextPlugin( "[name].html");
module = {
rules:[
 {
 {
            test: /\.(png|jpg|gif|svg|ico)$/,
            include: path.resolve( 'src/img' ),
            loader: 'url-loader',
            exclude: /node_modules/,
            options: {
                limit: 2048,
                name : "asset/[path][name].[ext]?[hash:8]"
            }
        },
            test: /\.html$/,
            loader: htmlExtractText.extract(
                {
                    fallbackLoader:"html-loader",
                    loader: "html-loader?name=[name].html&interpolate=require",
                    publicPath:""
                }),            
            include: path.resolve( 'src/html' ),
            exclude: /node_modules/   ,                  
        },
]
}

config.plugins = [
htmlExtractText 
]

index.html
if add image tag with src
＜img src="~logo.png" /＞
got error
ERROR in ./src/html/index.html
Module not found: Error: Can't resolve './\""' in 'E:\BackUpmedialandWork\other\
interactive_project_template\src\html'
resolve './\""' in 'E:\BackUpmedialandWork\other\interactive_project_template\sr
c\html'
  using description file: E:\BackUpmedialandWork\other\interactive_project_templ
ate\package.json (relative path: ./src/html)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: E:\BackUpmedialandWork\other\interactive_project
_template\package.json (relative path: ./src/html)
    using description file: E:\BackUpmedialandWork\other\interactive_project_tem
plate\package.json (relative path: ./src/html/"")
      as directory
        E:\BackUpmedialandWork\other\interactive_project_template\src\html\"" do
esn't exist
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        E:\BackUpmedialandWork\other\interactive_project_template\src\html\"" do
esn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        E:\BackUpmedialandWork\other\interactive_project_template\src\html\"".js
 doesn't exist
      .vue
        Field 'browser' doesn't contain a valid alias configuration
        E:\BackUpmedialandWork\other\interactive_project_template\src\html\"".vu
e doesn't exist
      .scss
        Field 'browser' doesn't contain a valid alias configuration
        E:\BackUpmedialandWork\other\interactive_project_template\src\html\"".sc
ss doesn't exist
[E:\BackUpmedialandWork\other\interactive_project_template\src\html\""]
[E:\BackUpmedialandWork\other\interactive_project_template\src\html\""]
[E:\BackUpmedialandWork\other\interactive_project_template\src\html\"".js]
[E:\BackUpmedialandWork\other\interactive_project_template\src\html\"".vue]
[E:\BackUpmedialandWork\other\interactive_project_template\src\html\"".scss]
 @ ./src/html/index.html 1:812-831
 @ ./src/js/main.require.js
 @ ./src/js/main.js
 @ multi index

**Comment by bebraw** [comment]
Can you include a whole project to study?
