### ISSUE TITLE
Any intention to publish the extract-text-webpack-plugin V2.0.0 to npmjs anytime soon?

### ISSUE THREAD

**Issue by yoavfranco** [webpack-contrib/extract-text-webpack-plugin#303]
Hi,
I was wondering if the extract-text-webpack-plugin V2.0.0 is close to being published on NPM?

Thanks

**Comment by JackuB** [comment]
You can install it from npm if you specify version `npm i extract-text-webpack-plugin@2.0.0-beta.4` or with a `beta` label `npm i extract-text-webpack-plugin@beta`

**Comment by bebraw** [comment]
Yeah, there's a `beta` now. We are currently running RCs and hopefully reach a final soon.
