### ISSUE TITLE
CSS ordering issue with shared modules

### ISSUE THREAD

**Issue by rstacruz** [webpack-contrib/extract-text-webpack-plugin#315]
If you have 2 bundles:

```js
// webpack.config.js
entry: {
  'app': 'css/app.js',
  'admin': 'css/admin.js'
},
plugins: [
    new ExtractTextPlugin('[name].css')
]
```

And both entry points use a common CSS file:

```js
// css/app.js
require('./a.css')
require('./common.css')
require('./b.css')
require('./c.css')
```

```js
// css/admin.js
require('./x.css')
require('./common.css')
require('./y.css')
require('./z.css')
```

The actual ordering gets messed up.

```js
// "app.css" bundle
common.css     ⚠
a.css
b.css
c.css
```

```js
// "admin.css" bundle
x.css
common.css
y.css
z.css
```

Notice how `common.css` is now in the wrong place in the 1st bundle.

I'm guessing this is unfixable considering how webpack + extract-text-webpack-plugin works. But is there a workaround I can do?

**Comment by scottdj92** [comment]
Closing due to age. If your issue persists, feel free to re-open.

**Comment by floorish** [comment]
Same issue here: all files imported in the first entry point are extracted first for all other entry points that import those same files.

```javascript
entry: {
  'one': 'one.js',
  'two': 'two.js'
},
```
```javascript
// one.js
import 'one.scss'
import 'component.scss'
```
```javascript
// two.js
import 'two.scss'
import 'component.scss'
```
Because `component.scss` is already imported in `one.js`, it is extracted first for `two.js`:
```javascript
// two.css bundle
component.css  // <- wrong order :(
two.css
```
