### ISSUE TITLE
how to support isomorphic apps

### ISSUE THREAD

**Issue by dalimian** [webpack-contrib/extract-text-webpack-plugin#332]
there is a growing pattern to rendering a url on server side if user lands on it, but render it on client side if user navigates to it from another page on your site - more about it here http://nerds.airbnb.com/isomorphic-javascript-future-web-apps/

we are trying to migrate a huge site (70 million page views/month) to react/react-router/webpack

my question is wether it is possible to support isomorphic apps with extract-text-plugin. so high lever requirements are 
1. when user lands on a page - render server side. we need to avoid flash of unstyled content by including the css file for that page via link tag on server side
2. but if user navigates to the page from a different page on our site we like to avoid a full refresh - load the page async.

it seems that open issues below are blockers for the above, maybe there is a workaround, please advise
- https://github.com/webpack/extract-text-webpack-plugin/issues/106
- https://github.com/webpack/extract-text-webpack-plugin/issues/120

**Comment by ufocoder** [comment]
@dalimian I think there is an offtopic question. 
But by the way you could check [my boilderplate](https://github.com/ufocoder/redux-universal-boilerplate)

**Comment by halt-hammerzeit** [comment]
> we need to avoid flash of unstyled content by including the css file for that page via link tag on server side

See how `universal-webpack` solves that completely:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example

**Comment by dalimian** [comment]
Thanks for sharing. But from I saw you are using style-loader? which means ur styles are embedded in js, which would in some cases cause a flash of unstyled content - we wanted to use a css file

**Comment by halt-hammerzeit** [comment]
No flash of unstyled content there

**Comment by bebraw** [comment]
Have you seen [isomorphic-style-loader](https://www.npmjs.com/package/isomorphic-style-loader)?

**Comment by michael-ciniawsky** [comment]
This is not in the scope of this plugin, it's sole purpose is to extract CSS from the bundle into separate files :)

**Comment by dalimian** [comment]
thanks all for suggestions

I ended up using https://www.npmjs.com/package/extract-css-chunks-webpack-plugin - which is a fork of extract-text-webpack-plugin to support the above use cases.
