### ISSUE TITLE
Plugins triggers known issue on Ubuntu for Windows 10

### ISSUE THREAD

**Issue by nicobrinkkemper** [webpack-contrib/extract-text-webpack-plugin#336]
I'm not expecting a fix for this issue, but it's good to know. This plugin makes Ubuntu bash for Windows 10 unusable. Commenting/removing the CSS require can fix it temporarily. The plugin works as expected on docker for windows. Let me know if anyone wants to learn more about this.

https://github.com/scravy/node-macaddress/issues/8

https://github.com/Microsoft/BashOnWindows/issues/468

![image](https://cloud.githubusercontent.com/assets/1597349/21994802/cd6476bc-dc21-11e6-9bc8-e07758634260.png)

**Comment by SpaceK33z** [comment]
The issue on the BashOnWindows repo has been closed, can you verify this is fixed?
