### ISSUE TITLE
Plugin hangs when used with UglifyJS plugin

### ISSUE THREAD

**Issue by ewiner** [webpack-contrib/extract-text-webpack-plugin#34]
I'm not sure how to make a minimal repro for this... but when I upgraded from extract-text-webpack-plugin 0.3.1 to 0.3.2, my webpack build started hanging at `69% 477/478 build modules`.  When I downgrade this plugin back to 0.3.1, or turn off the UglifyJS plugin, it works again.

Any ideas?  Happy to collect additional information if you tell me how.

I'm using this plugin for CSS, all default options.  If it helps, my full plugin list is:
- `IgnorePlugin(...)` (for a broken library)
- `NormalModuleReplacementPlugin(...)` (for another broken library)
- `new ExtractTextPlugin("[name].css")` (this is actually extracted into a variable and referenced in the `css` loader)
- `OccurenceOrderPlugin()`
- `DedupePlugin()`
- `AggresiveMergingPlugin()`
- `CommonsChunkPlugin('common', 'common.js, null, 2)`
- `UglifyJsPlugin()`

Thanks!

**Comment by jsg2021** [comment]
I'm seeing this on webpack `1.10.1` and extract-text-webpack-plugin `0.8.2`.
