### ISSUE TITLE
CSS Modules: ExtractTextPlugin changes the format of the imported style object

### ISSUE THREAD

**Issue by websash** [webpack-contrib/extract-text-webpack-plugin#348]
Been migrating to Webpack 2 and noticed my local CSS is not working with the new ExtractTextPlugin.
Consider this sample code:
```javascript
import style from './style.css'

const div = document.createElement('div')

div.className = 'foobarGlobal ' + style.foobarLocal

document.body.appendChild(div).textContent = 'css modules'

console.info('style', style)

```
Without ExtractTextPlugin I got this `style`:
![screen shot 2017-01-21 at 3 32 18 pm](https://cloud.githubusercontent.com/assets/679341/22174912/a6e3fa2e-dff2-11e6-888a-ee93afb90327.png)
which is fine and expected.

Now when using ExtractTextPlugin I'm getting this format:
![screen shot 2017-01-21 at 3 32 39 pm](https://cloud.githubusercontent.com/assets/679341/22174919/cd43fa3e-dff2-11e6-9a98-3a44f4d02441.png)
as if I'm supposed to use `style.locals.foobarLocal` now. Why is that?
My test webpack config https://github.com/websash/webpack2-css-modules/blob/master/webpack.config.js

**Comment by Ephem** [comment]
+1 I'm experiencing the same issue.

**Comment by Ephem** [comment]
This turned out to be related to #330 for me. Before figuring out what was wrong (I was using `use: ExtractTextPlugin({ ... })` instead of `loader: ExtractTextPlugin({ ... })`) I tried all kinds of configs to get it working. At some point I ended up with the error above, but when I got it working properly, css modules were exported correctly as well.

@websash Maybe you are having some kind of related issue?

This part is from your config:
``` js
use: [
  ExtractTextPlugin.extract({
    fallbackLoader: 'style-loader',
    loader: 'css-loader'
  }), {
    loader: 'css-loader',
    options: {
      minimize: true,
      modules: true,
      importLoaders: true,
      localIdentName: '[hash:6]'
    }
  }
],
```

Maybe something like this would work:

``` js
loader: ExtractTextPlugin.extract({
  fallbackLoader: 'style-loader',
  loader: {
    loader: 'css-loader',
    query: {
      minimize: true,
      modules: true,
      importLoaders: true,
      localIdentName: '[hash:6]'
    }
  }
}),
```

You would have to do the same thing a bit further down in the config. I hope it helps!

**Comment by websash** [comment]
@Ephem thanx for the tip. Your config is definitely working for me 👍 I was sure I had to use `use` with an array all the time and `options` for loader configuration but here we need `query` 😕 Wish we had better docs

**Comment by michael-ciniawsky** [comment]
@websash @Ephem Yep the syntax will definitely be updated/fixed v2 final. Besides that if CSS Modules work correctly please close the issue 😛

**Comment by Ephem** [comment]
@websash No worries, glad I could help. :) PR #343 fixes this so that we can use `use` and PR #276 fixes `options`. I guess this time the docs were correct, but the implementation needed some tweaking. :) I think this issue could be closed now?

**Comment by d3viant0ne** [comment]
#343 has been merged, included in https://github.com/webpack-contrib/extract-text-webpack-plugin/releases/tag/v2.0.0-rc.0 and published to npm as `v2.0.0-rc.0`

**Comment by yinjunok** [comment]
@Ephem that's cool, thanks.

**Comment by arisunarya** [comment]
@Ephem thanks, that's work
