### ISSUE TITLE
ExtractTextPlugin should do stricter option validation

### ISSUE THREAD

**Issue by bebraw** [webpack-contrib/extract-text-webpack-plugin#351]
I.e., `fileName` option should fail hard.

Related to #344.

**Comment by michael-ciniawsky** [comment]
Should it have a fallback to `config.output.filename` etc, if no options `{String}`/ options.filename `{Object}` specified, before failing hard ?

Has webpack it's own logic for handling errors in plugins, like loaders do (pretty-format)? Or is throwing a classic `new Error()` ok?

**Comment by bebraw** [comment]
> Should it have a fallback to config.output.filename etc, if no options {String}/ options.filename {Object} specified, before failing hard ?

I don't see a fallback like that in the current logic and it might be counter-intuitive to do that. It's likely enough if we can accept `filename` directly or through an options object.

> Has webpack it's own logic for handling errors in plugins, like loaders do (pretty-format)? Or is throwing a classic new Error() ok?

I haven't seen any and the current plugins just seem to throw if the fail validation. I think the ideal solution would be to write a JSON Schema for the options and then process through [ajv](https://www.npmjs.com/package/ajv). A good schema could be used to write the documentation section of the readme even (needs a little tool to transform).

**Comment by michael-ciniawsky** [comment]
> I don't see a fallback like that in the current logic and it might be counter-intuitive to do that. It's likely enough if we can accept filename directly or through an options object.

Yep there is none 😛 , it would be ?filename/?options.filename > config.output.filename, but agreed it can be confusing

> I haven't seen any and the current plugins just seem to throw if the fail validation.

kk

>  I think the ideal solution would be to write a JSON Schema for the options and then process through ajv. 

kk

**Comment by scottdj92** [comment]
[#358](https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/358)

**Comment by scottdj92** [comment]
Are we closing this, now that [#358](https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/358) is merged?

**Comment by bebraw** [comment]
Yeah, good point.
