### ISSUE TITLE
Previously working stylus configuration broken as of 2.0.0-rc.0

### ISSUE THREAD

**Issue by zachmullen** [webpack-contrib/extract-text-webpack-plugin#363]
I have the following loader configurations that were working on 2.0.0-beta.5.

```
{
                test: /\.styl$/,
                include: loaderPaths,
                loader: ExtractTextPlugin.extract({
                    fallbackLoader: 'style-loader',
                    loader: ['css-loader', {
                        loader: 'stylus-loader',
                        query: {
                            'resolve url': true
                        }
                    }]
                })
            },
            // CSS
            {
                test: /\.css$/,
                include: loaderPathsNodeModules,
                loader: ExtractTextPlugin.extract({
                    fallbackLoader: 'style-loader',
                    loader: ['css-loader']
                })
            }
```

And I use the following plugin on the target:

```
new ExtractTextPlugin({
                        filename: '[name].min.css',
                        allChunks: true
                    })
```

After upgrading to rc.0, the build fails for all my stylus files with:

    Module build failed: ReferenceError: window is not defined

Removing the `fallbackLoader` altogether makes the build succeed, but the extraction no longer works at that point. It's possible I was relying on undefined behavior before, but I have no idea what I'm doing wrong here, any thoughts? Thanks!

**Comment by zachmullen** [comment]
This might be important info too: this is being built into a library using the DllPlugin, not an entry chunk.

**Comment by baohouse** [comment]
I'm using 
`const extractCss = new ExtractTextPlugin({
  filename: '[name].[contenthash].css',
  allChunks: true,
});
...
module: {
  loaders: [
    {
      test: /\.css$/,
      exclude: /node_modules/,
      loaders: extractCss.extract(['css-loader','postcss-loader']),
    },
  ]
}
`

When I observe the compiled Javascript:

# Before
`
"./components/Layout/Layout.css": function(e, t) {
    e.exports = {
        layout: "_2qM7",
        content: "_18xm",
        fadeDown: "_1DEl",
        centered: "_1erU",
        relative: "_3P4O",
        box: "_2Abo",
        "login-error": "_2utm",
        title: "qQTB",
        back: "_1QAN",
        breadcrumb: "_7xQ"
    }
},
`

# After
`
"./components/Layout/Layout.css": function(e, t, n) {
    t = e.exports = n("./node_modules/css-loader/lib/css-base.js")(),
    t.push([e.i, "._2qM7{background:#fbfbfb;border-top:1px solid #e8e8e8}...truncated", ""]),
    t.locals = {
        layout: "_2qM7",
        content: "_18xm",
        fadeDown: "_1DEl",
        centered: "_1erU",
        relative: "_3P4O",
        box: "_2Abo",
        "login-error": "_2utm",
        title: "qQTB",
        back: "_1QAN",
        breadcrumb: "_7xQ"
    }
}
`

Initially I thought the recent **loader-runner** dependency update (version 2.2.0 to 2.3.0) was the culprit, and I had to generate an npm-shrinkwrap.json file to lockdown the dependency versions, but my app didn't work until I rolled back **extract-text-webpack-plugin** to version 2.0.0-beta.5.

**Comment by blake-newman** [comment]
This is also an issue with sass-loader with`rc.0`

Configuration values for include paths cause issues. 

`File to import not found or unreadable: style/settings.`

**Comment by bebraw** [comment]
Here is the [diff](https://github.com/webpack-contrib/extract-text-webpack-plugin/compare/e30595e...6e67199).

It likely has to do with that `query` related change. Could you update your configuration to use `options` instead?

**Comment by zachmullen** [comment]
@bebraw to clarify, do you mean changing:

```
query: {
    'resolve url': true
}
```

to

```
options: {
    'resolve url': true
}
```

? I tried that, but still got the same errors.

**Comment by bebraw** [comment]
@zachmullen Yeah, that's the new format. There's something else going on.

**Comment by zachmullen** [comment]
I'm also seeing similar errors for my other rules that matches just .css files, so it's not only related to the stylus loader. The errors disappear when I remove the fallbackLoader entirely, but then the extraction doesn't occur and I get the CSS duplicated between the css file and the js file.

```
ERROR in ./~/bootstrap/dist/css/bootstrap.css
Module build failed: ReferenceError: window is not defined
```

**Comment by bebraw** [comment]
Based on this and #364 I would say the modified version of `ExtractTextPlugin.prototype.extract` broke an underlying assumption. In the old version that returned a query string while the version returns an array of objects. It's exactly that what webpack chokes with.

Perhaps the fastest fix would be to normalize back to query although I suspect this could be handled on webpack core as well.

**Comment by bebraw** [comment]
The problem with query normalization is that then we would lose functions (no postcss). I guess ideally webpack should be able to handle the current format without hickups.

**Comment by insin** [comment]
@zachmullen any difference if you replace `loader: ExtractTextPlugin.extract(...)` with `use: ExtractTextPlugin.extract(...)`?

**Comment by zachmullen** [comment]
`Fatal error: Element from loaders list should have one of the fields 'loader' or 'loaders'`

**Comment by zachmullen** [comment]
I upgraded to webpack 2.2.0 (I was on an early 2.x version) and this issue went away. Thanks for the help.

**Comment by Nilegfx** [comment]
I am aware that this one is closed, but if you ever came to here, make sure that you don't use style-loader as one of `ExtractTextPlugin`'s loaders

**Comment by zachmullen** [comment]
@Nilegfx I use it as the `fallbackLoader`, not sure that ever gets invoked though.

**Comment by bebraw** [comment]
@zachmullen It gets invoked **only** if you have set `allChunks: false` and you have a split point that refers to CSS (or whatever styling you are using) somewhere.

**Comment by psulek** [comment]
@Nilegfx removing 'style-loader' was my case. Thanks.
