### ISSUE TITLE
Error vs fallbackLoader

### ISSUE THREAD

**Issue by khankuan** [webpack-contrib/extract-text-webpack-plugin#365]
Hi, I would like to understand more about error handling. I encountered an error while building:
```
Module build failed: ModuleBuildError: Module build failed: BrowserslistError: Unknown version 59 of chrome
```
Unfortunately, it seems like webpack did not fail and continued building successfully. I wonder if the behavior is expected. 

Cheers.

**Comment by bebraw** [comment]
Can you provide more info? How to repro?

**Comment by khankuan** [comment]
It worked after updating dependencies. My main concern is extract-text-webpack-plugin failing silently as well as going to fallback loader without warning dev. Have experienced that a few times such as syntax errors.

**Comment by scottdj92** [comment]
Isn't this resolved with the new JSON schema validation now? It'll throw an error if none of the correct properties are passed in.

**Comment by bebraw** [comment]
The validation will catch typos, yup. I'm still a little puzzled on the original report as there's no project to test.

`fallbackLoader` would come into play with code splitting (`require.ensure`/dynamic `import`) and `allChunks` option. If you don't extract all, then it needs some fallback. Normally you configure it to inline that styling.

**Comment by khankuan** [comment]
Hmm, is falling back to inline style a common pattern? I feel like it is more dangerous to have styles loaded magically. I have not used chunking much, is it a common pattern to load styles by inline?

**Comment by bebraw** [comment]
> Hmm, is falling back to inline style a common pattern? I feel like it is more dangerous to have styles loaded magically. I have not used chunking much, is it a common pattern to load styles by inline?

That's the way it has been specified by the current code. You would need to tweak `allChunks` to get the behavior you want.

I would need a repository to study to say more about the error. There's no other way I can fix it.

**Comment by khankuan** [comment]
Ic. Hmm double check, regardless of the configurations (allChunks, fallbackLoader etc), it is expected the the plugin would error out when the file contains error? I can't seem to find tests on error, do you think it'll help if we start with writing a test?

**Comment by bebraw** [comment]
I don't know what emits the error yet. Not enough info yet to tell.

**Comment by khankuan** [comment]
Sorry I might have been unclear, the error above was resolved after reinstalling node modules. However, the confusion is when webpack did not exit with error after that.

**Comment by bebraw** [comment]
Ah... I see. There's something known as `bail` flag you can set on configuration root. If I remember right, webpack does not stop building by default.

Thanks for confirming it works now. Time to close.

**Comment by khankuan** [comment]
Ah interesting, didn't know about that option. Thanks!
