### ISSUE TITLE
style: upgrade to ES2015 syntax?

### ISSUE THREAD

**Issue by scottdj92** [webpack-contrib/extract-text-webpack-plugin#367]
With Node 6.9.4 reaching LTS, would it be possible to convert the codebase from ES5 to ES6 syntax?

**Comment by michael-ciniawsky** [comment]
Refactor PR's are highly welcome but baseline is Node v4.3 LTS atm to align with webpack core. http://node.green

**Comment by scottdj92** [comment]
Ahh, so webpack-core is in the process of being upgraded to support 6.9.4?

**Comment by michael-ciniawsky** [comment]
nope, node 4 :) for now, bc it's still active LTS

**Comment by scottdj92** [comment]
Ahh, so we're following LTS Argon, not Boron? Thanks!

Should we keep this issue open for future upgrade reference?

**Comment by bebraw** [comment]
Yeah, let's leave this open. It's better to port after we get a stable version of the plugin out there and agree on project standards.

**Comment by d3viant0ne** [comment]
This has been completed and will be landing in master Monday.
