### ISSUE TITLE
Fail hard if `loader: plugin.extract` is used

### ISSUE THREAD

**Issue by bebraw** [webpack-contrib/extract-text-webpack-plugin#370]
This is an important check to make as `extract` works only with `use`.

**Comment by bebraw** [comment]
This might need webpack core work since `loader: plugin.extract(...)` doesn't give the plugin (or rather loader) a chance to do anything about it. I think the core needs to detect that an array is passed (shouldn't validation pick this up, though?) and give a nice error.

CC @sokra @TheLarkInn

**Comment by TheLarkInn** [comment]
Hmm, @Sokra we could do this but I'm not sure if schema could catch.

**Comment by bebraw** [comment]
I think we might not need this after all. Looks like implementing a custom `toString` for `extract` solves it. See https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/374 for details.

I'm not sure how to handle functions (postcss) in this case, but @sokra can probably give some insight to that.

**Comment by sokra** [comment]
Actually `loader: Array` is supported for backward-comp.

`use: {loader: Array}` should be catched by the schema.

**Comment by bebraw** [comment]
Alright. No need to do anything about this then. The error that lead to this issue had to do with another loader that doesn't work with the new scheme. Since `extract` appears to work against `loader:`, there's not much to do here.
