### ISSUE TITLE
Build failing with "Error: data['notExtractLoader'] should NOT have additional properties" - Is notExtractLoader still supported?

### ISSUE THREAD

**Issue by jgliner** [webpack-contrib/extract-text-webpack-plugin#375]
Hi, my build has been failing for the past day or two. I have tried updating to the latest version (rc.2), as well as rolling back a couple versions with no success. I did some digging and found out that `notExtractLoader` from my webpack config 

Stacktrace:
```
BASE_FOLDER/node_modules/extract-text-webpack-plugin/schema/validator.js:11
                throw new Error(ajv.errorsText());
                ^

Error: data['notExtractLoader'] should NOT have additional properties
    at validate (BASE_FOLDER/node_modules/extract-text-webpack-plugin/schema/validator.js:11:9)
    at Function.ExtractTextPlugin.extract (BASE_FOLDER/node_modules/extract-text-webpack-plugin/index.js:190:3)
    at Object.<anonymous> (BASE_FOLDER/webpack.client.prod.js:74:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

Going into the commit history, I have determined that [03bb4aa](https://github.com/webpack-contrib/extract-text-webpack-plugin/commit/03bb4aa50f4cf2b580512d066c82886230303571) is likely the culprit. Below is the plugin being used in my webpack config:
``` js
...
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract({
          notExtractLoader: 'style-loader',
          loader: 'css-loader',
        }),
      },
...
```
Namely, your loader schema does not include `notExtractLoader`. Is this still supported? It is still referenced in the `example` folder, so I went ahead and made a PR for your consideration. Thanks in advance!

**Comment by bebraw** [comment]
`loader: ExtractTextPlugin.extract` should become `use: ExtractTextPlugin.extract`. I have a fix for `loader`, but it's waiting on feedback from Tobias.

**Comment by bebraw** [comment]
The validation fails because `notExtractLoader` field does not do anything. I think you may have meant `fallbackLoader`.

**Comment by bebraw** [comment]
> Namely, your loader schema does not include notExtractLoader. Is this still supported? It is still referenced in the example folder, so I went ahead and made a PR for your consideration. Thanks in advance!

That example should be fixed. Sounds like that wasn't updated when the loader was updated in the past.

**Comment by jgliner** [comment]
Got it. Thanks!

**Comment by xavica** [comment]
Is this issue fixed? we still facing same issue.

**Comment by bebraw** [comment]
It's fixed, yeah. Read the validation message carefully.

**Comment by RSO** [comment]
For other people ending up here because of similar errors, the error message seems to indicate that the key you're using is incorrect. In my case I was using `fallBack` instead of `fallback`.

**Comment by mnpenner** [comment]
I'm still encountering this. What's the solution?

My config looks like this:

```js
{
    module: {
        rules: [
            {
                test: /\.css$/,
                use: ExtractTextPlugin({
                    fallback: 'style-loader',
                    use: [{
                        loader: 'css-loader',
                        options: {
                            sourceMap: false,
                            root: '/home/mpenner/Projects/project/www',
                            localIdentName: '[name]_[local]--[hash:base64:5]'
                        }
                    },
                        {loader: 'postcss-loader'}],
                }),
            },
        ]
    }
}
```

**Comment by wzup** [comment]
@RSO doesn't work what you say
