### ISSUE TITLE
Specify Output Path

### ISSUE THREAD

**Issue by joezimjs** [webpack-contrib/extract-text-webpack-plugin#377]
I'd like a way to just specify a path where the file is being written without using `../styles/` because otherwise the AssetsPlugin generates this: 

``` json
{
  "main": {
    "js": "/scripts/bundle.js",
    "css": "/scripts/../styles/styles.4e3230cbd3e79891f49e02389c16cb58.css"
  }
}
```

adding an additional `path` for the output of the CSS file would be helpful and more explicit

**Comment by bebraw** [comment]
Can you show how you are calling the plugin right now? The plugin call provides control, but I would need to see your current definition to say how to tweak it.

**Comment by joezimjs** [comment]
Honestly, I don't remember making this issue (man my memory has been sucking lately) and I can't find the project that would have given an output like that. @Aenohe may be able to help since he hit the thumbs up.

**Comment by michael-ciniawsky** [comment]
Feel free to reopen if you can provide more info and it's still relevant :)
