### ISSUE TITLE
2.0.0-rc.2 might break the build (ajv)

### ISSUE THREAD

**Issue by amazingcode-de** [webpack-contrib/extract-text-webpack-plugin#380]
Listing ajv in devDependencies and not explicitly in dependencies might break the build of packages relying on extract-text-webpack-plugin. ajv might not be installed at all or might be resolved to a wrong version. 

In our specific project, we have ajv@5.0.1-beta.0 as dependency in our main package.json, leading to the following error, since extract-text-webpack-plugin expects ajv to be version 4 but finds version 5:

`Error: no schema with key or ref "http://json-schema.org/draft-04/schema#"`

**Comment by michael-ciniawsky** [comment]
@amazingcode-de Yep that should be fixed, good catch.
Do you want to send a PR for it? 
Otherwise I will do it when I have a few minutes :)

**Comment by bebraw** [comment]
Merged.
