### ISSUE TITLE
Move API to use/fallback in v2

### ISSUE THREAD

**Issue by bebraw** [webpack-contrib/extract-text-webpack-plugin#382]
To comply with `use`, the API should look like this (to quote @sokra):

```javascript
use: ETP.extract({
  fallback: [
    { loader: "style-loader", options: {} }
  ],
  use: [
    { loader: "css-loader" },
    { loader: "postcss-loader", options: { plugin() { ... } } }
  ]
})
```

We probably should give deprecation messages for the old fields.

**Comment by jaydenseric** [comment]
Should it not be `loader: ETP.extract({`?

When did `fallbackLoader` get replaced with a `fallback` array? The readme must need updating.

Also, just want to clarify mixing objects and strings in `use` arrays will be ok, [like with webpack](https://webpack.js.org/configuration).

So:

```js
loader: ETP.extract({
  fallbackLoader: 'style-loader',
  use: [
    'css-loader',
    {
      loader: "postcss-loader",
      options: { ... }
    }
  ]
})
```

**Comment by bebraw** [comment]
Hi,

This change hasn't been done yet. That's why the READMe isn't done yet.

The old `loader: plugin.extract` legacy syntax is still supported although `use` is preferred.
