### ISSUE TITLE
Document how to fix pitch loaders like font-awesome-loader

### ISSUE THREAD

**Issue by bebraw** [webpack-contrib/extract-text-webpack-plugin#383]
We should document briefly how to fix loaders like font-awesome-loader to work with v2.

**Comment by bebraw** [comment]
Related: https://github.com/shakacode/font-awesome-loader/issues/7 .

**Comment by michael-ciniawsky** [comment]
The `ident` (Complex Options) is obsolete since  webpack >= v2.2.1 and this isn't really related to ETWP or do I miss something? In this case reopen please 😛  I will open an issue about eventual removal of the Complex Options (`ident`) docs @webpack/webpack.js.org

**Comment by bebraw** [comment]
Yeah, ok to close I think.
