### ISSUE TITLE
Extract Text Plugin does not work in child compilations

### ISSUE THREAD

**Issue by jantimon** [webpack-contrib/extract-text-webpack-plugin#389]
From https://github.com/jantimon/html-webpack-plugin/issues/579

The root problem is that the extract text plugin uses kind of a hack to communicate between loader and plugin. (See here https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/master/index.js#L216-L227 and here https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/master/loader.js#L26)
This hack works only in the main compilation however the html-webpack-plugin is using a child compilation.

This might add a feature request for the webpack core (easier communication between loaders and plugins)

**Comment by bebraw** [comment]
> This might add a feature request for the webpack core (easier communication between loaders and plugins)

This actually raises an interesting question. How to associate a loader or loaders with some specific plugin? Perhaps this means there needs to be a concept of identity. webpack core already uses something known as `ident`. If we went with that, you would pass `ident` field through a loader/plugin to associate them with each other (probably many to many should work too).

**Comment by michael-ciniawsky** [comment]
Is there anything new happend recently in terms of webpack core ? How to start with this, any ideas?

**Comment by bebraw** [comment]
Please ask Tobias for details.

**Comment by michael-ciniawsky** [comment]
Maybe #483, but I didn't take a deeper look at it

**Comment by StevenTheEVILZ** [comment]
So it looks like this isn't getting fixed any time soon :/ because ultimately, #483 needs https://github.com/webpack/webpack/pull/4704, which contains breaking changes and therefore will wait until webpack 3.

**Comment by StevenTheEVILZ** [comment]
Any progress besides that?

**Comment by d3viant0ne** [comment]
Given this is dependent on multiple `semver: Majors` upstream as well as at least two in `extract-text-webpack-plugin` all of which require coordination, testing, beta builds => bug fixes the only thing anyone can tell you for certain about the time frame is it's certainly too early to be asking about.

**Comment by zfanning** [comment]
I saw that webpack 3 is out and was wondering about the current status of this issue?

**Comment by michael-ciniawsky** [comment]
@zfanning #483 should have fixed it :)

**Comment by PTC-JoshuaMatthews** [comment]
I am still seeing this error using webpack 3.4.1.

**Comment by Mouvedia** [comment]
Webpack 3.10.0 is still affected.

**Comment by evilebottnawi** [comment]
@PTC-JoshuaMatthews can you create minimum reproducible test repo and create new issue

**Comment by sunilb0575** [comment]
my gem 'webpacker', '~> 3.2' version,
and I am stuck with this issue
https://stackoverflow.com/questions/55130980/error-extract-text-webpack-plugin-loader-is-used-without-the-corresponding-pl
