### ISSUE TITLE
feat: support nested output paths

### ISSUE THREAD

**Issue by paulmichalak** [webpack-contrib/extract-text-webpack-plugin#39]
I'm having an issue when dealing with multiple entry bundles. While I can specify the path for the css file output for each bundle all the fonts in my CSS are just dumped to the base output path.

**Comment by antwan1986** [comment]
Hey,

Resurrecting an old ticket but I too am essentially wanting to have multiple output folders for my entry bundles. An example:

Bundle A and Bundle B get output into `./assets/js/`
Bundle C gets output into `./another-folder/js`

**Comment by Swivelgames** [comment]
Uh, yup. Just ran into the same dilemma. Bump :smiley:

**Comment by antwan1986** [comment]
Just an update to say that I've currently got around this issue by using `webpack-stream`, and not specifying any output options in the webpack configuration. I then use gulp-rename to update the paths of the streams based upon a manifest I keep that coincides with my webpack entry bundles, and that does the job. Slightly convoluted but it's a viable workaround!

**Comment by AsaAyers** [comment]
Same here. I have a webpack configuration that needs to output to 2 different folders. `output.path` is the base and `output.filename` contains `[name]/`.

I don't know what the implementation would involve, but it seems clear to me the right answer is either reuse `output.filename`, or allow us to specify a `filename` option that works the same way.

**Comment by brandonmp** [comment]
it's a little hackish, but the most simple solution for me was adding some shell commands to my npm scripts. 

eg
```
"scripts": {
    "build": "webpack -p --colors --optimize-dedupe && cp ./path/to/index.html ./dist/index.html"
  }
```

**Comment by lcrespom** [comment]
I am working on a small project and already stumbled with this limitation. In my case, I want some code in the `dist/` folder and some other code in the `web/` folder.

As a suggestion, this could be a way to specify it:

```javascript
entry: {
    example: './src/examples/main.ts',
    'my-lib': './src/my-lib.ts'
},
output: {
    path: path.resolve(__dirname),
    filenames: {
        example: 'web/example.js',
        'my-lib': 'dist/my-lib.js'
    }
}
```

**Comment by red2678** [comment]
+1
