### ISSUE TITLE
using `use` property cause webpack2 bundling error

### ISSUE THREAD

**Issue by everedifice** [webpack-contrib/extract-text-webpack-plugin#393]
1. Check the version of package you are using. If it's not the newest version, update and try again (see changelog while updating!).

i use `extract-text-webpack-plugin 2.0.0-rc3` and `webpack 2.2.1`

2. If the issue is still there, write a minimal project showing the problem and expected output.

using 'use' property name on both (webpack's rules and plugin option) cause bundling error.

```javascript
module: {
  rules: [ {
    test: /\.css$/,
    use: ExtractTextPlugin.extract({use: 'css-loader', options: {sourceMap: true}})
  }]
}
```

![2017-02-07 11 08 12](https://cloud.githubusercontent.com/assets/1061205/22674918/e7a30c72-ed25-11e6-8d9a-2b26c6ddb1cc.png)

it seems to be `ExtractTextPlugin.prototype.extract()` can't make `use` value for webpack2 bundler 

if i change 'use' to 'loader' (2word of upper example) show deprecated message but work fine.

3. Link to the project and mention Node version and OS in your report.

macOS sierra 10.12.3

**Comment by michael-ciniawsky** [comment]
@everedifice 

```diff
module: {
  rules: [{
    test: /\.css$/,
// { use: 'css-loader', options {...} } => ~.extract([ { loader: 'css-loader', {...} } ])
-  use: ExtractTextPlugin.extract({use: 'css-loader', options: {sourceMap: true}})
+  use: ExtractTextPlugin.extract({
+     fallback: 'style-loader',
+     use: [ { loader: 'css-loader', options: { sourceMap: true } }, ...]
+   })
  }]
}
```

**Comment by michael-ciniawsky** [comment]
Inside of a `rules.use[i]`  the loader `{Object}` still uses `loader` => `{ loader: 'name-loader', options: {} }`

**Comment by everedifice** [comment]
@michael-ciniawsky in that case. cause error on `RuleSet`

```js
  }, {
    test: /\.css$/,
    use: ExtractTextPlugin.extract({
      fallback: 'style-loader',
      use: [{loader: 'css-loader'}]
    })
  }, {
```
![2017-02-07 11 46 31](https://cloud.githubusercontent.com/assets/1061205/22675816/36b2750a-ed2b-11e6-89d2-08cf151a8198.png)

**Comment by michael-ciniawsky** [comment]
@everedifice `[ { loader: 'css-loader' } ] => [ 'css-loader' ]` you only need an `{Object}`  when using options **(but both should work)**, also the error is caused by `eslint-loader`, can you try without it please?

**Comment by michael-ciniawsky** [comment]
Guessing the error is thrown bc it should be like  `use: [ { loader: 'eslint-loader', options: { configFile: './.eslintrc'} } ]` instead of `{ use: [ 'eslint-loader' ], /* => options: { configFile: './.eslintrc'} <= */ }`

**Comment by everedifice** [comment]
I moved all options of loader to query string. `eslint-loader?configFile=./.eslintrc`, `file-loader?name=[name].[ext]` then works properly.

I think that options of library, plugins are not completely refactored. So i pass configuration to query string method for now.

```javascript
  rules: [{
    test: /\.js$/,
    exclude: /(node_modules|bower_components)/,
    enforce: 'pre',
    use: 'eslint-loader?configFile=./.eslintrc'
  }, {
    test: /\.js$/,
    exclude: /(node_modules|bower_components)/,
    use: 'babel-loader'
  }, {
    test: /\.css$/,
    use: ExtractTextPlugin.extract({use: 'css-loader'})
  }, {
    test: /\.hbs$/,
    use: 'handlebars-loader'
  }, {
    test: /\.(png|gif)$/,
    use: 'file-loader?name=share/img/[name].[ext]'
  }, {
    test: /\.(woff|ttf|eot)$/,
    use: 'file-loader?name=share/css/fonts/[name].[ext]'
  }]
```

**Comment by michael-ciniawsky** [comment]
```js
  rules: [{
    test: /\.js$/,
    exclude: /(node_modules|bower_components)/,
    enforce: 'pre',
   // In your example above this was the issue, bc you did /* 1 */
    use: [ { loader: 'eslint-loader', options: { configFile: './.eslintrc' } } ] // <= Fix
    /* 1
    use: 'eslint-loader',
    options: { configFile: './.eslintrc' } <= Error
    */
  }, {
    test: /\.js$/,
    exclude: /(node_modules|bower_components)/,
    use: 'babel-loader'
  }, {
    test: /\.css$/,
    use: ExtractTextPlugin.extract({ use: 'css-loader' })
  }, {
    test: /\.hbs$/,
    use: 'handlebars-loader'
  }, {
    test: /\.(png|gif)$/,
    // url-loader => size =< 8192 bytes ? DataURI : 'file-loader' 
    use: [ { loader: 'file-loader', options: { name: 'share/img/[name].[ext]', limit: 8192 } } ]
  }, {
    test: /\.(woff|ttf|eot)$/,
    // url-loader => size =< 8192 bytes ? DataURI : 'file-loader' 
    use: [ { loader: 'url-loader', options: { name: 'share/css/fonts/[name].[ext]', limit: 8192 } } ]
  }]
```

You can try it if you like and have the time, otherwise if it works for now please close the issue :)

**Comment by everedifice** [comment]
@michael-ciniawsky It works. thank you very much!
