### ISSUE TITLE
Relative path to images in css

### ISSUE THREAD

**Issue by demyan1411** [webpack-contrib/extract-text-webpack-plugin#396]
Hello!

I wont to get in production next directories
|-dist
|----assets
|---------js
|---------css
|---------images
|----index.html

And I make this directories, i have next code

`{
            test: /\.scss$/,
            loader: ExtractTextPlugin.extract('style-loader', 'css-loader!postcss-loader!resolve-url-loader!sass-loader?sourceMap', {
                publicPath: '../'
            })
        },`

`{
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'file',
        query: {
          limit: 10000,
          name: 'assets/images/[name].[ext]'
        }
      },`

`new ExtractTextPlugin('assets/css/[name].css', {
        allChunks: true
    }),`

and it all ok, but in css i have as result 
`background('../assets/images/...')`
BUT! i need 
`background('../images/...')`

How can i get it?

**Comment by scottdj92** [comment]
I'm not quite sure I understand. It looks like the `background('../images/...)` is referencing a different location?

I also want to ask why you are piping `resolve-url-loader` before `postcss-loader`.

Did you create your html file with `html-webpack-plugin`?

**Comment by bebraw** [comment]
Please re-open if still relevant.
