### ISSUE TITLE
Angular 2 throws 'cssText.replace is not a function' Exception

### ISSUE THREAD

**Issue by alvaro9210** [webpack-contrib/extract-text-webpack-plugin#397]
I have two projects: Project A and Project B.
Project A:
 - Webpack@2.2.1
 - Extract-text-webpack-plugin@2.0.0-rc.3
 - Angular 2.4.3

Project B
- Angular 2.4.3

Project B provides a series of modules/components to Project A. 
The code is compiled (not bundled) into a dist folder which then is being used by Project A via `npm link`.

Right now, with the `webpack.common.js` settings using the `ExtractTextPlugin` the browsers throws an Exception: 
![screen shot 2017-02-09 at 12 29 03 pm](https://cloud.githubusercontent.com/assets/4240006/22797476/fbb42774-eec3-11e6-94e6-f9a22f678e95.png)

This exception is being thrown by Angular 2, but **only** when this plugin is used.
I am saying this, because if I load `.css` extensions using `raw-loader` everything works fine, but when using ExtractTextPlugin, it just breaks.

**_VALID_**
-------------------------------------------------------------------------------------------------
webpack.config.js
```javascript
module: {
   rules: [
      {
         test: /\.css$/,
         use: [ "raw-loader" ],
      }
   }
}
```
Output:
![screen shot 2017-02-09 at 12 43 14 pm](https://cloud.githubusercontent.com/assets/4240006/22797895/a39f8be4-eec5-11e6-9424-134e25eff7aa.png)

**_INVALID (using ExtractTextPlugin)_**
-------------------------------------------------------------------------------------------------
webpack.config.js
```javascript
module: {
   rules: [
      {
         test: /\.css$/,
         use: ExtractTextPlugin.extract( {
                  fallback: "raw-loader",
                  use: [ "raw-loader" ]
         } )
      }
   }
},
plugins: [
   new ExtractTextPlugin( "[name].css" ),
]
```
Output:
![screen shot 2017-02-09 at 12 30 20 pm](https://cloud.githubusercontent.com/assets/4240006/22797961/d9036792-eec5-11e6-8cfb-5ec3be9655b8.png)
Exception thrown:
```
Uncaught TypeError: cssText.replace is not a function
    at extractStyleUrls (http://localhost:8080/vendor.js:75001:52)
```

Node: 6.2.0
OS: macOS Sierra (10.12.2)

**Comment by bebraw** [comment]
Instead of `use: [ "raw-loader" ]` you could use `use: "raw-loader"`, but I suspect it would fail even then.

I would need a standalone project to say anything concrete on this.

**Comment by bebraw** [comment]
I found https://github.com/angular/angular/blob/master/modules/@angular/compiler/src/style_url_resolver.ts . Based on the error that `cssText` is something else than a string (`undefined`?). That would be a good place for you to start debugging. Get a trace if possible.

**Comment by bebraw** [comment]
Any update?

**Comment by alvaro9210** [comment]
This is still not working and I still don't know why.
The exception, like you said, is being thrown by angular, but I don't know why when I use this plugin it's always returning an object as an argument of the `style_url_resolver.ts` `extractStyleUrls` function.
When I use a configuration for scss/css files without using the ExtractTextPlugin, everything works fine, but when using the loader it just doesn't work.

**This works:**
```typescript
{ 
    test: /\.s?css$/,
    use: [ "raw-loader", "sass-loader" ]
},
```

**This DOESN'T work:**
```typescript
{ 
    test: /\.s?css$/,
    // This doesn't work
    use: ExtractTextPlugin.extract( { fallback: "style-loader", use: [ "css-loader", "sass-loader" ] } )
    // This neither
    use: ExtractTextPlugin.extract( { fallback: "style-loader", use: [ "raw-loader", "sass-loader" ] } )
    // This neither
    use: ExtractTextPlugin.extract( { fallback: "raw-loader!sass-loader", use: [ "raw-loader", "sass-loader" ] } )
},
```

Now it's throwing an error while bundling, it says:
```
Invalid CSS after "module.exports": expected "{", was '= ":host {\\n  displ'
```

<img width="666" alt="screen shot 2017-02-20 at 5 06 14 pm" src="https://cloud.githubusercontent.com/assets/4240006/23144687/f22cda6a-f78e-11e6-9fa7-52946ceea0e8.png">

I stumbled up on this thread, which says that minimizing was causing the loader to return an object, but I am not doing that. So I really have no idea of what's going on...
https://github.com/react-toolbox/react-toolbox/issues/662#issuecomment-258467812
*carbonldp-panel-panel is my `ProjectB`

**Comment by bebraw** [comment]
There is some mismatch going on. Note that `ExtractTextPlugin.extract` returns an array of objects (new protocol). Earlier it returned a string query. Could Angular choke on that somehow?

**Comment by kb3eua** [comment]
I was able to get around this by adding 'to-string-loader' into the mix, like so:

`use: ['to-string-loader'].concat(ExtractTextPlugin.extract(...))`

**Comment by Van-Vu** [comment]
or     `styles: [require('./navmenu.component.scss').toString()]`

**Comment by michael-ciniawsky** [comment]
See @Van-Vu's comment, this is won't fix from the ETWP side of affairs

**Comment by michaeljpeake** [comment]
@kb3eua solution worked a charm for me. If someone could explain to me why this is, that would be great.

**Comment by Amos47** [comment]
What's the status on this? Still seeing the error. Is there a proper solution?

**Comment by evanjmg** [comment]
Any update on this?
