### ISSUE TITLE
publicPath doesn't work with 2.0.0-rc.3

### ISSUE THREAD

**Issue by jiayihu** [webpack-contrib/extract-text-webpack-plugin#399]
It seems that `publicPath` option is ignored:

```javascript
new ExtractTextPlugin("libs.css"),

// ...later

use: ExtractTextPlugin.extract({
  fallback: 'style-loader',
  use: 'css-loader',
  publicPath: 'assets'
}),
```

The file is still at `dist/libs.css`, using `dist` from webpack `output.publicPath` configuration.

**Comment by bebraw** [comment]
If you want to help, see carefully what happens at https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/6abf42da2dd57ab3e87c22f5b8d7ab345760a34e/loader.js#L47 .

**Comment by jiayihu** [comment]
I noticed that line, but it's not clear for me at which point `loader.js` is loaded (at least I can't see it used in `index.js`) and why there is still the `query` name now that we use `options`.
Would be nice to contribute/help anyway (:

**Comment by bebraw** [comment]
That `query` is legacy naming I think. Webpack 1 style config should still work although webpack 2 style is preferred.

**Comment by tmcmah1** [comment]
In case it helps, it looks to me like at line 47 referenced above, the following variables are:
query.publicPath:  **undefined** 
this._compilation.outputOptions.publicPath:  **/**

when I do a `cross-env NODE_ENV=production node build/build.js`

However, I believe the config settings that should have been used in my environment are:
  build: {
    env: require('./prod.env'),
    index: path.resolve(__dirname, '../dist/index.html'),
    assetsRoot: path.resolve(__dirname, '../dist'),
    assetsSubDirectory: 'assets',
    assetsPublicPath: **'/mdc-admin/'**,
    productionSourceMap: true,
    productionGzip: false,
    productionGzipExtensions: ['js', 'css']
  },

Hope that helps - this is new to me also, but it does seem to be ignoring the PublicPath setting.

Thanks!

**Comment by bebraw** [comment]
@tmcmah1 How are you setting `publicPath` for the plugin?

**Comment by tmcmah1** [comment]
In my webpack.base.conf.js file, I have the following:
output: {
    path: config.build.assetsRoot,
    **publicPath**: isProduction ? config.build.assetsPublicPath : config.dev.assetsPublicPath,
    filename: '[name].js'
  }

Update: I'm sorry, this is probably not a webpack issue, and probably is related to vuejs-templates.  And perhaps I just don't understand the differences between "assetsSubDirectory" and "assetsPublicPath" which seems to have been introduced by vuejs-templates.  But I was able to accomplish what I needed in the final built files by just changing `assetsSubDirectory` to the full destination path ('/webApp/assets/') and changing `assetsPublicPath` to ''
This seemed to solve the issue for me.

**Comment by bebraw** [comment]
I understand what's going on now. It writes `publicPath` correctly, but it fails to take that into account when emitting a file. That has to do with the way **file-loader** works. Based on its implementation it does **not** use `publicPath` when emitting. That explains the behavior.

Based on that I would say we cannot fix the issue at **extract-text-webpack-plugin** and should push it to **file-loader** instead. If its behavior changed, that would be a breaking change, but it could be a bug too.

Any thoughts on this @sokra?

**Comment by bebraw** [comment]
I think I figured this out. `publicPath` option applies only to the context in which `ExtractTextPlugin` runs. So you could use it to adjust each image path within CSS and so on.

To get the behavior you want, instead of `new ExtractTextPlugin("libs.css"),` you should use `new ExtractTextPlugin("assets/libs.css"),`.

**Comment by zcoding** [comment]
still not working.
I need to set the publicPath with a CDN prefix.

**Comment by bebraw** [comment]
@zcoding Can you open a separate issue with a runnable example?
