### ISSUE TITLE
extract Text Plugin and cscc Loader for Rc3

### ISSUE THREAD

**Issue by squadwuschel** [webpack-contrib/extract-text-webpack-plugin#401]
I was using "2.0.0-beta.4" with the following scss Loader that was working fine

       {
             test: /\.scss$/,
              loader: [
                    ExtractTextPlugin.extract({ fallbackLoader: 'style-loader', loader: ['css-loader'] }),
                        'to-string-loader',
                        'css-loader',
                        'sass-loader'
                    ],
                    exclude: [helpers.root('Content')],
                    include: [helpers.root('App')
        }

now I've updaed to version 2.0.0-Rc.3 and the Array of loaders is not allowed any more. I get a error message 

    Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
     - configuration.module.rules[6].use should be one of these:
       non-empty string | function | object { loader?, options?, query? } | function | [non-empty string | function | object { loader?, options?, query? }]

So I've tried this, but thats nor working, its compilling but then I get a Angular Error

      {
                    test: /\.scss$/,
                    use: ExtractTextPlugin.extract({
                        fallback: 'style-loader',
                        use: [{ loader: 'css-loader' }, { loader: 'sass-loader' }]
                    }),
                    exclude: [helpers.root('Content')],
                    include: [helpers.root('App')]
     },

the angular Error: Error: Expected 'styles' to be an array of strings. ....

Whats the best way to get the styleUrls in Angular 2 loaded ?

that are my current dev dependencies

 ```
 "devDependencies": {
    "@types/node": "6.0.51",
    "angular2-template-loader": "0.6.2",
    "awesome-typescript-loader": "3.0.3",
    "css-loader": "0.26.1",
    "css-to-string-loader": "0.1.2",
    "file-loader": "0.10.0",
    "url-loader": "0.5.7",
    "html-loader": "0.4.4",
    "svg-url-loader": "2.0.1",
    "less": "2.7.2",
    "less-loader": "2.2.3",
    "node-sass": "4.5.0",
    "sass-loader": "5.0.0",
    "style-loader": "0.13.1",
    "raw-loader": "0.5.1",
    "to-string-loader": "1.1.5",
    "clean-webpack-plugin": "0.1.4",
    "extract-text-webpack-plugin": "2.0.0-rc.3",
    "postcss-loader": "1.3.0",
    "postcss-import":  "9.1.0",
    "autoprefixer": "6.7.2",
    "html-webpack-plugin": "2.21.0",
    "webpack-notifier": "1.5.0",
    "webpack": "2.2.1",
    "webpack-dev-middleware": "1.10.0",
    "webpack-dev-server": "2.3.0",
    "webpack-md5-hash": "0.0.5",
    "webpack-merge": "2.3.0",
    "typescript": "2.0.10",
    "typings": "2.0.0"
  }

```

at the moment I am using postcss because the above postet code is not working with the current setup. But the you see all my used devdependencies

**Comment by bebraw** [comment]
Maybe you want

```javascript
use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: 'css-loader'
}).concat([
  'to-string-loader',
  'css-loader',
  'sass-loader'
])
```

Worth a go. I don't understand Angular enough to give a definite answer. I would need a project to run anything more.

**Comment by aminpaks** [comment]
You might try the `raw-loader` like this:

`
    use: [{ loader: 'raw-loader' }, { loader: 'css-loader' }, { loader: 'sass-loader' }]
`

For some reason Angular is not working with `css-loader` alone!

**Comment by squadwuschel** [comment]
@bebraw that I've tried its not working. When I've some time I will create a short example

**Comment by squadwuschel** [comment]
@aminpaks the problem is the ExtractText Plugin, when I don't use it I get it running with postcss loader

**Comment by davidanaya** [comment]
I'm getting the same error with this configuration
```
{
  test: /\.scss$/,
  use: ExtractTextPlugin.extract({
     fallback: 'style-loader',
     use: ['css-loader', 'resolve-url-loader', 'sass-loader?sourceMap']
  })
},
...
plugins: [
  ...
  new ExtractTextPlugin('app.css')
]
```
The app.css file is being generated but then I get the `Expected styles to be an array...` and the load does not load.

**Comment by davidanaya** [comment]
Ok, I see what is happening, but I don´t know if this is a buf or there's a way to fix this.
When I use this configuration
```
{
          test: /\.scss$/,
          use: ExtractTextPlugin.extract({
            fallback: 'style-loader',
            use: ['css-loader', 'sass-loader']
          })
        }
```
and I check into the bundle.js I see that the component has been transformed into this
```
AppComponent = __decorate([
    core_1.Component({
        selector: 'app-root',
        styles: [__webpack_require__(23)],
        template: "\n    <div class=\"app\">\n      Hello!\n    </div>\n  "
    })
], AppComponent);
```
and if I check module 23, it's empty
```
/* 23 */
/***/ (function(module, exports) {

// removed by extract-text-webpack-plugin

/***/ }),
```
this kind of makes sense, since all css is now extracted into an external file app.css, but then how to remove these `styles: [] ` property in the component? and actually, why is it giving an error? this is actually an array, an empty array.

**Comment by davidanaya** [comment]
You can use a [simple seed here](https://github.com/davidanaya/my-angular-seed) to test it (branch develop) and play with the configuration file for development in /config

**Comment by spyter** [comment]
@davidanaya I am having the exact same issue. If I manually add in the following module exports statement, it will work fine. Did you end up finding any resolution to this?

/* 23 */
/***/ (function(module, exports) {

// removed by extract-text-webpack-plugin
module.exports = "";
/***/ }),

**Comment by michael-ciniawsky** [comment]
The simple answer is that angular isn't really compatible with ETWP and the ETWP portion works correctly
