### ISSUE TITLE
CSS Modules in production mode

### ISSUE THREAD

**Issue by batmandarkside** [webpack-contrib/extract-text-webpack-plugin#403]
Hi all.
I can not solve the problem with CSS Modules and extract-text-webpack-plugin@2.0.0-rc.3
Different blocks of the same class Header

**NODE_ENV=development**
![2](https://cloud.githubusercontent.com/assets/897840/22885899/7ac67774-f20c-11e6-8f81-4b34dfd102d5.png)

**NODE_ENV=production**
![1](https://cloud.githubusercontent.com/assets/897840/22885905/80c4c428-f20c-11e6-9906-28c004819320.png)

![loaders js - rbo-front-app - pro rbo-front-app 2017-02-13 16-36-51](https://cloud.githubusercontent.com/assets/897840/22885910/873295f6-f20c-11e6-92dd-727693e9a26a.png)

![webpack common js - rbo-front-app - pro rbo-front-app 2017-02-13 16-37-54](https://cloud.githubusercontent.com/assets/897840/22885912/8ba72a5c-f20c-11e6-8a7e-b9ec26455096.png)

webpack@2.2.1
css-loader@0.26.1
extract-text-webpack-plugin@2.0.0-rc.3

**Comment by michael-ciniawsky** [comment]
@batmandarkside Could you try changing the `localIdent` to `[path]__[name]__[hash:base64:5]`  or the like ?
