### ISSUE TITLE
error when install extract-text-webpack-plugin

### ISSUE THREAD

**Issue by ramonmulia** [webpack-contrib/extract-text-webpack-plugin#408]
Guys, I was trying to install but I got this error:

 **extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none was installed.**

How can I resolve this?

**Comment by michael-ciniawsky** [comment]
@ramonmulia This should be a npm warning only that you need to install `webpack` :D, if you have webpack@^1.x` installed which I assume is the case it should work. For `webpack@^2.x` please install `extract-text-webpack-plugin@2.0.0-rc.3` to work properly

**Comment by bebraw** [comment]
Closing as this was answered. The webpack 2 version is still under development.
