### ISSUE TITLE
 "extract-text-webpack-plugin" loader is used error with webpack 2.

### ISSUE THREAD

**Issue by eldyvoon** [webpack-contrib/extract-text-webpack-plugin#412]
```
            test: /\.css$/,
            use: ExtractTextPlugin.extract({
                fallback: 'style-loader',
                use: ['css-loader','less-loader']
            }),
```

What is wrong here? I got this error : Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin

I also tried this

```
            test: /\.css$/,
            loader: ExtractTextPlugin.extract({
                fallback: 'style-loader',
                loader: ['css-loader','less-loader']
            }),
```

Nothing works :(, my webpack version is ```"webpack": "^2.1.0-beta.25",```

**Comment by dorin131** [comment]
@eldyvoon Try this
```
test: /\.css$/,
loader: ExtractTextPlugin.extract({
  fallback: 'style-loader',
  use: 'css-loader!less-loader'
}),
```

**Comment by eldyvoon** [comment]
@dorin131 tried your code but it doesn't work 

my package.json

"extract-text-webpack-plugin": "beta",
"webpack": "^2.1.0-beta.25",
"webpack-dev-server": "^2.1.0-beta.0",

**Comment by dorin131** [comment]
@eldyvoon 
I would also try to use the latest versions of these packages. Like this:
```
"extract-text-webpack-plugin": "^2.0.0-rc.3",
"webpack": "^2.2.1",
"webpack-dev-server": "^2.3.0"
```
delete you node_modules and reinstall

**Comment by dorin131** [comment]
@eldyvoon Have you installed `css-loader` and `less-loader`?

**Comment by eldyvoon** [comment]
@dorin131 yes I have them installed.

> "less-loader": "^2.2.3",
> "css-loader": "^0.23.1"

here's my whole webpack.dev.config.js http://pastebin.com/raw/SU2qi5JE

**Comment by dorin131** [comment]
@eldyvoon 
I think you should have "loaders" instead of "rules"
So try changing this
```
module: {
  rules: [
```
to
```
module: {
  loaders: [
```

**Comment by eldyvoon** [comment]
@dorin131  nope it still has the same error.

**Comment by eldyvoon** [comment]
@bebraw Which file you need?

**Comment by bebraw** [comment]
@eldyvoon I don't see how you are initializing the plugin. That's what the error is complaining about.

**Comment by dorin131** [comment]
@eldyvoon It looks like you're missing `new ExtractTextPlugin` in your plugins constant. Check the documentation.

**Comment by eldyvoon** [comment]
@dorin131 exactly! I missed this `plugins : ExtractTextPlugin("styles.css")` but I have no clue what's that style.css for.

**Comment by dorin131** [comment]
@eldyvoon That is where your styles are going to be saved to.

**Comment by eldyvoon** [comment]
@dorin131 I changed it to testingAbc.css, but after done compiling I don't see any testingAbc.css.

**Comment by dorin131** [comment]
@eldyvoon nothing in your /public folder?
are you still getting an error?

**Comment by scottdj92** [comment]
@eldyvoon Can you share your whole webpack config?

**Comment by Moocow89** [comment]
I am getting the same error:

![screen shot 2017-02-18 at 11 17 46 pm](https://cloud.githubusercontent.com/assets/17732223/23099375/f424991e-f632-11e6-930d-3ea20019b4d2.png)

But I am using the plugin in my config:

![screen shot 2017-02-18 at 2 11 41 pm](https://cloud.githubusercontent.com/assets/17732223/23099374/f4235842-f632-11e6-9f2f-66e5663b8aa5.png)

using the following versions: 
"extract-text-webpack-plugin": "^2.0.0-rc.3",
"webpack": "^2.2.1",

**Comment by eldyvoon** [comment]
@scottdj92 it worked now, I just missed 

```
plugins: [
      new ExtractTextPlugin('css/[name].css'),
]
```

**Comment by scottdj92** [comment]
@bebraw close this issue?

**Comment by bebraw** [comment]
Yeah, good call.

**Comment by Moocow89** [comment]
You never answered my problem

**Comment by scottdj92** [comment]
@Moocow89 Can you provide a repo so I can debug it? :)

**Comment by bebraw** [comment]
@Moocow89 Can you open a separate issue with a project to run? The configuration looks fine, but we are missing info.

**Comment by Moocow89** [comment]
sure, here is the repo:

https://github.com/Moocow89/portfolio-website

**Comment by Moocow89** [comment]
Added a new issue:

https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/417
