### ISSUE TITLE
Fallback loader is not used even if plugin is disabled

### ISSUE THREAD

**Issue by szimek** [webpack-contrib/extract-text-webpack-plugin#416]
I'm using `2.0.0-rc.3` and have `style-loader` set as the fallback loader, but even when the plugin is disabled, it still puts all styles in a blob instead of `<style>` element. I'm not sure what `allChunks` options actually does, but I tried it both ways and it always uses a blob. This unfortunately breaks loading of all assets referenced in CSS (I'm using absolute paths like `src: url(/fonts/proxima-1234.woff2`).

Here's my config:
```js
module.exports = {
  module: {
    rules: [{
      test: /\.(sass|scss)$/,
      use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: [{
          loader: 'css-loader',
          options: {
            autoprefixer: false,
            zindex: false,
            sourceMap: true,
          },
        }, {
          loader: 'postcss-loader',
        }, {
          loader: 'sass-loader',
        }],
      }),
    }],
  },

  plugins: [
    new ExtractTextPlugin({
      filename: '/css/[name]-[hash].css',
      disable: true,
      allChunks: false // true,
    }),
  ],
};
```

In which case is the fallback loader used exactly?

**Comment by scottdj92** [comment]
If you disable ExtractTextWebpackPlugin, webpack will revert back to its own CSS bundling in a blob and the loader you specify in your fallback is never used.

Are you trying to extract your CSS with only `style-loader`?

**Comment by szimek** [comment]
I'll explain what I'm actually trying to do ;)

Currently my config looks more or less like this:
```js
isDev ? {
  test:  /\.(sass|scss)$/,
  use: ['style-loader', 'css-loader', 'postcss-loader', 'sass-loader'],
} : {
  test:  /\.(sass|scss)$/,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: ['css-loader', 'postcss-loader', 'sass-loader'],
  )},
}
```
I hoped that I can have only one config for CSS instead, i.e. always use this plugin, but simply disable it in development. However, I can't figure out how to make this plugin to output styles inside `<style>` element and not in a blob.

**Comment by scottdj92** [comment]
You can replace `style-loader` with [inline-style-loader](https://www.npmjs.com/package/inline-style-loader) for your development config to have your styles loaded inline.

**Comment by szimek** [comment]
@scottdj92 Thanks for your help, but I don't understand 😕  Are you saying I should replace `fallback: 'style-loader'` with `fallback: 'inline-style-loader'`.

The code I posted above with separate configs for development and production works fine (i.e. in development I got `<style>` element with all styles inside and in production a <link> element with `src` pointint to `.css` file). I'd like to simplify this code and replace it with a single config that uses `ExtractTextPlugin` and simply uses `style-loader` fallback in development that would put all styles in `<style>` element and extract it to a `.css` file in production. Is it possible?

**Comment by scottdj92** [comment]
It's generally a better practice to separate configuration logic regarding different environments.

```js
isDev ? {
  test:  /\.(sass|scss)$/,
  use: ['inline-style-loader', 'css-loader', 'postcss-loader', 'sass-loader'],
} : {
  test:  /\.(sass|scss)$/,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: ['css-loader', 'postcss-loader', 'sass-loader'],
  )},
}```

ExtractTextPlugin is mainly used to extract CSS. Someone with more intimate knowledge of the plugin will need to answer this question, but I believe that what you're trying to do will take much more work and fiddling than separating them like you have now :)

**Comment by szimek** [comment]
@scottdj92 Thanks! I thought that when `disabled` option is on, this plugin will simply pass everything through defined loaders without doing much else.
