### ISSUE TITLE
Webpack throwing config validation error

### ISSUE THREAD

**Issue by Programmix** [webpack-contrib/extract-text-webpack-plugin#418]
Here's (most of) my webpack configuration:
![image](https://cloud.githubusercontent.com/assets/13167687/23153466/9f88364a-f7bd-11e6-8eaf-8909d3dd77be.png)

Here's the issue I'm experiencing:
![image](https://cloud.githubusercontent.com/assets/13167687/23152878/f212401c-f7b9-11e6-95a0-e1ca07c54143.png)

The issue, to my knowledge, seems to reside in the `.extract` function in the rules configuration.

**Comment by michael-ciniawsky** [comment]
```diff
{
   loader: 'css-loader',
-   query: {...}
+   options: { importLoaders: 2 , sourceMap: true, minimize: !__DEV__ }
}
{
   loader: 'sass-loader',
   options: {
     includePaths: '...'
+   sourceMap: __DEV___
   },
-   query: {
-     sourceMap: __DEV__
-  }
}
```

How does POSTCSS_OPTIONS look like ?

**Comment by Programmix** [comment]
Thanks for those changes!
![image](http://i.imgur.com/AzhMQms.png)
These are my POSTCSS_OPTIONS.

**Comment by michael-ciniawsky** [comment]
cssnano is used by css-loader internally when you set `minimize: true`, I think you can even pass these options (`POSTCSS_OPTIONS`) to `['css-loader'].minimize` directly => 

```js
{ loader: 'css-loader', options: {...options, minimze: !__DEV__ ? POSTCSS_OPTIONS : false } }
```

Anyways 😛 , does it build now ?

**Comment by Programmix** [comment]
Awesome, removed `postcss-loader` and it built successfully. Thank you so much. 😄
