### ISSUE TITLE
Module build failed: No input specified: provide a file name or a source string to process

### ISSUE THREAD

**Issue by xtianus79** [webpack-contrib/extract-text-webpack-plugin#422]
1. Check the version of package you are using. If it's not the newest version, update and try again (see changelog while updating!).
2. If the issue is still there, write a minimal project showing the problem and expected output.
3. Link to the project and mention Node version and OS in your report.
I am using this version of the plugin... 
 "extract-text-webpack-plugin": "^2.0.0-rc.3",

The error message is the following:
RROR in ./src/app/xxxxx/xxxxxx/xxxxx-xxxx.component.scss
Module build failed: No input specified: provide a file name or a source string to process
 @ ./src/app/components/global/xxxxx-xxxxx.component.ts 18:17-54
 @ ./src/app/components/xxxxxx/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:xxxxx webpack/hot/dev-server ./src/xxxxx.ts

Essentially if there is nothing in an scss file it will throw this error... for now i added body {} as a fill in... 

I believe a similiar issue is found here on StackOverflow:
http://stackoverflow.com/questions/42151205/webpack-extracttextplugin-extract-module-build-failed-no-input-specified-p

**Comment by scottdj92** [comment]
can you provide your webpack config?

**Comment by xtianus79** [comment]
here it is....

**Comment by scottdj92** [comment]
I mean your configuration file :)

**Comment by xtianus79** [comment]
@scottdj92 oh sorry :)

    module.exports = {
    entry: {
        'polyfills': './src/polyfills.ts',
        'vendor': './src/vendor.ts',
        'app': './src/main.ts'
    },

    resolve: {
        extensions: ['*', '.ts', '.js', 'scss', 'sass', '.json']
    },

    module: {
        loaders: [
            {
                test: /\.ts$/,
                loaders: ['awesome-typescript-loader', 'angular2-template-loader']
            },
            {
                test: /\.json$/, 
                loader: 'json-loader'
            },
            {
                test: /\.html$/,
                loader: 'html-loader'
            },
            {
                test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
                loader: 'file-loader?name=assets/[name].[hash].[ext]'
            },
            {
                test: /\.(scss|sass)$/,
                include: helpers.root('src/app'),
                exclude: [/\.global\.(scss|sass)$/, 'src'],
                loaders: ['raw-loader?sourceMap', 'sass-loader?sourceMap']
            },
            {
                test: /\.(scss|sass)$/,
                exclude: helpers.root('src/app'),
                loader: ExtractTextPlugin.extract({
                    fallbackLoader: 'isomorphic-style-loader',
                    loader: 'css-loader?sourceMap!sass-loader?sourceMap'
                })
            },
            {
                test: /\.css$/,
                exclude: helpers.root('src/app'),
                loader: ExtractTextPlugin.extract({ 
                    fallbackLoader: 'isomorphic-style-loader', 
                    loader: 'css-loader?sourceMap' 
                })
            },
            {
                test: /\.css$/,
                include: helpers.root('src/app'),
                loader: 'raw-loader'
            }
        ]
    },

    plugins: [
        new CheckerPlugin(),
        
        new webpack.optimize.CommonsChunkPlugin({
            name: ['app', 'vendor', 'polyfills']
        }),

        new HtmlWebpackPlugin({
            template: 'src/index.html'
        }),

        new webpack.ContextReplacementPlugin(
            // The (\\|\/) piece accounts for path separators in *nix and Windows
            /angular(\\|\/)core(\\|\/)(esm(\\|\/)src|src)(\\|\/)linker/,
            helpers.root('src') // location of your src
        ),

        new webpack.EnvironmentPlugin([
            "NODE_ENV",
            "URL",
            "BASEURL"
        ])

    ]
    };

**Comment by scottdj92** [comment]
ahh, the syntax changed from webpack 1 to webpack 2.

```js
  {
            test: /\.(scss|sass)$/,
            include: helpers.root('src/app'),
            exclude: [/\.global\.(scss|sass)$/, 'src'],
            use: ['raw-loader?sourceMap', 'sass-loader?sourceMap']
        },
```

**Comment by xtianus79** [comment]
so all loaders and loader should be use?

**Comment by scottdj92** [comment]
It should be, yes. Webpack should have thrown a warning informing you of this, but maybe the `sass-loader` threw an error before then, and prevented that behavior.

**Comment by xtianus79** [comment]
ok thanks, i will check this out

**Comment by scottdj92** [comment]
Yup! Webpack 2.2.1.

**Comment by xtianus79** [comment]
@scottdj92 this still did not do anything.  the error still persists

**Comment by scottdj92** [comment]
Oh, I missed this earlier. You need to add a `new ExtractTextPlugin({filename: '[name].css'});` in your `plugins` array.

**Comment by xtianus79** [comment]
@scottdj92 what is this option supposed to do... i will read up on it

**Comment by xtianus79** [comment]
i did what you were saying and it still doesn't work.  I didn't even notice anything different with what you were saying.

**Comment by scottdj92** [comment]
in `plugins: []` add `new ExtractTextPlugin({filename: '[name].css'});`. You need to create the plugin and give it a filename for it to extract text.

**Comment by stephenbaidu** [comment]
@xtianus79 Try adding any css to `src/index.scss`. I resolved this with:
```js
// src/index.scss
.a {}
```

**Comment by xtianus79** [comment]
@stephenbaidu i know this works but this is not an accurate solution.  this should not be happening

**Comment by michael-ciniawsky** [comment]
[#403](https://github.com/webpack-contrib/sass-loader/issues/403) should be fixed now

**Comment by qasimraza1979** [comment]
any reason why leaving scss file empty forces the build to get failed

**Comment by alexeycrystal** [comment]
The have the same issue. 
Thank's to stephenbaidu, problem is now solved. But I also don't think that this is a correct solution... must be another way to fix this.
