### ISSUE TITLE
DeprecationWarning .  --- extract-text-webpack-plugin + webpack 2.x

### ISSUE THREAD

**Issue by humorHan** [webpack-contrib/extract-text-webpack-plugin#427]
premise:
Webpack2.x extract-text-webpack-plugin2.0.0-rc.3
Throw as shown below warning, it is not found the reason.

![c6933aef-d47b-4ce5-b57d-2f06bfc5375d](https://cloud.githubusercontent.com/assets/10398024/23294238/5ca1a8e4-faa5-11e6-88f0-30963b332ee8.png)

**Comment by logicoder** [comment]
https://github.com/webpack/loader-utils/issues/56

**Comment by scottdj92** [comment]
@michael-ciniawsky @bebraw :shipit:

**Comment by humorHan** [comment]
@bebraw  Thank you very much for solving this problem, because it looks so bad。
