### ISSUE TITLE
lowerCased option filename doesnt make sense

### ISSUE THREAD

**Issue by dKab** [webpack-contrib/extract-text-webpack-plugin#430]
option names are inconsistant
I wonder why it is `ignoreOrder` and `allChunks` (camelCase), but `filename`. I mean shouldn't it also be `fileName`? I understand that renaming it would break existing configs, but we could add alias fileName which would also work.

**Comment by ryanwilsonperkin** [comment]
@dKab `filename` is actually considered correct english spelling
see: https://en.wikipedia.org/wiki/Filename

**Comment by dKab** [comment]
@ryanwilsonperkin Very interesting, I didn't know that, my apologies.

**Comment by scottdj92** [comment]
Thanks for your input! Closing this issue. Re-open if you want to discuss it again.
