### ISSUE TITLE
How to minify the css file extract by extract-text-webpack-plugin?

### ISSUE THREAD

**Issue by qidaneix** [webpack-contrib/extract-text-webpack-plugin#434]
I use webpack@2.2.1 and extract-text-webpack-plugin to extract css into a separate .css file. I have read the document but I can find a way to minify the .css file. How to do it?

**Comment by michael-ciniawsky** [comment]
@qidaneix Set the minimize option in `css-loader` 

```diff 
+ { loader: 'css-loader', options: { minimize: true } )
``` 

or use `postcss-loader`+ `cssnano`,  `csso-loader` etc. `ExtractTextPlugin` has nothing to do with minification, it's just for extraction regardless if contents are minified or not. 😛

**Comment by albertogasparin** [comment]
@qidaneix @michael-ciniawsky 
The downside of `css-loader` is that the minification is per included file, not global. If you like to have the entire css bundle minified I would suggest you to have a look at [OptimizeCssAssetsPlugin](https://github.com/NMFR/optimize-css-assets-webpack-plugin).

**Comment by armandoborge** [comment]
Despite this issue is closed, maybe this code can help other developers looking for the same:
```

module: {
            rules: [
                {
                    test: /\.css$/,
                    use: ExtractTextPlugin.extract({
                        fallback: 'style-loader',
                        use: [
                            { loader: 'css-loader', options: { minimize: true } }
                        ]
                    })
                }
           ]
}
```

**Comment by chhaymenghong** [comment]
@albertogasparin I tried using OptimizeCssAssetsPlugin, but it seems to embed the sourcemap information inside the css bundle itself and as a result increase the bundle size. Any ideas on how to use sourceMap url instead?

**Comment by albertogasparin** [comment]
@chhaymenghong I'm actually turning css source maps off on production. You already [reported it](https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/33), so let's see what the owner has to say

**Comment by X-Y** [comment]
For anybody using css-loader 1.0.0, the minimize options is removed and you have to use postcss + cssnano instead. 
https://github.com/webpack-contrib/css-loader/blob/43179a82c88532bf93ccfafb4f78c10cdb80cbf7/CHANGELOG.md
