### ISSUE TITLE
css extracted incorrectly when using split chunks

### ISSUE THREAD

**Issue by kostasmanionis** [webpack-contrib/extract-text-webpack-plugin#436]
I'm not entirely sure if this is a bug(might not even be related to this plugin), but I think it should be pretty easy to identify. I've setup a repro case here https://github.com/kostasmanionis/webpack-extract-import

## The setup
Two entry files. Each one imports a module(`asyncModuleLoader.js`) that loads another module on demand(`asyncModule.js`). BUT one of the entry files also imports a third module(`randomModule.js`), that imports some of the on demand module styles(`asyncModule.scss`).

## What I'm getting

An async chunk `0.js` that's a child of both entry files, but the css only get extracted to `user.scss` chunk file.

## What I'm expecting
Same structure, but the css should be in both chunk css files, `user.scss` & `home.scss`.

**Comment by evilebottnawi** [comment]
@kostasmanionis do your have solution for this? PR welcome!

**Comment by kostasmanionis** [comment]
Didn't have a solution at the time that I filed this issue, I somehow ended up solving this problem for myself lol. Might as well get back to this, maybe I'll figure something out
