### ISSUE TITLE
With latest extract text plugin, css loader is failing

### ISSUE THREAD

**Issue by KalpanaPagariya** [webpack-contrib/extract-text-webpack-plugin#439]
Using below in package.json:
 "extract-text-webpack-plugin": "^2.0.0",
 "file-loader": "^0.10.1",
    "style-loader": "^0.13.2",
    "url-loader": "^0.5.8",
"css-loader": "^0.26.2",
webpack.config.js:

{ test: /\.css$/,
        loader: ExtractTextPlugin.extract("css?minimize|style-loader")

      },

Now its failing on
ERROR in ./src/com/components/index.js
Module not found: Error: Can't resolve 'css?minimize|style-loader' 

Before updating new release of extract text plugin, it was working. Please help to resolve this issue

**Comment by michael-ciniawsky** [comment]
@KalpanaPagariya webpack version and full `webpack.config.js` please 😛 , in case you're using webpack >= `v2.0.0`, try this

**webpack.config.js**
```js
{
   test: /\.css$/,
   use: ExtractTextPlugin.extract({
      fallback: 'style-loader',
      use: [ 
         { loader: 'css-loader', options: { minimize: true } } 
      ]
   })
}
```

**Comment by KalpanaPagariya** [comment]
Thanks for update. 
"dependencies": {
    "react": "^15.4.2",
    "react-bootstrap-table": "^3.0.0",
    "react-dom": "^15.4.2"
  },
  "devDependencies": {
    "babel-core": "^6.23.1",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^6.3.2",
    "babel-polyfill": "^6.23.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-react": "^6.23.0",
    "babel-preset-stage-0": "^6.22.0",
    "babel-register": "^6.23.0",
    "css-loader": "^0.26.2",
    "express": "^4.14.1",
    "extract-text-webpack-plugin": "^2.0.0",
    "file-loader": "^0.10.1",
    "style-loader": "^0.13.2",
    "url-loader": "^0.5.8",
    "webpack": "^2.2.1",
    "webpack-dev-middleware": "^1.10.1"
  }

After suggesting your changes, now build is not failing. but now style.css file is not getting created. what could be the reason? webpack.config.js below

var path = require('path');
var webpack = require('webpack');
var ExtractTextPlugin = require("extract-text-webpack-plugin");


module.exports = {
  devtool: 'source-map',
  entry: [
  //  'webpack-dev-server/client?http://localhost:8080/', // WebpackDevServer host and port
  //   'webpack/hot/only-dev-server', // "only" prevents reload on syntax errors
    './src/com/components/index'],
  output: {
    filename: 'bundle.js',
    path: path.join(__dirname, '/public'),
    publicPath: 'http://localhost:8080/public/'
  },
  module: {
    loaders: [
      { test: /\.js$/, loaders: ['babel-loader'] ,  exclude: /node_modules/},
     {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
            fallback: 'style-loader',
            use: [ 
              { loader: 'css-loader', options: { minimize: true } } 
            ]
        })
      },
      { test: /\.png$/, loader: "url-loader?limit=100000" }
     
        
    ]
  },

  plugins: [
   new ExtractTextPlugin({filename:'style.css',  allChunks: true }),
   //new webpack.HotModuleReplacementPlugin()
   
 ]

};

**Comment by horaciom** [comment]
Have the same problem that @KalpanaPagariya

**Comment by bebraw** [comment]
Can you try `use: { loader: 'css-loader', options: { minimize: true } } `?

**Comment by bebraw** [comment]
Feel free to re-open with a runnable example (mentioned in issue template).
