### ISSUE TITLE
Module build failed: Unknown word

### ISSUE THREAD

**Issue by joetidee** [webpack-contrib/extract-text-webpack-plugin#441]
After running `npm build` I get this (webpack v2.2.1 and extract-text-webpack-plugin v2.0.0):

```
ERROR in ./~/css-loader!./~/extract-text-webpack-plugin/loader.js?{"id":1,"omit":1,"remove":true}!./~/style-loader!./~/css-loader?{"minimize":true}!./client/src/css/fonts.css
Module build failed: Unknown word (5:1)

  3 | // load the styles
  4 | var content = require("!!../../../node_modules/css-loader/index.js?{\"minimize\":true}!./fonts.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | // add the styles to the DOM
  7 | var update = require("!../../../node_modules/style-loader/addStyles.js")(content, {});
  8 | if(content.locals) module.exports = content.locals;

 @ ./client/src/css/fonts.css 4:14-248
 @ ./client/src/app.jsx
 @ multi ./client/src/app.jsx
```

I'm assuming that it is referring to fonts.css, so here is the file:

```
@font-face {
    font-family: 'cabinmedium';
    src: url('../fonts/cabin_medium/Cabin-Medium-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}
@font-face {
    font-family: 'cabinbold';
    src: url('../fonts/cabin_bold/Cabin-Bold-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}
@font-face {
    font-family: 'lato_bold';
    src: url('../fonts/lato_bold/lato-bold-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}
@font-face {
    font-family: 'open_sansregular';
    src: url('../fonts/opensans_regular/OpenSans-Regular-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}
```

**Comment by bebraw** [comment]
It's hard to say anything without have full config and ideally a project to study.

**Comment by joetidee** [comment]
Here is my webpack.config.js file:

```
// hack for Ubuntu on Windows
try {
    require('os').networkInterfaces();
}
catch (e) {
    require('os').networkInterfaces = () => ({});
}

const path = require('path');
const merge = require("webpack-merge");
const webpack = require("webpack");
var nodeExternals = require('webpack-node-externals');

const TARGET = process.env.npm_lifecycle_event;
const PATHS = {
    app: path.join(__dirname, '/client/src/app.jsx'),
    build: path.join(__dirname, '/client/dist'),
    test: path.join(__dirname, '/client/tests')
};


const common = {
    entry: [
        PATHS.app
    ],
    output: {
        path: PATHS.build
    },
    module: {
        rules: [{
            test: /\.js?$/,
            use: ['babel-loader'],
            include: path.join(__dirname, '/shared')
        },{
            test: /\.jsx?$/,
            use: ['react-hot-loader','babel-loader?' + JSON.stringify({
                presets: ["es2015", "stage-0", "react"]
            })],
            include: path.join(__dirname, '/client/src')
        },{
            test: /\.less$/,
            use: ['style-loader', 'css-loader', 'less-loader']
        },
        {
            test: /\.ico$/,
            use: ["file-loader"]
        },
        {
            test: /\.png$/,
            use: ["url-loader?limit=100000"]
        },
        {
            test: /\.jpg$/,
            use: ["file-loader"]
        },
        {
            test: /\.(woff|woff2)(\?v=\d+\.\d+\.\d+)?$/,
            use: ["url-loader?limit=10000&mimetype=application/font-woff"]
        },
        {
            test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
            use: ["url-loader"]
        },
        {
            test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
            use: ["file-loader"]
        },
        {
            test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
            use: ["url-loader?limit=10000&mimetype=image/svg+xml"]
        },{
            test: /\.css$/,
            use: ['style-loader', 'css-loader']
        }]
    },
    plugins: [
        new webpack.ProvidePlugin({
            "$":"jquery",
            "jQuery":"jquery",
            'global.jQuery': 'jquery'
        }),
        new webpack.DefinePlugin({ 'typeof window': '\"object\"' })
    ],
    resolve: {
        extensions: ['.js', '.jsx', '.less', '.css'],
        alias: {
            'jquery-ui': 'jquery-ui-dist/jquery-ui.js'
        }
    }
};

// Default config.
if(TARGET === 'start' || TARGET){
    module.exports = merge(common, {
        devtool: 'eval-source-map',
        entry: [
            'eventsource-polyfill',
            'webpack-hot-middleware/client',
            'webpack/hot/only-dev-server',
            'babel-polyfill'
        ],
        output: {
            filename: 'app.js',
            publicPath: '/public/'
        },
        plugins: [
            new webpack.HotModuleReplacementPlugin(),
            new webpack.DefinePlugin({
                'process.env': {
                    'NODE_ENV': JSON.stringify('development')
                }
            })
        ],
        resolve: {
            modules: [
                path.resolve('./client/src'),
                "node_modules"
            ]
        },
        watch: true
    });
}

// Tests config.
if(TARGET === 'test' || TARGET === 'tdd' || TARGET === 'test-mocha'){
    module.exports = merge(common, {
        devtool: "cheap-module-source-map", // faster than 'source-map'
        externals: [
            nodeExternals(), // in order to ignore all modules in node_modules folder.
            {
                'react/addons': true,
                'react/lib/ExecutionEnvironment': true,
                'react/lib/ReactContext': true
            }
        ],
        output: {
            // sourcemap support for IntelliJ/Webstorm
            devtoolModuleFilenameTemplate: '[absolute-resource-path]',
            devtoolFallbackModuleFilenameTemplate: '[absolute-resource-path]?[hash]'
        },
        resolve: {
            alias: {
                'app': PATHS.app
            }
        },
        module: {
            rules: [
                {
                    test: /\.js$/,
                    use: ["babel-loader"]
                },
                {
                    test: /\.jsx?$/,
                    use: ['babel-loader?cacheDirectory']
                }
            ]
        },
        target: 'node' // in order to ignore built-in modules like path, fs, etc.
    });
}

// Build config.
if(TARGET === 'build' || TARGET === 'stats'){
    var CompressionPlugin = require('compression-webpack-plugin');
    const HtmlWebpackPlugin = require('html-webpack-plugin');
    const CleanPlugin = require('clean-webpack-plugin');
    const ExtractTextPlugin = require('extract-text-webpack-plugin');
    const extractCSS = new ExtractTextPlugin('styles.css');
    const Visualizer = require('webpack-visualizer-plugin');
    //const pkg = require("./package.json");

    module.exports = merge(common, {
        entry: [
            /*vendor: Object.keys(pkg.dependencies).filter(function (v) {
             return v;
             }),*/
        ],
        module: {
            rules: [
                {
                    test: /\.css$/,
                    use: extractCSS.extract({
                        fallback: 'style-loader',
                        use: [
                            { loader: 'css-loader', options: { minimize: true } }
                        ]
                    })
                }
            ]
        },
        output: {
            filename: 'app.[chunkhash].js',
            /*filename: '[name].js',*/
            publicPath: 'http://auditor.tidee.com/public/'
        },
        plugins: [
            new webpack.DefinePlugin({
                'process.env': {
                    'NODE_ENV': JSON.stringify('production')
                }
            }),
            new webpack.optimize.UglifyJsPlugin(),
            /*new webpack.optimize.AggressiveMergingPlugin(), //Merge chunks*/
            new CompressionPlugin({
                asset: "[path].gz[query]",
                algorithm: "gzip",
                test: /\.js$|\.css$|\.html$/,
                threshold: 10240,
                minRatio: 0.8
            }),
            new HtmlWebpackPlugin({
                template: 'node_modules/html-webpack-template/index.ejs',
                title: 'Tidee',
                appMountId: 'app',
                inject: false
            }),
            new CleanPlugin(path.join(__dirname, '/client/dist')),
            new ExtractTextPlugin('[name].[chunkhash].css'),
            new Visualizer({
                filename: './statistics.html'
            })
        ],
        resolve: {
            modules: [
                path.resolve('./client/dist'),
                "node_modules"
            ]
        }
    });
}
```

**Comment by bebraw** [comment]
@joetidee You have `new ExtractTextPlugin('[name].[chunkhash].css'),` without `ExtractTextPlugin.extract` and `extractCSS.extract` without `extractCSS()`. Your plugin and loader are disconnected (both are missing a pair). You should fix either and remove the remaining as instructed in the documentation.

**Comment by joetidee** [comment]
ok, I adjusted the webpack.config.js file in line with the instructions as follows:

```
// hack for Ubuntu on Windows
try {
    require('os').networkInterfaces();
}
catch (e) {
    require('os').networkInterfaces = () => ({});
}

const path = require('path');
const merge = require("webpack-merge");
const webpack = require("webpack");
var nodeExternals = require('webpack-node-externals');

const TARGET = process.env.npm_lifecycle_event;
const PATHS = {
    app: path.join(__dirname, '/client/src/app.jsx'),
    build: path.join(__dirname, '/client/dist'),
    test: path.join(__dirname, '/client/tests')
};


const common = {
    entry: [
        PATHS.app
    ],
    output: {
        path: PATHS.build
    },
    module: {
        rules: [{
            test: /\.js?$/,
            use: ['babel-loader'],
            include: path.join(__dirname, '/shared')
        },{
            test: /\.jsx?$/,
            use: ['react-hot-loader','babel-loader?' + JSON.stringify({
                presets: ["es2015", "stage-0", "react"]
            })],
            include: path.join(__dirname, '/client/src')
        },{
            test: /\.less$/,
            use: ['style-loader', 'css-loader', 'less-loader']
        },
        {
            test: /\.ico$/,
            use: ["file-loader"]
        },
        {
            test: /\.png$/,
            use: ["url-loader?limit=100000"]
        },
        {
            test: /\.jpg$/,
            use: ["file-loader"]
        },
        {
            test: /\.(woff|woff2)(\?v=\d+\.\d+\.\d+)?$/,
            use: ["url-loader?limit=10000&mimetype=application/font-woff"]
        },
        {
            test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
            use: ["url-loader"]
        },
        {
            test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
            use: ["file-loader"]
        },
        {
            test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
            use: ["url-loader?limit=10000&mimetype=image/svg+xml"]
        },{
            test: /\.css$/,
            use: ['style-loader', 'css-loader']
        }]
    },
    plugins: [
        new webpack.ProvidePlugin({
            "$":"jquery",
            "jQuery":"jquery",
            'global.jQuery': 'jquery'
        }),
        new webpack.DefinePlugin({ 'typeof window': '\"object\"' })
    ],
    resolve: {
        extensions: ['.js', '.jsx', '.less', '.css'],
        alias: {
            'jquery-ui': 'jquery-ui-dist/jquery-ui.js'
        }
    }
};

// Default config.
if(TARGET === 'start' || TARGET){
    module.exports = merge(common, {
        devtool: 'eval-source-map',
        entry: [
            'eventsource-polyfill',
            'webpack-hot-middleware/client',
            'webpack/hot/only-dev-server',
            'babel-polyfill'
        ],
        output: {
            filename: 'app.js',
            publicPath: '/public/'
        },
        plugins: [
            new webpack.HotModuleReplacementPlugin(),
            new webpack.DefinePlugin({
                'process.env': {
                    'NODE_ENV': JSON.stringify('development')
                }
            })
        ],
        resolve: {
            modules: [
                path.resolve('./client/src'),
                "node_modules"
            ]
        },
        watch: true
    });
}

// Tests config.
if(TARGET === 'test' || TARGET === 'tdd' || TARGET === 'test-mocha'){
    module.exports = merge(common, {
        devtool: "cheap-module-source-map", // faster than 'source-map'
        externals: [
            nodeExternals(), // in order to ignore all modules in node_modules folder.
            {
                'react/addons': true,
                'react/lib/ExecutionEnvironment': true,
                'react/lib/ReactContext': true
            }
        ],
        output: {
            // sourcemap support for IntelliJ/Webstorm
            devtoolModuleFilenameTemplate: '[absolute-resource-path]',
            devtoolFallbackModuleFilenameTemplate: '[absolute-resource-path]?[hash]'
        },
        resolve: {
            alias: {
                'app': PATHS.app
            }
        },
        module: {
            rules: [
                {
                    test: /\.js$/,
                    use: ["babel-loader"]
                },
                {
                    test: /\.jsx?$/,
                    use: ['babel-loader?cacheDirectory']
                }
            ]
        },
        target: 'node' // in order to ignore built-in modules like path, fs, etc.
    });
}

// Build config.
if(TARGET === 'build' || TARGET === 'stats'){
    const CompressionPlugin = require('compression-webpack-plugin');
    const HtmlWebpackPlugin = require('html-webpack-plugin');
    const CleanPlugin = require('clean-webpack-plugin');
    const ExtractTextPlugin = require("extract-text-webpack-plugin");
    const Visualizer = require('webpack-visualizer-plugin');

    module.exports = merge(common, {
        module: {
            rules: [
                {
                    test: /\.css$/,
                    use: ExtractTextPlugin.extract({
                        fallback: "style-loader",
                        use: "css-loader"
                    })
                }
            ]
        },
        output: {
            filename: 'app.[chunkhash].js',
            publicPath: 'http://auditor.tidee.com/public/'
        },
        plugins: [
            new webpack.DefinePlugin({
                'process.env': {
                    'NODE_ENV': JSON.stringify('production')
                }
            }),
            new webpack.optimize.UglifyJsPlugin(),
            new CompressionPlugin({
                asset: "[path].gz[query]",
                algorithm: "gzip",
                test: /\.js$|\.css$|\.html$/,
                threshold: 10240,
                minRatio: 0.8
            }),
            new HtmlWebpackPlugin({
                template: 'node_modules/html-webpack-template/index.ejs',
                title: 'Tidee',
                appMountId: 'app',
                inject: false
            }),
            new CleanPlugin(path.join(__dirname, '/client/dist')),
            new ExtractTextPlugin("styles.css"),
            new Visualizer({
                filename: './statistics.html'
            })
        ],
        resolve: {
            modules: [
                path.resolve('./client/dist'),
                "node_modules"
            ]
        }
    });
}
```

and here is the output:

> Hash: 969bc3719ebbd67f42c9
> Version: webpack 2.2.1
> Time: 48233ms
>                                  Asset       Size  Chunks                    Chunk Names
>  f2bce001e16fa48466239a51378474d1.woff      28 kB          [emitted]
>  6a00de061f4fcc2ae24f25da53a02f4d.woff    13.2 kB          [emitted]
>   f4769f9bdb7466be65088239c12046d1.eot    20.1 kB          [emitted]
>  fa2772327f55d8198301fdb8bcfc8158.woff    23.4 kB          [emitted]
> 448c34a56d699c29117adc64c43affeb.woff2      18 kB          [emitted]
>   89889688147bd7575d6327160d64e760.svg     109 kB          [emitted]
>  1fff7dfa22a6c8ba9382ad03726139d3.woff    27.1 kB          [emitted]
> 9b281482a6fbc52739698e0c130ea52a.woff2    11.3 kB          [emitted]
>  36eeac2edc10f0533f49c8e008896e40.woff    38.4 kB          [emitted]
>  79515ad0788973c533405f7012dfeccd.woff    22.7 kB          [emitted]
>            app.820083ac2b53c8260b0b.js    1.98 MB       0  [emitted]  [big]  main
>                             styles.css     255 kB       0  [emitted]  [big]  main
>                          styles.css.gz    57.1 kB          [emitted]
>         app.820083ac2b53c8260b0b.js.gz     505 kB          [emitted]  [big]
>                             index.html  867 bytes          [emitted]
>    [0] ./~/react/react.js 56 bytes {0} [built]
>   [23] ./~/react-dom/index.js 59 bytes {0} [built]
>   [24] (webpack)/buildin/global.js 509 bytes {0} [built]
>   [30] ./~/jquery/dist/jquery.js 267 kB {0} [built]
>   [39] ./~/react-intl/lib/index.es.js 55 kB {0} [built]
>  [240] ./~/intl/index.js 574 bytes {0} [built]
>  [447] ./client/src/app.jsx 19.1 kB {0} [built]
>  [529] ./~/bootstrap/dist/js/bootstrap.js 69.7 kB {0} [built]
>  [579] ./~/intl-locales-supported/index.js 925 bytes {0} [built]
>  [828] ./client/src/helpers/loadTranslation.js 1.68 kB {0} [built]
>  [836] ./client/src/routes.js 5.81 kB {0} [built]
>  [838] ./~/react-intl/locale-data/en.js 7.15 kB {0} [built]
>  [916] ./~/bootstrap/dist/css/bootstrap.css 1.24 kB {0} [built]
>  [918] ./client/src/css/tidee-app.less 1.07 kB {0} [built]
>  [930] multi ./client/src/app.jsx 28 bytes {0} [built]
>     + 918 hidden modules
> 
> ERROR in ./~/css-loader!./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/style-loader!./~/css-loader!./~/bootstrap/dist/css/bootstrap.css
> Module build failed: Unknown word (5:1)
> 
>   3 | // load the styles
>   4 | var content = require("!!../../../css-loader/index.js!./bootstrap.css");
> > 5 | if(typeof content === 'string') content = [[module.id, content, '']];
>     | ^
>   6 | // add the styles to the DOM
>   7 | var update = require("!../../../style-loader/addStyles.js")(content, {});
>   8 | if(content.locals) module.exports = content.locals;
> 
>  @ ./~/bootstrap/dist/css/bootstrap.css 4:14-189
>  @ ./client/src/app.jsx
>  @ multi ./client/src/app.jsx
> 
> ERROR in ./~/css-loader!./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/style-loader!./~/css-loader!./client/src/css/fonts.css
> Module build failed: Unknown word (5:1)
> 
>   3 | // load the styles
>   4 | var content = require("!!../../../node_modules/css-loader/index.js!./fonts.css");
> > 5 | if(typeof content === 'string') content = [[module.id, content, '']];
>     | ^
>   6 | // add the styles to the DOM
>   7 | var update = require("!../../../node_modules/style-loader/addStyles.js")(content, {});
>   8 | if(content.locals) module.exports = content.locals;
> 
>  @ ./client/src/css/fonts.css 4:14-237
>  @ ./client/src/app.jsx
>  @ multi ./client/src/app.jsx
> 
> ERROR in ./~/css-loader!./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/style-loader!./~/css-loader!./client/src/css/animate.css
> Module build failed: Unknown word (5:1)
> 
>   3 | // load the styles
>   4 | var content = require("!!../../../node_modules/css-loader/index.js!./animate.css");
> > 5 | if(typeof content === 'string') content = [[module.id, content, '']];
>     | ^
>   6 | // add the styles to the DOM
>   7 | var update = require("!../../../node_modules/style-loader/addStyles.js")(content, {});
>   8 | if(content.locals) module.exports = content.locals;
> 
>  @ ./client/src/css/animate.css 4:14-239
>  @ ./client/src/app.jsx
>  @ multi ./client/src/app.jsx
> 
> ERROR in ./~/css-loader!./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/style-loader!./~/css-loader!./client/src/fontello/css/animation.css
> Module build failed: Unknown word (5:1)
> 
>   3 | // load the styles
>   4 | var content = require("!!../../../../node_modules/css-loader/index.js!./animation.css");
> > 5 | if(typeof content === 'string') content = [[module.id, content, '']];
>     | ^
>   6 | // add the styles to the DOM
>   7 | var update = require("!../../../../node_modules/style-loader/addStyles.js")(content, {});
>   8 | if(content.locals) module.exports = content.locals;
> 
>  @ ./client/src/fontello/css/animation.css 4:14-253
>  @ ./client/src/app.jsx
>  @ multi ./client/src/app.jsx
> 
> ERROR in ./~/css-loader!./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/style-loader!./~/css-loader!./client/src/fontello/css/fontello.css
> Module build failed: Unknown word (5:1)
> 
>   3 | // load the styles
>   4 | var content = require("!!../../../../node_modules/css-loader/index.js!./fontello.css");
> > 5 | if(typeof content === 'string') content = [[module.id, content, '']];
>     | ^
>   6 | // add the styles to the DOM
>   7 | var update = require("!../../../../node_modules/style-loader/addStyles.js")(content, {});
>   8 | if(content.locals) module.exports = content.locals;
> 
>  @ ./client/src/fontello/css/fontello.css 4:14-252
>  @ ./client/src/app.jsx
>  @ multi ./client/src/app.jsx
> 
> ERROR in ./~/css-loader!./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/style-loader!./~/css-loader!./client/src/css/select2.css
> Module build failed: Unknown word (5:1)
> 
>   3 | // load the styles
>   4 | var content = require("!!../../../node_modules/css-loader/index.js!./select2.css");
> > 5 | if(typeof content === 'string') content = [[module.id, content, '']];
>     | ^
>   6 | // add the styles to the DOM
>   7 | var update = require("!../../../node_modules/style-loader/addStyles.js")(content, {});
>   8 | if(content.locals) module.exports = content.locals;
> 
>  @ ./client/src/css/select2.css 4:14-239
>  @ ./client/src/components/AuditTemplateListFilterModal.jsx
>  @ ./client/src/containers/AuditTemplateListFilterModalContainer.jsx
>  @ ./client/src/components/AuditTemplateList.jsx
>  @ ./client/src/routes.js
>  @ ./client/src/app.jsx
>  @ multi ./client/src/app.jsx
> 
> ERROR in ./~/css-loader!./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/style-loader!./~/css-loader!./client/src/css/select2.css
> Module build failed: Unknown word (1:1)
> 
> > 1 | // removed by extract-text-webpack-plugin
>     | ^
> 
> 
> ERROR in ./~/css-loader!./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/style-loader!./~/css-loader!./client/src/css/animate.css
> Module build failed: Unknown word (1:1)
> 
> > 1 | // removed by extract-text-webpack-plugin
>     | ^
> 
> 
> ERROR in ./~/css-loader!./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/style-loader!./~/css-loader!./client/src/fontello/css/animation.css
> Module build failed: Unknown word (1:1)
> 
> > 1 | // removed by extract-text-webpack-plugin
>     | ^
> 
> 
> ERROR in ./~/css-loader!./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/style-loader!./~/css-loader!./client/src/fontello/css/fontello.css
> Module build failed: Unknown word (1:1)
> 
> > 1 | // removed by extract-text-webpack-plugin
>     | ^
> 
> 
> ERROR in ./~/css-loader!./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/style-loader!./~/css-loader!./~/bootstrap/dist/css/bootstrap.css
> Module build failed: Unknown word (1:1)
> 
> > 1 | // removed by extract-text-webpack-plugin
>     | ^
> 
> 
> ERROR in ./~/css-loader!./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/style-loader!./~/css-loader!./client/src/css/fonts.css
> Module build failed: Unknown word (1:1)
> 
> > 1 | // removed by extract-text-webpack-plugin
>     | ^
> 
> Child html-webpack-plugin for "index.html":
>        [0] ./~/lodash/lodash.js 540 kB {0} [built]
>        [1] (webpack)/buildin/global.js 509 bytes {0} [built]
>        [2] (webpack)/buildin/module.js 517 bytes {0} [built]
>        [3] ./~/html-webpack-plugin/lib/loader.js!./~/html-webpack-template/index.ejs 6.74 kB {0} [built]
> Child extract-text-webpack-plugin:
>        [0] ./~/css-loader/lib/css-base.js 1.46 kB {0} [built]
>        [1] ./~/css-loader!./client/src/css/select2.css 14.8 kB {0} [built]
> Child extract-text-webpack-plugin:
>        [0] ./~/css-loader/lib/css-base.js 1.46 kB {0} [built]
>        [1] ./~/css-loader!./client/src/css/animate.css 54.6 kB {0} [built]
> Child extract-text-webpack-plugin:
>        [0] ./~/css-loader/lib/css-base.js 1.46 kB {0} [built]
>        [1] ./~/css-loader!./client/src/fontello/css/animation.css 1.6 kB {0} [built]
> Child extract-text-webpack-plugin:
>                                      Asset     Size  Chunks             Chunk Names
>      6a00de061f4fcc2ae24f25da53a02f4d.woff  13.2 kB          [emitted]
>     9b281482a6fbc52739698e0c130ea52a.woff2  11.3 kB          [emitted]
>        [0] ./~/css-loader/lib/css-base.js 1.46 kB {0} [built]
>        [1] ./client/src/fontello/font/fontello.woff 83 bytes {0} [built]
>        [2] ./client/src/fontello/font/fontello.woff2 84 bytes {0} [built]
>        [3] ./~/css-loader!./client/src/fontello/css/fontello.css 3.62 kB {0} [built]
> Child extract-text-webpack-plugin:
>                                      Asset     Size  Chunks             Chunk Names
>       f4769f9bdb7466be65088239c12046d1.eot  20.1 kB          [emitted]
>      fa2772327f55d8198301fdb8bcfc8158.woff  23.4 kB          [emitted]
>     448c34a56d699c29117adc64c43affeb.woff2    18 kB          [emitted]
>       89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]
>        [0] ./~/bootstrap/dist/fonts/glyphicons-halflings-regular.eot 82 bytes {0} [built]
>        [1] ./~/css-loader/lib/css-base.js 1.46 kB {0} [built]
>        [2] ./~/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf 60.6 kB {0} [built]
>        [3] ./~/bootstrap/dist/fonts/glyphicons-halflings-regular.woff 83 bytes {0} [built]
>        [4] ./~/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2 84 bytes {0} [built]
>        [5] ./~/bootstrap/dist/fonts/glyphicons-halflings-regular.svg 82 bytes {0} [built]
>        [6] ./~/css-loader!./~/bootstrap/dist/css/bootstrap.css 121 kB {0} [built]
> Child extract-text-webpack-plugin:
>                                     Asset     Size  Chunks             Chunk Names
>     1fff7dfa22a6c8ba9382ad03726139d3.woff  27.1 kB          [emitted]
>     f2bce001e16fa48466239a51378474d1.woff    28 kB          [emitted]
>     36eeac2edc10f0533f49c8e008896e40.woff  38.4 kB          [emitted]
>     79515ad0788973c533405f7012dfeccd.woff  22.7 kB          [emitted]
>        [0] ./~/css-loader/lib/css-base.js 1.46 kB {0} [built]
>        [1] ./client/src/fonts/cabin_bold/Cabin-Bold-webfont.woff 83 bytes {0} [built]
>        [2] ./client/src/fonts/cabin_medium/Cabin-Medium-webfont.woff 83 bytes {0} [built]
>        [3] ./client/src/fonts/lato_bold/lato-bold-webfont.woff 83 bytes {0} [built]
>        [4] ./client/src/fonts/opensans_regular/OpenSans-Regular-webfont.woff 83 bytes {0} [built]
>        [5] ./~/css-loader!./client/src/css/fonts.css 807 bytes {0} [built]
> 
> npm ERR! Linux 3.4.0+
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
> npm ERR! node v6.9.5
> npm ERR! npm  v4.2.0
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! auth_app@1.0.0 build: `NODE_ENV=development webpack --config webpack.config.js -p`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the auth_app@1.0.0 build script 'NODE_ENV=development webpack --config webpack.config.js -p'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the auth_app package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     NODE_ENV=development webpack --config webpack.config.js -p
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs auth_app
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls auth_app
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/tidee/.npm/_logs/2017-03-04T14_37_40_444Z-debug.log

**Comment by Orgil** [comment]
@joetidee webpack-merge is merging your config not replacing it. So your loader stack is messed when extracting.

**Comment by michael-ciniawsky** [comment]
The `Unknown work` error is related to `css-loader` and should be fixed now, Please update to the latest version and try again. If still regressions with this, please open an issue in `css-loader` instead :)

**Comment by hectorsabina** [comment]
For the record, I was having a similar issue and @Orgil comment pointed me in the right direction. If you split your webpack config, make sure you compose well your loader stack and plugins.

In my case I was able to use webpack-merge [smart merge](https://github.com/survivejs/webpack-merge#smart-merging) feature to avoid duplicating loader definitions so the extract text plugin was working nicely in production builds.

**Comment by micchyboy** [comment]
Love you @Orgil and @hectorsabina , really saved a lot of time. I was using react-static and it already has default loaders for css. So I just had to remove them before placing mine. Thanks
