### ISSUE TITLE
V2.0.0 does not support `filename: function`

### ISSUE THREAD

**Issue by scottdj92** [webpack-contrib/extract-text-webpack-plugin#444]
Comparing `master` to `v2.0.0`, I can see we're missing the validation mode `function` for `filename`. There's been a deluge of issues related to this, so I'd like to tag the current master branch into a `v2.1.0` release to resolve these issues.

**Comment by scottdj92** [comment]
@webpack-contrib/admin-team

**Comment by scottdj92** [comment]
#437

**Comment by bebraw** [comment]
Someone needs to cut 2.1 release, yeah.

**Comment by scottdj92** [comment]
Solved with 2.1.0 release.
