### ISSUE TITLE
why is it called extract-text-webpack-plugin?

### ISSUE THREAD

**Issue by zzzgit** [webpack-contrib/extract-text-webpack-plugin#447]
why this plugin is named `extract-text-webpack-plugin` rather than `extract-css-webpack-plugin`?

**Comment by michael-ciniawsky** [comment]
@zzzgit Because in 'theory' you can extract any 'text-based' `{String}` contents with it, practically the most common usecase is simply to extract CSS into a separate file for parallel resource loading in production builds.
