### ISSUE TITLE
css file not written when CommonsChunkPlugin active

### ISSUE THREAD

**Issue by mattfordham** [webpack-contrib/extract-text-webpack-plugin#45]
Hi there. 

While I am not getting any errors, the css file is not getting generated when I have the CommonsChunkPlugin activated. My CSS is not within a common chunk, FWIW. It appears as though the text is being extracted... just no css file. 

Here's what I've got:

```
  commonsPlugin = new webpack.optimize.CommonsChunkPlugin 'common.bundle.js'

  extractText = new ExtractTextPlugin("main.css", {allChunks: true})

  config =
    entry: 
      main: "./src/main.coffee"
    output:
      publicPath: "/dist/"
      path: __dirname + "/dist"
      filename: "[name].bundle.js"
    module:
      loaders: [
        {test: /\.styl$/, loader: ExtractTextPlugin.extract("style-loader", "css-loader!stylus-loader")}
      ]
    plugins: [commonsPlugin, extractText]

  webpack config, (err, stats) ->
    throw new gutil.PluginError("webpack", err) if err
    gutil.log "[webpack]", stats.toString()
    cb()
```

Any ideas?

**Comment by necolas** [comment]
this is probably fixed by now

**Comment by XVincentX** [comment]
It does not look like. I still have this issue.

**Comment by bebraw** [comment]
@XVincentX Do you still have the issue?

**Comment by chasedeanda** [comment]
Still getting the same issue here

**Comment by bebraw** [comment]
@chasedeanda Ok. Could you set up a standalone repository? There's not enough information to debug.
