### ISSUE TITLE
Add loader() method to documentation

### ISSUE THREAD

**Issue by dimsmol** [webpack-contrib/extract-text-webpack-plugin#46]
Documentation (in README) does not mention `loader()` method which makes unclear if it is public and allowed to use.

However, this method is very useful for automatic config building:
- it does not do any not fully clear actions `extract()` method does
- with it it's easier to create the chain of loaders, especially if there are more than one of them before the extraction step
- it allows to use `remove` and `extract` options which are really useful in some configurations
  - we are using `{remove: false, extract: true}` with hot loading, for example

**Comment by sokra** [comment]
It was public but is deprecated in favor of `extract`. You can do everything possible with `loader` with `extract` too: i. e. `extract("xyz-loader", {remove: false, extract: true})`

**Comment by dimsmol** [comment]
Not exactly.
I have code like this:

```js
  var styleLoaders = ['style-loader'];
  if (someCondition) {
    styleLoaders.push(ExtractTextPlugin.loader(someOptions));
  }
  styleLoaders.push('css-loader');
  if (someOtherCondition) {
    styleLoaders.push('stylus-loader');
  }
```

But surely there can be more complex cases.

I need something like `extract()` without any arguments except the options, which is exactly what `loader()` is.

Also, ability to specify `extract` and `remove` options with `extract()` call is not documented as well.

**Comment by judewang** [comment]
Agree, I want to use another plugin within my loader chain, I can't do it with `extract()`.
