### ISSUE TITLE
Multiple JS Entries with Different Styles

### ISSUE THREAD

**Issue by yussinsharp** [webpack-contrib/extract-text-webpack-plugin#460]
I am wanting to use this repo for its efficient bundling but I believe it was built under the assumption that it was for one application.

My code base serves multiple by having multiple different JS entries. The reason for this is that we have different applications for different types of users (admin vs. customer etc.).

I know how to set up multiple entries with Javascript and that has gone well, but I can't figure out how to handle the SCSS files? With this plugin, it simply bundles ALL my stylesheets, not just the ones used within a certain application.

Does ExtractText have support for this? Or am I using the wrong package?

**Comment by michael-ciniawsky** [comment]
It's not working on an entry basis you will need to setup multiple rules and Instances of ETWP to get separate files (per entry)

```js
const ETWP = require('extract-text-webpack-plugin')

const adminCSS = new ETWP({ filename: 'admin.css' })
const customerCSS = new ETWP({ filename: 'customer.css' })

const config = {
  module: {
   rules: [
     {
        test: /\.css$/,
        use: adminCSS.extract(...)
        include: '/path/to/admin/css'
     },
     {
        test: /\.css$/,
        use: customerCSS.extract(...)
        include: '/path/to/customer/css'
     },
     ...
   ]
 },
 plugins: [
    adminCSS,
    customerCSS
 ]
}
```
