### ISSUE TITLE
TypeError: chunk.isInitial is not a function

### ISSUE THREAD

**Issue by jony89** [webpack-contrib/extract-text-webpack-plugin#461]
versions :
    
     "webpack": "^2.2.1"
    "extract-text-webpack-plugin": "^2.1.0",

error : 

> \node_modules\extract-text-webpack-plugin\index.js:267
> 				var shouldExtract = !!(options.allChunks || chunk.isInitial());
> 				                                                  ^
> 
> TypeError: chunk.isInitial is not a function
>     at \node_modules\extract-text-webpack-plugin\index.js:267:55
>     at \node_modules\extract-text-webpack-plugin\node_modules\async\dist\async.js:3025:16
>     at eachOfArrayLike (\node_modules\extract-text-webpack-plugin\node_modules\async\dist\async.js:940:9)
>     at eachOf (\node_modules\extract-text-webpack-plugin\node_modules\async\dist\async.js:990:5)
>     at Object.eachLimit (\node_modules\extract-text-webpack-plugin\node_modules\async\dist\async.js:3089:3)
>     at ExtractTextPlugin.<anonymous> (\node_modules\extract-text-webpack-plugin\index.js:265:10)
>     at Compilation.applyPluginsAsync (\node_modules\gulp-webpack\node_modules\tapable\lib\Tapable.js:71:13)
>     at Compilation.seal (\node_modules\gulp-webpack\node_modules\webpack\lib\Compilation.js:525:7)
>     at Compiler.<anonymous> (\node_modules\gulp-webpack\node_modules\webpack\lib\Compiler.js:397:15)
>     at \node_modules\gulp-webpack\node_modules\tapable\lib\Tapable.js:103:11
>     at Compilation.<anonymous> (\node_modules\gulp-webpack\node_modules\webpack\lib\Compilation.js:445:10)
>     at \node_modules\gulp-webpack\node_modules\webpack\lib\Compilation.js:417:12
>     at \node_modules\gulp-webpack\node_modules\webpack\lib\Compilation.js:332:10
>     at \node_modules\async\lib\async.js:52:16
>     at done (\node_modules\async\lib\async.js:246:17)
>     at \node_modules\async\lib\async.js:44:16

for some reason I could not attach the ZIP to the message, so here a link to simple standalone project : https://ufile.io/596a0

**Comment by bebraw** [comment]
Here's the project - https://github.com/jony89/simple-webpack-extract-plugin .

I tried this on macOS (Node 6.9.1) and it completed without any problems.

I wonder if it's Windows specific.

**Comment by jony89** [comment]
@bebraw I ran it on win7 & node 6.8.0 

updated to node 6.10.0 and same issue. I find it hard to believe it is specific to win7.

to run the project correctly (in case u didnt) : 

in console : 

1) npm install 
2) gulp

**Comment by bebraw** [comment]
Ah... You ran it through Gulp. I get the error then too if go through `node_modules/.bin/gulp`.

If you execute `node_modules/.bin/webpack`, it builds as you might expect.

I can see you are using [gulp-webpack](https://www.npmjs.com/package/gulp-webpack). You probably want to use [webpack-stream](https://www.npmjs.com/package/webpack-stream) instead as **gulp-webpack** isn't actively maintained by the looks of it.

**Comment by kostasmanionis** [comment]
Quick look at `gulp-webpack`, seems that it has `"webpack": "^1.12.9"` as a dependency. `webpack-stream` seems to have the same issue.

Not really familiar with their implementations, but they probably should have webpack as a peer dep.

**Comment by bebraw** [comment]
@kostasmanionis Nice! That explains it.

@jony89 Please open issues at those projects unless they have ones open already. There's nothing we can do about the issue in this plugin as it's an upstream issue.

**Comment by jony89** [comment]
tnx, temporary solution is to give webpack-stream your own webpack version: 

```js
webpackStream(config, require('webpack'))
```

see https://github.com/shama/webpack-stream/issues/125

**Comment by huelgasjcowork** [comment]
asdsa
asd
