### ISSUE TITLE
Ordering of React modules before Main module in css output

### ISSUE THREAD

**Issue by wooderz** [webpack-contrib/extract-text-webpack-plugin#462]
So I have in my webpack entry file

import 'stylus/app.styl'

and then in a component further down the hierarchy I have
import '../styles/component.styl'

The component.styl classes are put in the CSS before the app.styl. This means they could be overridden, whereas I'd rather the ones specifically set in the class are the ones used?

Any ideas?

**Comment by michael-ciniawsky** [comment]
The order of your styles is determined by how webpack walks the `import style from './style.styl' / require('./style.styl') in your application, if the order is off for some reason, that's not caused or solveable by ETWP, since it has no context about the CSS hierarchy try to reorganise your styles
