### ISSUE TITLE
z-indexs were recalculated just with this plugin

### ISSUE THREAD

**Issue by rubyisapm** [webpack-contrib/extract-text-webpack-plugin#464]
```
css:[ { loader: '/Users/rubyisapm/work/webpack-test/node_modules/extract-text-webpack-plugin/loader.js',
      options: { omit: 1, remove: true } },
      { loader: 'vue-style-loader' },
      { loader: 'css-loader'} ]
```
I use like that css loader configuration, the z-indexs in the exact css  were recalculated.

After I remove this plugin like this:

```
css:[ { loader: 'vue-style-loader' },
      { loader: 'css-loader'} ]
```

Everything was fine.

**Comment by michael-ciniawsky** [comment]
That's not possible since ETWP doesn't transform any content, you also using `vue-loader` and only a part of ETWP (`loader.js`) I can't tell you which particular side-effects this inoffical usage in conjunction with `vue-loader` possibly may has 😛 You need to reconfigure your setup
