### ISSUE TITLE
Javascript assets included in CSS modules are executed during build

### ISSUE THREAD

**Issue by darrenscerri** [webpack-contrib/extract-text-webpack-plugin#465]
If CSS contains Javascript assets, these are executed during build and can interfere with the build and build output.

See this repo for more information: https://github.com/darrenscerri/webpack-extract-text-plugin-empty-require-error.

Related issues: 
https://github.com/webpack/webpack/issues/4541
https://github.com/webpack-contrib/css-loader/issues/462

**Comment by michael-ciniawsky** [comment]
`url('')` will be rewritten by to `url(require('./'))` by `css-loader`, it's an issue in `css-loader` tracking this an discussion moved to  [#462](https://github.com/webpack-contrib/css-loader/issues/462) i'm still wondering about the 'usecase' 🙃
