### ISSUE TITLE
beta cannot install on mac

### ISSUE THREAD

**Issue by hqqxxf** [webpack-contrib/extract-text-webpack-plugin#473]
on mac：
npm i extract-text-webpack-plugin@beta does not work

**Comment by michael-ciniawsky** [comment]
@hqqxxf Why are you installing ETWP with the `@beta` tag? 😛  There is no active `@beta` atm
v2.x is released and available via the `@latest` tag 

```npm i -D extract-text-webpack-plugin```

Please try a 'normal' install and if there are still regressions feel free to reopen
