### ISSUE TITLE
Doesn't read multiple imports

### ISSUE THREAD

**Issue by omichelsen** [webpack-contrib/extract-text-webpack-plugin#474]
I have an entry point that looks like this:

```js
import 'layout.less';
import 'landing.less';
```

The content from `layout.less` is included but nothing from `landing.less` is included in the file.

My config is like this for Webpack 2.3.3 and extract-text-webpack-plugin 2.1.0:

```js
new ExtractTextPlugin({ filename: 'styles-[hash:6].css', allChunks: true }),
...
rules: [
  {
    test: /\.less$/,
    use: ExtractTextPlugin.extract({
      fallback: 'style-loader',
      use: ['css-loader?importLoaders=1&minimize', 'postcss-loader', 'less-loader'],
    }),
  },
],
```

Also any `.less` file I import from my react components are also ignored.

**Comment by michael-ciniawsky** [comment]
I need more info about your setup and does it work without `extract-text-webpack-plugin` ?

**Comment by omichelsen** [comment]
I found out the culprit was the CommonsChunkPlugin. In the new docs they have [added instructions](https://webpack.js.org/plugins/commons-chunk-plugin/#passing-the-minchunks-property-a-function) (at the end of that paragraph) to work better together with ExtractTextPlugin. 

Must admit this required a lot of trial and error on my part, so maybe this is something you could add/link to in the readme?

**Comment by michael-ciniawsky** [comment]
An example describing this in a more elaborative way would be highly apprectiate, PR welcome 😛
