### ISSUE TITLE
CommonChunkPlugin with ExtractTextPlugin causes buildin/global to disappear

### ISSUE THREAD

**Issue by huan086** [webpack-contrib/extract-text-webpack-plugin#475]
Node 7.8.0
Windows 10.0.14393
Bug demo: https://github.com/huan086/webpackbug

The setup

- script1.js reference style.css
- script2.js reference style.css

causes webpack/buildin/global **not** to get bundled in common.js. Thus, any access to `global` will cause an error.

When you open index.html, you will see

```
TypeError: modules[moduleId] is undefined
ReferenceError: blue is not defined
```

**What doesn't trigger the bug**
When script1.js and script2.js doesn't share any CSS, or
When ExtractTextPlugin is removed, or
When CommonChunkPlugin is removed

**Comment by aoc** [comment]
You're missing the all `allChunks: true` option.

This should fix it:

``` js
new ExtractTextPlugin({
  filename: "[name].css",
  allChunks: true
}),
```
