### ISSUE TITLE
Is `ExtractTextWebpackPlugin` only for extracting styles?

### ISSUE THREAD

**Issue by liweinan0423** [webpack-contrib/extract-text-webpack-plugin#484]
I am confused with the name of this plugin. Most use cases I've seen so far of this plugin is to extract styles from webpack bundle into a separate file. 

If this plugin is dedicatedly extracting styles from bundle, why not just name it as `ExtractStylesWebpackPlugin`?

**Comment by psabharwal123** [comment]
i have the same question, can we not use it to extract js or images?

**Comment by evilebottnawi** [comment]
@liweinan0423 @psabharwal123  because in theory your can use loader not only for `css` files, also `styles` is very wide name (`sass`, `less` and more more more).

**Comment by evilebottnawi** [comment]
@liweinan0423 @psabharwal123 also for question for such a nature use `stackoverflow`, also each such new issue makes contributors spend time on it, although this time could be spent on solving a more important problem, but still thanks for the interest shown :smile:

**Comment by michael-ciniawsky** [comment]
It iss the 99.9% usecase yep 😛 , but 'in theory' it would be possible to extract other resources with it
