### ISSUE TITLE
 Cannot find module 'webpack/lib/Chunk'

### ISSUE THREAD

**Issue by manuelro** [webpack-contrib/extract-text-webpack-plugin#485]
I'm not even using the plugin and I get the following error when I run `webpack` from my terminal:
```
module.js:471
    throw err;
    ^

Error: Cannot find module 'webpack/lib/Chunk'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ([absolute path to project folder]\node_modules\extract-text-webpack-plugin\index.js:9:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
The plugin is loading a module called `Chunk` (see line 9 on the index file):
`var Chunk = require("webpack/lib/Chunk"); // Line 9 @ extract-text-webpack-plugin/index.js`

But there is not such folder in Webpack module:
![image](https://cloud.githubusercontent.com/assets/4284074/25100705/5bc710fc-236e-11e7-81e3-3a29b6576063.png)

Any ideas of why this is happening?

Webpack version: `v2.3.3`
Plugin version: `2.1.0`
NPM version: `3.10.9`
Node version: `v6.9.2`

**Comment by manuelro** [comment]
UPDATE: Installing a previous version of Webpack solved the issue.

`npm install webpack@2.2.0 --save-dev`

**Comment by radix** [comment]
why did you close this? is there a way to use this plugin with recent versions of webpack?

**Comment by DanielTate** [comment]
This is still an issue on Webpack 2.6

**Comment by manuelro** [comment]
I just reopened this because there seem to be issues with recent Webpack versions as well. As I stated it before, I fixed this by using a previous version (`npm install webpack@2.2.0 --save-dev`). But clearly this was not an optimal solution.

**Comment by b4dnewz** [comment]
``` bash
Error: Cannot find module 'webpack/lib/Chunk'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    ...
```

using __webpack version 3.4.1__ with the snippet from the readme.

```javascript
const path = require('path');
const ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: "css-loader"
        })
      }
    ]
  },
  plugins: [
    new ExtractTextPlugin("styles.css"),
  ]
};
```

**Comment by evilebottnawi** [comment]
@manuelro @DanielTate @radix seems problem with installation `webpack` or maybe `webpack` have problems in `2.*` version with location `webpack/lib/Chunk`, but we can't fix this in `extract-text-webpack-plugin` :disappointed: I close the problem here, feel free to reopen if your have solution for this (or minimum reproducible test repo which demonstrate problem), thanks!

**Comment by Newbie012** [comment]
There's no need to downgrade the Webpack version. You just need to save it locally (not globally). Not the best solution, but I believe that's temporary.

Fo more details: https://stackoverflow.com/a/34673117/1860540

**Comment by charltoons** [comment]
For the people still Googling this issue. If you need to have a globally installed webpack, you can pass in a `NODE_PATH` environment variable to your global `node_modules` like so:

```
export NODE_PATH=/usr/local/lib/node_modules webpack
```

**Comment by vZanchiV** [comment]
> UPDATE: Installing a previous version of Webpack solved the issue.
> 
> `npm install webpack@2.2.0 --save-dev`

worked for me
