### ISSUE TITLE
Image background from node_modules

### ISSUE THREAD

**Issue by sptheme** [webpack-contrib/extract-text-webpack-plugin#486]
Hello,

I have problem with sass files that have relative path background images and try to ExtractTextPlugin for production but got error:
Module not found: Error: Can't resolve '../flags/1x1/un.svg'

I have used @import "~flag-icon-css/sass/flag-icon"  

Does anyone can resolve this issue?

**Comment by michael-ciniawsky** [comment]
@sptheme I need more info about your setup (`webpack.config.js`) and a full error log, this can be tricky to do 😛

**Comment by michael-ciniawsky** [comment]
This is unrelated to ETWP in particular since it's an issue with url resolving in a vendor package, where EWTP doesn't have any influence upon
