### ISSUE TITLE
Webpack produces a bundle with empty modules, when all the content is extracted

### ISSUE THREAD

**Issue by halfzebra** [webpack-contrib/extract-text-webpack-plugin#489]
If I have a bundle of CSS files, which are getting extracted in the end, webpack will produce a bundle with empty modules.

Here's my minimal config to reproduce the behaviour described above:

```js
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const path = require('path');

const extractCss = new ExtractTextPlugin({filename: 'bundle.css'});

module.exports = {

  entry: {
    bundle: ['./index.css', './module.css']
  },

  output: {
    path: path.resolve(__dirname, './build'),
    filename: '[name].js'
  },

  module: {

    rules: [
      {
        test: /\.css$/,
        loader: extractCss.extract({
          use: [
            {loader: 'css-loader'}
          ]
        })
      }
    ]
  },

  plugins: [
    extractCss
  ]

};
```

In the output, I'm getting a bundle, with a bunch of empty module definitions:

```js
/* 0 */
/***/ (function(module, exports) {

// removed by extract-text-webpack-plugin

/***/ }),
```

Here's a minimal example of the issue [webpack-empty-bundle](https://github.com/halfzebra/webpack-empty-bundle)

I assume the expected behavior would be not to emit the `bundle.js`.

Is this how it is meant to be?

**Comment by michael-ciniawsky** [comment]
> I assume the expected behavior would be not to emit the bundle.js.

Could you elaborate on this futher 🙃 . Wat do you excatly men by **not** emiting a bundle?

This behaviour should be correct, all ETWP is doing is extracting the CSS Chunk from the bundle into a separate CSS file and leave a comment where it did so, the JS [bundle] containing other code is still emitted

**Comment by halfzebra** [comment]
@michael-ciniawsky sorry for wrong wording.

It's just my assumption, but I would expect webpack to strip [bundle.js](https://github.com/halfzebra/webpack-empty-bundle/blob/master/build/bundle.js) file from the output since it contains only empty chunks.

I would want to keep only [bundle.css](https://github.com/halfzebra/webpack-empty-bundle/blob/master/build/bundle.css)

As far as I understand, serving [bundle.js](https://github.com/halfzebra/webpack-empty-bundle/blob/master/build/bundle.js) to the client will have no effect whatsoever.

Is it supposed to work like that?

**Comment by michael-ciniawsky** [comment]
So in your case the `bundle.js` is mostly empty after ETWP extracted the chunks ?  😛 That's an uncommon usecase tbh, normally when you need the CSS on build time, let's say to localise it  (CSS Modules) and update the classnames in your components, you import the CSS and for production builds it's recommended to extract it into a separate file to enable parallel loading of CSS && JS (Critical Render Path)

```js
...
import styles from './style.css'

class Foo extends React.Component {
   render () {
      return (
        <div className={styles.foo}></div> // update .foo {} => .gjeqw&58 {}
      )
   }
}
```

If your bundle doesn't contain any other logic and is empty, you better use a task runner like grunt, gulp to build your CSS 😛

**Comment by michael-ciniawsky** [comment]
Reopen if still any regressions

**Comment by halfzebra** [comment]
@michael-ciniawsky makes sense!

Thanks for clarifying that 🙂

**Comment by professorkolik** [comment]
@halfzebra 
Did you find the solution?

Same problem I need extracted files, but also I need to require separate modules into js

**Comment by avesus** [comment]
@michael-ciniawsky I'm not satisfied by your advice
> If your bundle doesn't contain any other logic and is empty, you better use a task runner like grunt, gulp to build your CSS 

because it's important to keep automatic track of component dependencies suitable to build a production bundle too.

I know many developers who prefer stable style names instead of the generated hashes.

For a typical web app with 250 components, the piece of code which does nothing weigh 13 kilobytes: `,function(module,exports){}` for "exports" and `__webpack_require__(249);` for "imports".

It's _possible_ to just ignore those 13 kB and live with that, but which opinion developers have here?

(I stuck on it so much that even wanted to write my own bundler to deal with CSS imports...)
