### ISSUE TITLE
Can I extract JavaScript file, either?

### ISSUE THREAD

**Issue by aleen42** [webpack-contrib/extract-text-webpack-plugin#490]
I have used Webpack 1, and I want to use Webpack to build a specific JavaScript file. Can that plugin implement the requirement for me? I have set up my Webpack configuration file like the following:

```js
var ExtractTextPlugin = require('extract-text-webpack-plugin');

module: {
    plugins: [
        new ExtractTextPlugin(scriptPath + '/IE8-hack.min.js')
    ],
    loaders: [
        { test: path.resolve(scriptPath + '/IE8-hack.js'), loader: ExtractTextPlugin.extract() }
    ]
}
```

Then, if I have require the file in the file `main.js` of my project, the Webpack building process will throw out an error like this:

```
ERROR in missing path
 @ ./script/main.js 1:0-24
```

But if I don't require it, nothing happened at all. How can I do?

**Comment by michael-ciniawsky** [comment]
Set this file as an entry point or use the Common Chunk plugin to include it in your vendor bundle, the name `extract-text-webpack-plugin` is a bit misleading tbh, but the 99% usecase for this plugin is to extract CSS chunks 😛
