### ISSUE TITLE
Sass is not building into the css folder

### ISSUE THREAD

**Issue by kniteshift** [webpack-contrib/extract-text-webpack-plugin#492]
For some reason my scss files are not being built into my /build/ folder.

```
const path = require('path');
const HtmlWebPackPlugin = require('html-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
	entry: path.join(__dirname, 'src', 'app.js'),
	output: {
		path: path.join(__dirname, 'build'),
		filename: 'bundle.js'
	},
	module: {
		rules: [
			{
				test: /\.js$/,
				include: /src/,
				exclude: /(node_modules)/,
				use: 'babel-loader'
			},{
				test: /\.scss$/,
				use: ExtractTextPlugin.extract({
					fallback: "style-loader",
					use: ['css-loader', 'sass-loader']
				})
			}
		],
	},
	plugins: [
		new ExtractTextPlugin({
			filename: 'build/[name].bundle.css',
		}),
	]
}
```

I'm using webpack 2.4.1, extract text ^2.1.0. Latest node sass, sass loader, css loader.

**Comment by tcschiller** [comment]
@kniteshift Your .scss files don't live in a directory one level up from your entry point, do they? I'm seeing an issue like that resulting in this error when I run webpack:

`foo.scss doesn't export content`

**Comment by michael-ciniawsky** [comment]
@kniteshift The config looks sane, there must be an issue with the structure somewhere 😛 could you please post the `tree` and an example `.scss` file?

**Comment by Sunzhuoyi** [comment]
@kniteshift How do you solve this problem? I use less and do not know how to deal with it

**Comment by kniteshift** [comment]
@Sunzhuoyi I corrected it as @tcschiller had pointed out to me. I pretty much just setup an entry for the scss file. 

Here's the entire config in case you're wondering.
`
module.exports = {
	entry: {
		bundle: ['./src/app.js', './src/styles/styles.scss'],
		vendor: VENDOR_LIB
	},
	output: {
		path: path.join(__dirname, 'build'),
		filename: '[name].[chunkhash].js'
	},
	module: {
		rules: [
			{
				test: /\.js$/,
				include: /src/,
				exclude: /(node_modules)/,
				use: 'babel-loader'
			},{
				test: /\.(eot|ttf|woff2?|otf)$/,
				use: 'url-loader?limit=1024&name=fonts/[name].[ext]'
			},{
				test: /\.(jpe?g|png|gif|svg)$/,
				include: /src/,
				use: 'url-loader?limit=5000&name=assets/img/[name].[ext]'
			},{
				test: /\.(mp4)$/,
				use: 'url-loader?limit=500000&name=assets/video/[name].[ext]'
			},{
				test: /\.scss$/,
				include: [/(src)/, /(node_modules)/],
				exclude: /fonts/,
				use: ExtractTextPlugin.extract(['css-loader', 'resolve-url-loader', 'sass-loader?sourceMap'])
			}
		],
	},
	plugins: [
		extractSass,
		new HtmlWebPackPlugin({
			template: 'src/index.html'
		}),
		new webpack.optimize.CommonsChunkPlugin({
			name: ['vendor', 'manifest']
		}),
		new CopyWebpackPlugin([
			{ from: 'src/assets/', to: 'assets/'}
		])
	]
}
`

**Comment by evilebottnawi** [comment]
Closed because was solved https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/492#issuecomment-299095332

**Comment by Borduhh** [comment]
I just ran into this issue myself. The above solution worked, but I also found that adding this to my ./src/app.js file worked:

`import './styles/styles.scss';`
