### ISSUE TITLE
Simplest possible usecase: Bundle CSS - how?

### ISSUE THREAD

**Issue by codeofsumit** [webpack-contrib/extract-text-webpack-plugin#493]
So the docs really improved when starting with webpack. I got everything JS related working pretty fast and the config is straightforward 👍 .

However when I start to get into CSS, everything is confusing again.

I got a folder:
`src/css/` with two files in it:
`a.css` and `b.css`.
Now I want them bundled to `dist/bundle.css`.

I followed [these docs](https://webpack.js.org/plugins/extract-text-webpack-plugin/#usage-example-with-css) but CSS is simply ignored.

I would expect to name an output dir and an entry file, just like with JS.

This is my full config:

```
const ExtractTextPlugin = require("extract-text-webpack-plugin");
const path = require('path');

module.exports = {
  watch: true,
  devtool: "cheap-eval-source-map",
  entry: './src/js/L.PM.js',
  output: {
    filename: 'leaflet.pm.min.js',
    path: path.resolve(__dirname, 'dist')
  },
  module: {
    rules: [
      {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: "css-loader"
        })
      }
    ]
  },
  plugins: [
    new ExtractTextPlugin("leaflet.pm.css"),
  ]
};
```

**Comment by codeofsumit** [comment]
seems like I have to import my CSS into my JavaScript files to make it work...?
This isn't mentioned anywhere where:
https://webpack.js.org/plugins/extract-text-webpack-plugin/#usage-example-with-css
I import my CSS files into JavaScript so Webpack takes the CSS out again and puts it into a separate file?
This doesn't really make sense. Am I doing this correctly?

**Comment by michael-ciniawsky** [comment]
> I import my CSS files into JavaScript so Webpack takes the CSS out again and puts it into a separate file?

@codeofsumit Yep 😛 , webpack is **JS Module Bundler**  and doesn't understand CSS 'natively' (that why you need a 'loader' `css => module.exports = `${css}` `), it builds a dependency graph by walking the `import/require()` statements and ETWP will gather the chunks and extracted them into **one separate** file per **Instance**

```js
const ExtractTextPlugin = require('extract-text-webpack-plugin')

const extractCSS = new ExtractTextPlugin({ filename: 'css.bundle.css' })
const extractSASS = new ExtractTextPlugin({ filename: 'sass.bundle.css' })

const config = {
   module: {
     rules: [
       {
          test: /\.css$/,
          use: extractCSS.extract({ // Instance 1
            fallback: 'style-loader',
            use: [ 'css-loader' ]
          })
       },
       {
          test: /\.scss$/,
          use: extractSASS.extract({ // Instance 2
            fallback: 'style-loader',
            use: [ 'css-loader', 'sass-loader' ]
          })
       }
     ]
   },
   plugins: [
      extractCSS // Instance 1
      extractSASS // Instance 2
   ]
}
```
I showing you this example, bc ETWP doesn't work per **entry**, it's alsways a combo of a loader rule and a plugin Instance regradless of how many entries you have 😛 

> This doesn't really make sense. Am I doing this correctly?

It makes sense when you need the CSS (`{String}`) during build time (e.g CSS Modules) or to rewrite `url()` with the correct assets paths in case you load them via webpack.

**component.css**
```
.app {
  display: flex;
  background: url('./image.png')
  /* => background: url(require('path/to/image.png')) */
}
```

**component.js**
```
import style from './style.css'
import image from './image.png' 

// style.app === '362fzewvf'
const Component = () => render(<div class=`${style.app}`></div>)
```

It doesn't make sense if you are using e.g **Bootstrap** and you don't need the CSS at build time, then just use a CDN or add a 

```html
<link href="path/to/lib">
```

manually 😛

**Comment by codeofsumit** [comment]
thanks for the detailed explanation @michael-ciniawsky - I'll send a PR with what I think would've helped me. Your post definitely did!

**Comment by qasimraza1979** [comment]
codeofsumit: did the solution provide by michael-ciniawsky worked for you ?? Can you share the code.
I am also trapped into the same problem that I also want to bundle some how or the other  'cssBundle' with the package. its 2 days now :(

**Comment by Polyterative** [comment]
@qasimraza1979 Solved your issue?

**Comment by mansisce** [comment]
@michael-ciniawsky  This worked for me. Thanks. I was doing some silly mistake.

**Comment by Polyterative** [comment]
I also was able to make it work. 
Here is my code

> package.json => NPM
> add these to dependencies 
```javascript
"extract-text-webpack-plugin"
```
and this is you want to minify extracted CSS
```javascript
'optimize-css-assets-webpack-plugin' 
```

> NPM scripts for starting webpack in different modes
```javascript
"scripts": {
    "webpack-production": "cross-env NODE_ENV=production webpack --env.prod=true",
    "passive-WebpackCompile": "webpack  --display-reasons --config webpack.config.js",
  }
```

___
Now

> webpack.config.js => top of the file 

```javascript
const ExtractTextPlugin = require("extract-text-webpack-plugin");
const OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin'); //if want to minify CSS in prod
```

> webpack.config.js => isProd variable

```javascript
module.exports = function (env) {
    //shell level constants
    const nodeEnv = env && env.prod ? 'production' : 'development';
    const isProd = nodeEnv === 'production';

    //...
}
```

> webpack.config.js => inside module
```javascript
        module: {
            rules: [
                {
                    test: /\.css$/,
                    // exclude: /node_modules/,
                    use:
                        ExtractTextPlugin.extract({
                            fallback: 'style-loader',
                            use: [{
                                loader: 'css-loader',
                                options: {
                                    sourceMap: !isProd,
                                    // sourceMap: toString(!isProd),
                                    // minimize: isProd
                                }
                            }, {
                                loader: 'sass-loader',
                                options: {
                                    sourceMap: !isProd
                                }
                            }]
                            
                        })

                },
            ],
            loaders: [
                {
                    test: /\.css$/,
                    loader: ExtractTextPlugin.extract(
                        'style-loader',
                        'css-loader'
                    )
                }
            ]
        },
```

Also added this plugin for CSS minification in PROD

> webpack.config.js => add this in plugins, when in production
```javascript
//minify extracted CSS, works with text extractor
            new OptimizeCssAssetsPlugin({
                assetNameRegExp: /\.optimize\.css$/g,
                cssProcessor: require('cssnano'),
                cssProcessorOptions: { discardComments: { removeAll: true } },
                canPrint: true
            }),
```

I hope this helps

**Comment by m1is** [comment]
What is the syntax for referencing the CSS files in TypeScript?

**Comment by pxwee5** [comment]
Is there a way to just output the css file without including it into the bundle?

**Comment by Polyterative** [comment]
@pxwee5 I'm pretty sure that's default behavior. Maybe check your config file for any plugin that does that

**Comment by pxwee5** [comment]
It doesn't seem like there's a way to do that in Webpack. LOL Had to manually do it using CLI and run it before the npm build command.
