### ISSUE TITLE
chunk.modules deprecated

### ISSUE THREAD

**Issue by contra** [webpack-contrib/extract-text-webpack-plugin#494]
Just a heads up, webpack master emits this warning for 2.1.0 -

```
(node:33863) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
    at /Users/contra/Projects/staeco/node_modules/extract-text-webpack-plugin/index.js:268:24
```

Source of the issue: https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/master/index.js#L268

**Comment by zhuweiyou** [comment]
same warning

**Comment by iroy2000** [comment]
same warning here

` 94% asset optimization(node:35014) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.                                                                                Hash: 737f15654eb9035eafed
Version: webpack 3.0.0
`

**Comment by evilebottnawi** [comment]
Guys don't duplicate issues, we known about this, we do fix and release this asap

**Comment by ReactPhoenix** [comment]
(node:1266) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.

Why this happening?

**Comment by d3viant0ne** [comment]
@reactphoenix it's an internal deprecation warning from Webpack to extract text. Nothing to worry about.

There is already an open pull request updating the methods in question

**Comment by michael-ciniawsky** [comment]
Fixed in [v3.0.0-rc.1](https://github.com/webpack-contrib/extract-text-webpack-plugin/releases/tag/v3.0.0-rc.1)

**Comment by iwarner** [comment]
Im still seeing this on verision 3.6.0
"webpack": "^3.6.0"

**Comment by Brian-Kaplan** [comment]
Seeing this webpack 3.8.1

**Comment by d3viant0ne** [comment]
@Brian-Kaplan  It's not from extract-text

I know `webpack-md5-hash` still has this deprecation warning & I know there are others as well.
Everything that `webpack-contrib` owns, has been updated. If you post your dev-deps, I can probably pick out the offending lib.

**Comment by bkumar-webfares** [comment]
DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.

Version: webpack 3.0.0-rc.1

Is there any solution?

**Comment by ywxgod** [comment]
Seeing this in verision 3.10.0
 "webpack": "^3.10.0",

**Comment by mknet** [comment]
I'm also seeing this in version 3.11.0
"webpack": "^3.11.0",

**Comment by montogeek** [comment]
@ywxgod @mknet Which versions of this plugin are you using?
