### ISSUE TITLE
fallback or use can't use,loader.query  property is undefined

### ISSUE THREAD

**Issue by kinglerzou** [webpack-contrib/extract-text-webpack-plugin#495]
"version": "2.0.0-beta.4"
fallback or use  can't use
then instead:
ExtractTextPlugin.extract(
 { fallbackLoader:'style-loader',
  loader:["css-loader"]
 }
);

**Comment by evilebottnawi** [comment]
@kinglerzou can you create minimal reproducible repo or show your config and files where your get an error?

**Comment by michael-ciniawsky** [comment]
> "version": "2.0.0-beta.4"

@kinglerzou Please update to the `latest` version before submitting an issue :)

**Comment by kinglerzou** [comment]
@michael-ciniawsky   ok,i know,but i suggest it should be compatible for the low version
