### ISSUE TITLE
ExtractTextPlugin does not create output 

### ISSUE THREAD

**Issue by dsslimshaddy** [webpack-contrib/extract-text-webpack-plugin#497]
There is no file in the project called `darkstyles.css`

my structure is like 
```
-root 
 --- webpack.config.js
 --- web
     ----static
        ----cssstylesheet
           ----- a.css
           ----- b.css
```

``` 

  plugins: [
     new ExtractTextPlugin("darkstyles.css"), 
  ]
```

```
  module: {
    rules: [
      {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: "css-loader"
        })
      },
```

Im using 

```
 "webpack": "^2.5.0"

    "css-loader": "^0.28.1",
    "extract-text-webpack-plugin": "^2.1.0", 
    "style-loader": "^0.17.0",

```

**Comment by evilebottnawi** [comment]
@dsslimshaddy seems your forgot add plugin:
```shell
const ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: "css-loader"
        })
      }
    ]
  },
  plugins: [
    new ExtractTextPlugin("styles.css"), // I am here :)
  ]
}
```

**Comment by dsslimshaddy** [comment]
yeah i mentioned it i did add `new ExtractTextPlugin("darkstyles.css")` in plugins

**Comment by evilebottnawi** [comment]
@dsslimshaddy can your create minimal reproducible test repo?

**Comment by DmitryScaletta** [comment]
@evilebottnawi [minimal reproducible test repo](//github.com/DmitryScaletta/extract-text-plugin-issue).

    > webpack

    Hash: 4fe9606973bfcbb9ff65
    Version: webpack 2.5.1
    Time: 49ms
           Asset     Size  Chunks             Chunk Names
    js/bundle.js  2.64 kB       0  [emitted]  main
       [0] ./src/js/script.js 0 bytes {0} [built]

**Comment by dsslimshaddy** [comment]
@DmitryScaletta  i used that same thing happens with mine. i want a bundle.css file. not bundle.js file.

**Comment by BTMPL** [comment]
Your demo repo is not importing the css file.

Add

```
import Style from "../css/style.css";
```
to index.js

**Comment by evilebottnawi** [comment]
@dsslimshaddy comment above resolve your problem?

**Comment by dsslimshaddy** [comment]
Its fixed now
