### ISSUE TITLE
css path is incorrect when use relative path

### ISSUE THREAD

**Issue by ray0324** [webpack-contrib/extract-text-webpack-plugin#501]
wen config css file output like
```
new ExtractTextPlugin('css/[name].css')
```
the path in css  is incorrect like this
```
body {
  background: url(assets/logo.png);
}
```
the right is
```
body {
  background: url(../assets/logo.png);
}
```

**Comment by evilebottnawi** [comment]
@ray0324 `ETWP` don't handle `url` in `css`

**Comment by bebraw** [comment]
Note that you can fix this by setting `publicPath: '../'` at `.extract`.

**Comment by evilebottnawi** [comment]
@ray0324 can we close this issue?

**Comment by ray0324** [comment]
@evilebottnawi  yes
