### ISSUE TITLE
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin

### ISSUE THREAD

**Issue by xcsweb** [webpack-contrib/extract-text-webpack-plugin#505]
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usa
ge example
    at Object.module.exports.pitch (E:\www\dev\node_modules\._extract-text-webpack-plugin@2.1.0@extract-text-webpack-plugin\loader.js:27:9)

**Comment by michael-ciniawsky** [comment]
Without your `webpack.config.js` we can't help, please consider the README or provide your config
