### ISSUE TITLE
Extract css from multiple entries is incorrect

### ISSUE THREAD

**Issue by KELiON** [webpack-contrib/extract-text-webpack-plugin#509]
I've already opened an issue #294, but I couldn't find the reason. Now I managed to find it and created a [repository for demo](https://github.com/KELiON/webpack-extract-css-bug-demo). I've tested it with node 7.9.0 on MacOS.

#### Problem
I have two rules for `ExtractTextPlugin` – [one](https://github.com/KELiON/webpack-extract-css-bug-demo/blob/master/webpack.config.js#L17) for `global.css`, that should be processed without css modules, and [second](https://github.com/KELiON/webpack-extract-css-bug-demo/blob/master/webpack.config.js#L24) for all other files. 

Everything works fine, when I use only one entry point in webpack (`src/index.js`) that imports `global.css`. After running webpack it generates `style.css` with content: 

```
.style__el___2epDL {
  margin: 50px;
  padding: 50px;
  border: red;
}body {
  background: yellow;
}
```

So, both rules are added (first one from `Test/style.css` and second from `global.css`)

But as soon as I add second entry point (`src/additional.js`), that [doesn't](https://github.com/KELiON/webpack-extract-css-bug-demo/blob/master/src/additional.js#L5) import `global.css`, I see output as:

```
.style__el___2epDL {
  margin: 50px;
  padding: 50px;
  border: red;
}
```

I expect the same output, as before. Also I can add, that the same logic with webpack 1 and `extract-text-webpack-plugin@1.0.1` works fine.

**Comment by cnatis** [comment]
@KELiON, the problem you are experiencing is likely that the extract text plugin is overwriting the css file with each additional entry. You can include [name] or [contenthash] in the filename option to fix this, however you won't get a single css file, you will end up with an additional css file for each rule, thats the part I am running into that I wish would produce a single css file for each instance of the extract text plugin.

**Comment by KELiON** [comment]
@cnatis yep, it is the way I solved it – I changed `filename: 'style.css'` to `filename: '[name].css'`. Anyway, it is not clear if it is expected behaviour.

**Comment by tals** [comment]
There's actually a bug with ordering.
Given two entry points that share `import`ed modules that extract-text processes, their actual load order (as they appear in the concatenated file) will be incorrect

For example:
```js
// programA.js
import './css/first.css'
import './css/second.css'
import './css/third.css'
```
```js
// programB.js
import './css/second.css'
import './css/first.css'
```

Yields:
```css
/* extracted programA.css */

/* <content of first.css>... */
/* <content of second.css>... */
/* <content of third.css>... */
```
```css
/* extracted programA.css */
/* <content of first.css>... <-- this is wrong! */
/* <content of second.css>... */
```

Repro: https://github.com/tals/extract-text-plugin-ordering-bug

**Comment by evilebottnawi** [comment]
Closed because was solved https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/509#issuecomment-304230051
