### ISSUE TITLE
Error: data['disabled'] should NOT have additional properties

### ISSUE THREAD

**Issue by randomvasya** [webpack-contrib/extract-text-webpack-plugin#511]
Terminal:

> webpack-test@1.0.0 dev /home/ubuntu/workspace/webpack-test
> webpack -d --watch
> 
> /home/ubuntu/workspace/webpack-test/node_modules/extract-text-webpack-plugin/schema/validator.js:11
>                 throw new Error(ajv.errorsText());
>                 ^
> 
> Error: data['disabled'] should NOT have additional properties
>     at validate (/home/ubuntu/workspace/webpack-test/node_modules/extract-text-webpack-plugin/schema/validator.js:11:9)
>     at new ExtractTextPlugin (/home/ubuntu/workspace/webpack-test/node_modules/extract-text-webpack-plugin/index.js:125:3)
>     at Object.<anonymous> (/home/ubuntu/workspace/webpack-test/webpack.config.js:31:3)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at requireConfig (/home/ubuntu/workspace/webpack-test/node_modules/webpack/bin/convert-argv.js:96:18)
>     at /home/ubuntu/workspace/webpack-test/node_modules/webpack/bin/convert-argv.js:109:17
>     at Array.forEach (native)
>     at module.exports (/home/ubuntu/workspace/webpack-test/node_modules/webpack/bin/convert-argv.js:107:15)
>     at Object.<anonymous> (/home/ubuntu/workspace/webpack-test/node_modules/webpack/bin/webpack.js:153:40)
>     at Module._compile (module.js:571:32)
> 
> npm ERR! Linux 4.9.17-c9
> npm ERR! argv "/home/ubuntu/.nvm/versions/node/v7.10.0/bin/node" "/home/ubuntu/.nvm/versions/node/v7.10.0/bin/npm" "run" "dev"
> npm ERR! node v7.10.0
> npm ERR! npm  v4.2.0
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! webpack-test@1.0.0 dev: `webpack -d --watch`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the webpack-test@1.0.0 dev script 'webpack -d --watch'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the webpack-test package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     webpack -d --watch
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs webpack-test
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls webpack-test
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/ubuntu/.npm/_logs/2017-05-20T16_46_15_334Z-debug.log

debug.log:

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/home/ubuntu/.nvm/versions/node/v7.10.0/bin/node',
> 1 verbose cli   '/home/ubuntu/.nvm/versions/node/v7.10.0/bin/npm',
> 1 verbose cli   'run',
> 1 verbose cli   'dev' ]
> 2 info using npm@4.2.0
> 3 info using node@v7.10.0
> 4 verbose run-script [ 'predev', 'dev', 'postdev' ]
> 5 info lifecycle webpack-test@1.0.0~predev: webpack-test@1.0.0
> 6 silly lifecycle webpack-test@1.0.0~predev: no script for predev, continuing
> 7 info lifecycle webpack-test@1.0.0~dev: webpack-test@1.0.0
> 8 verbose lifecycle webpack-test@1.0.0~dev: unsafe-perm in lifecycle true
> 9 verbose lifecycle webpack-test@1.0.0~dev: PATH: /home/ubuntu/.nvm/versions/node/v7.10.0/lib/node_modules/npm/bin/node-gyp-bin:/home/ubuntu/workspace/webpack-test/node_modules/.bin:/home/ubuntu/.nvm/versions/node/v7.10.0/bin:/usr/local/rvm/gems/ruby-2.3.0/bin:/usr/local/rvm/gems/ruby-2.3.0@global/bin:/usr/local/rvm/rubies/ruby-2.3.0/bin:/mnt/shared/bin:/home/ubuntu/workspace/node_modules/.bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/mnt/shared/sbin:/opt/gitl:/opt/go/bin:/mnt/shared/c9/app.nw/bin:/usr/local/rvm/bin
> 10 verbose lifecycle webpack-test@1.0.0~dev: CWD: /home/ubuntu/workspace/webpack-test
> 11 silly lifecycle webpack-test@1.0.0~dev: Args: [ '-c', 'webpack -d --watch' ]
> 12 silly lifecycle webpack-test@1.0.0~dev: Returned: code: 1  signal: null
> 13 info lifecycle webpack-test@1.0.0~dev: Failed to exec dev script
> 14 verbose stack Error: webpack-test@1.0.0 dev: `webpack -d --watch`
> 14 verbose stack Exit status 1
> 14 verbose stack     at EventEmitter.<anonymous> (/home/ubuntu/.nvm/versions/node/v7.10.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at EventEmitter.emit (events.js:194:7)
> 14 verbose stack     at ChildProcess.<anonymous> (/home/ubuntu/.nvm/versions/node/v7.10.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at ChildProcess.emit (events.js:194:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:899:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 15 verbose pkgid webpack-test@1.0.0
> 16 verbose cwd /home/ubuntu/workspace/webpack-test
> 17 error Linux 4.9.17-c9
> 18 error argv "/home/ubuntu/.nvm/versions/node/v7.10.0/bin/node" "/home/ubuntu/.nvm/versions/node/v7.10.0/bin/npm" "run" "dev"
> 19 error node v7.10.0
> 20 error npm  v4.2.0
> 21 error code ELIFECYCLE
> 22 error errno 1
> 23 error webpack-test@1.0.0 dev: `webpack -d --watch`
> 23 error Exit status 1
> 24 error Failed at the webpack-test@1.0.0 dev script 'webpack -d --watch'.
> 24 error Make sure you have the latest version of node.js and npm installed.
> 24 error If you do, this is most likely a problem with the webpack-test package,
> 24 error not with npm itself.
> 24 error Tell the author that this fails on your system:
> 24 error     webpack -d --watch
> 24 error You can get information on how to open an issue for this project with:
> 24 error     npm bugs webpack-test
> 24 error Or if that isn't available, you can get their info via:
> 24 error     npm owner ls webpack-test
> 24 error There is likely additional logging output above.
> 25 verbose exit [ 1, true ]

package.json:

> {
>   "name": "webpack-test",
>   "version": "1.0.0",
>   "description": "",
>   "main": "index.js",
>   "scripts": {
>     "dev": "webpack -d --watch",
>     "prod": "webpack -p"
>   },
>   "keywords": [],
>   "author": "",
>   "license": "ISC",
>   "devDependencies": {
>     "css-loader": "^0.28.1",
>     "extract-text-webpack-plugin": "^2.0.0-rc.0",
>     "html-webpack-plugin": "^2.28.0",
>     "node-sass": "^4.5.3",
>     "sass-loader": "^6.0.5",
>     "style-loader": "^0.17.0",
>     "webpack": "^2.2.0",
>     "webpack-dev-server": "^2.4.5"
>   }
> }

webpack.config.js:
> let HtmlWebpackPlugin = require('html-webpack-plugin');
> let ExtractTextPlugin = require('extract-text-webpack-plugin');
> 
> module.exports = {
> 	entry: './src/app.js',
> 	output: {
> 		path: 'dist',
> 		filename: 'app,bundle.js'
> 	},
> 	module: {
> 		rules: [
> 			{
> 				test: /\.scss$/, 
> 				use: ExtractTextPlugin.extract({
> 					fallback: 'style-loader',
> 					use: ['css-loader', 'sass-loader'],
> 					publicPath: '/dist'
> 				})
> 			}
> 		]
> 	},
> 	plugins: [
> 		new HtmlWebpackPlugin({
> 			title: 'Custom',
> 			minify: {
> 				collapseWhitespace: true
> 			},
> 			hash: true,
> 			template: './src/index.ejs',
> 		}),
> 		new ExtractTextPlugin({
> 			filename: 'app.css',
> 			disabled: false,
> 			allChunks: true
> 		})
> 	]
> }

**Comment by michael-ciniawsky** [comment]
`disabled` => `disable` and please update to the latest version of ETWP (`v2.1.0`)
