### ISSUE TITLE
Scss work in production, but in developement not

### ISSUE THREAD

**Issue by Loppone** [webpack-contrib/extract-text-webpack-plugin#523]
Here is my config:

```
	var webpack = require('webpack');

	const ExtractTextPlugin = require("extract-text-webpack-plugin");
	const extractSass = new ExtractTextPlugin({
		filename: "bundle.css",
		disable: process.env.NODE_ENV === "development"
	});

	module.exports = {
		entry: {
			'app': './assets/app/main.ts'
		},

		resolve: {
			extensions: ['.js', '.ts']
		},

		module: {
			rules: [
				{
					test: /\.html$/,
					use: [{ loader: 'html-loader' }]
				},
				{
					test: /\.css$/,
					use: [{ loader: 'raw-loader' }]
				},
				{
					test: /\.scss$/,
					use: extractSass.extract({
						use: [{
							loader: "css-loader"
						}, {
							loader: "sass-loader"
						}],
						fallback: "style-loader"
					})
				}],
			exprContextCritical: false
		},
		plugins: [
			extractSass
		]
	};


```

My component:

```
@Component({
  styleUrls: ['./auth.component.scss','../common/common.scss']
})

```

In developement i get this error:

```
Uncaught Error: Expected 'styles' to be an array of strings.

```

Thanks for any help.

**Comment by evilebottnawi** [comment]
@Loppone config looks good, can your provide minimal reproducible test repo?

**Comment by Loppone** [comment]
@evilebottnawi 
I just created a scheleton part of my app: just a app.component with the environment i use. It's enough to replicate the problem.

Repo is here: [https://github.com/Loppone/test_scss](url)

Thanks!!
Max

**Comment by michael-ciniawsky** [comment]
@Loppone I don't know exactly where `@Component` is coming from (Angular 2 ?), but if you what the CSS content as `{String}` in there you need to `require()/ import` them nevertheless :) Only if your framework would handle the FIle I/O itself the example above may work, but like I stated above there is not enough context given to be sure about that fact.

```diff
@Component({
-   styleUrls: ['./auth.component.scss','../common/common.scss']
})

@Component({
+  styleUrls: [ require('./auth.component.scss'), require('../common/common.scss') ]
})
```

But you are using `.scss` there and the correct config for this would be like you did for `.css` files with `raw-loader` (`raw-loader!sass-loader`). if you want to extract the styles instead, better just 

```diff
+ import './path/to/style.scss'

@Component({
-   styleUrls: ['./auth.component.scss','../common/common.scss']
})
```

EWTP creates a separate CSS files from these `import`s then

**Comment by Loppone** [comment]
@michael-ciniawsky 
it's an Angular 2 app.

You solved my problem!!

```
 import './common/common.scss'

@Component({
  styleUrls: ['./auth.component.css,']
})

```

This work percfecty both in development and in production.
Instead, using require into "StyleUrls" didn't worked.

Thank you very much!!  🥇 
Max
