### ISSUE TITLE
[Validation] ajv version mismatch with webpack

### ISSUE THREAD

**Issue by jabberwo** [webpack-contrib/extract-text-webpack-plugin#524]
Just got extract-text-webpack so I'm up-to-date.  It pulled in a new module "ajv@5.1.5".  When I run webpack it's this new module that is throwing.  

Error: no schema with key or ref "http://json-schema.org/draft-04/schema#"

Since extract-text-webpack is the one that needed it; I'm posting here; because maybe someone else noticed this already or can tell me how to not even need it.

I only using the plugin to build up a CSS file.  Using it just like the github homepage says:

```js
{
   rules: [
      {
         test: /\.css$/,
         use: ExtractTextPlugin.extract({
            fallback: "style-loader",
            use: "css-loader"
         })
      }
   ]
   },
   plugins: [
      new ExtractTextPlugin( {
         filename: "[name].css"
      }),
   ]
}
```

thanks,
Jab

**Comment by jabberwo** [comment]
Note, AJV was updated to require new schema's in April -- perhaps extract-text-webpack-plugin only works with older version?

**Comment by thomasgwatson** [comment]
I'm trying to upgrade from 2.0.0.beta.6 (I know) to 3.0.0-rc.1 and having issues.

` throw new _ValidationError2.default(ajv.errors, name);
    ^

false`

Does this mean I've got a stale version of ajv or that I need to change something in my webpack config as I upgrade to 3.1.0?

**Comment by michael-ciniawsky** [comment]
did you clear the npm `cache` and `node-modules`?

**Comment by matt-d-rat** [comment]
@thomasgwatson I was getting the error you report recently as I upgraded from an old beta of webpack 2 to webpack 3. The issue in my case was caused by an incorrect option passed to ```ExtractTextPlugin.extract``` - I was passing ```fallbackLoader``` (old config option) instead of ```fallback``.

Make sure you double check the options you are providing to both the ExtractTextPlugin and ExtractTextPlugin.extract in your webpack configuration file(s).

The error is a little vague though, it simply says ```false``` on the second line, but doesn't explain what part of the webpack configuration was incorrect.

**Comment by tim545** [comment]
Thanks @matt-d-rat! that helped me a lot, for me I had to rename the `fallbackLoader` option to `fallback` and `loader` to `use`

**Comment by manoj-nandakumar** [comment]
My test webpack.config.js
```

const ExtractTextPlugin = require('extract-text-webpack-plugin');
const path = require('path');

module.exports = {
  entry: ['./src/app.js', './src/scss/main.scss'],  
  module: {
    rules: [
      {
        test: /\.scss$/, 
        use: ExtractTextPlugin.extract({
            fallback: 'style-loader',
            use: ['css-loader','sass-loader'],
            publicPath: '/dist'
        })
      }
    ]
	},
  plugins: [
    new ExtractTextPlugin({
        filename: 'app.css',
        disable: false,
        allChunks: true
    })
	],
  devtool: 'inline-source-map',
  devServer: {
    contentBase: './dist'
  },  
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist')
  }
};
```

**Comment by harp29** [comment]
Getting same error:

node_modules/extract-text-webpack-plugin/node_modules/schema-utils/dist/validateOptions.js:40
    throw new _ValidationError2.default(ajv.errors, name);


webpack.config.js file:

const path = require('path');
var webpack = require('webpack');
var htmlWebpackPlugin = require('html-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
 
module.exports = {
    entry: './src/app.js',
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'app.bundle.js'
    },
    devServer: {
        contentBase: path.join(__dirname, "/dist"),
        compress: true,
        port: 3000,
        hot: true,
        stats: "errors-only",
        open: true
    },
    module:{
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: 'babel-loader'
            },
            {
                test: /\.css$/,
                use:[
                     "style-loader" , "css-loader"
                    ]
            },
            {
                test: /\.scss$/,
                use: ExtractTextPlugin.extract({
                    fallbackLoader: 'style-loader',
                    loader: [
                        'css-loader', 'sass-loader'
                    ],
                    publicPath: '/dist'
                })
            }
        ]
    },
    plugins: [
        new htmlWebpackPlugin({
            title: 'Webpack template html only',
            template: './src/index.ejs',
            minify: {
                collapseWhitespace: true
            },
            hash: true
        }),
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NamedModulesPlugin(),
        new ExtractTextPlugin({
            filename: 'app.css',
            disable: false,
            allChunks: true
        })
    ]
 
};

How to fix this?

Thanks.
