### ISSUE TITLE
CSS bundles get emitted on every file change in watch mode

### ISSUE THREAD

**Issue by maggo** [webpack-contrib/extract-text-webpack-plugin#525]
I have an issue with the latest webpack and extract-text-webpack-plugin where in watch mode the CSS bundles will be emitted on each and every file change, even if they're 100% not depending on each other.

You can have a look at my example repo: https://github.com/maggo/extract-watch-issue After `npm install && npm run build` try to change the content of script.js, it will always trigger an emit of style.css

**Comment by michael-ciniawsky** [comment]
Only with latest webpack (did it work before?). CSS as an entry point is not recommended, I'm not sure how webpack handles that internally. If you change a entry file and an new bundle is generated without using e.g `CommonsChunkPlugin`, `ExtractTextPlugin`  will try to extract contents from this **one**  bundle containing your entries
