### ISSUE TITLE
CSS loads if not on App component

### ISSUE THREAD

**Issue by pbreah** [webpack-contrib/extract-text-webpack-plugin#528]
I have version 2.1.0 installed and just experienced this issue after updating.

The problem is if I do an `import '../styles/App.css'` on the App component. The CSS is not picked up. If I include the CSS elsewhere on ComponentX the CSS gets picked up.

It's a weird problem and an annoying one. Below is my webpack.config.js

Any ideas?

```js
module.exports = {
  entry: {
      bundle: './src/index.js',
      vendor: VENDOR_LIBS
  },
  output: {
    path: path.join(__dirname, 'public/build'),
    filename: '[name].[chunkhash].js'
  },
  module: {
      rules: [
          {
              use: 'babel-loader',
              test: /\.js$/,
              exclude: /node_modules/
          },
          {
              test: /\.css$/i,
              use: ExtractTextPlugin.extract({
                  fallback: 'style-loader',
                  use: 'css-loader'
              })
          }
      ]
  },
  devServer: {
      contentBase: path.join(__dirname, 'public'),
      historyApiFallback: true
  },
  plugins: [
    new ExtractTextPlugin({
        filename: 'style.css',
        allChunks: true
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: ['vendor', 'manifest'],
    }),
    new HtmlWebpackPlugin({
        template: 'src/index.html'
    }),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV' : JSON.stringify(process.env.NODE_ENV)
    }),
    new WebpackShellPlugin({
        onBuildExit: [
            `./postbuild.sh`
        ],
    })
  ]
};
```

**Comment by pbreah** [comment]
It was a react-router v4 routing issue.

**Comment by phlorie** [comment]
Hello. I think I'm getting the same error.
Would you mind explaining how you solved it?
Thanks

**Comment by pbreah** [comment]
The problem was that I was using react-router v3 code on a react-router v4 dependency.

Since the App component was not even loading, the CSS import was not loading. When I migrated my react-router v3 code to react-router v4 everything worked again. So this means you might have to rewrite or merge the App component with your routes (to keep a similar structure as v3, but you can also put routes anywhere following v4 philosophy), so it can load the CSS import.

Check their docs here:

https://reacttraining.com/react-router/web/example/basic

the react-router lib changes its API a lot from one release to another, so these issues are very common as far as I know - I just didn't expect it to be a entire rewrite of react-router on v4.
