### ISSUE TITLE
schema errors on webpack.config.js

### ISSUE THREAD

**Issue by AjGabriel** [webpack-contrib/extract-text-webpack-plugin#544]
I am trying to use the ExtractTextPlugin for my webpack but I am getting an code ELIFECYCLE errno 1

I am unable to see any resolution.. please help.. here's my code:

      rules: [
         {
            test: /\.scss$/,
            use: ExtractTextPlugin.extract({
               fallback: 'style-loader',
               use: ['css-loader', 'sass-loader'],
               publicPath: '/Users/AJ/Desktop/Simple\ Websites/Webpack/dist'
            })
         }
      ]

      new ExtractTextPlugin({
         filename: 'app.css',
         disabled: false,
         allChunks: true
      })

  "devDependencies": {
    "css-loader": "^0.28.4",
    "extract-text-webpack-plugin": "^2.1.2",
    "html-webpack-plugin": "^2.28.0",
    "node-sass": "^4.5.3",
    "sass-loader": "^6.0.5",
    "style-loader": "^0.18.2",
    "webpack": "^2.6.1",
    "webpack-dev-server": "^2.4.5"
  }

**Comment by michael-ciniawsky** [comment]
```diff
  new ExtractTextPlugin({
     filename: 'app.css',
-    disabled: false,
+    disable: false,
     allChunks: true
  })
```

**Comment by michael-ciniawsky** [comment]
If you don't intend to disable the plugin this option is redundant anyways, so maybe remove it entirely

**Comment by AjGabriel** [comment]
@michael-ciniawsky 

Great! I have removed it entirely and the build runs now.. thanks so much!
