### ISSUE TITLE
How can I hash my class names in both DOM and SCSS?

### ISSUE THREAD

**Issue by amerllica** [webpack-contrib/extract-text-webpack-plugin#545]
Hi
I saw the [FlipKart](https://flipkart.com) , they made hash all of their classNames and its CSSes.
I know that they use SCSS for building CSS.
How can I config my WebPack to make my exportation like their:

![capture](https://user-images.githubusercontent.com/10472437/27254080-155c4b3e-5396-11e7-8e15-8f828fa26ee6.JPG)

This is my webpack:

```
var webpack = require('webpack'),
    path = require('path'),
    ExtractTextPlugin = require('extract-text-webpack-plugin'),
    UglifyJSPlugin = require('uglifyjs-webpack-plugin'),
    OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin');

var DistDir = path.resolve(__dirname, 'app/dist'),
    SrcDir = path.resolve(__dirname, 'app/src');

module.exports = {
    entry: SrcDir,
    output: {
        path: DistDir,
        filename: "bundle.min.js"
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                include: SrcDir,
                loader: 'babel-loader'
            },
            {
                test: /\.scss$/,
                exclude: /node_modules/,
                use: ExtractTextPlugin.extract({
                    use: [{
                        loader: "css-loader", options: {
                            sourceMap: false
                        }
                    }, {
                        loader: "sass-loader", options: {
                            sourceMap: false
                        }
                    }],
                    fallback: "style-loader"
                })
            },
            {
                test: /\.png$/,
                loader: "file-loader",
                exclude: /node_modules/
            }
        ]
    },
    plugins: [
        new webpack.DefinePlugin({
            'process.env': {
                'NODE_ENV': JSON.stringify('production')
            }
        }),
        new ExtractTextPlugin("bundle.min.css"),
        new OptimizeCssAssetsPlugin({
            cssProcessor: require('cssnano'),
            cssProcessorOptions: { discardComments: {removeAll: true } },
            canPrint: true
        }),
        new UglifyJSPlugin({
            compress: {
                unused: true,
                dead_code: true,
                warnings: false,
                drop_debugger: true,
                conditionals: true,
                evaluate: true,
                drop_console: true,
                sequences: true,
                booleans: true
            },
            comments: false
        }),
        new webpack.IgnorePlugin(/^\.\/locale$/, [/moment$/]),
        new webpack.NoEmitOnErrorsPlugin(),
        new webpack.optimize.AggressiveMergingPlugin()
    ]
};
```

**Comment by michael-ciniawsky** [comment]
´´´diff
{
  loader: "css-loader", 
  options: {
     modules: true, // <=
     sourceMap: false
   }
}
´´´

https://github.com/webpack-contrib/css-loader#modules
https://github.com/css-modules/css-modules

**Comment by amerllica** [comment]
Thanks @michael-ciniawsky  but I know `modules: true` dude, It make the CSSes hash but the DOM has Dev version className,
I want the config that transform classNames in DOM.

**Comment by michael-ciniawsky** [comment]
You can pass a different hashing pattern to `options.localIdentName`  in `css-loader` 

```js
const env = process.env.NODE_ENV
...
{
  loader: 'css-loader',
  options: { 
    modules: true, 
    localIdentName: env === 'production' 
     ? '[hash:base64]' 
     : '[path][name]__[local]--[hash:base64:5]' 
  }
}
```

> I want the config that transform classNames in DOM

What do you mean by that ?

**Comment by amerllica** [comment]
Dear @michael-ciniawsky , I think my poor english make this mistake.
you can see my quenstion in [this link](https://stackoverflow.com/questions/44612399/webpack-extract-text-plugin-localidentname-not-working-in-dom)

> I want the config that transform classNames in DOM

I mean, when I use `modules: true`, Just class names in CSS file deformed to hash, but class names that sets is `JSX` codes, still remain to dev version. see the capture:

![asdf](https://user-images.githubusercontent.com/10472437/27276730-4b49427c-54f1-11e7-9339-6b69d662352d.JPG)

See red area, their class name are not mach with their class name in CSS file, because with `modules: true` just CSS transformed not class names in DOM.

**Comment by michael-ciniawsky** [comment]
```js
import style from './file.css'

class Component extends React.Component {
   render () {
     return (
       <div className=${style.app}></div> 
    )
  }
}
```

```js
import style from 'style.css'

document.body.innerHTML =  `
   <div class=${style.app}></div<
`
```


When `modules` are set you get the `classNames` on the CSS `import` as an `{Object}` :)

**Comment by amerllica** [comment]
Thanks, complicated concept with no clear documentation :'(

**Comment by amerllica** [comment]
Hi Dear @michael-ciniawsky 
When I use your solution I got this error from Terminal:

`You may need an appropriate loader to handle this file type.`

![capture](https://user-images.githubusercontent.com/10472437/27326277-49593ea2-55c0-11e7-8e3a-3c701e850ffd.JPG)

I set the `css-loader` in my `webpack` config file. you can see my `webpack` config file in top of this page in my question.

**Comment by michael-ciniawsky** [comment]
> ./blub/blub/blub/_breadcrumb.**css**

Typo 😛 ?  The `rule` doesn't match `.css` files (extensions) atm, so webpack treats it as a `js` file (no loaders), therefore

> "You may need an appropiate loader to handle this file type"

**webpack.config.js**
```
...
test: /\.scss$/ <=
... 
```

```diff
- test: /\.scss$/
+ test: /\.(scss|css)$/ // maybe 
```

**Comment by amerllica** [comment]
Thanks dear @michael-ciniawsky , It works
