### ISSUE TITLE
How to choose extract postion?

### ISSUE THREAD

**Issue by ZikDead** [webpack-contrib/extract-text-webpack-plugin#547]
How to insert css file at the bottom of body?

**Comment by michael-ciniawsky** [comment]
You mean in your `index.html` ? If so *manually* 😛 the purpose of this plugin is CSS extraction only

**Comment by ZikDead** [comment]
It changes link to style tag, btw...

**Comment by michael-ciniawsky** [comment]
🙃 ? No... that's either the `fallback` (`style-loader`) getting triggert then or something else in your config. Anyways by injecting in the body, my assumption above was 'correct' and the issue can be closed as won't fix here ?
