### ISSUE TITLE
Output logging level verbosity

### ISSUE THREAD

**Issue by wayofthefuture** [webpack-contrib/extract-text-webpack-plugin#550]
I would like possibly recommend a logging level option. My webpack build is always nice and clean until it gets to extract-text plugin, then I get a largely verbose output and pages of display which makes it hard to notice build errors with webpack.

If possible I think maybe adding an option called logLevel may help. We could use values such as: quiet, warning, error, detail. Thoughts? Thanks...

**Comment by evilebottnawi** [comment]
@wayofthefuture can your provide what exactly your want to see in logs?

**Comment by wayofthefuture** [comment]
I would think instead of showing every single file that it converts, show something like this:

Child extract-text-webpack-plugin:
  Extracted X files - total size XX.XKB

And that's it, unless there are errors then can display those. Thoughts?

**Comment by zallek** [comment]
would be great

**Comment by evilebottnawi** [comment]
@zallek you can disable output in `webpack`, we use `createChildCompiler` https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/7ae32d9c560ef0a7dd584e3bf5991bacd5753093/src/loader.js#L44 and `webpack` output this information

**Comment by wayofthefuture** [comment]
@evilebottnawi My webpack is already full of so much scaffolding I'd rather not implement more. There should be a simple fix to this. Thanks.

**Comment by wayofthefuture** [comment]
@d3viant0ne I think a higher priority may be better... It is possible for us to miss very important build errors due to the output of this plugin. I'm always having to scroll endlessly up the terminal screen.

**Comment by evilebottnawi** [comment]
@wayofthefuture can you example detail what you get and what you want?

**Comment by wayofthefuture** [comment]
Please see above comment for possible output...

**Comment by PengJiyuan** [comment]
+1

**Comment by joejuzl** [comment]
+ 1

**Comment by lucasjsoliveira** [comment]
For me, setting `stats.children` to `false` removed all the info extract-text was giving and I didn't need. Hope it helps while we don't get a verbosity level setting.

**Comment by cletusw** [comment]
@lucasjsoliveira Will this hide errors, though? If errors still show, then that should be perfect.

**Comment by evilebottnawi** [comment]
@wayofthefuture `stats.children` solve you problem?
@lucasjsoliveira no error always output

**Comment by wayofthefuture** [comment]
@evilebottnawi I don't know... first I need to know if errors will output regardless

**Comment by shellscape** [comment]
@evilebottnawi could this be a target for webpack-log?

**Comment by thasmo** [comment]
It looks like this for me:
```sh
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-1!node_modules/postcss-loader/lib/index.js!node_modules/sass-loader/lib/loader.js!assets/components/logo/styles/base.scss:
       2 modules
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-1!node_modules/postcss-loader/lib/index.js!node_modules/sass-loader/lib/loader.js!assets/components/navigation/styles/base.scss:
       2 modules
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-1!node_modules/postcss-loader/lib/index.js!node_modules/sass-loader/lib/loader.js!assets/components/navigation/styles/default.scss:
       2 modules
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-1!node_modules/postcss-loader/lib/index.js!node_modules/sass-loader/lib/loader.js!assets/components/panel/styles/base.scss:
       2 modules
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-1!node_modules/postcss-loader/lib/index.js!node_modules/sass-loader/lib/loader.js!assets/components/section/styles/base.scss:
       2 modules
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-1!node_modules/postcss-loader/lib/index.js!node_modules/sass-loader/lib/loader.js!assets/components/section/styles/default.scss:
       2 modules
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-1!node_modules/postcss-loader/lib/index.js!node_modules/sass-loader/lib/loader.js!assets/components/button/styles/base.scss:
       2 modules
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-1!node_modules/postcss-loader/lib/index.js!node_modules/sass-loader/lib/loader.js!assets/components/tab/styles/base.scss:
       2 modules
```
Just much longer. ;)

Setting `stats.children` to `false` doesn't work for me in this case.

**Comment by thasmo** [comment]
Oh, nevermind. I was wrong - `stats.children` did help!

**Comment by wayofthefuture** [comment]
stats.children false solved the problem!!! THANKS!

**Comment by ismailbayram** [comment]
```
stats: {
      builtAt: false,
      children: false,
      modules: false
    }
```
webpack: 4.5.0
webpack-dev-server: 3.1.3
