### ISSUE TITLE
[webpack 3.0.0] TypeError: chunk.isInitial is not a function

### ISSUE THREAD

**Issue by pedroabreu** [webpack-contrib/extract-text-webpack-plugin#554]
I've just updated to webpack 3.0.0 and I'm started getting this issue when running my tests.

```
26 06 2017 17:42:57.000:ERROR [karma]: TypeError: chunk.isInitial is not a function
    at isInitialOrHasNoParents (/node_modules/extract-text-webpack-plugin/dist/lib/helpers.js:15:16)
    at /node_modules/extract-text-webpack-plugin/dist/index.js:187:94
    at /node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3083:16
    at eachOfArrayLike (/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1003:9)
    at eachOf (/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1051:5)
    at Object.eachLimit (/ocelot/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3145:5)
```

Any idea on how to fix this ?

**Comment by lightsaway** [comment]
Have same problem

**Comment by d3viant0ne** [comment]
Need a minimal proj where this is reproducible.

**Comment by d3viant0ne** [comment]
Pick up `extract-text-webpack-plugin@3.0.0-rc.2`

**Comment by tauseef-inbetween** [comment]
Still not working

**Comment by tsfahmad** [comment]
Facing same problem with extract-text-webpack-plugin@3.0.0-rc.2

**Comment by pedroabreu** [comment]
Updating `karma-webpack` worked for me (plus using the latest `extract-text-webpack-plugin`)

**Comment by jk171505** [comment]
Facing the same problem with webpack 3.5.5

**Comment by tauseef-inbetween** [comment]
Passing latest webpack into the gulpWebpack function worked for me

**Comment by jk171505** [comment]
updating memory-fs to the latest break exposes this bug again. From that moment on nothing helps.
I tried to reinstall node, npm, nothing helped.
My current setup:
    "ajv": "^5.2.2",
    "css-loader": "^0.28.5",
    "extract-text-webpack-plugin": "^3.0.0",
    "handlebars": "^4.0.10",
    "metalsmith": "^2.3.0",
    "metalsmith-express": "^0.1.0",
    "metalsmith-in-place": "^1.4.4",
    "metalsmith-layouts": "^1.8.1",
    "metalsmith-permalinks": "^0.5.0",
    "metalsmith-swig": "^1.2.1",
    "metalsmith-watch": "^1.0.3",
    "metalsmith-webpack": "^1.0.3",
    "node-sass": "^4.5.3",
    "script-loader": "^0.7.0",
    "style-loader": "^0.18.2",
    "swig": "^1.4.2",
    "webpack": "^3.5.5"

I tried it in:
node versions: 6.11.2, 7.4.0, 8.4.0
npm: 5.3.0

Still:
TypeError: chunk.isInitial is not a function
    at isInitialOrHasNoParents (/Users/janusz/Sites/androidworks/Red7eKentuckyOwl/kentucky-owl/node_modules/extract-text-webpack-plugin/dist/lib/helpers.js:15:16)
