### ISSUE TITLE
Problems with React-Redux-Toastr

### ISSUE THREAD

**Issue by sh4d1t0** [webpack-contrib/extract-text-webpack-plugin#559]
I have problems with [React-Redux-Toastr](https://github.com/diegoddox/react-redux-toastr), I have this issue:

> ERROR in ./~/react-redux-toastr/src/styles/index.scss
> Module parse failed: /home/develop/sites/react/node_modules/react-redux-toastr/src/styles/index.scss Unexpected character '@' (1:0)
> You may need an appropriate loader to handle this file type.
> | @import './variables.scss';
> | @import './animation.scss';
> | @import './confirm.scss';
>  @ ./src/index.es6 21:0-46
>  @ multi (webpack)-dev-server/client?http://localhost:3333 webpack/hot/dev-server ./index.es6

I was imported like this:

`import "!style-loader!sass-loader!react-redux-toastr/src/styles/index";`

And know I have this new issue:

> ERROR in ./~/sass-loader/lib/loader.js!./~/react-redux-toastr/src/styles/index.scss
> Module parse failed: /home/develop/sites/react/node_modules/sass-loader/lib/loader.js!/home/develop/sites/react/node_modules/react-redux-toastr/src/styles/index.scss Unexpected token (1:0)
> You may need an appropriate loader to handle this file type.
> | .animated {
> |   animation-duration: 1s;
> |   animation-fill-mode: both; }
>  @ ./~/style-loader!./~/sass-loader/lib/loader.js!./~/react-redux-toastr/src/styles/index.scss 4:14-74 13:2-17:4 14:20-80
>  @ ./src/index.es6
>  @ multi (webpack)-dev-server/client?http://localhost:3333 webpack/hot/dev-server ./index.es6

**Comment by michael-ciniawsky** [comment]
`import "!style-loader!sass-loader!react-redux-toastr/src/styles/index";`
 
You are using `style-loader` and `css-loader` is missing. It won't work that way with ETWP, how did you set that up in `webpack.config.js` ?  What is `react-reduy-toastr` ? A webpack loader ?

**Comment by sh4d1t0** [comment]
@michael-ciniawsky of course, I was missing css-loader, anyway here is my webpack config and the solution was in the import line:
```
const path = require("path");
const ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
    "context": path.resolve(__dirname, "./src"),
    "entry": {
        "app": "./index.es6"
    },
    "output": {
        "path": path.resolve(__dirname, "./dist/assets"),
        "filename": "./bundle.js",
        "publicPath": "/"
    },
    "module": {
        "rules": [
            // JSX and ES6 transpilation using babel
            {
                "test": /\.(es6|jsx)$/,
                "exclude": /node_modules/,
                "use": "babel-loader"
            },
            // Image path loader
            {
                "test": /\.(jpg|jpeg|png|gif)$/,
                "exclude": /node_modules/,
                "use": [
                    {"loader": "url-loader", "options": {"limit": 8192}}
                ]
            },
            // Font path loader
            {
                "test": /\.(eot|ttf|woff|woff2|svg|otf)$/,
                "use": [
                    {"loader": "file-loader"}
                ]
            },
            /* SASS modularization using style and css loader */
            {
                "test": /\.scss$|\.css$/,
                "use": ExtractTextPlugin.extract({
                    "fallback": "style-loader",
                    "use": [
                        {
                            "loader": "css-loader",
                            "query": {"modules": false, "sourceMaps": true}
                        },
                        {
                            "loader": "sass-loader",
                            "query": {"sourceMaps": true}
                        }
                    ]
                }),
                "include": /flexboxgrid/
            }
        ]
    },
    "resolve": {
        "alias": {
            "api": path.resolve(__dirname, "./src/api/"),
            "assets": path.resolve(__dirname, "./src/assets/"),
            "common": path.resolve(__dirname, "./src/common/"),
            "constants": path.resolve(__dirname, "./src/constants/"),
            "containers": path.resolve(__dirname, "./src/containers/"),
            "services": path.resolve(__dirname, "./src/services/"),
            "store": path.resolve(__dirname, "./src/store"),
            "util": path.resolve(__dirname, "./src/util")
        },
        "extensions": [".js", ".es6", ".json", ".jsx", ".scss"]
    },
    "devtool": "cheap-module-source-map",
    "plugins": [
        // replace with new ExtractTextPlugin("[name]_[hash].css") for prod
        new ExtractTextPlugin({
            "filename": "[name].css?v=[contenthash]",
            "allChunks": true
        })
    ],
    "devServer": {
        "contentBase": path.join(__dirname, "./dist"),
        "compress": false,
        "inline": true,
        "host": "localhost",
        "port": 3333
        // Display only errors to reduce the amount of output.
        // "stats": "errors-only"
    },
    "watch": true
};
```
I added css-loader too into sass-loader in my index.es6 (or index.js or .jsx), just like this:

> import "!style-loader!sass-loader!react-redux-toastr/src/styles/index";

Now works perfectly, thanks Michael

**Comment by michael-ciniawsky** [comment]
```diff
{
    loader: "${name}-loader",
-  "query": {"sourceMaps": true}
+   options: {  sourceMaps: true }
}
```

`query` is deprecated in favour of `options` since `webpack >= v2.0.0`, otherwise look 👍 to me

Reopen in case you still have any regressions in regard to `ETWP`
