### ISSUE TITLE
Error HtmlWebpackPlugin if(typeof content...)

### ISSUE THREAD

**Issue by imaninyasia** [webpack-contrib/extract-text-webpack-plugin#571]
I'm getting this error when i npm run watch:
Module build failed: Unknown word (5:1)
 5 | if(typeof content === 'string') content = [[module.id, content, '']];

```javascript
...
plugins: [
    new HtmlWebpackPlugin({
      title: 'Urban Arts Summer Intensive',
      xhtml: true,
      inject: false,
      debug: true,
      template: require('html-webpack-template'),
      appMountId: 'root-container'
    }),
    new ExtractTextPlugin(
    {
      filename:'./css/[name].css',
      allChunks: true
    })
  ]
...
 module : {
    rules: [
      {
        test: /\.css$/,
        include: path.join(__dirname, 'src'),
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: ["css-loader","style-loader"]
  })
}]}
... 
```
module and rules is closed. 

What's wrong with my syntax? i'm using webpack 3.3.0 with React.js and here's my babel file, 
{
  "presets" : ["es2015", "react", 'stage-0'],
  "compact" : true,
  "plugins": [
    ["transform-strict-mode", {
      "strict": true
    }],
    ["transform-runtime", {
      "helpers": false, // defaults to true
      "polyfill": false, // defaults to true
      "regenerator": true, // defaults to true
      "moduleName": "babel-runtime" // defaults to "babel-runtime"
    }]
  ]
}

**Comment by imaninyasia** [comment]
my webpack.config.js file:

'use strict'
const webpack           = require('webpack');
const path              = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

const BUILD_DIR         = path.resolve(__dirname, 'dist');
const APP_DIR           = path.resolve(__dirname, 'src');

module.exports = {
  entry: `${APP_DIR}/index.js`,
  output: {
    path: `${BUILD_DIR}`,
    filename: `./js/[name].js`,
  },
  cache: true,
  devtool: 'eval-source-map',
  stats: {
    colors: true,
    reasons: true
  },
  plugins: [
    new HtmlWebpackPlugin({
      title: 'Urban Arts Summer Intensive',
      xhtml: true,
      inject: false,
      debug: true,
      template: require('html-webpack-template'),
      appMountId: 'root-container'
    }),
    new ExtractTextPlugin({
      filename:'/css/[name].css',
      disable: false,
      allChunks: true
    }),
    new webpack.LoaderOptionsPlugin({
    debug: true
    })
  ],
  //just added this
    devServer: {
      historyApiFallback: true
  },

  module : {
    rules: [
      {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: ["css-loader","style-loader"]
  })


      },
      {
        test: /\.svg$/,
        include: path.join(__dirname, 'src'),
        loader: 'file-loader?name=/img/[name].[hash:base64:5].[ext'
      },
      {
        test: /\.gif$/,
        include: path.join(__dirname, 'src'),
        loader: 'file-loader?name=/img/[name].[hash:base64:5].[ext]'
      },
      { test: /\.jpg$/,
        include: path.join(__dirname, 'src'),
        loader: 'file-loader?name=/img/[name].[hash:base64:5].[ext]'
      },
      {
        test: /\.(js|jsx)$/,
        exclude: [path.resolve(__dirname, "node_modules")],
        loader: `babel-loader`
      },
      {
        test: /\.otf(\?v=\d+\.\d+\.\d+)?$/,
        include: path.join(__dirname, 'src'),
        loader: 'file-loader?name=/fonts/[name].[ext]'

      }
    ]
  }

};

**Comment by evilebottnawi** [comment]
@imaninyasia change `use: ["css-loader","style-loader"]` to `use: ["css-loader"]` in `module.rules`

**Comment by michael-ciniawsky** [comment]
```diff
use: ExtractTextPlugin.extract({
  fallback: "style-loader",
- use: ["css-loader","style-loader"]
+ use: [ "css-loader" ]
})
```
