### ISSUE TITLE
extract to different directory than utput

### ISSUE THREAD

**Issue by jk171505** [webpack-contrib/extract-text-webpack-plugin#572]
I'd like to output the css to different directory than the main output
I'm using webpack 1.
Here is my setup:
`output: {`
`    path: path.join(__dirname, './build', 'assets/js'),`
`      filename: '[name].bundle.js'`
`    },`
`    plugins: [`
`      new ExtractTextPlugin('../css/main.css', { disable: false, allChunks: true })`
`    ]`

The main.css isn't created at all. If I change the path for ExtractTextPlugin to 'css/main.css' I get the error:
Error: Cannot readFile on directory '/.../build/assets/js/css'
The same happens if I put the path to the filename of the output.

What am I doing wrong?

**Comment by evilebottnawi** [comment]
@jk171505 whick version of `ExtractTextPlugin` your use? Current version `3.0.0` works only with `webpack@3`. But before search what is wrong, i strongly recommend upgrade to latest webpack version first.

**Comment by jk171505** [comment]
I'm using the one that works with webpack v1:
extract-text-webpack-plugin: 1.0.1
webpack: 1.15.0

**Comment by evilebottnawi** [comment]
@jk171505 can your provide minimum reproducible repo? Most likely the bug will not be easy to fix, the old versions.

**Comment by jk171505** [comment]
here is the repo:
https://github.com/jk171505/metalsmith-webpack

after install just run: node .

**Comment by evilebottnawi** [comment]
@jk171505 your have very old version `extract-text-webpack-plugin`, please update to latest version, old version can contain bugs and unexpected behavior, seems it is impossible change directory using this old version. After update your can use `filename` as `function` and set directory. Thanks!

**Comment by michael-ciniawsky** [comment]
```diff
- path: path.join(__dirname, './build', 'assets/js'),
+ path: path.join(__dirname, 'build', 'assets/js'),
```
