### ISSUE TITLE
[v3.0.0] Load order is broken when used with multiple entry points

### ISSUE THREAD

**Issue by tals** [webpack-contrib/extract-text-webpack-plugin#573]
Given two entry points that share `import`-ed modules that extract-text processes, these modules actual load order (as they appear in the concatenated file) will be incorrect

For example:
```js
// programA.js
import './css/first.css'
import './css/second.css'
import './css/third.css'
```
```js
// programB.js
import './css/second.css'
import './css/first.css'
```

Yields:
```css
/* extracted programA.css */

/* <content of first.css>... */
/* <content of second.css>... */
/* <content of third.css>... */
```
```css
/* extracted programB.css */
/* <content of first.css>... <-- this is wrong! */
/* <content of second.css>... */
```

Repro: https://github.com/tals/extract-text-plugin-ordering-bug

```
    "extract-text-webpack-plugin": "^3.0.0"
    "webpack": "^3.3.0"
```
> Version in description added by @d3viant0ne

**Comment by michael-ciniawsky** [comment]
Without `allChunks: true` aswell, did it work before and if what was the latest version it worked correctly?

**Comment by tals** [comment]
allChunks makes no difference.

I've only recently started using this plugin, so it never worked for me.
It fails on `2.1.0` and `3.0.0`.

**Comment by elrumordelaluz** [comment]
Don't know if it's related to this issue but upgrading from `2.1.2` into `3.0.0`, noted lots of order changes in the output. 
Using in both versions `allChunks: true` and `ignoreOrder: true`.
Also `modules`, `postcss-loader`, `postcss-nested` and SSR (in case this info could help).

Commenting in the meantime I am [trying to create a repo to reproduce the behaviour](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/548#issuecomment-315152756)

**Comment by ciaran-phillips** [comment]
I also have loading order issues which are only present when using multiple entry points. Have not yet tested `allChunks` but I can confirm I also see the issue on both `2.1.0` and `3.0.0`. I'm not sure yet on what version it worked correctly.

**Comment by evilebottnawi** [comment]
@tals thanks for issue! Can your do PR with failing tests? It help to solve the problem faster

**Comment by rkovalyov** [comment]
same with `2.1.2`

**Comment by giotramu** [comment]
Any update about this Issue?

**Comment by AndrewBogdanovTSS** [comment]
Any updates regarding this issue?

**Comment by tals** [comment]
@AndrewBogdanovTSS Was not aware of that! Thanks!

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
