### ISSUE TITLE
Using ExtractTextPlugin and also include output in bundle?

### ISSUE THREAD

**Issue by kochis** [webpack-contrib/extract-text-webpack-plugin#575]
I know that `ExtractTextPlugin` is used for removing code from the bundle into a separate file, but is there a way to extract the text _and_ also do some processing on the content to keep in the bundle?

Basically, I want to extract all my postCSS modules into one file (using ExtractTextPlugin) but also have the classnames available in the bundle to reference in JS. Is the what the `fallback` open is for?

Ideally, I would be able to do something like the following:

```js
 {
    test: /\.p?css$/,
    use: ExtractTextPlugin.extract([ "css-loader", "postcss-loader" ]),
  },
  {
    test: /\.p?css$/,
    use: [  
      {
        loader: "emit-file-loader",
        options: {
          name: "dist/[path][name].pcss",
        },
      },
      {
        loader: "skeleton-loader",
        options: {
          procedure: function (content) {
            return `module.exports = ${content}`
          },
        },
      },
      "postcss-loader",
    ]),
  }
```
Where each test will generate different output (one to `css`, and one to js module). They way this seems to be working though is that it all becomes part of the same loader chain for any given module.

**Comment by michael-ciniawsky** [comment]
[extract-loader](https://github.com/peerigon) or setting up different `module.rules` one with `extract-text-webpack-plugin` and one without it for modules 

```js
{ 
   test: /\.css$/,
   use: [...loaders], 
   include: 'path/to/include/?', 
   exclude: 'path/to/exclude/?'
},
{ 
   test: /\.css$/,
   use: ExtractTextPlugin.extract({...options}), 
   include: 'path/to/include/?', 
   exclude: 'path/to/exclude/?'
}
```
