### ISSUE TITLE
How to detect when new text was extracted in watch mode?

### ISSUE THREAD

**Issue by wmertens** [webpack-contrib/extract-text-webpack-plugin#577]
I'm trying to do hot reloading of extracted CSS (so that dev and prod have the exact same CSS), and that's working, but I'm having trouble figuring out when there was a change to the CSS.

I tried attaching to "after-emit", but I can't really see what I should filter on to detect if a css file was rebuilt in the current compilation run.

Any hints? Maybe a special event should be emitted?

**Comment by evilebottnawi** [comment]
@wmertens seems add event is good solution. Can your write PR this for this?

**Comment by wmertens** [comment]
@evilebottnawi I'd gladly create a PR but I don't know how to know when a text file was changed.

**Comment by evilebottnawi** [comment]
@wmertens in theory we can store hash of extracted files and when compare them with new extracted files, what do your think about this?

**Comment by wmertens** [comment]
If you are already creating a hash, that would be great; if not, it seems
that there could be a more direct way somehow? Like keeping a list of files
that were output in this compile?

**Comment by evilebottnawi** [comment]
@wmertens we already have content have https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/master/src/index.js#L209

**Comment by evilebottnawi** [comment]
@wmertens btw can your describe more informatively why it is needs?

**Comment by wmertens** [comment]
It seems that hash only gets created on-demand, so it would be a shame to
create it every time…

I tried to describe my use case above. I need to know when a CSS file was
emitted, so that I can tell the browser to hot-reload it. Right now I'm hot
reloading every time, which is annoying…

**Comment by evilebottnawi** [comment]
@wmertens why don't store hash of files directly in `webpack-hot-middleware`?

**Comment by wmertens** [comment]
If I can get the hashes of all files after a compile was done, and know which ones were generated by extract-text-plugin, that would be great. Then I can indeed track hashes and emit on change.

But I don't know how to do that, which events to listen to…

**Comment by michael-ciniawsky** [comment]
ETWP entered maintenance mode and won't receive any feature updates, please open an issue in [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) instead
