### ISSUE TITLE
Webpack 3: You may need an appropriate loader to handle this file type. (Sass)

### ISSUE THREAD

**Issue by ariona** [webpack-contrib/extract-text-webpack-plugin#580]
I can't import my sass in my js.
```js
import './style.scss'
```
It keep producing
```
Module parse failed: /.../ style.scss Unexpected token (1:4)
You may need an appropriate loader to handle this file type.
```
But i am pretty sure i've installed the loaders, Here is my rule for the loader
```js
module.exports = {
  test: /\.s[ac]ss$/,
  include: config.paths.sass,
  loader: ExtractTextPlugin.extract({
    use: [
      {
        loader: 'css-loader',
        options: {
          sourceMap:isdev
        }
      },
      {
        loader: 'postcss-loader',
        options: {
          sourceMap: true,
          plugins: () => [autoprefixer]
        }
      },
      {
        loader: 'sass-loader',
        options: {
          sourceMap: true
        }
      }
    ],
    fallback: 'style-loader',
  })
}
```

`webpack: 3.3.0` and `extract-text-webpack-plugin: 3.0.0`

**Comment by awesomenaz** [comment]
@ariona how about swapping out loader with use? try it out as the docs.

**Comment by ariona** [comment]
Hi @awesomenaz, thanks for replying,  I have tried below configurations:
```js
...
use: ExtractTextPlugin.extract({
    use: [
      {
        loader: 'css-loader',
        options: {
          sourceMap:isdev
        }
      },
      ...
```
still producing `You may need an appropriate loader to handle this file type.`

Also tried:
```js
...
use: ExtractTextPlugin.extract({
    loader: [
      {
        loader: 'css-loader',
        options: {
          sourceMap:isdev
        }
      },
      ...
```
Still no luck, got this instead 😄 
```
/Users/username/.../node_modules/schema-utils/dist/validateOptions.js:40
    throw new _ValidationError2.default(ajv.errors, name);
    ^

false
```

**Comment by awesomenaz** [comment]
Try it like this:

```javascript
const ExtractTextPlugin = require("extract-text-webpack-plugin");
 
const extractSass = new ExtractTextPlugin({
    filename: "[name].[contenthash].css",
    disable: process.env.NODE_ENV === "development"
});
 
module.exports = {
    ...
    module: {
        rules: [{
            test: /\.scss$/,
            use: extractSass.extract({
                use: [{
                    loader: "css-loader"
                }, {
                    loader: "sass-loader"
                }],
                // use style-loader in development 
                fallback: "style-loader"
            })
        }]
    },
    plugins: [
        extractSass
    ]
};
```

Let me know if this helps.

**Comment by awesomenaz** [comment]
include requires you to resolve the path. Which based on you earlier submission, I can't seem to see the path being resolve. 

```javascript
include: [
          path.resolve(__dirname, 'fileName.ext'),
        ],
```

**Comment by ariona** [comment]
😄  it's defined in another file. It it's not defined then i'll get different error.

**Comment by awesomenaz** [comment]
That's right. Hope that solved it. If it is just close this issue. 😄

**Comment by ariona** [comment]
I mean, i already defined the path for include prop in another file. 😄 . the error still tho

**Comment by awesomenaz** [comment]
If it is possible, add the file somewhere we I could probably inspect. As it is not complete. Would be easier.

**Comment by ariona** [comment]
Sorry, My bad. here is the gist https://gist.github.com/ariona/ece9ba6711e61150ea2c41c7e6f8f4d6

The `webpack.config` is the main config and the `app.config` contain the paths and some app configs.

If i am trying to import the style (sass) from js file it keep producing `You may need an appropriate loader to handle this file type.`

**Comment by awesomenaz** [comment]
@ariona is the issue resolved?

**Comment by ariona** [comment]
nope

**Comment by awesomenaz** [comment]
I still think it's a validation issue, especially with the earlier validation error.

The configuration you had:

```javascript
  test: /\.css/
  use: ExtractTextPlugin.extract({
    use: [{
        loader: 'css-loader',
        options: {
          sourceMap:isdev
  })
```

Instead, do this: 
```javascript
  use: ExtractTextPlugin.extract({
        use: 'css-loader',
        fallback: 'style-loader'
  })
```

**Comment by evilebottnawi** [comment]
@ariona problem still exists?

**Comment by GJordan904** [comment]
I too have encountered this error and I've been banging my head against it for awhile now. Was hoping to find answers here but oh well, so here is a little more info. 

Minimal [repo](https://github.com/GJordan904/polymp) with error.

In addition to the method I'm using in the repo, I have tried a number of other configs based off of the docs and other threads I've read. With other configs, I get other errors or the same error but haven't had success yet. The only thing I did figure out was I needed the include array.

**Comment by nantao605** [comment]
I got the same problem!but when i change the file from scss to less,it is all ok.

**Comment by evilebottnawi** [comment]
@nantao605 please provide you `webpack` config, thanks!

**Comment by nantao605** [comment]
when i use scss file, my config is blow:  

        `rules:[
            {
                test: /.\js$/,
                use: ['babel-loader'],
                exclude:[/node_modules/],
            },{
                test:/.\scss$/,
                use:ExtractTextPlugin.extract({
                    fallback:'style-loader',
                    use: ['css-loader','sass-loader']
                }),
                include: path.resolve(__dirname,'src/style')
            },{
                test: /.\css$/,
                use:ExtractTextPlugin.extract({
                    fallback:'style-loader',
                    use: 'css-loader'
                }),
            }
        ]`

and the config of using less is similar to sass,which i just change sass-loader to less-loader.

Sorry,my English is not good!

**Comment by evilebottnawi** [comment]
@nantao605 why you use `include`?
`include` - `An array of paths or files where the imported files will be transformed by the loader`.
In other path, example `node_modules` this loader doesn't works.

**Comment by gauravksoni** [comment]
Were you able to resolve this issue?
Coming only in my machine

**Comment by bitstrider** [comment]
using `webpack@3.81`

because my css has `@import`, i get the build error `Module build failed: ModuleParseError: Module parse failed: Unexpected character '@'` with this rule:

```
loader: ExtractTextPlugin.extract({
  fallback: 'style-loader',
  loader: 'css-loader?minimize'
})
```

but works with `use` instead of `loader`:

```
loader: ExtractTextPlugin.extract({
  fallback: 'style-loader',
  use: 'css-loader?minimize'
})
```

Its too bad the error message isn't more helpful here.

**Comment by tvsijin** [comment]
Exactly same issue here

`const UglifyJsPlugin = require('uglifyjs-webpack-plugin')
const ExtractTextPlugin = require("extract-text-webpack-plugin");


const path = require('path');

module.exports = {
  	entry: ['./js/theme.js', './js/app.js', './js/config.js', './js/directives.js', './js/controllers.js','./css/animate.css', './css/style.css'],
  	output: {
    	filename: 'app.js',
    	path: path.resolve(__dirname, 'dist')
    },
    module: {
        loaders: [
            {
                test: ['./css/animate.css', './css/style.css'],
                use: ExtractTextPlugin.extract("style-loader", "css-loader")
            }
        ]
    },
    plugins: [
    	new ExtractTextPlugin("app.css"),
    	// new UglifyJsPlugin({
    	// 	cache: true,
    	// 	parallel: true
    	// })
  	]
  		
};`

**Comment by michael-ciniawsky** [comment]
```diff
const UglifyJsPlugin = require('uglifyjs-webpack-plugin')
const ExtractTextPlugin = require("extract-text-webpack-plugin");


const path = require('path');

module.exports = {
-  	entry: ['./js/theme.js', './js/app.js', './js/config.js', './js/directives.js', './js/controllers.js','./css/animate.css', './css/style.css'],
+       entry: [ './js/theme.js', './js/app.js', './js/config.js', './js/directives.js', './js/controllers.js' ]
  	output: {
    	filename: 'app.js',
    	path: path.resolve(__dirname, 'dist')
    },
    module: {
-        loaders: [
+       rules: [
            {
-              test: ['./css/animate.css', './css/style.css'],
+              test: /\.css$/,
-              use: ExtractTextPlugin.extract("style-loader", "css-loader")
+              use: ExtractTextPlugin.extract({
+                   fallback: "style-loader", 
+                   use: [ "css-loader" ]
+                })
            }
        ]
    },
    plugins: [
-    	new ExtractTextPlugin("app.css"),
+       new ExtractTextPlugin({ filename: "[name].css" }),
    	// new UglifyJsPlugin({
    	// 	cache: true,
    	// 	parallel: true
    	// })
  	]
  		
};
```

**Comment by allan2coder** [comment]
hi, gays~ have you solve this problem?

**Comment by liuyingbin19222** [comment]
i met these problems again!

**Comment by senseijames** [comment]
This issue can occur due to invisible characters in your SCSS file.  Oddly enough, most IDEs (WebStorm included) will not detect these erring characters!  You'd need to paste your code into an SCSS linter to see them:
https://www.sassmeister.com/

**Comment by sonnguy** [comment]
Excluding node_modules was the solution for me.
{ 
  test: /\.scss$/i, 
  exclude: /node_modules/, 
  use: isDevBuild ? ['style-loader', 'css-loader', 'sass-loader'] : 
  ExtractTextPlugin.extract({ use: ['css-loader', 'sass-loader'] }) 
}

**Comment by ngthtung** [comment]
It's work for me https://github.com/webpack-contrib/css-loader/issues/38

**Comment by sfisoc** [comment]
For CSS raw loader worked for me:

`{
                test: /\.(html|css)$/,
                loader: 'raw-loader'
            },`
        "raw-loader": "^0.5.1",

**Comment by RossHathaway** [comment]
I was getting this error, and I believe it was because I had a .babelrc file which listed the presets and I also had them in my webpack config. Once I commented them out in the webpack config, it solved the problem.
