### ISSUE TITLE
 chunk.sortModules is not a function

### ISSUE THREAD

**Issue by GZWZC** [webpack-contrib/extract-text-webpack-plugin#582]
```
"extract-text-webpack-plugin": "^3.0.0",
"webpack": "^2.5.0",
```

webpack.config.js
```
module: {
        rules:[
            {
                test:/\.js$/,
                exclude:/node_modules/,
                loader: ['babel-loader']
            },
            {
                test: /\.css$/,
                use: ExtractTextPlugin.extract(['style-loader', 'css-loader?modules', 'postcss-loader'])
            }
        ]
    },
```
when i webpack,cmd is console  `chunk.sortModules is not a function`，what should i do?

**Comment by michael-ciniawsky** [comment]
> "webpack": "^2.5.0"

`extract-text-webpack-plugin >= v3.0.0` isn't compatible with `webpack =< v2.0.0`, use `v2.0.0` of the plugin `npm i -D extract-text-webpack-plugin@^2.0.0` if you intend to use webpack `v2.0.0` or update to `webpack v3.0.0`
