### ISSUE TITLE
css will emitted everytime when watch mode

### ISSUE THREAD

**Issue by winnerhp** [webpack-contrib/extract-text-webpack-plugin#584]
#### my package.json like this:
``` json
"extract-text-webpack-plugin": "^2.0.0",
"webpack": "^2.2.1"
'CommonsChunkPlugin': xxx
```
#### question?
everytime I save my entry js not the css, the css will emitted again however the css did not change, so what happens?

I notice that this plugin register 'compilation.plugin("additional-assets")' and everytime compilation.assets[somecssfile] =` new object`, so the compilation.assets[somecssfile].emitted = true

who can help me, thanks?

**Comment by evilebottnawi** [comment]
@winnerhp thanks for issue. Can your provide minimum reproducible test repo?

**Comment by winnerhp** [comment]
@evilebottnawi 

* [repos](https://github.com/winnerhp/issues-test.git)
* npm install
* npm run dev

#### then

everytime you change src/page/entry_one.js or entry_two.js，the control will print like
```
          Asset      Size  Chunks             Chunk Names
js/entry_two.js    2.8 kB       1  [emitted]  entry_two
  entry_one.css  42 bytes       0  [emitted]  entry_one
  entry_two.css  22 bytes       1  [emitted]  entry_two
```
both entry_one.css and  entry_two.css will emitted,however the content of css is not change.

**Comment by evilebottnawi** [comment]
@winnerhp seems related to https://github.com/webpack/webpack/issues/5321 (just information)

**Comment by evilebottnawi** [comment]
@winnerhp Duplicate https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/594. Thanks for issue!
