### ISSUE TITLE
Explicitly disable sourcemaps for CSS files

### ISSUE THREAD

**Issue by mcongy** [webpack-contrib/extract-text-webpack-plugin#587]
Hello,

webpack version: 3.4.1
extract-text-webpack-plugin: 3.0.0

In production, I'm using `devtool: 'source-map'` which implicitly enables sourcemaps (even for my extracted css files - and I don't want that).

Is there a way to explicitly disable them? And if so, can you provide a working solution?
I've been experimenting with webpack.SourceMapDevToolPlugin, but without any luck.

Thanks!

**Comment by evilebottnawi** [comment]
@mcongy just disable `sourceMap` for `css-loader` (https://github.com/webpack-contrib/css-loader#options) in `production` env, thanks!
