### ISSUE TITLE
Extract css file to a path that different  from the bundle path, the background-img url will be wrong

### ISSUE THREAD

**Issue by maihaihua** [webpack-contrib/extract-text-webpack-plugin#589]
Version:
`webpack: "3.4.1"`
`extract-text-webpack-plugin: "3.0.0"`

Description:

There is a css rule in my css file like this:

```css
#app {
	background: url(../img/logo.png);
}
```
First, I config plugins like this in webpack.config.js:

```js
new ExtractTextPlugin({
        filename: "[name].css"
});
```
This work well. In the css file , the background url is `'img/logo.png'`.

However, when i want to output the css file to other directory something goes to wrong.I config plugins like this in webpack.config.js:

```js
new ExtractTextPlugin({
        filename: "css/[name].css"
})
```

Finally, the css file generate to the right directory but in the css file the background url is still `'img/logo.png'` and lead to 404 not found about the background-img. The right url should be `'../img/logo.png'`.

**Comment by evilebottnawi** [comment]
@maihaihua `extract-text-webpack-plugin` don't handle `url`, seems your have invalid configuration, please provide full config or minimum reproducible test repo.

**Comment by maihaihua** [comment]
My repo config like this：
https://github.com/maihaihua/webpack-test.git

**Comment by halionn** [comment]
i also have this problem

**Comment by halionn** [comment]
solve this problem by other way, change the file-loader param like this
loader: 'file-loader?name=../../images/[name].[ext]'

my webpack.config.js:

var path = require('path')
var webpack = require('webpack')
var HtmlWebpackPlugin = require('html-webpack-plugin')
var ExtractTextPlugin = require('extract-text-webpack-plugin')
var CopyWebpackPlugin = require('copy-webpack-plugin')


module.exports = {
    entry: {
        "upload-business-license": path.resolve(__dirname, 'app/upload-business-license/index.js'),
        //page2: path.resolve(__dirname, 'app/page2.js')
    },
    output: {
        path: __dirname + "/dist",
        //filename: "[name].[chunkhash:8].js",
        filename: "[name].js",
        //publicPath: '/'
    },

    resolve:{
        extensions:['.js']
    },

    module: {
        rules: [
            {
                test: /\.(scss|sass|css)?$/,
                exclude: /(node_modules)/,
                use: ExtractTextPlugin.extract({ //分离css
                    fallback: "style-loader",
                    use: [
                        {
                            loader: 'css-loader',
                            options: {
                                importLoaders: 1
                            }
                        },
                        'postcss-loader',
                        'sass-loader'
                    ]
                })
            },
            {
                test: /\.(jpg|jpeg|gif|bmp|png|webp)?$/i,
                exclude: /(node_modules)/,
                loader: 'file-loader?name=../../images/[name].[ext]'
            }
        ]
    },

    plugins: [

        new webpack.BannerPlugin("author: jhl \ndate: 2017-10-25"),

        new HtmlWebpackPlugin({
            template: __dirname + '/app/upload-business-license/index.tmpl.html',
            filename: 'upload-business-license.html',
            chunks: ['upload-business-license']
        }),

        //new ExtractTextPlugin('css/[name]/[name].css'),
        //new ExtractTextPlugin('[name].css'),
        new ExtractTextPlugin('css/[name]/[name].css'),

        new CopyWebpackPlugin([
            {
                from: 'static/css/common/common.css',
                to: 'css/common'
            },
            {
                from: 'static/js/plugins/flexible.js',
                to: 'js/plugins'
            },
            {
                from: 'static/images',
                to: 'images'
            }
        ])

    ]
}

**Comment by halionn** [comment]
solve this problem by other way, modify the file-loader param to change the image url , like this: 
```
loader: 'file-loader?name=../../images/[name].[ext]'
```

**Comment by hamodey85** [comment]
same issue here

**Comment by evilebottnawi** [comment]
@maihaihua use `publicPath` option for this purpose https://github.com/webpack-contrib/extract-text-webpack-plugin#extract.

For other:
Please read my comments above, ETWP __don't handle url__. In most use case it is just invalid configuration. Feel free to feedback and/or create new issue with description and reproducible test repo. Thanks for everyone!
