### ISSUE TITLE
How does options.publicPath work?

### ISSUE THREAD

**Issue by nyngwang** [webpack-contrib/extract-text-webpack-plugin#591]
version: "extract-text-webpack-plugin": "^3.0.0",

I want to know how exactly publicPath option does. The following settings didn't override "foo/" with "bar/".

```
var HtmlWebpackPlugin = require("html-webpack-plugin");
var ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
    entry: "./src/app.js",
    output: {
        path: __dirname + "/dist",
        filename: "javascript/app.bundle.js",
        publicPath: "foo/"                                // original
    },
    module: {
        rules: [{
            test: /\.css$/,
            use: ExtractTextPlugin.extract({
                fallback: "style-loader",
                use: "css-loader",
                publicPath: "bar/"                        // this should override original
            })
        }]
    },
    plugins: [
        new HtmlWebpackPlugin({
            hash: true,
            minify: {
                collapseWhitespace: true
            },
            title: "Yeah",
            filename: "index.html",
            template: "src/template/index.html"
        }),
        new ExtractTextPlugin({
            filename: "css/app.css"
        })
    ]
};
```

**Comment by evilebottnawi** [comment]
@nyngwang should be works https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/7ae32d9c560ef0a7dd584e3bf5991bacd5753093/src/loader.js#L39. Can your create minimum reproducible test repo? Thanks!

**Comment by rodfersou** [comment]
this is not working here

**Comment by zigang93** [comment]
yes, this is not working! 
same issue: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/693

**Comment by evilebottnawi** [comment]
@rodfersou @zigang93 can you describe issue more verbose?

**Comment by rodfersou** [comment]
@evilebottnawi well.. the publicPath option is not working.. you set the publicPath, like the example here in this issue, but the string is not added before the generated file reference.

**Comment by MarkPolivchuk** [comment]
I'm having the same issue. My public path in the output is `/js/`, and I am attempting to override it like so: 
```
      {
        test: /\.(scss|sass)$/,
        use: ExtractTextPlugin.extract({ 
          use: ['css-loader?minimize', 'postcss-loader?sourceMap', 'sass-loader?sourceMap'],
          publicPath: '/css/',
        })
      },
```
But the resulting extracted CSS ends up in `/js/`. 

`publicPath` property is being totally ignored

**Comment by zigang93** [comment]
Other loader 's `publicPath` will overwrite your ExtractTextPlugin `publicPath` .
For my case, my `file-loader` `publicPath` overwrite my ExtractTextPlugin `publicPath`.

Please double check your webpack config file.

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
