### ISSUE TITLE
JS file change is emitted on CSS change since version 3

### ISSUE THREAD

**Issue by dmitrybelyakov** [webpack-contrib/extract-text-webpack-plugin#593]
Hi,

We are seeing a strange behaviour with extract text version 3: when a sass file is being changed several times in a row we get different file changes being emitted. Basically it alternates between just the css file and both js and css files although the js file was not changed at all. That happens every other time so that when you do several saves in a row:

  * css is reported
  * both css and js is being reported
  * then again just the css
  * then both again
  * etc

Here is a screenshot to demonstrate that behaviour:

![screen shot 2017-08-05 at 09 43 55](https://user-images.githubusercontent.com/178866/28994357-ed2e96cc-79c3-11e7-9096-7edb69382d73.png)

This however does not happen with version 2, when only the css file is being reported as in this screenshot:

![screen shot 2017-08-05 at 09 45 50](https://user-images.githubusercontent.com/178866/28994366-30a06bc4-79c4-11e7-9265-91e9d80f2759.png)

We have created two minimal reproducible examples with version 2 and version 3, so you can just `git clone`, `npm install` and then `npm run watch`:

  * extract text v2.1: https://github.com/dmitrybelyakov/webpack-browsersync/tree/extract2
  * extract text v3.0: https://github.com/dmitrybelyakov/webpack-browsersync/tree/master

I hope I managed to explain it clear enough. Do you guys know why this might be happening?

**Comment by malinushj** [comment]
I'm having this issue as well

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
