### ISSUE TITLE
Wrong output when importing a css module

### ISSUE THREAD

**Issue by vinpac** [webpack-contrib/extract-text-webpack-plugin#595]
Hi, I'm getting a strange behavior when I import a css module.
When I Include..
```
import 'font-awesome/css/font-awesome.css'
import 'normalize.css'
```
...in my Layout.js the output css is only these two and the rest of my `.scss` files are ignored. It looks like they replace all the style imported before and replace them. I tried import them later, importing only one, the behavior is the same. If I remove these two the output is all my `.scss` as it should be but without the modules I need.

package.json
```
"webpack": "3.4.1",
"extract-text-webpack-plugin": "^3.0.0",
```

webpack.config.js
```

const styleRules = [
  // Process external/third-party styles
  {
    loader: 'css-loader',
    options: {
      sourceMap: isDebug,
      minimize: !isDebug,
      discardComments: { removeAll: true },
    },
  },

  // Process internal/project styles (from src folder)
  {
    loader: 'css-loader',
    options: {
      // CSS Loader https://github.com/webpack/css-loader
      importLoaders: 1,
      sourceMap: isDebug,
      // CSS Modules https://github.com/css-modules/css-modules
      modules: false,
      localIdentName: isDebug ? '[name]-[local]-[hash:base64:5]' : '[hash:base64:5]',
      // CSS Nano http://cssnano.co/options/
      minimize: !isDebug,
      discardComments: { removeAll: true },
    },
  },

  // Apply PostCSS plugins including autoprefixer
  {
    loader: 'postcss-loader',
    options: {
      config: {
        path: './tools/postcss.config.js',
      },
    },
  },

  // Compile Sass to CSS
  // https://github.com/webpack-contrib/sass-loader
  // Install dependencies before uncommenting: yarn add --dev sass-loader node-sass
  {
    loader: 'sass-loader',
  },
]

// ---------------- the rule
{
  test: /\.(css|less|scss|sss)$/,
  rules: [
    {
      exclude: path.resolve(__dirname, '../src'),
      use: extractTextPlugin.extract({
        fallback: 'style-loader',
        use: [styleRules[0], styleRules[2]],
      }),
    },

    {
      test: /\.css/,
      include: path.resolve(__dirname, '../src'),
      use: extractTextPlugin.extract({
        fallback: 'style-loader',
        use: [styleRules[1], styleRules[2]],
      }),
    },

    {
      test: /\.scss$/,
      include: path.resolve(__dirname, '../src'),
      use: extractTextPlugin.extract({
        fallback: 'style-loader',
        use: [styleRules[1], styleRules[2], styleRules[3]],
      }),
    },
  ],
}
```

**Comment by evilebottnawi** [comment]
@vinpac Most likely you just have the wrong configuration. Why your use `test` before `rules`? Why your add `include` and `exclude` options for rules? Can your provide minimum reproducible test repo?

**Comment by vinpac** [comment]
Include and exclude make the rule only applied on different files, so I can control differently css libs and internal scss files.

" Why your use test before rules?" I don't get where it can change something, sorry.

The repo and file where I change the imports:
https://github.com/vinpac/react-base/blob/master/src/components/Layout/Layout.js

It happens when building. Use 'yarn build-release or npm run build-release'.

Thanks

**Comment by michael-ciniawsky** [comment]
```diff
const styleRules = [
  {
    loader: 'css-loader',
    options: {
      sourceMap: isDebug,
+      minimize: !isDebug ? { discardComments: { removeAll: true } } : false,
-      discardComments: { removeAll: true },
    },
  },
 ...

{
-  test: /\.(css|less|scss|sss)$/,
  rules: [
    // What is this actually doing ?
    {
      exclude: path.resolve(__dirname, '../src'),
      test: // (?),
      use: extractTextPlugin.extract({
        fallback: 'style-loader',
        use: [styleRules[0], styleRules[2]],
      }),
    },

    {
      test: /\.css$/,
      include: path.resolve(__dirname, '../src'),
      use: extractTextPlugin.extract({
        fallback: 'style-loader',
        use: [styleRules[1], styleRules[2]],
      }),
    },

    {
      test: /\.scss$/,
      include: path.resolve(__dirname, '../src'),
      use: extractTextPlugin.extract({
        fallback: 'style-loader',
        use: [styleRules[1], styleRules[2], styleRules[3]],
      }),
    },
  ],
}
```

Please include `{Error}` logs/stacktraces aswell

> ⚠️  `inlcude/exclude` seems to be buggy with `extract-text-webpack-plugin`  so please try without aswell to at least confirm it doesn't fail elsewhere

Maybe use two different instances of ETWP instead 

**webpack.config.js**
```js
const ExtractCSS = new ExtractTextPlugin({ filename: 'lib.css' })
const ExtractSASS = new ExtractTextPlugin({ filename: '[name].css' })

const config = {
  ...
  module: {
    rules: [
      {
         test: /\.css$/,
         use: ExtractCSS.extract(...)
      },
      {
        test: /\.scss$/,
        use: ExtractSASS.extract(...)
      }
    ]
  },
  plugins: [
     ExtractCSS,
     ExtractSASS
  ]
}

module.exports = config
```

**Comment by vinpac** [comment]
```
const extractTextPlugin = new ExtractTextPlugin({
  filename: 'style.css',
})


---- new rules

      {
        test: /\.css$/,
        use: isDebug ? undefined : extractTextPlugin.extract({
          fallback: 'style-loader',
          use: ['css-loader'],
        }),
        rules: !isDebug ? undefined : [
          { use: 'style-loader' },
          styleRules[1],
          styleRules[2],
        ],
      },
      {
        test: /\.scss$/,
        use: isDebug ? undefined : extractTextPlugin.extract({
          fallback: 'style-loader',
          use: ['css-loader', 'sass-loader'],
        }),
        rules: !isDebug ? undefined : [
          { use: 'style-loader' },
          styleRules[1],
          styleRules[2],
          styleRules[3],
        ],
      },

``

And I still get the wrong output when I import a module like 'normalize.css'. The output becomes only normalize.css.

I don't get errors when building.

```
➜  react-base git:(master) ✗ yarn build-release
yarn build-release v0.21.3
$ babel-node tools/run build-release 
[11:35:23] Starting 'buildRelease'...
[11:35:24] Starting 'build'...
[11:35:24] Starting 'clean'...
[11:35:24] Finished 'clean' after 27 ms
[11:35:24] Starting 'copy'...
[11:35:24] Finished 'copy' after 9 ms
[11:35:24] Starting 'bundle'...
Child client:
    Time: 10794ms
                       Asset      Size  Chunks                    Chunk Names
                111fad64.jpg   67.2 kB          [emitted]         
          client.2f52c3d7.js     19 kB       0  [emitted]         client
          vendor.790a4f99.js    331 kB       1  [emitted]  [big]  vendor
                   style.css   7.76 kB    0, 1  [emitted]         client, vendor
      client.2f52c3d7.js.map   95.7 kB       0  [emitted]         client
               style.css.map  86 bytes    0, 1  [emitted]         client, vendor
      vendor.790a4f99.js.map   3.03 MB       1  [emitted]         vendor
    ../../templates/html.hbs   1.28 kB          [emitted]         
Child server:
    Time: 3232ms
            Asset     Size  Chunks             Chunk Names
     111fad64.jpg  67.2 kB          [emitted]  
        server.js    50 kB       0  [emitted]  server
    server.js.map  41.3 kB       0  [emitted]  server
[11:35:35] Finished 'bundle' after 10876 ms
[11:35:35] Finished 'build' after 10913 ms
[11:35:35] Finished 'buildRelease' after 11603 ms
Done in 12.90s.
```

**Comment by michael-ciniawsky** [comment]
Like mentioned in my last comment you need **multiple**  Instances of ETWP (per rule) to make it work

```diff
+const extractCSS = new ExtractTextPlugin({ filename: 'lib.css' })
+const extractSCSS = new ExtractTextPlugin({ filename: '[name].css' })
...
+module: {
+  rules: [
      {
        test: /\.css$/,
        use: isDebug ? undefined : extractCSSextract({
          fallback: 'style-loader',
          use: ['css-loader'],
        }),
-       rules: !isDebug ? undefined : [
-         { use: 'style-loader' },
-          styleRules[1],
-         styleRules[2],
        ],
      },
      {
        test: /\.scss$/,
-       use: isDebug ? undefined : extractSCSS.extract({
          fallback: 'style-loader',
          use: ['css-loader', 'sass-loader'],
        }),
-        rules: !isDebug ? undefined : [
-          { use: 'style-loader' },
-          styleRules[1],
-          styleRules[2],
-          styleRules[3],
-        ],
      }
  ]
},
+plugins: [
+  extractCSS,
+  extractSCSS
+]
```

Or just add `normalize.css` and other vendor libs via `<link href="cdn/path/to/lib.css" rel="stylesheet">` since you doing plain {String} copying for those anyways and only deal with App specific CSS in webpack

**Comment by vinpac** [comment]
There's no way of putting this all in the same file?

**Comment by michael-ciniawsky** [comment]
`sass-loader` should be able to handle `.css` aswell so you may join the rule and let `css-loader`@import "xyz.css";` then. I never used that before myself but you can try... Still long-term caching will be better if you split `lib|vendor.css` from `app.css` if via  CDN or separate rule is entirely your choice, albeit you don't really gain anything from doing it via webpack (`extract-text-plugin`)

```js
{
   test: /\.(scss|css)$/, // <=
   use: extractCSS.extract({ use: [ ...loaders ], fallback: 'style-loader' }) 
}
```
