### ISSUE TITLE
It is occur error when use require.ensure function lazy load the module incudle css file.

### ISSUE THREAD

**Issue by linkeer8802** [webpack-contrib/extract-text-webpack-plugin#597]
**index.js:**
```
$('.btn').click(function () {
  require.ensure([], function (require) {
    var Dialog = require('../components/dialog/dialog.js')
    new Dialog()
  })
})
```
**dialog.js**
```
require('./css/dialog.css')
var html = require('./tmpl/dialog.html')

module.exports = function () {
  var $dialog = $(html).clone()
  $dialog.find('.close').on('click', function () {
    $dialog.fadeOut(function () {
      $(this).remove()
    })
  })
  $('body').append($dialog)
  $dialog.fadeIn()
}
```
I config the index.js as a entry,but the  dialog.js are not,that is to say dialog.css will not to be extracted,
it will inline in js file, in this case will occur error.

**Comment by evilebottnawi** [comment]
@linkeer8802 please show your error(s), without this information we can not help (maybe invalid configuration or old version(s), or maybe your are right it is bug), better if your create minimum reproducible test repo, thanks!

**Comment by evilebottnawi** [comment]
@linkeer8802 Thanks for issue. Duplicate https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/455
