### ISSUE TITLE
chunk.sortModules is not a function

### ISSUE THREAD

**Issue by lilian132** [webpack-contrib/extract-text-webpack-plugin#598]
v 3.0.0

`rules:[
      {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: "css-loader"
        })
      },
    ]`

` plugins: [
    new ExtractTextPlugin({
      filename: "[name].[contenthash].css"
    })
]`

Converting the version back to 2.0.0 does not appear to be the problem, but this problem occurs only in 3.0.0

**Comment by kostasmanionis** [comment]
`chunk.sortModules` has been introduced in `webpack@v3.1.0`, you must be using an older version of webpack 🤔

**Comment by tom10271** [comment]
I am using webpack v2.2.x but still getting this error. So I am installing a wrong version of extract-text-webpack-plugin?

**Comment by rohitjindal18** [comment]
Either upgrade your webpack to 3.1.0 or if your webpack is below version 3 use 2.1.0 version of extract-text-webpack-plugin
