### ISSUE TITLE
whether can i config such like this?

### ISSUE THREAD

**Issue by anlexN** [webpack-contrib/extract-text-webpack-plugin#603]
![default](https://user-images.githubusercontent.com/8686739/29306033-26db0c72-81ce-11e7-8332-2586e20f7ab6.PNG)

**Comment by evilebottnawi** [comment]
@anlexN Example of configuration contain in (https://github.com/webpack-contrib/extract-text-webpack-plugin#usage). Can your describe about your problem more?

**Comment by anlexN** [comment]
i see your example. i just hope you can help me justify if  my configuration is correct!

**Comment by evilebottnawi** [comment]
@anlexN what your got - error or don't extract css? Please describe your problem, thanks!

**Comment by michael-ciniawsky** [comment]
@anlexN 

```diff
ExtractTextPlugin.extract({
+ fallback: 'style-loader'
+ use: [
- { loader: style-loader },
+  ...loaders
+ ]
})
```
