### ISSUE TITLE
css file not generated with webpack 3.5.4 and extract-text-webpack-plugin 3.0.0

### ISSUE THREAD

**Issue by althamash-chaipoint** [webpack-contrib/extract-text-webpack-plugin#607]
My project has a scss file that imports other scss modules. Production bundle should compile it into css and extract the code and generate a new .css file. Its quietly failing without errors. (.css file is not being generated).

sample repo:
[https://github.com/althamash-chaipoint/sample-webpack-extract](https://github.com/althamash-chaipoint/sample-webpack-extract)

steps:
npm install
webpack -p --config webpack.config.js --progress

**Comment by mbhuvaneswaran** [comment]
you are loading asynchronously change the following files if you are not intending to do so
`const path = require("path");
const ExtractTextPlugin = require("extract-text-webpack-plugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
     entry: {
        app: "./index.js"
    },
    output: {
        path: path.join(__dirname, "dist"),
        publicPath: "/",
        filename: "[name].js",
        chunkFilename: "[name].js"
    },
  module: {
    rules: [
      {
        test: /\.scss$/,
        use: ExtractTextPlugin.extract({fallback: 'style-loader',
          use: ["css-loader", "sass-loader"]
        })
      }
    ]
  },
  plugins: [
    new ExtractTextPlugin("styles.css"),
    new HtmlWebpackPlugin({
        hash: false,
        template: "./index.html"
    })
  ]
}`

`import './test.scss'
var blah = "blah";
`

**Comment by althamash-chaipoint** [comment]
This fixed it. thanks for the help!

**Comment by sarbull** [comment]
More readable code here.

```js
const path = require("path");
const ExtractTextPlugin = require("extract-text-webpack-plugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
  entry: {
    app: "./index.js"
  },
  output: {
    path: path.join(__dirname, "dist"),
    publicPath: "/",
    filename: "[name].js",
    chunkFilename: "[name].js"
  },
  module: {
    rules: [
      {
        test: /.scss$/,
        use: ExtractTextPlugin.extract({fallback: 'style-loader',
          use: ["css-loader", "sass-loader"]
        })
      }
    ]
  },
  plugins: [
    new ExtractTextPlugin("styles.css"),
    new HtmlWebpackPlugin({
      hash: false,
      template: "./index.html"
    })
  ]
}
```

**Comment by evilebottnawi** [comment]
@sarbull If you have problem please open new issue. Thanks!

**Comment by sarbull** [comment]
@evilebottnawi i just commented so that the code is readable for others when they come to this page. 

Big thanks!
