### ISSUE TITLE
chunk.sortModules is not a function

### ISSUE THREAD

**Issue by Omazon** [webpack-contrib/extract-text-webpack-plugin#608]
I'm using Vue with simple webpack, and it is problem that chunk.sortModules is not a function, have researched and supposedly is the webpack and plugin version problem, but both are in the latest version and not know that most make it to make it work.

**Comment by kostasmanionis** [comment]
Looking at the simple webpack template it seems that it's using `"webpack": "^2.6.1"`. You either need to upgrade webpack to `v3.1.0` at a minimum, or downgrade extract-text-webpack-plugin to  `v2.1.2`.

**Comment by Omazon** [comment]
That is indeed what is happening, I was assumed that the command vue-webpack-simple cli installed the latest version of webpack and it is not, manually updated it and works perfect. Thank you for your answer.

**Comment by evilebottnawi** [comment]
@kostasmanionis thanks for helping :+1:
