### ISSUE TITLE
301 Moved Permanently - Webpack 2 production build

### ISSUE THREAD

**Issue by kkomaz** [webpack-contrib/extract-text-webpack-plugin#610]
On my local build I am able to separate my js and sass/css files without any issues on the front-end application.  However, on the production build I am getting a  **301 Moved Permanently** status code and none of my styles are implemented.  I am unsure why this is occurring and haven't seen anything related.  Any help would be appreciated.  

Version:
Webpack 2.2.1
extract-Text-webpack-plugin 2.1.2

```js
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const extractSCSS = new ExtractTextPlugin('stylesheets/style-one.css');
const extractCSS = new ExtractTextPlugin('stylesheets/style-two.css');

// module code:
module: {
  rules: [
        {
          test: /\.scss$/,
          use: extractSCSS.extract({
            fallback: 'style-loader',
            use: [
              'css-loader?importLoaders=2',
              'postcss-loader',
              'sass-loader',
            ],
          }),
        },
        {
          test: /\.css$/,
          use: extractCSS.extract({
            fallback: 'style-loader',
            use: 'css-loader',
          }),
        },
  ]
}
//plugin code
plugins: [
...,
extractSCSS,
extractCSS,
]
```

Index.html

```html
    <link rel="stylesheet" href="public/stylesheets/style-one.css">
    <link rel="stylesheet" href="public/stylesheets/style-two.css">
```

**Comment by evilebottnawi** [comment]
@kkomaz seems your have invalid server configuration. `extract-text-webpack-plugin` do not create any redirects. Just check your server configuration. If you do not know how to configure the server your can ask about this on  `stackoverflow` or other related resources. Thanks!
