### ISSUE TITLE
Module ID conflict on first dev server compilation

### ISSUE THREAD

**Issue by avaly** [webpack-contrib/extract-text-webpack-plugin#612]
The latest version of `extract-text-webpack-plugin` triggers a weird bug in a webpack bundle where multiple modules share the same module ID.

For more context, see: https://github.com/webpack/webpack/issues/5560#issuecomment-324339585

**Comment by evilebottnawi** [comment]
@avaly thanks for issue, can your provide minimum reproducible test repo?

**Comment by avaly** [comment]
Unfortunately, no I don't have a minimal test case. Any attempts to remove any number of modules from our giant bundle (1000+ modules) makes the bug not present itself.

**Comment by evilebottnawi** [comment]
@avaly maybe problem in webpack, if you disable `extract-text-webpack-plugin` all work fine?

**Comment by khalsah** [comment]
I'm running into a similar issue when attempting an upgrade of `extract-text-webpack-plugin`.

In our case webpack-dev-server successfully completes the initial build of the project.
If you edit a stylesheet the rebuild will have the inconsistent module ID issue mentioned here.
If you then edit a javascript file the rebuild will complete successfully.

Downgrading `extract-text-webpack-plugin` to 2.1.2 avoids the issue.
Bypassing `extract-text-webpack-plugin` and just using `style-loader` directly avoids the issue.

**Comment by evilebottnawi** [comment]
@khalsah maybe you can create minimum reproducible test repo or at least make the screenshot?

**Comment by sentience** [comment]
We're blocked from upgrading to 3.0 by this issue too, and I've managed to reduce our app down to a near-minimal test case: https://github.com/cultureamp/multi-loader-extract-text-bug

This Webpack configuration uses both `multi-loader` and `extract-text-webpack-plugin`, and removing either one seems to make the problem disappear, although I strongly suspect the use of `multi-loader` is merely a coincidence.

**Comment by sentience** [comment]
@avaly, @khalsah: Are either of you using multi-loader in your configs?

**Comment by khalsah** [comment]
No multi-loader in our config.

**Comment by joaovieira** [comment]
same issue, no multi-loader. also tested:
- `extract-text-webpack-plugin@2.1.2` + `webpack@3.5.6`: ok
- `extract-text-webpack-plugin@3.0.0-beta.0` + `webpack@3.5.6`: not ok

first build is fine, but on rebuild module IDs get moved around

**Comment by evilebottnawi** [comment]
@joaovieira can you provide minimum reproducible test repo, it is allow more faster find solution, thanks!

**Comment by joaovieira** [comment]
Yes, will try and see what I can find. Just had to run off of work earlier. Will post with details.

**Comment by joaovieira** [comment]
Ok, spent hours trimming it down to this: https://github.com/joaovieira/webpack-extract-bug. Maybe its too small as there are no CSS modules and the Sass file and class that go through `extract-text` are not even used. But the symptoms are always the same - a module is replaced and called with unexpected args.


I hope it helps. Removing any of the loaders causes it to work 😕

**Comment by evilebottnawi** [comment]
@joaovieira thanks!

**Comment by evilebottnawi** [comment]
@joaovieira seems something wrong with cache, try to add `cache: false` to `webpack.config.js` and all works as expected :confused:

**Comment by evilebottnawi** [comment]
@joaovieira just add code for invalidate cache to https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/master/src/loader.js#L51
```
var subCache = "subcache " + NS + " " + request; // eslint-disable-line no-path-concat
    childCompiler.plugin("compilation", function(compilation) {
      if(compilation.cache) {
        if(!compilation.cache[subCache])
          compilation.cache[subCache] = {};
        compilation.cache = compilation.cache[subCache];
      }
    });
```

**Comment by evilebottnawi** [comment]
@sentience @joaovieira and you are right, it is regression after upgrade from `2.1.2` to `3`

**Comment by evilebottnawi** [comment]
PR https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/627

**Comment by sokra** [comment]
This is a webpack bug. The cache is not correctly created. webpack should handle caches for child compilers.

**Comment by evilebottnawi** [comment]
@sokra should we https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/627 as workaround before `webpack` fir this bug?

**Comment by sokra** [comment]
Give me a few hours and I fix it in webpack...

**Comment by joaovieira** [comment]
Awesome. Great work guys! @sokra @evilebottnawi glad I could help.
