### ISSUE TITLE
chunk.isInitial is not a function

### ISSUE THREAD

**Issue by jk171505** [webpack-contrib/extract-text-webpack-plugin#616]
My setup:
"devDependencies": {
    "ajv": "^5.2.2",
    "css-loader": "^0.28.5",
    "extract-text-webpack-plugin": "^3.0.0",
    "handlebars": "^4.0.10",
    "metalsmith": "^2.3.0",
    "metalsmith-express": "^0.1.0",
    "metalsmith-in-place": "^1.4.4",
    "metalsmith-layouts": "^1.8.1",
    "metalsmith-permalinks": "^0.5.0",
    "metalsmith-swig": "^1.2.1",
    "metalsmith-watch": "^1.0.3",
    "metalsmith-webpack": "^1.0.3",
    "node-sass": "^4.5.3",
    "sass-loader": "^6.0.6",
    "script-loader": "^0.7.0",
    "style-loader": "^0.18.2",
    "swig": "^1.4.2",
    "webpack": "^3.5.5"
  },

node versions: 8.4.0
npm: 5.3.0

TypeError: chunk.isInitial is not a function
at isInitialOrHasNoParents (/node_modules/extract-text-webpack-plugin/dist/lib/helpers.js:15:16)...

**Comment by evilebottnawi** [comment]
@jk171505 can you create minimum reproducible test repo, thanks!

**Comment by jk171505** [comment]
@evilebottnawi here it is: https://github.com/jk171505/metalsmith-webpack

**Comment by jk171505** [comment]
@evilebottnawi anything?

**Comment by kostasmanionis** [comment]
@jk171505 it's `metalsmith-webpack`, it uses an old webpack verision. see https://github.com/christophercliff/metalsmith-webpack/blob/master/package.json#L23

If you can't update that package you probably gonna have to use `1.0.1` of `extract-text-webpack-plugin`

**Comment by jk171505** [comment]
@kostasmanionis good point, updated webpack of metalsmith, then after installing missing sass-loader in the root I see the same bug...

**Comment by jk171505** [comment]
Maybe this puts some light on the problem:
everything worked fine, but I wasn't able to change the output path of the generated css. I decided to update memory-fs globally. From that moment on 'chunk.isInitial is not a function' bug came up...

**Comment by kostasmanionis** [comment]
Are you sure that `metalsmith-webpack` is using `3.*.*` when you get that error? Take a look at the `node_modules` and check the `package.json`.

Doesn't seem likely that a global `memory-fs` update would cause issues.

**Comment by jk171505** [comment]
@kostasmanionis you're right... I'm not sure what I did before, but the webpack of metalsmith wasn't updated. Now everything works fine, except I can't change the output of the css file.

**Comment by evilebottnawi** [comment]
@jk171505 can we close issue?

**Comment by jk171505** [comment]
yes, thanks
