### ISSUE TITLE
publicPath not being detected

### ISSUE THREAD

**Issue by talwoolf** [webpack-contrib/extract-text-webpack-plugin#62]
I am adding the publicPath to the plugin and it still extract the css into the main webpack publicPath configuration.

What is the exact setup I should have within my webpack config? I presume this might be the issue.

Thanks

**Comment by sokra** [comment]
`publicPath` doesn't change the location on disk. It only changes the URL on the server where resources are fetched from.

**Comment by deanshub** [comment]
Is there a way to separate the paths of the files on the disk?
I think it's a legitimate request to output the css files into one directory and the js files to another

**Comment by deanshub** [comment]
sorry, found the way,
just put the relative path in the file name like so:
```
new ExtractTextPlugin('../styles/[name].css',{allChunks:true})
```

**Comment by necolas** [comment]
> sorry, found the way,

close this then?

**Comment by joezimjs** [comment]
I'd still like a way to just specify a path where the file is without using ../styles/ because otherwise the AssetsPlugin generates this: 

```json
{
  "main": {
    "js": "/scripts/bundle.js",
    "css": "/scripts/../styles/styles.4e3230cbd3e79891f49e02389c16cb58.css"
  }
}
```

adding an additional `path` for the output of the CSS file would be helpful and more explicit

**Comment by bebraw** [comment]
@joezimjs Can you open a separate issue about that?
