### ISSUE TITLE
angular universal build:prod "extract-text-webpack-plugin" loader is used without the corresponding plugin

### ISSUE THREAD

**Issue by peterpeterparker** [webpack-contrib/extract-text-webpack-plugin#623]
Hi,

I've got a universal project. I have integrated `extract-text-webpack-plugin`.

When I debug doing `npm start` everything is fine.
When I try do build for production `npm run build:prod` I face the following error:

> ERROR in ./node_modules/extract-text-webpack-plugin/dist/loader.js?{"omit":1,"remove":true}!./node_modules/null-loader!./node_modules/css-loader?{"minimize":true,"sourceMap":true}!./node_modules/resolve-url-loader?{"sourceMap":true}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./src/app/app.component.scss
>         Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example

My `webpack.common.js` is the following:

    const {root} = require('./helpers');
    
    const webpack = require('webpack');
    
    const copyWebpackPlugin = require('copy-webpack-plugin');
    
    const ExtractTextPlugin = require('extract-text-webpack-plugin');
    
    /**
     * This is a common webpack config which is the base for all builds
     */
    module.exports = {
      devtool: 'source-map',
      resolve: {
            extensions: ['.ts', '.js']
      },
      output: {
        path: root('dist')
      },
      module: {
        rules: [
          {test: /\.ts$/, loader: '@ngtools/webpack'},
          {test: /\.html$/, loader: 'raw-loader'},
          {
            test: /\.css$/,
            use: ['to-string-loader'].concat(ExtractTextPlugin.extract({
              fallback: 'null-loader',
              //resolve-url-loader may be chained before sass-loader if necessary
              use: [
                {
                  loader: 'css-loader', options: {
                    minimize: true,
                    sourceMap: true
                  }
                }
              ]
            }))
          },
          {
            test: /\.scss$/,
            use: ['to-string-loader'].concat(ExtractTextPlugin.extract({
              fallback: 'null-loader',
              //resolve-url-loader may be chained before sass-loader if necessary
              use: [
                {
                  loader: 'css-loader', options: {
                    minimize: true,
                    sourceMap: true
                  }
                },
                {loader: 'resolve-url-loader', options: {sourceMap: true}},
                {loader: 'sass-loader', options: {sourceMap: true}}
              ]
            }))
          },
          {
            test: /\.woff2?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            // Limiting the size of the woff fonts breaks font-awesome ONLY for the extract text plugin
            // loader: "url?limit=10000"
            use: "url-loader"
          },
          {
            test: /\.(ttf|eot|svg)(\?[\s\S]+)?$/,
            use: 'file-loader'
          }
        ],
    loaders: [
      {
        test: /bootstrap-sass[\/\\]assets[\/\\]javascripts[\/\\]/,
        loader: 'imports-loader?jQuery=jquery,$=jquery,this=>window'
      },
          {test: /\.(woff2?|svg)$/, loader: 'url-loader?limit=10000'},
          {test: /\.(ttf|eot)$/, loader: 'file-loader'}
        ]
      },
      plugins: [
        new copyWebpackPlugin([
          {
            from: './src/assets/',
            to: './'
          }
        ], {
          ignore: [
            'fonts/**/*.*'
          ]
        }),
        new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /a^/),
        new ExtractTextPlugin('style.css')
      ],
      entry: ['bootstrap-loader', './app']
    };

Versions:

Node 8.4.0
Npm 5.3.0
webpack 3.3.0
extract-text-webpack-plugin 3.0.0
null-loader 0.1.1
sass-loader 6.0.6
css-loader 0.28.7
to-string-loader 1.1.5

**Comment by evilebottnawi** [comment]
@peterpeterparker why you use `to-string-loader` before `ExtractTextPlugin`. Can you move `to-string-loader` to `fallback` option?

**Comment by peterpeterparker** [comment]
@evilebottnawi do you mean like following?

    {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          fallback: 'to-string-loader',
          use: [
            {
              loader: 'css-loader', options: {
                minimize: true,
                sourceMap: true
              }
            }
          ]
        })
      },
      {
        test: /\.scss$/,
        use: ExtractTextPlugin.extract({
          fallback: 'to-string-loader',
          use: [
            {
              loader: 'css-loader', options: {
                minimize: true,
                sourceMap: true
              }
            },
            {loader: 'resolve-url-loader', options: {sourceMap: true}},
            {loader: 'sass-loader', options: {sourceMap: true}}
          ]
        })
      }

If so, when I debug `npm start` my project my pages aren't rendered, I face following server side error then

     TypeError: cssText.replace is not a function

**Comment by evilebottnawi** [comment]
@peterpeterparker `fallback: ['to-string-loader', `style-loader`]`

**Comment by peterpeterparker** [comment]
thx, same error respectively 

    TypeError: cssText.replace is not a function
    at extractStyleUrls (/Users/me/myproject/dist/server.js:52802:52)

**Comment by evilebottnawi** [comment]
@peterpeterparker please provide minimum reproducible test repo, thanks!

**Comment by peterpeterparker** [comment]
@evilebottnawi sure, here you go:

    git clone https://github.com/peterpeterparker/universal-extract
    cd universal-extract
    npm install
    npm run build:prod

**Comment by evilebottnawi** [comment]
@peterpeterparker Workaround https://github.com/webpack-contrib/style-loader/issues/123#issuecomment-230079894, also i recommend read this thread, thanks!

**Comment by peterpeterparker** [comment]
@evilebottnawi thx for pointing that out but I'm probably dumb and a webpack noob. When I do like described in the comment

    {
        test: /.css$/,
        exclude: root('src', 'app'),
        loaders:[ExtractTextPlugin.extract('style', 'css-loader'), 'to-string', 'css']
    }

I get the error

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0].module.rules[2].loaders should be one of these:
   non-empty string | function | object { loader?, options?, query? } | function | [non-empty string | function | object { loader?, options?, query? }]

**Comment by evilebottnawi** [comment]
@peterpeterparker adapt this solution for `webpack@3`, chagen `loader` to `use`

**Comment by peterpeterparker** [comment]
@evilebottnawi sorry I'm pretty dumb but do you mean then something like for `webpack3`?

    {
                test: /.css$/,
               exclude: root('src', 'app'),
                use: ExtractTextPlugin.extract({
                    use: ['style-loader', 'css-loader', 'to-string-loader']
                })
            },
            {
                test: /.scss$/,
                use: ExtractTextPlugin.extract({
                    use: ['style-loader', 'resolve-url-loader', 'sass-loader', 'to-string-loader']
                })
            }

If so, then same error respectively

    Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin

**Comment by evilebottnawi** [comment]
@peterpeterparker 
1. Use `\.css$` and `\.scss$` (escape `\`), because `foo-bar.non-css` match with `.css$` regex, it can to strike strange errors and unpredictable behavior.
2. Double check configuration, seems you don't have `ETWP` plugin in `plugin` field, maybe you override this in merge.

But it is not bug and not feature and don't related to `ETWP` plugin. For consultation questions use `stackoverflow` and other similar resources (also you can create issue in `to-string-loader` repo and create PR which add documentation section around you problem), thank you!

**Comment by peterpeterparker** [comment]
@evilebottnawi thx for the feedback. ok I gonna let the task open till I find the solution to document it (if I find one one day, already spent way to much time on this...). Again thx for the help, appreciated

**Comment by peterpeterparker** [comment]
just printed out to the console the loaded webpack config, look like the `plugin` field is merged correctly respectively that `ExtractTextPlugin` is loaded. I think there is an incompatibility with `AotPlugin` which is not use when I debug which could explain why it works when I debug and not when I build prod

    { devtool: 'source-map',
      resolve: { extensions: [ '.ts', '.js' ] },
      output: 
       { path: '/project/dist',
         filename: 'client.js' },
      module: 
       { rules: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
         loaders: [ [Object], [Object], [Object] ] },
      plugins: 
       [ { apply: [Function: apply] },
         { apply: [Function: apply] },
         ContextReplacementPlugin {
           resourceRegExp: /moment[\/\\]locale$/,
           newContentResource: undefined,
           newContentRecursive: undefined,
           newContentRegExp: /a^/ },
         ExtractTextPlugin { filename: 'style.css', id: 1, options: {} },
         HtmlWebpackPlugin { options: [Object] },
         ScriptExtHtmlWebpackPlugin { options: [Object] },
         AotPlugin {
           _lazyRoutes: {},
           _compiler: null,
           _compilation: null,
           _typeCheck: true,
           _skipCodeGeneration: false,
           _replaceExport: false,
           _diagnoseFiles: {},
           _firstRun: true,
           _options: [Object],
           _tsConfigPath:     '/project/src/tsconfig.browser.json',
           _rootFilePath: [Array],
           _compilerOptions: [Object],
           _angularCompilerOptions: [Object],
           _basePath: '/project/src',
           _genDir: '/project/src/$$_gendir',
           _compilerHost: [Object],
           _program: [Object],
           _entryModule: '/project/src/app/browser-app.module#BrowserAppModule' } ],
      entry: '/project/src/main.browser.ts',
      target: 'web',
      node: { fs: 'empty', net: 'empty' } }

Gonna try to find something in that direction...

**Comment by hesampour** [comment]
I have the same problem

**Comment by zhiyingzzhou** [comment]
please remove eslint comment in you source file!

**Comment by michael-ciniawsky** [comment]
@hesampour show your config (`webpack.config.js`) please

**Comment by hesampour** [comment]
thank michael-ciniawsky  the problem solved. but I dont know how I solved it!!!

**Comment by neeeekto** [comment]
@hesampour Perhaps describe what you did?

**Comment by hesampour** [comment]
realy this problem is for a long time a go. I know Upgrate all my project to angular 5 and use the new angular cli generate command for universal. many problems are fixed in this version.

**Comment by peterpeterparker** [comment]
same here, I switched to the Angular CLI for a while now  which made this issue useless to me. 

Since I created this issue, I gonna allow myself to close it. If you face this problem like I did, I would advice to migrate to the Angular CLI too.
