### ISSUE TITLE
We cannot find that module webpack/lib/chunk

### ISSUE THREAD

**Issue by vytch** [webpack-contrib/extract-text-webpack-plugin#628]
https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/8de6558e33487e7606e7cd7cb2adc2cccafef272/src/index.js#L3

Which version of webpack would have that module?

**Comment by evilebottnawi** [comment]
@vytch 
`master`: https://github.com/webpack/webpack/blob/master/lib/Chunk.js
`3.6.0`: https://github.com/webpack/webpack/blob/v3.6.0/lib/Chunk.js
`2.7.0`: `https://github.com/webpack/webpack/blob/v2.7.0/lib/Chunk.js`
Please remove `package.lock` (if exists), remove `node_modules` and try to run `npm cache clean` and again `npm i`, thank you!
