### ISSUE TITLE
Chain loaders?

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack-contrib/extract-text-webpack-plugin#63]
Something that I haven't understood yet from this plugin is, how I could use multiple loaders. I.e.:

``` javascript
    loaders: [
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract('style', 'css')
      }
    ]
```

Logically, this will run CSS files through the `css-loader` and then through the `style-loader` and capturing its output (i guess?). But how do I apply multiple of these? Say I want to use some less files also but put their output into the bundled CSS as well. How do I do this?

**Comment by bebraw** [comment]
I think you might be able to get away with

```javascript
loader: ExtractTextPlugin.extract('style', 'css', 'less)
```

Remember to have `less-loader` installed.

I haven't tried this so no guarantee it will works. Worth a go, though.

**Comment by sokra** [comment]
``` js
loader: ExtractTextPlugin.extract('style', 'css!less')
```

**Comment by antitoxic** [comment]
@sokra but that will execute the loaders once per each css file. What about the case when someone wants to execute a loader at the whole result of `ExtractTextPlugin` ? A.k.a. apply a loader to the merged file?

Like running postcss' `cssnano`?

**Comment by sokra** [comment]
That's not supported. But you can write a webpack plugin that does that.

**Comment by antitoxic** [comment]
I though something like this. Thank you, @sokra . It's still beyond me to write a plugin but may be I'll be able to at some point.

And thank you for developing webpack ecosystem. A frontend revolutionary piece of software.

**Comment by necolas** [comment]
@antitoxic close this then?

**Comment by antitoxic** [comment]
@necolas My question is answered. If everyone else is happy close it  with no worries.

**Comment by ivan-kleshnin** [comment]
For some weird reason it works for me:

```js
{test: /\.(less(\?.*)?)$/, loader: ExtractTextPlugin.extract("css!less")}
```

while it doesn't 

```js
{test: /\.(less(\?.*)?)$/, loader: ExtractTextPlugin.extract("css", "less")}
```

It fails to parse LESS syntax.
Shouldn't be the same thing?!

I prefer to use native datastructures over DSL so I used this
```js
{test: /\.(less(\?.*)?)$/, loaders: ["style", "css", "less"]},
```
before `ExtractTextPlugin` and everything were fine.

Also I don't understand whether `style` loader is required with `ExtractTextPlugin` or not.
Some examples show it **with** `style` included and some without.

**Comment by chiplay** [comment]
@ivan-kleshnin try `loader: ExtractTextPlugin.extract('style', 'css!less')` as @sokra mentioned above.  I'm not sure why exactly the plugin method signature for `extract` is writen like that, but I agree that its a bit confusing and it took me reading the source code for the plugin and finding this issue before I got it.

**Comment by kadishmal** [comment]
This works for me `ExtractTextPlugin.extract('css-loader!stylus-loader')`.
