### ISSUE TITLE
css files are not generated separately with extract-text-webpack-plugin using webpack 3

### ISSUE THREAD

**Issue by nishanthnareddy** [webpack-contrib/extract-text-webpack-plugin#631]
I was trying to create a separate bundle for css based on the chunks name using extract-text-webpack-plugin with webpack@3.6.0.

I have spent more time and googled on identifying on the issue, but i could not find it. i have tried more options for this.

i will share my webpack.config.js file here,

I have added a web pack config in bitbucket server. please find it from below URL https://bitbucket.org/nishanth7475/webpackconfigalone/src/dca35d8c0eb31debfcefa2f7f282f987604b6d97?at=master

<img width="1103" alt="screen shot 2017-09-25 at 10 25 43 am" src="https://user-images.githubusercontent.com/29639782/30877726-91253c68-a2c8-11e7-898d-bcc1976ee000.png">

**Comment by idibidiart** [comment]
Webpack is a beast, with exponetial complexity by design.

I've been looking at Splittable by the guy behind the Google AMP project. It looks infinitely simpler and does all the basic things as webpack. I repeat: infinitely simpler. 

Webpack is a beast.

**Comment by kennycrosby** [comment]
Having the same issue

**Comment by genintho** [comment]
Same issue.

**Comment by michael-ciniawsky** [comment]
@genintho Does it work without the `cache-loader` ?

```diff
-       new ExtractTextPlugin("[name].[contenthash].css", {
+       new ExtractTextPlugin({
+           filename: "[name].[contenthash].css",
            allChunks: true,
        })
```

**Comment by genintho** [comment]
@michael-ciniawsky  everything works with your suggestion.

I think I got confused by the documentation. Having only one way to define the filename would might help avoiding errors.

**Comment by nishanthnareddy** [comment]
@michael-ciniawsky hey if you look at my webpack.config.js i don't have cache-loader but still having the same issue.

**Comment by AustinMatherne** [comment]
Same. I am also not using the cache-loader.

**Comment by christianztamayo** [comment]
+1

**Comment by rafaell-lycan** [comment]
Same.

**Comment by Pavel-Durov** [comment]
I was able to solve this issue with wepbpack 3.8.1, using different instances of a **extract-text-webpack-plugin** plugin for each css bundle.

for example: 
```

var ExtractTextPlugin = require('extract-text-webpack-plugin');
var blueETP = new ExtractTextPlugin();
var baseETP = new ExtractTextPlugin();
  module: {
    rules: [{
        test: /base.scss$/,
        use: baseETP.extract({
          fallback: 'style-loader',
          use: ['css-loader', 'sass-loader']
        })
      },{
        test: /blue.scss$/,
        use: blueETP.extract({
          fallback: 'style-loader',
          use: ['css-loader', 'sass-loader']
        })
      }],
  plugins: [blueETP,baseETP]
  ....
```

**Comment by michael-ciniawsky** [comment]
See @Pavel-Durov https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/631#issuecomment-347840202 @Pavel-Durov thx 👍
