### ISSUE TITLE
Why does extract-text-webpack-plugin adds extra dependency?

### ISSUE THREAD

**Issue by x-yuri** [webpack-contrib/extract-text-webpack-plugin#632]
I'm talking about [this][1] line. Not a major issue probably, but as a result, `fileDependencies` contains duplicates. `webpack` adds it [itself][2] before running normal loaders.

[1]: https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/v3.0.0/src/loader.js#L16
[2]: https://github.com/webpack/loader-runner/blob/v2.3.0/lib/LoaderRunner.js#L198

How to reproduce:

`package.json`:

```json
{
  "dependencies": {
    "css-loader": "^0.28.7",
    "extract-text-webpack-plugin": "^3.0.0",
    "webpack": "^3.6.0"
  }
}
```

`wepback.config.js`:

```js
const ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
    entry: './entry.js',
    output: {
        filename: 'bundle.js',
    },
    module: {
        rules: [{
            test: /\.css$/,
            loader: ExtractTextPlugin.extract('css-loader'),
        }],
    },
    plugins: [
        new ExtractTextPlugin('bundle.css'),
        {apply: function(compiler) {
            compiler.plugin('compilation', function(compilation) {
                compilation.plugin('seal', function() {
                    var m = this.modules.filter(function(m) {
                        return /\/style\.css$/.test(m.resource);
                    })[0];
                    console.log('compilation: ' + compilation.name);
                    console.log('fileDependencies:');
                    console.log(m.fileDependencies);
                });
            });
        }},
    ],
};
```

`entry.js`:

```js
require('./style.css');
```

`style.css`:

```css
body {
    margin: 0;
}
```

```
$ ./node_modules/.bin/webpack 
compilation: undefined
fileDependencies:
[ '/srv/http/s1/2/style.css', '/srv/http/s1/2/style.css' ]
compilation: extract-text-webpack-plugin /srv/http/s1/2/node_modules/extract-text-webpack-plugin/dist /srv/http/s1/2/node_modules/css-loader/index.js!/srv/http/s1/2/style.css
fileDependencies:
[ '/srv/http/s1/2/style.css' ]
Hash: e10d340fe2b3fadee7ca
Version: webpack 3.6.0
Time: 292ms
     Asset      Size  Chunks             Chunk Names
 bundle.js   2.62 kB       0  [emitted]  main
bundle.css  24 bytes       0  [emitted]  main
   [0] ./entry.js 24 bytes {0} [built]
   [1] ./style.css 41 bytes {0} [built]
    + 1 hidden module
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!style.css:
       [0] ./node_modules/css-loader!./style.css 189 bytes {0} [built]
        + 1 hidden module
```

[Archive](https://github.com/webpack-contrib/extract-text-webpack-plugin/files/1333126/extract-duplicate-dep.zip) with the files.

**Comment by evilebottnawi** [comment]
@x-yuri thank for issue, PR welcome

**Comment by michael-ciniawsky** [comment]
Could you try with additional `require()` please (e.g `require('./style2.css'), require('style3.css') ...`)

Does this only happen for the *first*  style import or foreach ?

**Comment by evilebottnawi** [comment]
@michael-ciniawsky no, it is `pitch` loader they don't add dependecy, we should do this manually, all works as expected. Thanks for issue!

**Comment by x-yuri** [comment]
@evilebottnawi Can you elaborate please? Pitch loaders don't add dependencies themselves, but if they don't return anything, the dependency is added by [`loader-runner`][1]. So the only case where this might be useful is [`this[NS] === false`][2]. (By the way, the debugger doesn't stop there for my testing app.) But then the line should be moved into this branch. Am I missing something?

[1]: https://github.com/webpack/loader-runner/blob/v2.3.0/lib/LoaderRunner.js#L198
[2]: https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/v3.0.2/src/loader.js#L25
