### ISSUE TITLE
Generate one (or more) resulting files merging the original results

### ISSUE THREAD

**Issue by danikaze** [webpack-contrib/extract-text-webpack-plugin#634]
Proposal for a feature to solve the frequently asked question about _how to generate only one file with extract-text-webpack-plugin_.
Usually solved by external plugins (i.e. `merge-files-webpack-plugin`) in a completely different step, this doesn't look to be working with v3. Also, it would be nice to have a _native_ solution.

My proposal is to have an extra `merge` option to work like this, generalising the stated point:

```js
// Generate one styles.css from all the *.styles.css
// and one themes.css from all the *.themes.css files
new ExtractTextPlugin({
  merge: [{
    filename: 'styles.css',       // name of the merged output file
    test: /\.style\.css$/,        // files to include (*.styles.css)
    preventOriginalOutput: true,  // when true (by default), original files won't be generated
  }, {
    filename: 'themes.css',
    test: /\.theme\.css$/,
    preventOriginalOutput: true,
  }],
});
```

So let's say we have this files as original output from this plugin:
- `a.style.css`
- `b.style.css`
- `c.style.css`
- `a.theme.css`
- `b.theme.css`
- `fooBar.css`

The resulting files after the execution should be this:
- `styles.css` merging `a.style.css` + `b.style.css` + `c.style.css`
- `themes.css` merging `a.theme.css` + `b.theme.css`
- `fooBar.css` which doesn't merge into any other file

If we set `preventOriginalOutput` option to `false`, then the resulting file will output also the original files:
- `styles.css` merged from `a.style.css` + `b.style.css` + `c.style.css`
- `themes.css` merged from `a.theme.css` + `b.theme.css`
- `a.style.css`
- `b.style.css`
- `c.style.css`
- `a.theme.css`
- `b.theme.css`
- `fooBar.css`

**Comment by d3viant0ne** [comment]
See comment in https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/636#issuecomment-333866537
