### ISSUE TITLE
Building separate Stylesheets for different themes with webpack

### ISSUE THREAD

**Issue by manulitopetito** [webpack-contrib/extract-text-webpack-plugin#639]
Right now we are using a scss mixin ( https://github.com/zellwk/themify ) to provide different themes for our react components in our app.

It works great, but produces rather long selector chains in the compiled css file.

While we do have to provide the ability to change themes during runtime ( which is no hassle with the current solution, we only have to switch one classname on the body element ) the default usecase is, that the theme does not change. 

So we thought about reducing the complexity and filesize of our stylesheets by splitting them up in separate files. 

Example: 

**themes.scss:**

    $themes: (
      red: (
        mainColor: #aa3939,
        secondaryColor: #D46A6A
      ),
      blue: (
        mainColor: #2e4272,
        secondaryColor: #4f628e
      )
    );

**button.sccs**

    @import 'themes.scss';
    
    .button {
      @include themify($themes) {
        color: themed('secondaryColor');  
        background-color: themed('mainColor');  
      }}
    }

This becomes:

    .theme-red .button {
      color: #D46A6A;
      background-color: #aa3939;
    }
    
    .theme-blue .button {
      color: #4f628e;
      background-color: #2e4272;
    }

Now I want this to become:

**theme-red.css:**

    .button {
      color: #D46A6A;
      background-color: #aa3939;
    }

**theme-blue.css:**

    .button {
      color: #4f628e;
      background-color: #2e4272;
    }

We are not depenent on the themify mixin, we could change that to any kind of solution one could make work with webpack. Any hint in the right direction would be appreciated! :)

**Comment by michael-ciniawsky** [comment]
CSS Custom Properties (CSS Variables) && postcss-custom-properties
