### ISSUE TITLE
Extracting styles with different configurations leads to error

### ISSUE THREAD

**Issue by ManuSevenval** [webpack-contrib/extract-text-webpack-plugin#640]
I am trying to extract my styles multiple times, each time with a different color configuration.
If I load the styles only once (one item in `themes` array) everything is fine.
If I add my other theme names, I get the following error:

ERROR in ./~/css-loader?{"localIdentName":"[hash:base64:5]","modules":true,"importLoaders":1}!./~/postcss-loader?{}!./~/sass-loader/lib/loader.js?{"data":"@import /"/Users/xxx/_theme-dark.scss/";"}!./~/extract-text-webpack-plugin/loader.js?{"id":3,"omit":1,"remove":true}!./~/style-loader!./~/css-loader?{"localIdentName":"[hash:base64:5]","modules":true,"importLoaders":1}!./~/postcss-loader?{}!./~/sass-loader/lib/loader.js?{"data":"@import /"/Users/xxx/_theme-dark.scss/";"}!./common/components/Button/Button.scss
Module build failed:
@import "../../css/common";
                                                                                                          ^
      Invalid CSS after "...load the styles": expected 1 selector or at-rule, was "var content = requi"
      in /Users/xxx/common/components/Button/Button.scss (line 1, column 108)

my `webpack.dev.js`:

```
module.exports = env => {
  const config = require('./webpack.common')(env);
  const project = env.project;

  const postcss = {
    loader: 'postcss-loader',
    options: postcssConfig(settings.browsers),
  };

  config.watch = true;
  config.devtool = 'eval';

  const themes = ['theme-base', 'theme-dark'];

  themes.forEach(themeKey => {
    const themeInstance = new ExtractTextPlugin('css/' + themeKey + '.css');
    const themePath = path.resolve(__dirname, '../../react/app/css/_' + themeKey + '.scss');

    config.module.rules.push({
      test: /\.s?css$/,
      exclude: /node_modules/,
      use: themeInstance.extract({
        fallback: 'style-loader',
        use: [
          {
            loader: 'css-loader',
            options: {
              localIdentName: '[hash:base64:5]',
              modules: true,
              importLoaders: 1,
            }
          },
          postcss,
          {
            loader: 'sass-loader',
            options: {
              data: `@import "${themePath}";`,
            }
          }
        ]
      }),
    });

    config.plugins.push(themeInstance);
  });
}
```

How can I execute the same test rule with different configurations?

**Comment by michael-ciniawsky** [comment]
This is not really supported and error prone consider using something like e.g CSS Custom Props instead

**Comment by evilebottnawi** [comment]
@ManuSevenval Yes right now it is not support.
@michael-ciniawsky What about add `test/include/exclude` option to allow this?

**Comment by michael-ciniawsky** [comment]
A combination of multiple  ETWP instances combined with `include/exclude` may more or less 'work', but as already mentioned in https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/640#issuecomment-334975017 theming is error prone and difficult with webpack and ETWP so YMMV
