### ISSUE TITLE
Extract array of assets preserving the order

### ISSUE THREAD

**Issue by devmarco** [webpack-contrib/extract-text-webpack-plugin#649]
I have a use case where we are bundling a set of modules for each theme, so each theme is independent and has it's own javascript and CSS files.

```
entry: {
    theme1: [js, js, js, css, css, css],
    theme2: [js, js, css, css]
}
```

The issue I am having is regarding the order of the css files, because one of them is the one that has the variables and definitions variables.

Do you guys know how I can solve that?

**Comment by michael-ciniawsky** [comment]
Theming in the 'traditional' way is a snake pit with EWTP for the reason, that the order is determined by JS Import/export semantics rather then logical CSS  file structure. Unfortunately you won't really be able to solve theming in a clean way. I answered similar questions/feature requests a few times now and the only solution is to use either `postcss-custom-properties` (fallback) or CSS Variables (CSS Custom Properties) directly (modern browsers) and set the vars via JS dynamically (logical branches/theme switcher). The webpack CSS workflow will change in the intermediate [future](https://medium.com/webpack/the-new-css-workflow-step-1-79583bd107d7).to avoid caveats like that. In case you aren't using CSS Modules, maybe building CSS with a separate task (e.g gulp) is something to consider in your case

**Comment by devmarco** [comment]
@michael-ciniawsky Thank you for the quick answer.

A solution I was thinking is to create a custom loader. But I couldn't find a way to access the current entry name in the loader function. Do you know if it is possible? With that, I would be able to fix my issue.

**Comment by michael-ciniawsky** [comment]
**style.(s)css**
```css
@import 'vars/theme*.(s)css';

...
```

**entry\*.js**
```js
import css from './style.css'

...
```

**webpack.config.js**
```js
{
   entry1: './entry1'
   entry2: './entry2'
}
...
new ExtractTextPlugin({
   filename: '[name].css'
})
```

```
output
| – entry1.bundle.js
| – entry1.bundle.css
| – entry2.bundle.js
| – entry2.bundle.css
```

This should basically work to some point, but be aware of async chunks (`import()/require.ensure()`) and split points (`CommonChunksPlugin`) ;)

The main reason to use ETWP is mainly CSS Modules (needs CSS at build time), otherwise at a certain complexity getting ETWP to work correctly will be a real hassle.

> A solution I was thinking is to create a custom loader

The main issue is the difference in semantics between CSS (`@import`) && JS (`import/import()/require()`), CSS isn't simply JS and doesn't 'behave' like it, so writing a new loader for it will be difficult atm with the way webpack works.

> But I couldn't find a way to access the current entry name in the loader function. Do you know if it is possible?

[Loader API](https://webpack.js.org/api/loaders)

`this.options` (Webpack Config, (deprecated)) <= best bet e.g via `this.options.entry`
`this._compiler` (Webpack Compiler Instance (hacky, deprecated))
`this._compilation` (Webpack Compilation (AST) (hacky, deprecated))

**Comment by devmarco** [comment]
@michael-ciniawsky Thank you

Let me ask you one more question.

Is it possible to create a plugin or something else to add entry modules dynamically?

In the project I am working, each react component has its own CSS file. But those files are not being imported in the JS file and I don't want to do this.

My idea is, as the plugins can access the current entry path being compiling. I was thinking in get the css file path based on the component path and add to the entry. Something like

```
(currentEntryPath) => {
   const cssPath = currentEntryPath + `-css`
   addToEntry(cssPath)
}
```

Thanks in advance

**Comment by michael-ciniawsky** [comment]
[Plugins](https://webpack.js.org/contribute/writing-a-plugin/)
[Plugin Patterns](https://webpack.js.org/contribute/plugin-patterns/)

[Compiler Hooks](https://webpack.js.org/api/compiler/#event-hooks)
[Compilation Hooks](https://webpack.js.org/api/compilation/)

[Resolver](https://webpack.js.org/api/resolver/)

**Comment by devmarco** [comment]
@michael-ciniawsky 

Sorry about being asking you many questions here, but I'm stuck just with the information in the docs. Let me try to explain you my real problem, and when you have time I would appreciate the help.

I am working with Themes

My webpack entry point is something like

```
{
   'theme-one/home-page': [ all js dependencies ]
   'theme-two/home-page': [ all js dependencies ]
}
```

The css for each js file is not being imported on the JS itself, so I want to create a plugin to check the current dependency, and add to the entry point the respective css file

Let's say this is the current module being processed `/project/header.js`

On the plugin I want to get this path, create a css path based on this, like
`/project/header.scss` and add to the correct theme entry point.

What I cound't find a way on the documentation is

- Get the current chunk name (Like: `theme-one/home-page`)
- Add the new css path to the array of modules of the current chunk name

Thank you in advance

**Comment by d3viant0ne** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support though you may also inquire in [Webpack Gitter](https://gitter.im/webpack/webpack). The issue tracker is for bug reports and feature discussions. See also our CONTRIBUTING guidelines.
