### ISSUE TITLE
The output is not deterministic

### ISSUE THREAD

**Issue by akihikodaki** [webpack-contrib/extract-text-webpack-plugin#654]
The output is not deterministic because the module is built asynchronously. The behavior is undesired for some use, and should be fixed or documented.

We have acutally encountered a situation the behavior is problematic when setting up distributed servers for an application. Each server serves CSSes extracted by extract-text-webpack-plugin. The servers are load-balanced with a reverse proxy, and the served file will be available for clients with the same path. We configured to run webpack (and extract-text-webpack-plugin) with same input to pack files to serve on _each server_, expecting they serves same files. However, the expectation was actually wrong.

To solve the issue, extract-text-webpack-plugin can be modified to have deterministic output. However, I think documentation is enough since the problem can be avoided by distributing an output throughout systems when they should have the same file.

**Comment by mrvicadai** [comment]
Ran into the same issue -- the CSS content are randomly re-ordered, therefore repeated builds seldom produce consistent artifacts.

**Comment by evilebottnawi** [comment]
@akihikodaki @mrvicadai can you create minimum reproducible test repo? Seems it is bug.

**Comment by akihikodaki** [comment]
https://github.com/pixiv/mastodon/tree/pawoo-music is an example in the real world. I'm writing a minimal test case now, and will make a pull request when I finished it.

**Comment by akihikodaki** [comment]
It was already fixed with commit 7ae32d9c560ef0a7dd584e3bf5991bacd5753093 for my case. It's my shame that I missed the change.
I'll close this issue. @mrvicadai may have a problem different from mine. I would recommend to open another issue in the case.
