### ISSUE TITLE
where to add `extract-text-webpack-plugin?sourceMap`

### ISSUE THREAD

**Issue by m31271n** [webpack-contrib/extract-text-webpack-plugin#658]
First, sorry for this stupid question.

<img width="954" alt="screen shot 2017-11-01 at 6 19 24 pm" src="https://user-images.githubusercontent.com/12194646/32270545-4636c3f4-bf31-11e7-850c-6c405b2fe02a.png">

`extract-text-webpack-plugin?sourceMap` is mentioned in `README.md`, but where should I add it?

If an example is provided, I'd sure be grateful.

**Comment by michael-ciniawsky** [comment]
```js
{
   test: /\.css$/,
   use: ExtractTextPlugin.extract({
     fallback: "style-loader",
     use: [
       { 
         loader: "css-loader", 
         options: { sourceMap: true }  // <=
       } 
     ]
  })
}
```

and don't forget to set `sourceMap` on all following loaders aswell e.g `postcss-loader, sass-loader`, they need to be updated for loader to loader to be correct
