### ISSUE TITLE
Source maps are incorrect when using extract-text, sass-loader, and eval-source-map

### ISSUE THREAD

**Issue by jasononeil** [webpack-contrib/extract-text-webpack-plugin#663]
When you use these 3 things together the generated source maps point to the incorrect positions (both filenames and line numbers are wrong):

* 'eval-source-map' (or any of the devtool options that use an 'eval')
* extractTextPlugin enabled (if you disable it, source maps are correct)
* sass-loader (if you remove this loader, source maps are correct)

## Expected vs Actual
Screenshot of correct source maps:

**Screenshot of INCORRECT source maps**:
![](https://user-images.githubusercontent.com/315158/32710760-e680c858-c88e-11e7-9e3c-ec730b3b7e9d.png)

**Screenshot of CORRECT source maps**:

![](https://user-images.githubusercontent.com/315158/32710761-e6e377a0-c88e-11e7-8485-c7fb381af8d6.png)

## Reproducable example:
I've created a reproducible test case starting from a freshly ejected create-react-app setup. 

* View changes necessary to reproduce: https://github.com/jasononeil/webpack-tests/pull/1
* Browse the branch: https://github.com/jasononeil/webpack-tests/tree/test/source-maps-same-line-problem
* Clone it: `git clone -b test/source-maps-same-line-problem git@github.com:jasononeil/webpack-tests.git`

## Versions:
* Node 8.7.0
* webpack@3.8.1
* sass-loader@6.0.6
* extract-text-webpack-plugin@3.0.2

## Extra info
I tried a variety of `devTool:` options.

* Worked correctly: `source-map`, `inline-cheap-module-source-map`, `cheap-module-source-map`
* Showed original sources, but wrong filenames and line numbers: `eval-source-map`, `cheap-eval-source-map`, `cheap-module-eval-source-map`
* Only showed compiled sources: `inline-cheap-source-map`, `cheap-source-map`

**Comment by evilebottnawi** [comment]
@jasononeil Thanks for issue. `sass-loader` use `node-sass` for compile `scss/sass`. `node-sass` have some issues with source maps and we don't something here :disappointed: In next major we add support for `dart-sass`, maybe it is solve problem. 
I agree what in some case you can get broken source map. Source maps is big problem in `webpack` and `ecosystem` :disappointed: Feel free to PR.

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
