### ISSUE TITLE
Css output for entry may not exist if it has only common chuck when using extract-text & commons-chunk together

### ISSUE THREAD

**Issue by sunel** [webpack-contrib/extract-text-webpack-plugin#665]
``` webpack.config.js```

```javascript
entry: {
   page1: './js/page1.js',
   page2: './js/page2.js'
},
plugins: [
    new UglifyJSPlugin(),
    new webpack.optimize.CommonsChunkPlugin({
        name: 'vendor'
    }),
    new ExtractTextPlugin({
      filename:"[name].css",
      allChunks: true
    })
]
```

``` page1.js```

```javascript
require('themePath/scss/theme.scss')
require('themePath/css/style.css')
require('themePath/js/jquery.js')
require('themePath/js/popper.js')
require('themePath/js/bootstrap.js')
require('themePath/js/dashboard.js')
```

``` page2.js```

```javascript
require('themePath/scss/theme.scss')
require('themePath/css/style.css')
require('themePath/css/page2.css')
require('themePath/js/jquery.js')
require('themePath/js/popper.js')
require('themePath/js/bootstrap.js')
require('themePath/js/dashboard.js')
```

Output

```bash

./dist/page1.js

./dist/page2.css
./dist/page2.js

./dist/vendor.css
./dist/vendor.js
```

If you see there is no ```page1.css``` as it doesnt have its own css, everything is moved into vendor.

Can we or Do we have option to create a enrty point css || js if its empty  or is there a event or callback before a file is created.

**Comment by michael-ciniawsky** [comment]
If there is no separate CSS  for `page1` what should `page1.css` contain then ? Maybe requiring an empty `page1.css` file works

**Comment by michael-ciniawsky** [comment]
**page1.js**
```diff
require('themePath/scss/theme.scss')
require('themePath/css/style.css')
+ require('themePath/css/page1.css') // empty
require('themePath/js/jquery.js')
require('themePath/js/popper.js')
require('themePath/js/bootstrap.js')
require('themePath/js/dashboard.js')
```

**Comment by sunel** [comment]
@michael-ciniawsky 

The issue is when including the out file in the html. We cannot check and include the file if exist, as it will increase the load in the server (consider we have 200 entry points)

Is there a way we can force create the css file

**Comment by michael-ciniawsky** [comment]
@sunel I still don't understand why you want to create this file, what is the use case ? Doesn't my suggestion work ?

**Comment by sunel** [comment]
@michael-ciniawsky 

I will explain the use case. 

Consider a **dynamic website** which has multiple entry point. 
Each entry point will have multiple js and css and scss file which will added based on the component added to the page.
Webpack with extract and common plugin works perfect and  its easy to optimize the page.


``` webpack.config.js```

```javascript
entry: {
   page1: './js/page1.js',
   page2: './js/page2.js'
},
plugins: [
    new UglifyJSPlugin(),
    new webpack.optimize.CommonsChunkPlugin({
        name: 'vendor'
    }),
    new ExtractTextPlugin({
      filename:"[name].css",
      allChunks: true
    })
]
```

``` page1.js```

```javascript
require('themePath/scss/theme.scss')
require('themePath/css/style.css')
require('themePath/js/jquery.js')
require('themePath/js/popper.js')
require('themePath/js/bootstrap.js')
require('themePath/js/dashboard.js')
```

``` page2.js```

```javascript
require('themePath/scss/theme.scss')
require('themePath/css/style.css')
+ require('themePath/css/component.css')
require('themePath/js/jquery.js')
require('themePath/js/popper.js')
require('themePath/js/bootstrap.js')
require('themePath/js/dashboard.js')
```

After running through webpack we will get two files for each (js and css)

As Expected Case 

```page1.js```  ```vendor.js```  ```page1.css```  ```vendor.css```

so we can add to output html as suggested here [#explicit-vendor-chunk](https://webpack.js.org/plugins/commons-chunk-plugin/#explicit-vendor-chunk)

```
<script src="vendor.js" charset="utf-8"></script>
<script src="page1.js" charset="utf-8"></script>

<link href="vendor.css" >
<link href="page1.css"  >
```
same goes for page2


But ```page1`` entry point dosn't have any extra css there will not css genrated for it, as all the css in it goes to vendor.css

In this case 

```
<link href="vendor.css" >
<link href="page1.css"  >
```

This will through 404 for ```page1.css``` . To avoid this we need to add a check if the file exist in the Html page which will not work for application with too many entry points.

**Comment by sunel** [comment]
@michael-ciniawsky 

> I still don't understand why you want to create this file, what is the use case ? Doesn't my suggestion work ?

We will not know until webpack run that ```page1.css``` is not generated, So we cannot add a empty file as you suggested. 

If we can have the listed of files that are generated for entry point through a plugin event or even a callback function.

Or before bail out trigger a event, so that the developer can act according to it.

I know that this not the scope of the plugin but this could a valid use-case for larger application which has dynamic js and css that are included through components.

**Comment by michael-ciniawsky** [comment]
`html-webpack-plugin` ?

**Comment by sunel** [comment]
@michael-ciniawsky 

Thanks,
Got few ideas from the ```html-webpack-plugin``` plugin
