### ISSUE TITLE
schema-utils validation errors not thrown properly

### ISSUE THREAD

**Issue by dinkzilla** [webpack-contrib/extract-text-webpack-plugin#667]
When validation in schema-util fails, schema-utils throws an error with fairly verbose messaging, but it is not being properly caught and rethrown within extract-text-webpack-plugin. As a result, you get unhelpful error messages in the console that look like this:

```
<project-path>\node_modules\schema-utils\dist\validateOptions.js:40
    throw new _ValidationError2.default(ajv.errors, name);
    ^

false
```

**Comment by dinkzilla** [comment]
I created a pull request fixing the issue...

https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/668

**Comment by michael-ciniawsky** [comment]
Could you install the latest `schema-utils` manually and see if it works ? I fixed it in `schema-utils` directly with a nearly similar approach a few days ago

**Comment by michael-ciniawsky** [comment]
Could you show a screenshot of the Error you get when using your patch instead please ? Adding the stack back to the `{Error}` was requested already :), I suppressed it in `schema-utils` tbh considering it noise when the Plugin Name etc is provided but in more complex setups it's unfortunately needed

**Comment by dinkzilla** [comment]
It looks like this...

```
<poject-path>\node_modules\extract-text-webpack-plugin\index.js:131
                        throw new Error(e.message);
         ^
Error: Validation Error

Extract Text Plugin Invalid Options

options['sourceMap'] should NOT have additional properties

    at new ExtractTextPlugin (<project-path>\node_modules\extract-text-webpack-plugin\index.js:131:10)
    at Object.css (C:\Code\dearborn-station\DynamicPricing\node_modules\@easy-webpack\config-css\src\index.ts:33:25)
    at generateConfig (<project-path>\node_modules\@easy-webpack\core\src\index.ts:71:40)
<...full stack trace continues...>
```

I agree, it's potentially a lot of noise. Originally I wasn't including it either and was just doing a console.warn(e.message), but that didn't actually help me solve my particular issues. It's mainly an issue for people using easy-webpack I imagine, as we are in this project.

**Comment by michael-ciniawsky** [comment]
We can limit it, the main issue is 

```
<project-path>\node_modules\extract-text-webpack-plugin\index.js:131
                        throw new Error(e.message);
```

being displayed. There is ongoing discussion in webpack/webpack about handling this better atm, so it's likely `schema-utils` needs a patch in the next days and I will also add the (limited) `stack` back then. Could you nevertheless do the dependency upgrade in #668 meanwhile and revert the `try/catch` handling ?

**Comment by dinkzilla** [comment]
Sounds good. Can do.

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
