### ISSUE TITLE
Webpack 2 upgrade - Extracting from sass files into seperte css files not working

### ISSUE THREAD

**Issue by Pavel-Durov** [webpack-contrib/extract-text-webpack-plugin#669]
Hi, I read the documentation and explored the issues - hope this one isn't a duplicate.
Basically, my issue is with upgrading from webpack 1 to the latest version.

I was using **extract-text-webpack-plugin** plugin with webpack 2 and it worked perfectly. 

It constructed my css files (**baseStyle.css**/**globalThemeBlue.css**) from baseStyle.sass and globalThemeBlue.sass.

**Webpack 1 config**
```
var ExtractBaseCSSTextPlugin = new ExtractTextPlugin('css/baseStyle.css');
var ExtractBlueCSSTextPlugin = new ExtractTextPlugin('css/globalThemeBlue.css');
....
 module: {
    loaders: [
      ....
      {
        test: /baseStyle.scss$/,
        loader: ExtractBaseCSSTextPlugin.extract('css?url=false!sass')
      },
      {
        test: /globalThemeBlue.scss$/,
        loader: ExtractBlueCSSTextPlugin.extract('css?url=false!sass')
      }
],
 plugins: [
    ExtractBaseCSSTextPlugin,
    ExtractBlueCSSTextPlugin
]};
```

After upgrading webpack (version 3.8.1) and used the new convention from README.md (Usage section) I'm getting the css files as two separate files - **baseStyle.css** and **globalThemeBlue.css** but each one with a merged content of both sass files **baseStyle.sass and globalThemeBlue.sass**.

**Webpack 2 config: **
```

var ExtractTextPlugin = require('extract-text-webpack-plugin');

  module: {
    rules: [{
      {
        test: /baseStyle.scss$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: ['css-loader', 'sass-loader']
        })
      },
      {
        test: /globalThemeBlue.scss$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: ['css-loader', 'sass-loader']
        })
      }],
  plugins: [
    new ExtractTextPlugin('css/baseStyle.css'),
    new ExtractTextPlugin('css/globalThemeBlue.css')]
```
Is there a possible configuration for extracting seperate css files from seperate sass file sources?

Thanks in advance :)

**Comment by Pavel-Durov** [comment]
Duplicate of https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/631

**Comment by evilebottnawi** [comment]
@Pavel-Durov I'm closing the problem here, duplicate, thank you for issue!
