### ISSUE TITLE
Removes needed css

### ISSUE THREAD

**Issue by mihailo-misic** [webpack-contrib/extract-text-webpack-plugin#670]
## Environment:

|    Item    |    Version    |
|---------|-------------|
|    OS    |    **Mac 10.13.1**    |
|    Node    |    **8.9.1**    |
|    npm    |    **5.5.1**    |
|    webpack    |    **3.8.1**    |
|    extract-text-webpack-plugin    |    **3.0.2**    |

<br>

## The issue:

I'm having is that the plugin is removing some of the css that I need.
These particular classes are added to the elements by JS (on input's blur/input).

One of the classes:
```scss
.form-group {
...
  .has-value,
  .has-value:focus {    
    color: $mf-input-color;
    font-weight: 400;
  }
}
```

The way it's added by JS: 
```js
inputs.on('input', (ev) => {
  const el = ev.target;
  const val = el.value;

  // Check for value
  if (val !== '') {
    $(el).addClass('has-value')
  } else {
    $(el).removeClass('has-value')
  }
});
```

<br>

> webpack.config.js _(with data not concerning the plugin removed)_
```js
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  module: {
    rules: [
      // SCSS
      {
        test: /\.scss$/,
        exclude: /node_modules/,
        use: ExtractTextPlugin.extract({
          publicPath: './',
          fallback: 'style-loader',
          use: [
            'css-loader',
            'postcss-loader',
            'sass-loader',
        ]}),
      },
    ]
  }
  plugins: [
    new ExtractTextPlugin({
      filename: 'css/main.bundle.css',
      disable: false, // When turned to true everything works as intended.
      allChunks: true,
    }),
  ]
}
```

Is there any way to tell the Plugin that i need those styles?

**Comment by michael-ciniawsky** [comment]
What do you exactly mean by remove ? Removing from the JS into a separate CSS file or completely ? In case it's the first issue you will need to add a second `module.rule` without using EWTP and `exclude` the inline CSS from the rule using EWTP. For the second case I need more info about your setup

**Comment by mihailo-misic** [comment]
It completely removed that part of the css while "parsing" it from the `scss` file. I guess it regarded it as **"unnecessary"** since it's not directly mentioned in the html, those classes are added to the inputs via **JS** using the code snippet I've provided.

The expected behaviour was:
- From the mentioned `scss` file extracted the required code/styling.
- Parse the extracted (used) style into css
- Put the extracted and parsed css into `css/main.bundle.css` in the `dist` folder

> All of the steps are ok except that the plugin makes a mistake in thinking i don't use certain styles _(mentioned in the snippet)_ and does not put them in the `main.bundel.css`.

What info about my setup would you like to know?
By EWTP do you mean ETWP?

**Comment by michael-ciniawsky** [comment]
> It completely removed that part of the css while "parsing" it from the scss file. I guess it regarded it as "unnecessary" since it's not directly mentioned in the html, those classes are added to the inputs via JS using the code snippet I've provided.

Neither the `sass-loader`, `css-loader` nor ETWP should remove any CSS according to your current config,  did you `require/import` this particular CSS file ?  I'm not using SASS myself is the syntax correct ? During build time there are no assumptions made about the DOM and unused CSS, this plugin only extracts the CSS

**Comment by michael-ciniawsky** [comment]
> What info about my setup would you like to know?

More about how you import the `.scss` file atm

> By EWTP do you mean ETWP?

Yes

**Comment by mihailo-misic** [comment]
I import the `scss` file in my entry file `main.js`:

> main.js
```js
import '../scss/main.scss';
```

The problem is **100%** connected to the ETWP because I've fiddled all around it _(with other plugins, ways I import the scss, etc.)_ and it only works perfectly when i **disable** ETWP, and stops working as soon as I enable it.

I might be making some mistake when using it here's a link to my [webpack.config.ts](https://gist.github.com/mihailo-misic/60cf87ec5f173252bd5ff6bfd4bcd1c8) file.

**Comment by michael-ciniawsky** [comment]
The problem is 100% connected to [PurifyCSS Plugin](https://gist.github.com/mihailo-misic/60cf87ec5f173252bd5ff6bfd4bcd1c8#file-webpack-config-js-L114) I'm afraid 😛

**Comment by mihailo-misic** [comment]
I've not disabled PurifyCSS even once, and it worked every time I disabled ETWP.
Can you explain what would the logic be behind this occurrence?

**Comment by michael-ciniawsky** [comment]
Sure, the PurifyCSS Plugin relies on ETWP to be present. ETWP needs to extract the CSS Modules and generate a CSS file which is pushed to ```compilation.assets[`${name}.css`] = ${css}``` beforehand. PurifyCSS Plugin uses this file then and doesn't have any affect if no CSS Asset is found

**Comment by mihailo-misic** [comment]
Oh interesting, now that you mention it I remember that the PurifyCSS Docs mention needing ETWP.

Thanks a lot for helping me out.

This is unrelated to ETWP, but could you tell me how I could patch this around?
I've tried using the `"whitelist"` param in the PurifyCSS options but it throws the following error:
```
Error: data['whitelist'] should NOT have additional properties
...
```

> webpack.config.js
```js
new PurifyCSSPlugin({
  paths: glob.sync(path.join(__dirname, 'src/*.ejs')),
  whitelist: ['has-value', 'has-error'], // Introducing this makes it not work :[
  minimize: true,
}),
```

**Comment by hdrabs** [comment]
Hello, I am having the same issue. I am not using PurifyCSS but I am getting the same error.

**Environment**
------------

Item | Version
---- | -------
OS|10.14 (18A391)
Node|8.9.4
NPM|5.6.0
Webpack|3.12.0
extract-text-webpack-plugin|3.0.2

**How I am adding the styles**
--------

> _styles.css_

```css
.IntakeFormsBody {
  margin: 30px 0;
}
```

> _index.js_

```javascript
import './styles'
...
<div class={'IntakeFormsBody'}>
...
</div>
```

> _webpack.base.babel.js (file that complies the CSS files)_

```javascript
{
  // Preprocess our own .css files
  // This is the place to add your own loaders (e.g. sass/less etc.)
  // for a list of loaders, see https://webpack.js.org/loaders/#styling
  test: /\.css$/,
  exclude: /node_modules/,
  use: ['style-loader', 'css-loader'],
},
{
  // Preprocess 3rd party .css files located in node_modules
  test: /\.css$/,
  include: /node_modules/,
  use: ['style-loader', 'css-loader'],
},
```

And I am getting the ```// removed by extract-text-webpack-plugin``` line written instead of all the styles.

Please help me how to debug or where I am wrong. All the other files are loading the styles only the new files/styles that I am adding are not working.

**Comment by hdrabs** [comment]
@michael-ciniawsky @mihailo-misic can you guys help me out in this?
