### ISSUE TITLE
webpack.config works on Windows & OS X but not on Ubuntu Linux

### ISSUE THREAD

**Issue by Pavel-Durov** [webpack-contrib/extract-text-webpack-plugin#673]
I'm having this exception only on Linux OS. 
The following configuration work on Windows and OS X but not on Ubuntu Linux.

**webpack.comfig** (as can be seen here: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/631)

```
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var blueETP = new ExtractTextPlugin('blue.scss');
var baseETP = new ExtractTextPlugin(''base.scss');
  module: {
    rules: [{
        test: /base.scss$/,
        use: baseETP.extract({
          fallback: 'style-loader',
          use: ['css-loader', 'sass-loader']
        })
      },{
        test: /blue.scss$/,
        use: blueETP.extract({
          fallback: 'style-loader',
          use: ['css-loader', 'sass-loader']
        })
      }],
  plugins: [blueETP,baseETP]
  ....
```
Exception:

> ERROR in ./base.scss
> Module build failed: 
> @import 'main/app-Layout/appLayout';
> ^
>       File to import not found or unreadable: main/app-Layout/appLayout.
> Parent style sheet: .../css/2-modules/modules-fol.scss
>       in .../css/2-modules/modules-fol.scss (line 5, column 1)
>  @ ./app/app.js 3:2-34
>  @ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server ./app/app.js
> 

As you can see, for some reason it tries to include this file **main/app-Layout/appLayout.**

- OS: 16.04.2-Ubuntu
- NPM version: 5.5.1
- Node version: 8.9.1
- npm node-sass versions: 4.7.2

**Comment by evilebottnawi** [comment]
@Pavel-Durov can you provide minimum reproducible test repo? I use Ubuntu

**Comment by Pavel-Durov** [comment]
@evilebottnawi thanks.

I tried to create a minimum reproducible test repo and I failed to reproduce it (although I still have it my major project).  

I will investigate this behaviour, probably it has nothing to do with this plugin.
There is nothing that I can put my finger on - let's close this ticket :)

**Comment by evilebottnawi** [comment]
@Pavel-Durov anyway thank for issue!

**Comment by Pavel-Durov** [comment]
It's a classic lowercase-uppercase path issue. 
Nothing to do with **extract-text-webpack-plugin**
