### ISSUE TITLE
sortModules error with latest version of extract-text-webpack-plugin

### ISSUE THREAD

**Issue by rrampreeth** [webpack-contrib/extract-text-webpack-plugin#675]
I am trying to upgrade my version of webpack to 3 and using this plugin for the css/less files.

here is the error i run into 

TypeError: this._modules.sortWith is not a function
    at Chunk.sortModules (/Users/pramana/compeu/compliancedashboardweb/node_modules/webpack/lib/Chunk.js:425:17)
    at /Users/pramana/compeu/compliancedashboardweb/node_modules/extract-text-webpack-plugin/dist/index.js:188:19
    at /Users/pramana/compeu/compliancedashboardweb/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3096:16
    at eachOfArrayLike (/Users/pramana/compeu/compliancedashboardweb/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1055:9)
    at eachOf (/Users/pramana/compeu/compliancedashboardweb/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1103:5)
    at Object.eachLimit (/Users/pramana/compeu/compliancedashboardweb/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3158:5)
    at Compilation.<anonymous> (/Users/pramana/compeu/compliancedashboardweb/node_modules/extract-text-webpack-plugin/dist/index.js:184:27)
    at Compilation.applyPluginsAsyncSeries (/compeu/blah/node_modules/tapable/lib/Tapable.js:206:13)
    at Compilation.seal (/compeu/blah/node_modules/webpack/lib/Compilation.js:579:8)
    at /compeu/blah/node_modules/webpack/lib/Compiler.js:514:17
    at /compeu/blah/node_modules/tapable/lib/Tapable.js:289:11
    at /compeu/blah/node_modules/webpack/lib/Compilation.js:481:11
    at /compeu/blah/node_modules/webpack/lib/Compilation.js:452:13
    at /compeu/blah/node_modules/async-listener/glue.js:188:31
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)

Webpack version: 3.10.0
extract-text-webpack-plugin@3.0.2 

webpack.hot.config file:

`var webpack = require('webpack'),
    ExtractTextPlugin = require('extract-text-webpack-plugin'),
    path = require('path'),
    fs = require('fs');

module.exports = {
    devtool: 'eval',
    entry: [
        'webpack-hot-middleware/client',
        './src/public/main.js'
    ],
    output: {
        path: path.join(__dirname, '.build/js'),
        publicPath: '/policy/js/',
        filename: 'bundle.js'
    },
    module: {
        rules: [{
            test: /\.(css|less)$/,
            use: ExtractTextPlugin.extract({
                fallback: 'style-loader',
                use: ['css-loader', 'less-loader']
            })
        }, {
            test: /\.jsx?$/,
            exclude: /node_modules/,
            loader: 'babel-loader',
            query: {
                stage: 0,
                plugins: ['react-transform'],
                extra: {
                    'react-transform': {
                        transforms: [{
                            transform: 'react-transform-hmr',
                            imports: ['react'],
                            locals: ['module']
                        }, {
                            transform: 'react-transform-catch-errors',
                            imports: ['react', 'redbox-react']
                        }]
                    }
                }
            }
        }, {
            test: /\.json$/,
            loader: 'json-loader'
        }, {
            test: /\.png$/,
            exclude: /node_modules/,
            loader: 'url?limit=100000'
        }]
    },
    resolveLoader: {
        moduleExtensions: ['-loader']
    },
    plugins: [
        new ExtractTextPlugin({
            filename: 'css/[name].css',
            disable: false,
            allChunks: true}),
        new webpack.HotModuleReplacementPlugin(),
        new webpack.DefinePlugin({
            '__DEVELOPMENT__': process.env.NODE_ENV ? /dev(elopment)?/.test(process.env.NODE_ENV) : true
        })
    ]
};

**Comment by michael-ciniawsky** [comment]
Please add at least one  \` (backtick) around the code blocks for readability

**Comment by rrampreeth** [comment]
`var webpack = require('webpack'),
    ExtractTextPlugin = require('extract-text-webpack-plugin'),
    path = require('path'),
    fs = require('fs');


module.exports = {
    devtool: 'eval',
    entry: [
        'webpack-hot-middleware/client',
        './src/public/main.js'
    ],
    output: {
        path: path.join(__dirname, '.build/js'),
        publicPath: '/policy/js/',
        filename: 'bundle.js'
    },
    module: {
        rules: [{
            test: /\.(css|less)$/,
            use: ExtractTextPlugin.extract({
                fallback: 'style-loader',
                use: ['css-loader', 'less-loader']
            })
        }, {
            test: /\.jsx?$/,
            exclude: /node_modules/,
            loader: 'babel-loader',
            query: {
                stage: 0,
                plugins: ['react-transform'],
                extra: {
                    'react-transform': {
                        transforms: [{
                            transform: 'react-transform-hmr',
                            imports: ['react'],
                            locals: ['module']
                        }, {
                            transform: 'react-transform-catch-errors',
                            imports: ['react', 'redbox-react']
                        }]
                    }
                }
            }
        }, {
            test: /\.json$/,
            loader: 'json-loader'
        }, {
            test: /\.png$/,
            exclude: /node_modules/,
            loader: 'url?limit=100000'
        }]
    },
    resolveLoader: {
        moduleExtensions: ['-loader']
    },
    plugins: [
        new ExtractTextPlugin({
            filename: 'css/[name].css',
            disable: false,
            allChunks: true}),
        new webpack.HotModuleReplacementPlugin(),
        new webpack.DefinePlugin({
            '__DEVELOPMENT__': process.env.NODE_ENV ? /dev(elopment)?/.test(process.env.NODE_ENV) : true
        })
    ]
};

**Comment by rrampreeth** [comment]
var webpack = require('webpack'),
    ExtractTextPlugin = require('extract-text-webpack-plugin'),
    path = require('path'),
    fs = require('fs');


module.exports = {
    devtool: 'eval',
    entry: [
        'webpack-hot-middleware/client',
        './src/public/main.js'
    ],
    output: {
        path: path.join(__dirname, '.build/js'),
        publicPath: '/policy/js/',
        filename: 'bundle.js'
    },
    module: {
        rules: [{
            test: /\.(css|less)$/,
            use: ExtractTextPlugin.extract({
                fallback: 'style-loader',
                use: ['css-loader', 'less-loader']
            })
        }, {
            test: /\.jsx?$/,
            exclude: /node_modules/,
            loader: 'babel-loader',
            query: {
                stage: 0,
                plugins: ['react-transform'],
                extra: {
                    'react-transform': {
                        transforms: [{
                            transform: 'react-transform-hmr',
                            imports: ['react'],
                            locals: ['module']
                        }, {
                            transform: 'react-transform-catch-errors',
                            imports: ['react', 'redbox-react']
                        }]
                    }
                }
            }
        }, {
            test: /\.json$/,
            loader: 'json-loader'
        }, {
            test: /\.png$/,
            exclude: /node_modules/,
            loader: 'url?limit=100000'
        }]
    },
    resolveLoader: {
        moduleExtensions: ['-loader']
    },
    plugins: [
        new ExtractTextPlugin({
            filename: 'css/[name].css',
            disable: false,
            allChunks: true}),
        new webpack.HotModuleReplacementPlugin(),
        new webpack.DefinePlugin({
            '__DEVELOPMENT__': process.env.NODE_ENV ? /dev(elopment)?/.test(process.env.NODE_ENV) : true
        })
    ]
};

**Comment by rrampreeth** [comment]
webpack.hot.config file

```
var webpack = require('webpack'),
    ExtractTextPlugin = require('extract-text-webpack-plugin'),
    path = require('path'),
    fs = require('fs');


module.exports = {
    devtool: 'eval',
    entry: [
        'webpack-hot-middleware/client',
        './src/public/main.js'
    ],
    output: {
        path: path.join(__dirname, '.build/js'),
        publicPath: '/policy/js/',
        filename: 'bundle.js'
    },
    module: {
        rules: [{
            test: /\.(css|less)$/,
            use: ExtractTextPlugin.extract({
                fallback: 'style-loader',
                use: ['css-loader', 'less-loader']
            })
        }, {
            test: /\.jsx?$/,
            exclude: /node_modules/,
            loader: 'babel-loader',
            query: {
                stage: 0,
                plugins: ['react-transform'],
                extra: {
                    'react-transform': {
                        transforms: [{
                            transform: 'react-transform-hmr',
                            imports: ['react'],
                            locals: ['module']
                        }, {
                            transform: 'react-transform-catch-errors',
                            imports: ['react', 'redbox-react']
                        }]
                    }
                }
            }
        }, {
            test: /\.json$/,
            loader: 'json-loader'
        }, {
            test: /\.png$/,
            exclude: /node_modules/,
            loader: 'url?limit=100000'
        }]
    },
    resolveLoader: {
        moduleExtensions: ['-loader']
    },
    plugins: [
        new ExtractTextPlugin({
            filename: 'css/[name].css',
            disable: false,
            allChunks: true}),
        new webpack.HotModuleReplacementPlugin(),
        new webpack.DefinePlugin({
            '__DEVELOPMENT__': process.env.NODE_ENV ? /dev(elopment)?/.test(process.env.NODE_ENV) : true
        })
    ]
};
```

**Comment by rrampreeth** [comment]
My webpack.config file is as below

var webpack = require('webpack'),
    path = require('path'),
    fs = require('fs'),
    shush = require('shush');

`var config = shush('config/config.json');

module.exports = {
    entry: [
        './src/public/main.js'
    ],
    output: {
        path: path.join(__dirname, '.build/js'),
        publicPath: config.requestURI + '/js/',
        filename: 'bundle.js'
    },
    module: {
        rules: [
            {
                test: /\.jsx?$/,
                exclude: /node_modules/,
                loader: 'babel-loader'
            },

            {
                test: /\.json$/,
                loader: 'json-loader'
            },
            {
                test: /\.png$/,
                exclude: /node_modules/,
                loader: 'url?limit=100000'
            }
        ]
    },
    plugins: [
        new webpack.DefinePlugin({
            '__DEVELOPMENT__': false,
            'process.env.NODE_ENV': '"production"'
        }),
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false
            }
        }),
        new webpack.optimize.UglifyJsPlugin({comments: false})
    ]
};`

**Comment by rrampreeth** [comment]
my file to call this config is as below

`'use strict';
module.exports = function(app) {

    require('slipper-paypal');
    //The require hook will bind itself to node's require and automatically compile files on the fly.
    require('babel/register');

        // Step 1: Create & configure a webpack compiler
    var webpack = require('webpack');
    var webpackConfig = require('./webpack.hot.config');
    var compiler = webpack(webpackConfig);

    // Step 2: Attach the dev middleware to the compiler & the server
    app.use(require("webpack-dev-middleware")(compiler, {
        noInfo: true,
        publicPath: webpackConfig.output.publicPath
    }));

    // Step 3: Attach the hot middleware to the compiler & the server
    app.use(require("webpack-hot-middleware")(compiler, {
        log: console.log,
        path: '/__webpack_hmr',
        heartbeat: 10 * 1000
    }));


};`

**Comment by rrampreeth** [comment]
@michael-ciniawsky  i also looked into this https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/629 it doesnt seem to be helping out. Like mentioned in the email extract-text-webpack-plugin 3.0 seems to be still having the error.

**Comment by michael-ciniawsky** [comment]
This looks like a config error in your setup somewhere, a hot candidates are 

1. Maybe this 'Chunk' fails 

```diff
entry: [
-   'webpack-hot-middleware/client', // I'm not even sure if this is still needed in newer versions 
     './src/public/main.js'
]
```

2. `babel-loader` Config  (`react-transform-hmr` etc) 
3. An 'unfresh' env `node_modules, lockfiles, npm/yarn cache` etc.

**Comment by rrampreeth** [comment]
@michael-ciniawsky are you saying we no longer require webpack.hot.config?

**Comment by d3viant0ne** [comment]
@rrampreeth - This first alpha build is more for us than it is for general consumption. There are more than a few loaders / plugins that need a bit of work & there are likely changes that will land in Webpack requiring further updates on our end.

I wouldn't burn a bunch of time on this initial alpha release.

**Comment by rrampreeth** [comment]
@https://github.com/d3viant0ne which one is alpha release I am not clear.We did the same upgrade for 1 of our other apps with the same version did not have an issue, this app seems to be an issue as we are using webpack hot middleware. My question is it required? Is extract-text-webpack-plugin failing for that?

**Comment by michael-ciniawsky** [comment]
@rrampreeth Did your build succeed without using/having `'webpack-hot-middleware/client'` as an entrypoint ? If so you may consider adding it only during `development` and ETWP in `production`since ETWP + HMR doesn't make sense anyways :)

**Comment by d3viant0ne** [comment]
Ignore me, I saw Upgrade & Webpack & assumed the 4.0 alpha

**Comment by rrampreeth** [comment]
@michael-ciniawsky  no i was not able to get a successful build all i get is the below error

Tue, 05 Dec 2017 17:48:19 GMT uncaughtException this._modules.sortWith is not a function
TypeError: this._modules.sortWith is not a function
    at Chunk.sortModules (//compeu/blah/node_modules/webpack/lib/Chunk.js:428:17)
    at //compeu/blah/node_modules/extract-text-webpack-plugin/dist/index.js:188:19
    at //compeu/blah/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3096:16
    at eachOfArrayLike (//compeu/blah/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1055:9)
    at eachOf (//compeu/blah/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1103:5)
    at Object.eachLimit (//compeu/blah/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3158:5)
    at Compilation.<anonymous> (//compeu/blah/node_modules/extract-text-webpack-plugin/dist/index.js:184:27)
    at Compilation.applyPluginsAsyncSeries (//compeu/blah/node_modules/tapable/lib/Tapable.js:206:13)
    at Compilation.seal (//blah/node_modules/webpack/lib/Compilation.js:605:8)
    at //blah/node_modules/webpack/lib/Compiler.js:504:17
    at //compeu/blah/node_modules/tapable/lib/Tapable.js:289:11
    at /compeu/blah/node_modules/webpack/lib/Compilation.js:507:11
    at //compeu/blah/node_modules/webpack/lib/Compilation.js:477:14
    at /compeu/blah/node_modules/async-listener/glue.js:188:31
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)

**Comment by rrampreeth** [comment]
@d3viant0ne  any thoughts about this issue?

**Comment by rrampreeth** [comment]
"dependencies": {
    "async": "~1.4",
    "babel": "^5.8.23",
    "babel-core": "^6.9.0",
    "babel-polyfill": "^6.7.4",
    "babel-register": "^6.9.0",
    "camelscore": "^0.1.2",
    "connect-slashes": "^1.3.0",
    "continuation-local-storage": "^3.1.3",
    "crypto": "0.0.3",
    "date-utils": "^1.2.17",
    "debug": "^2.2.0",
    "debuglog": "^1.0.1",
    "document-identifier-validator": "^1.0.15",
    "exports-loader": "^0.6.2",
    "express": "^4.8.4",
    "express-meta": "0.1.1",
    "express-session": "^1.12.1",
    "f0-content-parser": "^1.1.0",
    "file-loader": "0.11.2",
    "file-type": "^3.3.1",
    "formsy-react": "~0.17.0",
    "history": "1.12.5",
    "imports-loader": "^0.6.4",
    "isomorphic-fetch": "2.1.1",
    "keymirror": "^0.1.1",
    "less": "^2.5.3",
    "locale": "^1.1.8",
    "locale-clamp-middleware": "^7.1.0",
    "localizr": "^0.1.0",
    "lodash": "^3.10.1",
    "moment": "^2.10.6",
    "multer": "^0.1.7",
    "nconf": "^0.8.2",
    "node-jes": "^0.1.0",
    "object-mapper": "^2.2.5",
    "protocol-buffers": "~3.1.3",
    "query-string": "^3.0.1",
    "react": "~0.14.0",
    "react-addons-create-fragment": "^0.14.0",
    "react-addons-css-transition-group": "^0.14.0",
    "react-bootstrap": "^0.27.3",
    "react-content-loader": "^1.0.0",
    "react-dom": "~0.14.0",
    "react-dropzone-component": "^1.2.0",
    "react-engine": "3.0.0",
    "react-mixin": "^2.0.2",
    "react-page-slider": "0.0.10",
    "react-redux": "~2.1.2",
    "react-router": "1.0.0",
    "react-text-input": "^1.2.0",
    "read-chunk": "^1.0.1",
    "realtimedataserv": "^1.0.1",
    "redux": "~3.1.3",
    "node-id-validator": "1.0.0",
    "redux-persist": "~1.4.3",
    "redux-thunk": "^1.0.0",
    "require-directory": "^2.1.1",
    "shush": "0.0.1",
    "text-mask": "0.0.1",
    "topos": "~0.3.10",
    "ua-parser": "~0.3.5",
    "uuid": "^2.0.1",
    "validator": "^4.5.0",
    "vault": "^3.0.0",
   "winston": "^1.0.0",
    "sequest": "^0.9.0"
  },
  "devDependencies": {
    "babel-cli": "^6.18.0",
    "babel-core": "^6.9.0",
    "babel-eslint": "^7.1.0",
    "babel-istanbul": "^0.2.10",
    "babel-loader": "^7.1.2",
    "babel-plugin-react-transform": "^1.1.1",
    "babel-preset-es2015": "^6.18.0",
    "babel-runtime": "^6.3.19",
    "bootstrap-rtl": "^3.3.4",
    "browser-wurfl": "^1.0.2",
    "chai": "^3.4.0",
    "classnames": "^2.1.3",
    "css-loader": "^0.19.0",
    "data-driven": "^1.2.1",
    "enzyme": "^2.2.0",
    "eslint": "^3.10.1",
    "eslint-config-consumerweb": "^4.1.0",
    "eslint-plugin-consumerweb": "^1.9.1",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-react": "^4.2.3",
    "extract-text-webpack-plugin": "^3.0.0",
    "excel-to-json": "^0.0.7",
    "file-uploader": "^1.0.1",
    "grunt": ">=0.4.5 <1.0.0",
    "grunt-babel": "^5.0.1",
    "grunt-browserify": "^4.0.1",
    "grunt-cli": "^0.1.13",
    "grunt-config-dir": "^0.3.2",
    "grunt-contrib-clean": "^0.5.0",
    "grunt-contrib-jshint": "^0.10.0",
    "grunt-contrib-less": "~0.9",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-copy-to": "^0.0.12",
    "grunt-eslint": "18.1.0",
    "grunt-loop-mocha": "^1.1.0",
    "grunt-mocha-babel-istanbul": "^2.5.0",
    "grunt-mocha-cli": "^1.13.0",
    "grunt-mocha-istanbul": "^4.0.2",
    "grunt-shell": "^2.0.0",
    "grunt-webpack": "^3.0.2",
    "istanbul": "^0.4.3",
    "istanbul-harmony": "^0.3.16",
    "jsdom": "^3.1.2",
    "json-loader": "^0.5.3",
    "less-loader": "^4.0.5",
    "mitm": "^1.2.0",
    "mocha": "^2.4.5",
    "mocha-appscan-reporter": "^2.0.0",
    "mocha-jenkins-reporter": "^0.2.2",
    "mock-meddleware": "1.0.0",
    "mockery": "^2.0.0",
    "node-xlsx": "^0.6.0",
    "node-rest-client": "*",
    "pre-commit": "^1.1.3",
    "proxyquire": "^1.7.3",
    "q": "^1.4.1",
    "react-addons-test-utils": "^0.14.7",
    "react-transform-catch-errors": "^1.0.0",
    "react-transform-hmr": "^1.0.1",
    "reactify": "^1.1.0",
    "redbox-react": "1.2.6",
    "redux-devtools": "^2.1.2",
    "require-globify": "^1.1.0",
    "require-replacer": "^1.0.7",
    "sinon": "^1.15.4",
    "style-loader": "^0.12.4",
    "supertest": "^0.9.0",
    "url-loader": "^0.5.7",
    "webpack": "^3.5.5",
    "webpack-dev-middleware": "^1.6.1",
    "webpack-dev-server": "^2.7.1",
    "webpack-hot-middleware": "^2.1.0",
    "xlsjs": "^0.7.5",
    "xunit-file": "0.0.4"

**Comment by evilebottnawi** [comment]
@rrampreeth sorry for delay, problem still exists?

**Comment by rrampreeth** [comment]
@evilebottnawi  thank you for checking. Resolved this issue.

**Comment by evilebottnawi** [comment]
@rrampreeth Can you describe how you solved problem here for future people. Thanks!
