### ISSUE TITLE
Plugins error using this module with latest webpack 4.0.0-alpha.0

### ISSUE THREAD

**Issue by Kielan** [webpack-contrib/extract-text-webpack-plugin#681]
I have added to my wepback.common manifest in a typical webpack build using different configurations of loaders, but I think the issue has to do with webpack not reading this plugin properly
```
  plugins: [
    new ExtractTextPlugin("main.css") //also as {filename:"main.css", allChunks: true},
  ],
```
The webpack error is

```

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.plugins[0] should be one of these:
   object { apply, ... } | function
   -> Plugin of type object or instanceof Function
   Details:
    * configuration.plugins[0] misses the property 'apply'.
      function
      -> The run point of the plugin, required method.
    * configuration.plugins[0] misses the property 'apply'.
      function
      -> The run point of the plugin, required method.
    * configuration.plugins[0] should be an instance of function
      -> Function acting as plugin

```

when logging the const that I import using require I see the extractText function when I log it. It would appear this import does not satisfy, Function acting as plugin, though it does have a `new` instance on it

**Comment by d3viant0ne** [comment]
@Kielan - This will be taken care of in #676

**Comment by Kielan** [comment]
https://github.com/Kielan/testWebpackErr

Example repo just for reference, switch webpack versions back and forth and notice the different console logs.

**Comment by Kielan** [comment]
@d3viant0ne looks like the pr was declined, any update?

**Comment by Kielan** [comment]
I found out that the issue is that I was using deepmerge dependency, webpack-merge seems to be an up to date alternative dependency https://github.com/survivejs/webpack-merge
