### ISSUE TITLE
webpack require.ensure issues

### ISSUE THREAD

**Issue by lvming6816077** [webpack-contrib/extract-text-webpack-plugin#686]
There are some component A,B,C and A.less,B.less,C.less,A belongs to entry a,B belongs to entry b.
A:
`import C;
import A.less`
B:
`import B.less;
require.ensure([],function(require){
var C = require('C');
})
`
C:
`import C.less`

webpack.config.js:
`
plugins: [
	new ExtractTextPlugin({
		filename: '[name].css',
		allChunks: false
	})
]
`

About entry a ,extract the C.less into a.min.css.
About entry b the C.less should not to be extracted because of the require.ensure.
The result is the C.less is missing in entry b because the C.less has been extracted by entry a.

**Comment by lvming6816077** [comment]
I have made a pull request to fix this issue

**Comment by evilebottnawi** [comment]
@lvming6816077 Thanks for issue and PR!
