### ISSUE TITLE
[feature request] extract according to limit size option

### ISSUE THREAD

**Issue by JounQin** [webpack-contrib/extract-text-webpack-plugin#691]
As title, so that we can only extract css when entry styles is large.

**Comment by evilebottnawi** [comment]
@JounQin Thanks for issue. Feel free to PR.

**Comment by michael-ciniawsky** [comment]
ETWP entered maintenance mode and won't receive any feature updates, please open an issue in [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) instead
