### ISSUE TITLE
Error: Cannot find module 'webpack/lib/Chunk'

### ISSUE THREAD

**Issue by xgqfrms-gildata** [webpack-contrib/extract-text-webpack-plugin#694]
# bug ???

> Error: Cannot find module 'webpack/lib/Chunk'

![image](https://user-images.githubusercontent.com/29531779/34513129-88d25498-f0a1-11e7-9a55-8d5a5e6b842f.png)

**Comment by xgqfrms-gildata** [comment]
# maybe install path error bug!

**Comment by xgqfrms-gildata** [comment]
# `options.publicPath` doesn't work?


![image](https://user-images.githubusercontent.com/29531779/34513952-cf541e02-f0a5-11e7-9a92-c69ed6e4e0f2.png)

> `publicPath`, not work at all?

![image](https://user-images.githubusercontent.com/29531779/34513984-feccfadc-f0a5-11e7-8a0e-53726178d70a.png)

![image](https://user-images.githubusercontent.com/29531779/34514025-3441954c-f0a6-11e7-88cd-a28338c647cb.png)

**Comment by mrtypescript** [comment]
It is enough just to require 'extract-text-webpack-plugin' to trigger the error:
Here ara my webpack.config.js:

var ExtractTextPlugin = require('extract-text-webpack-plugin');
// const extractSASS = new ExtractTextPlugin({
//     filename: 'app.css',
//     disable: false,
//     allChunks: true
// });
module.exports = {
    entry: {
        main: ["./app.js"]
    },
    output: {
        filename: "[name].bundle.js",
        path: __dirname + "/dist"
    },
    watch: true,
    module: {
        rules: [
            {
                test: /\.js$/,
                loader: 'babel-loader',
                exclude: /(node_modules|bower_components)/,
                query: {
                    presets: ['env']
                }
            },
            {
                test: /\.scss$/,
                use: ['style-loader', 'css-loader', 'sass-loader']
            }
        ]
    },
    plugins:[

    ]
}

Here are my package.json:
{
  "name": "webpack",
  "version": "1.0.0",
  "description": "develop",
  "main": "index.html",
  "directories": {
    "lib": "lib"
  },
  "scripts": {
    "test": "no_test_cmd"
  },
  "repository": {
    "type": "git",
    "url": "none"
  },
  "keywords": [
    "webpack"
  ],
  "author": "tahh",
  "license": "UNLICENSED",
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.1",
    "css-loader": "^0.28.8",
    "extract-text-webpack-plugin": "^3.0.2",
    "node-sass": "^4.7.2",
    "sass-loader": "^6.0.6",
    "save-dev": "^2.0.0",
    "style-loader": "^0.19.1"
  },
  "dependencies": {}
}

**Comment by usmansbk** [comment]
Uninstall global webpack and install locally

**Comment by evilebottnawi** [comment]
@xgqfrms-gildata can you create minimum reproducible test repo?

**Comment by mrtypescript** [comment]
Totally worked - thanks @usmansbk :)

**Comment by evilebottnawi** [comment]
@xgqfrms-gildata please read comments above. Seems you have invalid dependencies. Thanks everyone.

**Comment by xgqfrms-gildata** [comment]
@evilebottnawi The comments above no useful for me.

# my solution

![image](https://user-images.githubusercontent.com/29531779/35728576-fe33d470-0846-11e8-97b8-5026082c02c7.png)

> css

```js

// const extractSCSS = new ExtractTextPlugin('stylesheets/[name]-one.scss');
const extractSCSS = new ExtractTextPlugin({
    filename: (getPath) => {
        // relative path
        return getPath('css/[name].[hash:16].css');
        // js/../css & bug ???
        // return getPath('../css/[name].css');
        // return getPath('../css/[name].[hash:16].css').replace('js/../css', './css');
        // return getPath('/css/[name].[hash:16].css').replace('/css', '/css');
        // return getPath('../css/[name].css').replace('js/css', 'css');// relative path
    },
    // allChunks: true,
});
// const extractSASS = new ExtractTextPlugin('css/[name].css');

```
> js

```js

    output: {
        path: path.resolve(__dirname, "build/"),
        // path: path.resolve(__dirname, "build/js/"),
        // filename: '[name].min.js',
        filename: 'js/[name].[hash:16].min.js',// hash version
        // [hash] & [chunkhash] can using [hash:16] (default 20)。
        // filename: "[chunkhash].bundle.js",
        // publicPath: '/'
        // pathinfo: true,
        // sourceMapFilename:  [name], [id], [hash] & [chunkhash], // default "[file].map"。
    },

```

**Comment by xgqfrms-gildata** [comment]
# perfect

>SAP ready

![image](https://user-images.githubusercontent.com/29531779/35728846-de467e82-0847-11e8-9b5c-5a4f6125dc83.png)

**Comment by evilebottnawi** [comment]
@xgqfrms-gildata Can you create minimum reproducible test repo?

**Comment by xgqfrms-gildata** [comment]
# Sure

> Please wait a moment. When I have some free time do that.

I will create a repo for that demo.

`webpack3-best-practical`

**Comment by xgqfrms-gildata** [comment]
@evilebottnawi I have been updated it for the demo!

https://github.com/gildata/webpack3-best-practical/tree/master
