### ISSUE TITLE
PostCSS: ExtractTextPlugin run twice

### ISSUE THREAD

**Issue by ArielGueta** [webpack-contrib/extract-text-webpack-plugin#699]
I am trying to create a new postcss plugin. The problem is that when I am using the ExtractTextPlugin, the code is run twice, so if, for example, I'm appending new rule, it will append this twice.

I was looking for a solution and people are suggested to add `allChunks: true`, but it does not work.

```
css.walkRules(function (rule) {

    rule.walkDecls(function (decl, i) {

       // this is run twice with ExtractTextPlugin

    });

});
```

```
  "devDependencies": {
    "clean-css": "^4.1.9",
    "css-loader": "^0.28.9",
    "extract-text-webpack-plugin": "^3.0.2",
    "postcss": "^6.0.16",
    "postcss-loader": "^2.0.10",
    "style-loader": "^0.19.1",
    "webpack": "^3.10.0"
  }
```

**Comment by evilebottnawi** [comment]
@ArielGueta Can you create minimum reproducible test repo?

**Comment by ArielGueta** [comment]
It's seems like allChunks: true fixed this.

**Comment by evilebottnawi** [comment]
@ArielGueta :+1: Feel free to feedback
