### ISSUE TITLE
Feature-request: standardize hash-placeholder in options

### ISSUE THREAD

**Issue by tomm1996** [webpack-contrib/extract-text-webpack-plugin#703]
In our project, we just discovered, that the plugin does not update the hash of our css ressources when changing the content. We found out that this is because we used ` filename: '[name].[chunkhash:8].css'` instead of  ` filename: '[name].[contenthash:8].css'`. To me, this appears kind of unpredictable because the placeholders are almost the same.

Wouldn't it be a good idea to make `[chunkhash]` work in the config instead? Shouldn't the hash change anyways, even if we used the other placeholder?

For reference: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/49 https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/153 these users seem to find it confusing aswell.

**Comment by michael-ciniawsky** [comment]
I tried this awhile ago, but the chunk hash `[chunkhash]` doesn't seem to be avialable at the stage ETWP runs. Can't conform to 💯 but likely not possible to utilize `[chunkhash]` within the plugins scope

**Comment by tomm1996** [comment]
Thanks for your fast reaction. I might look into it aswell if I can get round to wrapping my head around the code base.

**Comment by evilebottnawi** [comment]
@tomm1996 it is impossible, because [chunkhash] - is hash of chunk, `contenthash` is hash of content. it is not bug, we extract css from js and don't have chunk and can't have [chunkhash]

**Comment by tomm1996** [comment]
@evilebottnawi that's why this is a feature request, not a bug. I merely wish the configuration of webpack/plugins to be less confusing. Whether the name of the placeholder is changed or something else is done about improving the usability is, of course, completely up to you if you decide to tackle this issue.

**Comment by evilebottnawi** [comment]
@tomm1996 PR welcome :+1:

**Comment by michael-ciniawsky** [comment]
ETWP entered maintenance mode and won't receive any feature updates, please open an issue in [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) instead

`webpack` will likely move to `contenthash` as the default in the future due to issues with `chunkhash` being unreliable ('side-effects' e.g when sorting modules in the graph can incorrectly change the hash even if the content didn't actually change)
