### ISSUE TITLE
no css link tag in html file

### ISSUE THREAD

**Issue by anchal20** [webpack-contrib/extract-text-webpack-plugin#708]
Hi,
I tried to implement extract-text-webpack-plugin for my app but it is not generating the css link tag in the html file. Can someone please help me in identifying the issue in the config file. Is there something that I have missed? 
[Here](https://github.com/anchal20/oops-js) is the link for my repo.

**Comment by evilebottnawi** [comment]
@anchal20 Please use https://github.com/jantimon/html-webpack-plugin plugin for html files. Seems you missed this plugin.

**Comment by anchal20** [comment]
Hi @evilebottnawi ,
Which ever tutorial or webpack documentation I saw no where it was mentioned to have another plugin. Anyways, this plugin will generate a new html file with the link. But what if i already have a html file - index.html as is my case, then how can I have the link tag in that, is it possible?

**Comment by evilebottnawi** [comment]
@anchal20 Just add `link` html tag :smile: If you want to use `css` only in production and/or `[hash]` in filenames you should use this plugin. Please look on `template` option, it is allow use own html template for generate new html file.

**Comment by anchal20** [comment]
Yes, I want to use css in production with the hash.

**Comment by evilebottnawi** [comment]
@anchal20 You should use `html-webpack-plugin` plugin for this purpose. Webpack don't handle `html` files from out of box.

**Comment by anchal20** [comment]
@evilebottnawi Ok let me try with your suggestion and see the outcome.
Thanks for your help. 
Closing the issue now

**Comment by evilebottnawi** [comment]
@anchal20 Feel free to feedback.
