### ISSUE TITLE
style-loader does not working after css is extracted.

### ISSUE THREAD

**Issue by sasssssha** [webpack-contrib/extract-text-webpack-plugin#715]
Greetings
My style-loader is set as fallback and in dev mode extract-text-plugin is disabled.
What is interesting, when I don't bundle my project and extract all files in dist folder, everything works fine, I can see `<style></style>` tag(which is arranged right after link to compiled css). But when I build my project and try to run it in dev mode, everything is extracted in dist folder, and I see only `link` to bundled css in `head`.

E.g.
running in dev mode: 
`<head>`
`<link rel="stylesheet" href="static/css/styles.css"> //it's not working because css is not extracted` 
`<style type="text/css">...</style>`
`</head>`

build&extract and then running in dev mode: 
`<head>`
`<link rel="stylesheet" href="static/css/styles.css"> //it's working now`
`</head>`
`// no style-tag`

I think that somehow webpack sees that styles is already extracted and it's not necessary to include `style` tag. But actually it does not matter if configuration says that tag should be included.
Does anybody have any idea about what's going on? Thanks in advance!

**Comment by sasssssha** [comment]
I temporary solved this problem by removing `dist` folder before running in dev mode but problem still exists.

**Comment by michael-ciniawsky** [comment]
Closing in favor of [`style-loader` #301](https://github.com/webpack-contrib/style-loader/issues/301)
