### ISSUE TITLE
Contenthash/Chunckhash breaking plugin 'pipeline'

### ISSUE THREAD

**Issue by EtienneDG** [webpack-contrib/extract-text-webpack-plugin#717]
Hello,

I'm runnning into an issue with this plugin regarding chunkhash and contenthash. I read the docs and did some research and found out that this plugin's chunkhash is not the same as webpack's chunkhash. The change of naming is a bit misleading, but I switched to contenhash instead (which seemed to be webpack's chunkhash) equivalent.

When I build my dev script, everything works perfectly (css extracted and manifest correctly filled). But when I build my prod script which does the same as dev AND use [OptimizeCssPlugin](https://github.com/NMFR/optimize-css-assets-webpack-plugin) to prefix and minify the CSS I get an error. 
I found this bug in production, because I had css assets not refreshing (because of the hash staying the same).

# What's happening 
The reason is that OptimizeCSSPlugin is looking for [name].[chunkhash] file, which only contains default webpack module js, which makes the plugin fail. I understand that the "bug" is occuring in another plugin but the root cause is still this : 
<webpack.chunkhash> != <extractText.chunkhash> 
AND
<webpack.chunkhash> != <extractText.contenthash>

#  What I also tried
Also I found weird that the (chunk)hash was not refreshed after file edition. 
This is the first run whit chuckhash in output and contenthash in plugin config :
![image](https://user-images.githubusercontent.com/5869860/35872847-4ca32dda-0b68-11e8-918d-87549fdd7848.png)

This is the second run (after file edit) :
![image](https://user-images.githubusercontent.com/5869860/35872849-4f676af4-0b68-11e8-8832-eb4ed041a032.png)

This is the second run without ExtractText:
![image](https://user-images.githubusercontent.com/5869860/35872968-a919fb02-0b68-11e8-9f79-b029e8840672.png)
In the last test the chunkhash is webpack's one (and stays the same as long as the file doesn't change)

# My questions
- why is the hash of the 'green file' is not the one generated by webpack, why is it overriden ? 
- could it be possible to NOT specify a file name for the plugin ? So that the correct chunkhash (ie. webpack's) is kept as the final file name
- could it be a way to get the same hash as webpack chunkhash ? 

Here is an excerpt of my configuration :  
```
name: 'css',
    entry: {
        'public': [resolve('assets/public.less')],
    },
    output: {
        path: resolve('static'),
        publicPath: '/static/',
        filename: `css/[name].[chunkhash].css`,
    },
    plugins: [
        new ManifestRevisionPlugin(resolve('manifest.json'), {
            rootAssetPath: resolve('static')
        }),
        new ExtractTextPlugin({
            filename: `css/[name].[contenthash].css`, //first configuration was chunkhash
            publicPath: './static/'
        }),
        new OptimizeCSSPlugin({
            cssProcessorOptions: {
                safe: true
            }
        }),
    ],

    module: {
        noParse: [/static/],
        rules: [
            {
                test: /\.(css|less)$/,
                exclude: /node_modules/,
                loader: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: [
                    {
                        loader: 'css-loader',
                        options: {
                            url: false,
                        }
                    },
                    {
                        loader: 'postcss-loader'
                    },
                    {
                        loader: 'less-loader',
                    }]
                })
            }
        ],
    }
```

And the dependencies
```
"devDependencies": {
    "autoprefixer-core": "^5.2.1",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-loader": "^6.4.1",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-vue": "^2.0.0",
    "babel-runtime": "^5.8.38",
    "chalk": "^2.3.0",
    "copy-webpack-plugin": "^4.3.1",
    "css-loader": "^0.28.9",
    "es6-promise": "^3.3.1",
    "exports-loader": "^0.6.4",
    "expose-loader": "^0.7.4",
    "extract-text-webpack-plugin": "^3.0.2",
    "fs": "0.0.2",
    "imports-loader": "^0.6.5",
    "json-loader": "^0.5.7",
    "less": "^2.7.3",
    "less-loader": "^2.2.3",
    "less-plugin-autoprefix": "^1.5.1",
    "manifest-revision-webpack-plugin": "^0.4.1",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "path": "^0.12.7",
    "postcss-loader": "^2.0.10",
    "progress-bar-webpack-plugin": "^1.10.0",
    "raw-loader": "^0.5.1",
    "style-loader": "^0.13.2",
    "uglifyjs-webpack-plugin": "^1.1.6",
    "url-loader": "^0.5.9",
    "vue-hot-reload-api": "^1.3.3",
    "vue-html-loader": "^1.0.0",
    "vue-loader": "^7.5.3",
    "wdio": "^1.0.3",
    "webpack": "^3.10.0",
    "webpack-merge": "^4.1.1"
  }
```

**Comment by evilebottnawi** [comment]
@EtienneDG 
`webpack.chunkhash` is chunk of chunk.
`extractText.chunkhash` - is not supported right now (see docs `Name of the result file. May contain [name], [id] and [contenthash]`).
`extractText.contenthash` - is md5/sha1 or you specify hash of content.

That you expect? Hash should be change? Need implement this inside `OptimizeCssPlugin` (in past we have discussion about add event to allow other plugins optimize and change name, maybe we should investigate this more deeply).

**Comment by michael-ciniawsky** [comment]
`chunkhash` isn't available within ETWP and `contenthash` is the better solution anyways since `chunkhash` is unreliable (can change even without any actually changes to the code, e.g when the graph changes elsewhere). It's confusing atm absolutely agreeing upon that, `webpack` will likely switch to use `contenthash` instead of `chunkhash` in the future and hopefully remove options to set different hash placeholders then. This is won't fix for EWTP
