### ISSUE TITLE
There is no rules property under module - webpack.config.js

### ISSUE THREAD

**Issue by Legends** [webpack-contrib/extract-text-webpack-plugin#720]
There is no rules property under module - webpack.config.js.

How to register ExtractTextPlugin under `loaders` ?

 
![image](https://user-images.githubusercontent.com/966368/36204969-63d5309a-118d-11e8-9324-3433335c13fd.png)

**Comment by michael-ciniawsky** [comment]
Which version of `webpack` are you currently using ?
