### ISSUE TITLE
[Validation]Error2 ajv error

### ISSUE THREAD

**Issue by ddtch** [webpack-contrib/extract-text-webpack-plugin#723]
Hi guys I already looked at issue [524](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/524), [569](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/569), [580](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/580) but it not helped me. I got  next error when running webpack
![image](https://user-images.githubusercontent.com/765596/36379356-4cbf10dc-158f-11e8-8557-687304e9dc74.png)

`webpack version = 3.11.0`
`node version = 8.9.4`
`npm version = 5.6.0`

my webpack.base config is 
`    
    
    
    const Path = require("path");
    const Webpack = require("webpack");
    const HtmlWebpackPlugin = require("html-webpack-plugin");
    const CopyWebpackPlugin = require("copy-webpack-plugin");
    const ExtractTextPlugin = require("extract-text-webpack-plugin");
    const AutoPrefixer = require("autoprefixer");
    const Utils = require("./utils");
    
    const PROD = Utils.PROD;
    const DEBUG = !PROD;
    const MAX_INLINE_SIZE = 20*1024;
    
    module.exports = {
        context: Utils.STATIC_ROOT,
    
         //entry: [
             //"babel-polyfill",
             //Utils.SRC_PATH
         //],
    
        stats: {
            colors: true,
            modules: true,
            reasons: true,
            errorDetails: true
        },
    
        output: {
            path: Utils.BUILD_PATH,
            publicPath: Utils.PUBLIC_PATH,
            // filename: "[name].js",
            // chunkFilename: "[name].[id].js",
        },
    
        resolve: {
            modules: ["src" ,"node_modules"],
            extensions: [".js", ".less", ".styl"]
        },
    
        module: {
            unknownContextRegExp: /$^/,
            unknownContextCritical: false,
            exprContextRegExp: /$^/,
            exprContextCritical: false,
            wrappedContextRegExp: /$^/,
            wrappedContextCritical: false,
            rules: [
                {
                    parser: {
                        amd: false
                    }
                },
                {
                    test:   /\.css$/,
                    use: ExtractTextPlugin.extract({
                        fallback: "style-loader",
                        use: [
                            "css-loader",
                            "postcss-loader",
                            "resolve-url-loader",
                        ]
                    })
                },
                {
                    test:   /\.styl$/,
                    use: ExtractTextPlugin.extract({
                        fallback: "style-loader",
                        use: [
                            "css-loader",
                            "postcss-loader",
                            "resolve-url-loader?keepQuery",
                            "stylus-loader",
                        ],
                        publicPath: Utils.PUBLIC_PATH,
                    })
                },
                {
                    test:   /\.js$/,
                    use: [{
                        loader: "babel-loader",
                        options: {
                            comments: false,
                            cacheDirectory: DEBUG,
                            babelrc: false,
                            plugins: [
                                "transform-runtime",
                                "transform-class-properties",
                                "transform-exponentiation-operator",
                                "transform-decorators-legacy",
                            ],
                            presets: [
                                [
                                    "env",
                                    {
                                        "targets": {
                                            "browsers": ["last 2 versions", "ie >= 11"]
                                        },
                                        "modules": false,
                                        "useBuiltIns": true,
                                        "debug": true,
                                        "loose": true,
                                        "shippedProposals": true,
                                    }
                                ],
                                "es2015",
                                "stage-0",
                                "react",
                            ]
                        }
                    }],
                    exclude: /node_modules/
                },
                {
                    test: /\.pug$/,
                    use: [{
                        loader: "pug-loader",
                        options: {pretty: DEBUG}
                    }]
                },
                {
                    test: /\.svg.*?$/,
                    use: [{
                        loader: "svg-url-loader",
                        options: {
                            "limit": MAX_INLINE_SIZE,
                            "mimetype": "image/svg+xml",
                            "name": "images/[name].[ext]",
                            "iesafe": true
                        }
                    }]
                },
                {
                    test:   /\.(png|jpe?g|gif|ico).*$/,
                    use: [{
                        loader: "url-loader",
                        options: {
                            name: "images/[name].[ext]",
                            limit: MAX_INLINE_SIZE,
                        }
                    }]
                },
                {
                    test: /\.(woff|woff2).*$/,
                    use: [{
                        loader: "url-loader",
                        options: {
                            "limit": MAX_INLINE_SIZE,
                            "mimetype": "application/font-woff",
                            "name": "[name].[ext]"
                        }
                    }]
                },
                {
                    test: /\.ttf.*?$/,
                    use: [{
                        loader: "url-loader",
                        options: {
                            "limit": MAX_INLINE_SIZE,
                            "mimetype": "application/octet-stream",
                            "name": "[name].[ext]"
                        }
                    }]
                },
                {
                    test: /\.eot.*?$/,
                    use: [{
                        loader: "file-loader",
                        options: {
                            "name": "[name].[ext]"
                        }
                    }]
                },
            ]
        },
    
        node: {
            fs: "empty"
        },
        plugins: [
            new Webpack.LoaderOptionsPlugin({
                debug: !PROD,
                options: {
                    postcss: function () {
                        return {
                            defaults: [AutoPrefixer],
                            cleaner:  [AutoPrefixer({ browsers: ["last 2 versions"] })],
                        };
                    },
                    stylus: {
                        import: Path.resolve(process.cwd(), "src/styles/styleguide.styl")
                    }
                }
            }),
            new ExtractTextPlugin({
                filename: "[name].css",
                allChunks: true
            }),
            new HtmlWebpackPlugin({
                filename: "index.html",
                template: Path.join(Utils.SRC_PATH, "index.pug"),
                inject: false,
                hash: true,
            }),
            new Webpack.DefinePlugin({
                __DEV__: Number(DEBUG),
                "process.env.NODE_ENV": JSON.stringify(process.env.NODE_ENV),
            }),
            new Webpack.NamedModulesPlugin(),
            new Webpack.NoEmitOnErrorsPlugin(),
            new Webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /ru/),
            new CopyWebpackPlugin([
                // {from: Path.resolve(Utils.SRC_PATH, 'touch-icons'),  fromType: 'glob'},
                {from: Path.resolve(Utils.SRC_PATH, 'images'), to: 'images', fromType: 'glob'},
                {from: Path.resolve(Utils.SRC_PATH, 'robots.txt'),  fromType: 'glob'},
                {from: Path.resolve(Utils.SRC_PATH, 'fonts'), to: 'fonts', fromType: 'glob'}
            ])
        ]
    };
`
and webpack.dev config is.
```   const webpack = require('webpack');
    const webpackMerge = require('webpack-merge');
    const baseConfig = require('./base');
    const stylesConfig = require('./styles');
    const Path = require("path");
    
    module.exports = webpackMerge(baseConfig, {
        entry: [
            'babel-polyfill',
            'react-hot-loader/patch',
            'webpack-dev-server/client?http://localhost:3001',
            'webpack/hot/only-dev-server',
            './src/index.js'
        ],
        output: {
            filename: "[name].js",
        },
        plugins: [
            new webpack.HotModuleReplacementPlugin(),
        ],
        devtool: "cheap-module-source-map",
        devServer: {
            // contentBase: [Utils.BUILD_PATH],
            historyApiFallback: true,
            port: 3001,
            compress: true,
            hot: true,
            stats: 'minimal',
            open: true,
            // proxy: {
            //     '/api': {
            //         target: 'http://localhost:9000',
            //         secure: false
            //     }
            // }
        },
        resolve: {
            alias: {
                config: Path.join(__dirname, '../config/config.dev_local.js')
            }
        }
    });
```

package.json
```
{
  "name": "some",
  "version": "1.0.0-beta",
  "private": true,
  "description": "Web front end npm dependencies",
  "author": "Dd",
  "scripts": {
    "dev": "cross-env NODE_ENV=development webpack-dev-server --config ./webpack/development.js",
    "build": "cross-env NODE_ENV=production webpack --display-modules --config ./webpack/production.js",
    "build_dev": "cross-env NODE_ENV=development webpack --display-modules --config ./webpack/development_build.js",
    "build_stage": "cross-env NODE_ENV=production webpack --display-modules --config ./webpack/stage.js",
    "build_test": "cross-env NODE_ENV=production webpack --display-modules --config ./webpack/test.js",
    "build_prod": "cross-env NODE_ENV=production webpack --display-modules --config ./webpack/production.js"
  },
  "dependencies": {
    "autoprefixer": "^6.7.7",
    "axios": "^0.18.0",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.0.14",
    "babel-loader": "^7.1.3",
    "babel-plugin-transform-class-properties": "^6.10.2",
    "babel-plugin-transform-decorators": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-object-assign": "^6.5.0",
    "babel-plugin-transform-runtime": "^6.5.2",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.0.14",
    "babel-preset-es2016": "^6.24.1",
    "babel-preset-es2017": "^6.24.1",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-0": "^6.3.13",
    "babel-runtime": "^6.26.0",
    "bootstrap": "^3.3.7",
    "classnames": "^2.2.5",
    "config": "^1.30.0",
    "copy-webpack-plugin": "^4.5.0",
    "cross-env": "^5.1.0",
    "css-loader": "^0.28.10",
    "default-passive-events": "git+https://github.com/zzarcon/default-passive-events.git",
    "es6-shim": "^0.35.1",
    "es6-template-string-loader": "^2.0.0",
    "exports-loader": "^0.6.3",
    "expose-loader": "^0.7.1",
    "express": "^4.16.1",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.11",
    "font-awesome": "^4.7.0",
    "history": "^4.5.1",
    "html-webpack-plugin": "^3.0.4",
    "immutable": "^3.8.1",
    "imports-loader": "^0.7.0",
    "json-loader": "^0.5.4",
    "less": "^2.6.1",
    "less-loader": "^4.0.6",
    "lodash": "^4.17.5",
    "moment": "^2.21.0",
    "moment-duration-format": "^1.3.0",
    "moment-timezone": "^0.5.11",
    "node-sass": "^4.3.0",
    "postcss-loader": "^1.2.2",
    "prop-types": "^15.6.1",
    "pug": "^2.0.0-beta6",
    "pug-loader": "^2.3.0",
    "react": "^15.4.2",
    "react-addons-css-transition-group": "^15.4.2",
    "react-addons-shallow-compare": "^15.4.2",
    "react-autosuggest": "^9.3.4",
    "react-bootstrap": "^0.31.0",
    "react-datepicker": "^0.56.0",
    "react-dates": "^14.0.0",
    "react-dom": "^15.4.2",
    "react-ga": "^2.4.1",
    "react-google-maps": "^9.4.5",
    "react-google-tag-manager": "^2.2.1",
    "react-hot-loader": "^4.0.0",
    "react-notifications": "^1.3.0",
    "react-numeric-input": "^2.2.3",
    "react-redux": "^5.0.7",
    "react-router": "^3.0.5",
    "react-router-redux": "^4.0.8",
    "react-select": "^1.2.1",
    "react-slick": "^0.15.4",
    "react-text-mask": "^5.1.0",
    "react-yandex-metrika": "^2.3.0",
    "recompose": "^0.26.0",
    "redux": "^3.7.2",
    "redux-devtools": "^3.3.2",
    "redux-devtools-dock-monitor": "^1.1.3",
    "redux-devtools-extension": "^2.13.2",
    "redux-devtools-filterable-log-monitor": "^0.7.0",
    "redux-form": "^7.3.0",
    "redux-responsive": "^4.3.5",
    "reset-css": "^2.2.0",
    "resolve-url-loader": "^2.3.0",
    "ress": "^1.2.2",
    "rimraf": "^2.5.3",
    "script-loader": "^0.7.2",
    "seamless-immutable": "^7.1.3",
    "slick-carousel": "^1.8.1",
    "svg-fill-loader": "0.0.8",
    "sweetalert2-react": "^0.5.0",
    "text-mask-addons": "^3.7.1",
    "uglify-js": "^3.3.13",
    "url-loader": "^1.0.1",
    "validator": "^9.4.1",
    "webpack": "4.1.0",
    "webpack-cleanup-plugin": "^0.5.1",
    "webpack-sources": "^1.1.0",
    "xhr-promise": "^2.0.0",
    "zenscroll": "^4.0.2"
  },
  "devDependencies": {
    "babel-minify-webpack-plugin": "^0.3.0",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-minify": "^0.2.0",
    "clean-webpack-plugin": "^0.1.18",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "rollup-plugin-commonjs": "^8.4.1",
    "rollup-plugin-replace": "^2.0.0",
    "rollup-plugin-uglify": "^3.0.0",
    "style-loader": "^0.19.1",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "webpack-cli": "^2.0.10",
    "webpack-dev-server": "^3.1.0",
    "webpack-merge": "^4.1.2"
  }
}

```
what is wrong?

**Comment by evilebottnawi** [comment]
@ddtch try to `npm cache clear --force && npm install`

**Comment by ddtch** [comment]
@evilebottnawi not helped. I already updated to webpack 4, same problem

**Comment by evilebottnawi** [comment]
@ddtch can you create minimum reproducible test repo?

**Comment by nlt-dev-acc** [comment]
Try this version: "extract-text-webpack-plugin": "^2.0.0-beta.4"

**Comment by andrey-o-sim** [comment]
Try this version: "extract-text-webpack-plugin": "^2.0.0-beta.4"
The version "^3.0.2" didn't work for me
