### ISSUE TITLE
[4.0.0-alpha.0] Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by pshurygin** [webpack-contrib/extract-text-webpack-plugin#724]
Im having this issue time to time while using this plugin version 4.0.0-alpha0 with webpack 4.0.0-beta2 in watch mode. The issue does not persist and i'm not sure when exactly it occures.
>  91% additional asset processing ExtractTextPluginD:\Solomoto\impl\solo\SolomotoWebRole\node_modules\webpack\lib\JavascriptGenerator.js:117
> 		const template = dependencyTemplates.get(dependency.constructor);
> 		                                     ^
> 
> TypeError: Cannot read property 'get' of undefined
>     at JavascriptGenerator.sourceDependency (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\webpack\lib\JavascriptGenerator.js:117:40)
>     at JavascriptGenerator.sourceBlock (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\webpack\lib\JavascriptGenerator.js:32:9)
>     at JavascriptGenerator.generate (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\webpack\lib\JavascriptGenerator.js:25:8)
>     at NormalModule.source (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\webpack\lib\NormalModule.js:372:33)
>     at Function.renderExtractedChunk (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\extract-text-webpack-plugin\dist\index.js:115:38)
>     at ExtractTextPlugin.extractedChunks.forEach.extractedChunk (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\extract-text-webpack-plugin\dist\index.js:298:46)
>     at Array.forEach (<anonymous>)
>     at compilation.hooks.additionalAssets.tapAsync.assetCb (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\extract-text-webpack-plugin\dist\index.js:286:25)
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:12:1)
>     at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\tapable\lib\Hook.js:35:21)
>     at hooks.optimizeTree.callAsync.err (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\webpack\lib\Compilation.js:846:32)
>     at _err0 (eval at create (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:16:1)
>     at _async2.default.forEach.err (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\extract-text-webpack-plugin\dist\index.js:281:11)
>     at D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\async\dist\async.js:473:16
>     at iteratorCallback (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\async\dist\async.js:1050:13)
>     at D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\async\dist\async.js:958:16
>     at _async2.default.forEach.err (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\extract-text-webpack-plugin\dist\index.js:259:13)
>     at D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\async\dist\async.js:473:16
>     at eachOfArrayLike (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\async\dist\async.js:1043:9)
>     at eachOf (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\async\dist\async.js:1103:5)
>     at Object.eachLimit (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\async\dist\async.js:3158:5)
>     at _async2.default.forEach (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\extract-text-webpack-plugin\dist\index.js:214:27)
>     at D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\async\dist\async.js:3096:16
>     at eachOfArrayLike (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\async\dist\async.js:1055:9)
>     at eachOf (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\async\dist\async.js:1103:5)
>     at Object.eachLimit (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\async\dist\async.js:3158:5)
>     at compilation.hooks.optimizeTree.tapAsync (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\extract-text-webpack-plugin\dist\index.js:208:25)
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:12:1)
>     at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\tapable\lib\Hook.js:35:21)
>     at Compilation.seal (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\webpack\lib\Compilation.js:789:27)

**Comment by jmar777** [comment]
@pshurygin I just started running into this today after adding dynamic imports, and then noticed that the new update, `4.0.0-beta.0`, includes specific fixes for dynamic imports.

So far it's been smooth sailing after updating to the new version.

**Comment by pshurygin** [comment]
Yes i believe this one is fixed in beta0. Thanks!
