### ISSUE TITLE
Scss files not get compiled

### ISSUE THREAD

**Issue by weichenghsu** [webpack-contrib/extract-text-webpack-plugin#729]
Version: "extract-text-webpack-plugin": "3.0.2"

I have scss files under `src/css` and want to compile it through webpack.
It seems not working.
What's the possible root cause?
Thanks

        var webpack = require('webpack');
        var path = require('path');
        const ExtractTextPlugin = require("extract-text-webpack-plugin");
        var CopyWebpackPlugin = require('copy-webpack-plugin');
        var HtmlWebpackPlugin = require('html-webpack-plugin');

        const extractCustomCss = new ExtractTextPlugin('./custom.css');

        const scssCompileOption = {
            test: /\.scss$/,
            include: [
                path.resolve(__dirname, 'src/css')
            ],
            loader: ExtractTextPlugin.extract({
                use: [{
                    loader: 'css-loader'
                }, {
                    loader: 'sass-loader'
                }],
                fallback: 'style-loader'
            })
        }

        module.exports = {
            entry: {
                index: "./src/App.tsx"
            },
            output: {
                path: path.join(__dirname, "/dist/"),
                filename: "[name].js"
            },

            devtool: 'source-map',
            resolve: {
                extensions: ['.ts', '.tsx', '.js', '.json', '.scss']
            },

            module: {
                loaders: [
                    {test: /\.json$/, exclude: /node_modules/, loader: 'json'},
                ],
                rules: [
                    scssCompileOption

                ]
            },
            devServer: {
                stats: 'errors-only',
                hot: true
            },
            plugins: [
                extractCustomCss
            ]
            // target: 'node'
        };

**Comment by evilebottnawi** [comment]
@weichenghsu can you describe versions of `webpack`, `sass-loader`, `css-loader`, `style-loader`, `node`

**Comment by ngohungphuc** [comment]
@weichenghsu just follow my config and you will be good
```js
const path = require("path");
const webpack = require("webpack");
const ExtractTextPlugin = require("extract-text-webpack-plugin");
const extractCSS = new ExtractTextPlugin("cmscore.css");

module.exports = {
  entry: {
    main: "./wwwroot/frontend/js/main.js"
  },
  output: {
    path: path.resolve(__dirname, "wwwroot/dist"),
    filename: "[name].js",
    publicPath: "/dist/"
  },
  plugins: [
    extractCSS,
    new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery"
    }),
    new webpack.optimize.UglifyJsPlugin()
  ],
  module: {
    loaders: [
      {
        test: /\.scss$/,
        use: extractCSS.extract({
          use: [
            {
              loader: "css-loader",
              options: {
                minimize: true,
                sourceMap: true
              }
            },
            {
              loader: "sass-loader"
            }
          ],
          // use style-loader in development
          fallback: "style-loader"
        })
      },
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        loader: ["babel-loader", "eslint-loader"]
      },
      {
        test: /\.(jpe?g|png|gif)$/i,
        loader: "file-loader"
      },
      {
        test: /\.(woff|ttf|otf|eot|woff2|svg)$/i,
        loader: "file-loader"
      }
    ]
  },
  watch: true
};
```

**Comment by michael-ciniawsky** [comment]
Try without `include`
