### ISSUE TITLE
Entrypoint undefined = extract-text-webpack-plugin-output-filename after upgrade to webpack 4

### ISSUE THREAD

**Issue by ngohungphuc** [webpack-contrib/extract-text-webpack-plugin#731]
I got this error 

![code_2018-03-01_00-26-48](https://user-images.githubusercontent.com/13591213/36802501-a37894a2-1ce7-11e8-9f10-543bf787d2c5.png)

My `webpack.config` file

```js
const path = require("path");
const webpack = require("webpack");
const ExtractTextPlugin = require("extract-text-webpack-plugin");
const UglifyJSPlugin = require("uglifyjs-webpack-plugin");

module.exports = {
  entry: {
    main: "./wwwroot/frontend/js/main.js"
  },
  output: {
    path: path.resolve(__dirname, "wwwroot/dist"),
    filename: "[name].js",
    publicPath: "/dist/"
  },
  plugins: [
    new ExtractTextPlugin({
      filename: "cmscore.css"
    }),
    new UglifyJSPlugin({
      sourceMap: true
    })
  ],
  module: {
    rules: [
      {
        test: /\.scss$/,
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: "css-loader!sass-loader"
        })
      },
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: ["babel-loader", "eslint-loader"]
      }
    ]
  },
  watch: true
};

```

Am I missing something or webpack 4 is not ready to use with this plugin ?

**Comment by AtofStryker** [comment]
Webpack 4's new tapable plugin library broke some of the existing plugins. The fix should be relatively simple

**Comment by ngohungphuc** [comment]
I get this error in dev mode not sure about prod mode may be the same lol @RussGlover

**Comment by jbasilio** [comment]
I get this same error in Webpack 4. Regardless of mode.

**Comment by evilebottnawi** [comment]
Somebody can create minimum reproducible test repo?

**Comment by mauriciofergo** [comment]
Same error here,
The build is performed properly but when I enter the local server the entry point is not loaded.

**Comment by DaveBitter** [comment]
Same issue here. The fix probably isn't that big of a task. If I had more knowledge on this I would make a PR. Is there any ETA for the fix. I now have to downgrade to Webpack 3 just for this plugin.

**Comment by leereichardt** [comment]
Is Webpack 4 even ready for production use? I feel like they need to delay a few more weeks to allow some of the most important plugins to be updated?

**Comment by Edward-Lombe** [comment]
@leereichardt After using it for a couple of days, my survey would be no. It still works, but for a program as reliant on plugins as webpack is (especially those under the quasi-official webpack contrib), I would expect the release of v4 to correspond to all the important plugins being updated to v4.

**Comment by ngohungphuc** [comment]
@leereichardt 
>Webpack 4's new tapable plugin library broke some of the existing plugins. The fix should be relatively simple

**Comment by leereichardt** [comment]
So it has been said on various issues for the past 50 odd days. Yet this relatively simple fix hasn’t been fixed?

**Comment by ngohungphuc** [comment]
not sure why is take so long

**Comment by oliverguenther** [comment]
Responding here because I'm being notified of your recent comment. How about instead of complaining here, you contribute by helping in fixing the broken tests [in the v4 compatibility PR](https://github.com/jaredpalmer/razzle/pull/525) ?

Thanks to the maintainers that have provided our project with smooth upgrade paths from the early days of webpack. We are experiencing the same issue and will appreciate it being fixed as soon as the maintainers can handle it.

**Comment by ngohungphuc** [comment]
We just raise the concern, not complain. Also If I knowledge I would make Pr and fix it for you guys

**Comment by AvraamMavridis** [comment]
Same issue here, with webpack 4

<img width="504" alt="screen shot 2018-03-06 at 15 54 17" src="https://user-images.githubusercontent.com/283690/37039007-aac88aaa-2156-11e8-8f43-21470040183b.png">

**Comment by evilebottnawi** [comment]
We have a lot of issue when `webpack@4` was shipped. :disappointed: 

Feel free to PR to fix this.

**Comment by evilebottnawi** [comment]
I can look on `ETWP` only on next week, sorry

**Comment by sukonzer** [comment]
![sdd](https://user-images.githubusercontent.com/2359717/37200225-1e50c63a-23bf-11e8-8710-c2a31385b19e.png)

Same issue in Webpack 4. Regardless of mode

**Comment by zD98** [comment]
Maybe `entrypoint undefined = xxx` is a unfinished feature of webpack 4.  ? ? ?

> CSS Module Type — CSS as Entry (Goodbye ExtractTextWebpackPlugin)

> HTML Module Type — HTML as Entry

And Javascript EntryPoint doesn't have any errors.

**Comment by zD98** [comment]
```
    stats: {
        ...
        children: false, 
        ...
    },
```

Setting the property `children` to false will show off the log info. 
But I don't what happened.

**Comment by Krucial92** [comment]
Is there any updated on this? Any solution to resolve the issue "entrypoint undefined"? Thanks.

**Comment by benoitmaudet** [comment]
Same error with webpack 4 :    `Entrypoint undefined = extract-text-webpack-plugin-output-filename`.

**Comment by waleedahmed3045** [comment]
Alot of people are having this issue. Can this be resolved please?

**Comment by StalkAlex** [comment]
I have experiencing those messages for all non-js entrypoints, like css or html(how I undestand this), but with js entypoint I specified manually it shows correct output `Entrypoint main [big] = js/main.3bf77c.js ./css/main.f871d2.css js/main.3bf77c.js.map` and it's not causing any real problems, just those messages. Application is working as it suppose to. So what's real problem with that?

**Comment by polco** [comment]
If you're only using the extract-text plugin for CSS, you can use this plugin instead: https://github.com/webpack-contrib/mini-css-extract-plugin

It's compatible with webpack 4.

**Comment by benoitmaudet** [comment]
Works perfectly with https://github.com/webpack-contrib/mini-css-extract-plugin. Thanks !

**Comment by michael-ciniawsky** [comment]
TL;DR Use [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) instead :)

The `webpack >= v4.0.0` 'support' for `extract-text-webpack-plugin` was moved to [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) as more lightweight approach for `webpack >= v4.0.0` and ETWP entered maintenance mode. We are sorry for the inconvenience here, but ETWP reached a point where maintaining it become too much of a burden and it's not the first time upgrading a major `webpack` version was complicated and cumbersome due to issues with ETWP. The mid-term plan is integrate CSS support directly into `webpack` to avoid this kind of issue in the future

**Comment by maphi88** [comment]
@mauriciofergo Did you find the solution I have the same entry point in my application.

**Comment by mauriciofergo** [comment]
Sorry @maphi88 but I'm not continuing with the migration, good luck!

**Comment by GabrielDelepine** [comment]
@mauriciofergo #759 about compatibility section in the README file

**Comment by 7iomka** [comment]
@michael-ciniawsky 
mini-css-extract-plugin not working for me, because I needed to set publicPath in config. 
ETP prodive this posibility
```
 use: ExtractTextPlugin.extract({
                        publicPath: '../',
```

But mini-css-extract-plugin has no options(
Any ideas how to fix **"Entrypoint undefined = extract-text-webpack-plugin-output-filename" ?**

**Comment by ngohungphuc** [comment]
@7iomka check my pr to help you config webpack 4 
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/pull/71/files

**Comment by Tiendq** [comment]
`mini-css-extract-plugin` currently doesn't work with this error:

`Module build failed: TypeError: this[NS] is not a function`

I'd stay with `extract-text-webpack-plugin`, it's better to just see a warning :)

**Comment by bspatil0001** [comment]
Is this issue closed, Is there a solution for this issue? Moving to other plugin is the only solution.

**Comment by samboustani** [comment]
Switching to mini-css-extract-plugin brings a whole new set of problems and doesn't solve the build issues.

**Comment by Tiendq** [comment]
I just tried `mini-css-extract-plugin` again, version `0.4.0` and it works well with `SCSS` extraction. As authors of `extract-text-webpack-plugin` has suggested, you'd better to use  `mini-css-extract-plugin` for CSS now :)

**Comment by Tiendq** [comment]
@samboustani what are your problems? did you raise issues?

**Comment by mesmerize86** [comment]
Hi @tiendq 

Entrypoint mini-css-extract-plugin = *

When i use mini-css-extract-plugin I got above entry point. And it still stop bundling.

  {
        test: /\.(sa|sc|c)ss$/,
        use: [
          MiniCssExtractPlugin.loader,
          'css-loader',
          'sass-loader',
        ],
      }

    new MiniCssExtractPlugin({
      filename: '[name].min.css'
    }),

**Comment by nemanjacosovic** [comment]
+1

**Comment by wp-kitten** [comment]
Well done @ngohungphuc , **your solution was the only one that worked** and helped me not pulling all my hair out. Thanks a lot buddy!

**Comment by ngohungphuc** [comment]
@wp-kitten no problem glad that I can help 😄

**Comment by bigbizyou** [comment]
Hy !!!
do not forget to exclude node_modules, it was OK for me :

module: {
        rules: [
            {
                test: /\.scss$/,
                **exclude: /node_modules/,**
                use: ExtractTextWebpackPlugin.extract({
                    fallback: 'style-loader',
                    use: [{
                        loader: 'css-loader',
                        options: {minimize: true}
                    }, 'sass-loader', 'postcss-loader', 'import-glob-loader']
                })
            },
