### ISSUE TITLE
Fallback loader removed from/not included in bundle

### ISSUE THREAD

**Issue by woutervanvliet** [webpack-contrib/extract-text-webpack-plugin#739]
I have a setup where I have two types of css files (1) global styles not processed as css modules (2) module specific styles processed as css modules. CSS should be extracted to one css file, and this works. Then `style-loader` is used to load styles that come from dynamic imports. And here comes the problem;

When I set `style-loader` as fallback for both `ExtractTextPlugin.extract` calls, I get runtime errors telling me that moduleId `css-loader/lib/css-base` cannot be found. (Actually, the message is "Cannot read property 'call' of undefined" but I've debugged it down to the css-loader/lib/css-base.js module.

A functioning workaround at the moment is to only have a fallback for the `extract` call for my CSS Modules files, and manually importing `css-loader/lib/css-base` in my entry bundle. But this would only work as long as I have no "noModule" scss files being imported in dynamic imports.

The rules related to stylesheets look like follows. This array is spread out in `module.rules`.

I'm using webpack 4.0.1, extract-text-webpack-plugin 4.0.0-beta.0

```js
// defined higher up in my file
const styleLoader = 'style-loader';
const cssModuleLoader = {
	loader: 'css-loader',
	options: {
		importLoaders: 1,
		modules: true,
		localIdentName: cssIdentName,
	},
};

const cssPlainLoader = {
	loader: 'css-loader',
};

// actual style rules
export const styleRules = Object.values({
	cssModules: {
		use: buildTarget === 'server'
			? [styleLoader, cssModuleLoader]
			: extractCss.extract({
				fallback: styleLoader,
				use: cssModuleLoader,
			}),
		test: (filePath) => isStylesheet(filePath) && isModule(filePath),
	},
	cssNoModules: {
		use: buildTarget === 'server'
			? [styleLoader, cssPlainLoader]
			: extractCss.extract({
				/*
                		Using a fallback here will remove the style-loader
                		from the bundle, even though we need it for cssModules
                		therefore it is disabled, under the assumption that we
                		need no fallback for noModules styles. Might be a bug
                		*/
				// fallback: styleLoader,
				use: cssPlainLoader,
			}),
		test: (filePath) => isStylesheet(filePath) && !isModule(filePath),
	},
	postCss: {
		loader: 'postcss-loader',
		test: isStylesheet,
	},
	sassloader: {
		loader: 'sass-loader',
		test: /\.scss$/,
	},
});
```

**Comment by woutervanvliet** [comment]
Just created a minimal example repository to narrow down on the issue:

https://github.com/woutervanvliet/etwp-issue-739

- The issue is active on the `master` branch. 
- The branch `workaround` contains a working, though not ideal, workaround.
- The branch `webpack3` runs on, you guessed it, webpack3 - where the problem doesn't appear

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
