### ISSUE TITLE
add support for webpack v4

### ISSUE THREAD

**Issue by mojoaxel** [webpack-contrib/extract-text-webpack-plugin#741]
[Webpack v4 has been released](https://github.com/webpack/webpack/tags).
At the moment only webpack version 3.1.0 is supported:
* https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/master/package.json#L65

**Comment by montogeek** [comment]
Duplicate of https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/701

**Comment by mojoaxel** [comment]
@montogeek Sorry and thanks!
