### ISSUE TITLE
[4.0.0-beta.0] Incorrect output file name using [name] token and npm script entry points.

### ISSUE THREAD

**Issue by ryios** [webpack-contrib/extract-text-webpack-plugin#744]
I've got a simple webpack.config setup (still working on it). Right now it's just sass, extract text, and babel setup.

I've got two NPM scripts as follows for zeroless configuration (so I don't need multiple webpack.config files (per webpack 4's changes).

The issue I'm having is the extract text webpack plugin outputs my file names as "main.css" on any of my npm scripts. So I guess webpack is telling it "app-dev" and "vendor-dev" are called "main" even thought my src files are called "app.js" and "vendor.js". I've got my scripts split between app.js and vendor.js. So I've got 4 NPM Scripts.

So basically, app.js and vendor.js specified as my entry points in my npm scripts "app-dev" and "vendor-dev" appear to both be treated as "main" for their name, causing both of my NPM scripts to output a css file called "main.css" when what I expect is "app.css" and "vendor.css".

[Source Structure Image](https://i.stack.imgur.com/VJBN4.png)

[Output Image](https://i.stack.imgur.com/0TncA.png)

```

{
    "name": "redacted",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
        "app-dev": "webpack --mode development --display-error-details ./src/js/app.js --output ./dist/js/app.js",
        "app-prd": "webpack --mode production ./src/js/app.js --output ./dist/js/app.min.js",
        "vendor-dev": "webpack --mode development --display-error-details ./src/js/vendor.js --output ./dist/js/vendor.js",
        "vendor-prd": "webpack --mode production ./src/js/vendor.js --output ./dist/js/vendor.min.js"
    },
    "repository": {
        "type": "git",
        "url": "git+https://github.com/ReckTEK/Nodesome.git"
    },
    "author": "Ryios",
    "license": "ISC",
    "bugs": {
        "url": "redacted"
    },
    "homepage": "redacted",
    "devDependencies": {
        "babel-core": "^6.26.0",
        "babel-loader": "^7.1.3",
        "babel-preset-env": "^1.6.1",
        "babel-preset-vue": "^2.0.1",
        "css-loader": "^0.28.10",
        "extract-text-webpack-plugin": "^4.0.0-beta.0",
        "file-loader": "^1.1.11",
        "node-sass": "^4.7.2",
        "sass-loader": "^6.0.7",
        "style-loader": "^0.20.2",
        "webpack": "^4.0.1",
        "webpack-cli": "^2.0.10"
    },
    "dependencies": {
        "axios": "^0.18.0",
        "bootstrap": "^4.0.0",
        "bootstrap.native": "^2.0.21",
        "font-awesome": "^4.7.0",
        "vee-validate": "^2.0.5",
        "vue": "^2.5.13",
        "vue-router": "^3.0.1"
    }
}
```

```
const extractTextPlugin = require("extract-text-webpack-plugin");
const extractSass = new extractTextPlugin({
    filename: "css/[name].css"
});
module.exports = {
    module: {
        rules: [
            {
                test: /\.js$/,
                use: {
                    loader: "babel-loader"
                }
            },
            {
                test: /.(ttf|otf|eot|svg|woff(2)?)(\?[a-z0-9]+)?$/,
                use: [{
                    loader: 'file-loader',
                    options: {
                        name: '[name].[ext]',
                        outputPath: 'fonts/',
                        publicPath: '../'
                    }
                }]
            },
            {
                test: /\.scss$/,
                use: extractSass.extract({
                    use: [{
                        loader: "css-loader"
                    }, {
                        loader: "sass-loader"
                    }],
                    // use style-loader in development
                    fallback: "style-loader"
                })
            },
            {
                test: /\.css$/,
                use: extractSass.extract({
                    fallback: "style-loader",
                    use: "css-loader"
                })
            }
        ]
    },
    plugins: [
        extractSass
    ]


}
```

**Comment by michael-ciniawsky** [comment]
TL;DR Use [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) instead :)

The `webpack >= v4.0.0` 'support' for `extract-text-webpack-plugin` was moved to [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) as more lightweight approach for `webpack >= v4.0.0` and ETWP entered maintenance mode. We are sorry for the inconvenience here, but ETWP reached a point where maintaining it become too much of a burden and it's not the first time upgrading a major `webpack` version was complicated and cumbersome due to issues with ETWP. The mid-term plan is integrate CSS support directly into `webpack` to avoid this kind of issue in the future
