### ISSUE TITLE
[Webpack 3] When would you generally need a fallback? / Why is style-loader still used when css is extracted?

### ISSUE THREAD

**Issue by garygreen** [webpack-contrib/extract-text-webpack-plugin#747]
When using the extract text plugin, you can specify a `fallback` loader to use:

```js
{
  test: /\.css$/,
   use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: 'css-loader'
  })
},
```

So in these environments:

### Development

The extract text plugin will still split the css files, so the fallback is not needed?

### Production

Same as above.

### Development - Hot Module Replacement

It's generally recommended you disable the extract text plugin in this environment, so is this where the fallback would be useful, as it can then swap out the css with the help of style-loader?

---

I was surprised to find that in my production and development builds, the style-loader boilerplate code is added even though the CSS was extracted. This goes against what is written in the docs:

> fallback - used when the CSS is not extracted (i.e. in an additional chunk when allChunks: false)

What I've been doing is removing the fallback in my production builds because I don't see why it should be needed?

```js
{
 test: /\.css$/,
  use: ExtractTextPlugin.extract({
	 fallback: env == 'dev-hot' ? 'style-loader' : undefined,
	 use: 'css-loader'
  })
},
```

Could anyone clarify what the recommended usage and why the style-loader seems to be used even though css is extracted?

**Comment by lili21** [comment]
You can disable this plugin in development.

**Comment by benlind** [comment]
I have the same question. I don't expect `style-loader` to ever be used in production, so why is it provided as a fallback?

**Comment by garygreen** [comment]
Yeah I think this is a bug. When all css is extracted and style-loader is used, it shouldn't be included in the bundle at all. The only time it should be included is:

* CSS was not extracted
* HMR
* Async chunks/bundles.

All other cases the style-loader should not be included in the bundle at all, but it seems it is no matter what.

**Comment by evilebottnawi** [comment]
Please don't use `extract-text-webpack-plugin` to extract css for `webpack@4` use https://github.com/webpack-contrib/mini-css-extract-plugin

**Comment by garygreen** [comment]
Should of mentioned, this is for Webpack 3.
