### ISSUE TITLE
Hot Module Reload?

### ISSUE THREAD

**Issue by imjakechapman** [webpack-contrib/extract-text-webpack-plugin#75]
I noticed that one of the caveats is that there is no HMR. Is there a specific reason for it not being implemented?

Does it just need to be PR'd in?

**Comment by carlosepp** [comment]
please enable this, we are so close to get a great workflow and would love HMR

**Comment by carlosepp** [comment]
@imjakechapman is there any plan to enable HMR in the future?

**Comment by imjakechapman** [comment]
I have no idea, I stopped developing with Webpack due to lack of people at my work switching over. I'm still trying to use it on personal projects but am not actively contributing. Hopefully someone else can chime into this?

**Comment by carlosepp** [comment]
Is there a better tool you recommend to keep an eye on?, currently our team is happy with webpack but always open to try new things, also, will try to dive in and see if I can enable this.

Thanks @imjakechapman

**Comment by glebmachine** [comment]
+

**Comment by IAMtheIAM** [comment]
Still waiting for this. Any updates?

**Comment by bebraw** [comment]
Keep an eye on https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/89.
