### ISSUE TITLE
CSS file not emitted when loaders defined with query string syntax

### ISSUE THREAD

**Issue by james-s-turner** [webpack-contrib/extract-text-webpack-plugin#752]
I am trying to use [multi-loader](https://github.com/webpack-contrib/multi-loader) so that I can emit multiple CSS bundle files (one per theme). The multi loader only accepts query string style loader parameters. So I used the [combine-loaders](https://www.npmjs.com/package/webpack-combine-loaders) to stringify the output from ETWP. However when I do this the CSS bundle file is not emitted.
I have simplified my config - removing SASS and PostCSS etc leaving the following to isolate the issue
````
const extractTheme1 = new ExtractTextPlugin('theme1.css');
const extractLoader1 = extractTheme1.extract([
    {loader: 'css-loader'}
]);
const theme1Combined = combineLoaders(
    extractLoader1
);

module.exports = {
    entry: path.resolve('src/index.js'),
    output: {
        filename: "[name].js",
        path: path.resolve("dist")
    },
    module: {
        //rules: [{ test: /\.css$/, loader: theme1Combined}]  // LINE XXX
        rules: [{ test: /\.css$/, loader: extractLoader1}]   // LINE YYY
    },
    plugins: [
        extractTheme1
    ]
};
````
When I run the code as shown - the output of ETWP is use directly, everything is OK and the CSS bundle is written to `/dist/theme1.css`
When I run combineLoaders on the output of the extract() function ( uncommenting line XXX and removing line YYY) then the CSS bundle file is no longer written.
For fully working project see the [repo](https://github.com/james-s-turner/webpack-mult-theme)

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
