### ISSUE TITLE
invalid set options.filename 

### ISSUE THREAD

**Issue by JX-Zhuang** [webpack-contrib/extract-text-webpack-plugin#756]
why style'name is "index"
![7da2b6f0-b493-49a8-b86b-a7dc7bbd46d5](https://user-images.githubusercontent.com/8744030/37662224-90355c68-2c91-11e8-8f97-1d5aacfbf47d.png)

**Comment by JX-Zhuang** [comment]
why name is index

**Comment by michael-ciniawsky** [comment]
Because your `entry` is named `index.js` and that's what `[name]` placeholder will resolve to (per chunk) :). The CSS filenames are 'ignored'.

**Comment by JX-Zhuang** [comment]
Thx,I want  [name] is the CSS filenames,how can i do.

**Comment by michael-ciniawsky** [comment]
Explicitly choose a file name for each CSS bundle

```js
const bundle = {
  css: 'public/foo.[contenthash:8].css',
  less: 'public/bar.[contenthash:8].css',
  scss: 'public/baz.[contenthash:8].css'
}

const css = new ExtractTextPlugin(`${bundle.css}`)
const less = new ExtractTextPlugin(`${bundle.less}`)
const scss = new ExtractTextPlugin(`${bundle.scss}`)
```

The `[module]` placeholder **isn't** available for ETWP to my knowledge, but you can try :)

```js
const css = new ExtractTextPlugin('public/[module].[contenthash:8].css')
```

**Comment by JX-Zhuang** [comment]
Thx  :)
