### ISSUE TITLE
The use of webpack's splitChunks feature causes ExtractTextPlugin to not output css properly

### ISSUE THREAD

**Issue by fixterer** [webpack-contrib/extract-text-webpack-plugin#758]
webpack: `^4.1.1`
extract-text-webpack-plugin: `^4.0.0-beta.0`

My webpack config
```javascript
// ...
optimization: {
        splitChunks: {
            cacheGroups: {
                commons: {
                    // test: /[\\/]node_modules[\\/]/,
                    name: 'react',
                    chunks: 'all'
                }
            }
        }
    },
plugins: [
     ...htmls,
    new ExtractTextPlugin('style/[name].[chunkhash:8].css')
]
```
If I do not use splitChunks independent react then outpu
```
index.css
home.css
```
Output after use
```
react.css
```
I want to know why this is so, I can't find explanation about this on the internet.

**Comment by Shafley** [comment]
I have the same problem with set options `allChunk: true`

**Comment by fixterer** [comment]
```javascript
new ExtractTextPlugin('style/[name].[chunkhash:8].css', {
    allChunks: true
})
```
@Shafley 
Thanks, but this property has no effect

**Comment by Shafley** [comment]
@fixterer  I mean if I set `allChunks: true`, `ExtractTextPlugin ` just split  css from my `.less` files,  and lost `css` from `antd-design`, if I set `allChunks: false`, the `css` from `antd-design` are injected into html with style tag

**Comment by evilebottnawi** [comment]
Please don't use `extract-text-webpack-plugin` for extract `css` for `webpack@4`, use https://github.com/webpack-contrib/mini-css-extract-plugin, in near future we will update README. Thanks!
