### ISSUE TITLE
Error: Path variable [contenthash] not implemented in this context: style/[name].[contenthash].css

### ISSUE THREAD

**Issue by moorthy-g** [webpack-contrib/extract-text-webpack-plugin#763]
I get the following error after webpack upgrade (4.3.0)
`Error: Path variable [contenthash] not implemented in this context: style/[name].[contenthash].css`

My plugin config is
```js
new ExtractTextWebpackPlugin({
    filename: 'style/[name].[contenthash].css'
})
```
extract-text-webpack-plugin's version is 4.0.0-beta.0.

Its working good with webpack 4.1.0 though.

**Comment by Alorel** [comment]
This appears to be a conflict with webpack 4.3 which introduced a `[contenthash]` variable of its own: https://github.com/webpack/webpack/releases/tag/v4.3.0

**Comment by esausilva** [comment]
I just upgraded to Webpack 4.3 and got the same error. I hope this gets fixed, but for the moment I changed `[contenthash]` to `[hash]` to get it working again.

**Comment by evilebottnawi** [comment]
Please use https://github.com/webpack-contrib/mini-css-extract-plugin for extract css for `webpack@4`

**Comment by esausilva** [comment]
@evilebottnawi Thanks. I will give it a try once it supports HMR

**Comment by Bessonov** [comment]
@evilebottnawi does it mean that extract-text-webpack-plugin is deprecated at least for css?

**Comment by evilebottnawi** [comment]
@Bessonov yes, future `ETWP` is only extracted content without features like `ordering`, `code splitting`, `tree shaking`, `purifying` or other specific action for each type of assets (i.e. `css`/`html`/etc). Just extract. Thanks!

**Comment by gmincof** [comment]
A temporary solution that you can use until it's fixed, is to replace `[contenthash]` with something like `[md5:contenthash:hex:20]`.

**Comment by ajoslin103** [comment]
@gmincof where would I do this in my webpack.config.js ?

**Comment by jalmansa88** [comment]
I still have this error. I ran `npm install mini-css-extract-plugin@latest --save` and still hapenning when au build --env prod`. Only doing the change `[md5:contenthash:hex:20]` fixed the error.

**Comment by DavOnGit** [comment]
@esausilva  You can check ```extract-css-chunks-webpack-plugin``` it supports HMR!

**Comment by ChhXin** [comment]
> I just upgraded to Webpack 4.3 and got the same error. I hope this gets fixed, but for the moment I changed `[contenthash]` to `[hash]` to get it working again.

thanks,resolved

**Comment by prog1dev** [comment]
> @evilebottnawi Thanks. I will give it a try once it supports HMR

Why would you use `extract-text-webpack-plugin` in development?

You dont need HMR in production so switching to https://github.com/webpack-contrib/mini-css-extract-plugin is okay
