### ISSUE TITLE
No output file when maxChunks: 1

### ISSUE THREAD

**Issue by Diokuz** [webpack-contrib/extract-text-webpack-plugin#767]
I tried to migrate to `webpack@4`, so I had to upgrade `extract-text-webpack-plugin` to `^4.0.0-beta.0`. Now it fails to create any css files when I use

```
new webpack.optimize.LimitChunkCountPlugin({
  maxChunks: 1,
}),
```

I need that to create one single server side js bundle (+ one single css file).

**Comment by evilebottnawi** [comment]
@Diokuz Don't use `ETWP` for extract `css`. For `css` just use https://github.com/webpack-contrib/mini-css-extract-plugin. Thanks!
