### ISSUE TITLE
Entrypoint undefined = extract-text-webpack-plugin-output-filename

### ISSUE THREAD

**Issue by bspatil0001** [webpack-contrib/extract-text-webpack-plugin#770]
Here is the test repo https://github.com/bspatil0001/extract-text-webpack-plugin-test.git

I am trying to generate .css from .scss but it is giving undefined Entrypoint.

Can anyone help me on this?

Thank you

**Comment by evilebottnawi** [comment]
@bspatil0001 Don't use `ETWP` for extract css. Please use for this purpose https://github.com/webpack-contrib/mini-css-extract-plugin. Thanks!
