### ISSUE TITLE
[4.0.0-beta.0] There is no parsing for the correct style for css modules.

### ISSUE THREAD

**Issue by hopefuture** [webpack-contrib/extract-text-webpack-plugin#776]
When I use 4.0.0-beta.0 and webpack 4.5.0, The generated css is js format.
The following is the code snippet.

module.exports = exports['default'];:root{--font-size-base:.875rem;--theme-primary:#2196f3;--theme-secondary:#e040fb;--theme-background:#fff;--theme-primary-light:#64b5f6;--theme-secondary-light:#ea80fc;--theme-primary-lighter:#bbdefb;--theme-secondary-lighter:#e1bee7;--theme-primary-lightest:#e3f2fd;--theme-secondary-lightest:#f3e5f5;--theme-primary-dark:#1976d2;--theme-secondary-dark:#d500f9;--theme-primary-darker:#1565c0;--theme-secondary-darker:#a0f;--theme-primary-darkest:#0d47a1;--theme-secondary-darkest:#4a148c;

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
