### ISSUE TITLE
Module build failed: Error: write EOFat exports._errnoException at WriteWrap.afterWrite 

### ISSUE THREAD

**Issue by wxl035446** [webpack-contrib/extract-text-webpack-plugin#779]
"webpack": "^4.4.1",   "extract-text-webpack-plugin": "2.1.0",
// index.js
import './index.less';

.app-wrapper{
   position: absolute;
   top:0px;
   left: 0px;
   width:100% ;
   height:100%;
   z-index:10;
   background-image: url(./assets/images/bg.jpg);
   background-size: cover;
}

webpack.config.js  less config
 {test: /\.less/,
              exclude:  /^node_modules$/,
              use: extractLESS.extract({
                fallback: "style-loader",
                use: [
                  { loader: 'css-loader', options: { importLoaders: 1 }},
                  {
                    loader: 'postcss-loader',
                    options: {
                      plugins: function () {
                        return [
                          require('autoprefixer')
                        ]
                      }
                    }
                  },
                  {loader: 'less-loader'}
                ]
              }),
            },

![111](https://user-images.githubusercontent.com/19813104/39036368-c77604d0-44af-11e8-958e-d287176589ae.png)
![222](https://user-images.githubusercontent.com/19813104/39036396-e799ca94-44af-11e8-80ca-31d764faaa58.png)

**Comment by blemaire** [comment]
I believe you need to use extract-text-webpack-plugin v4.0.0-beta.0 if you want to use Webpack 4

**Comment by wxl035446** [comment]
I use is extract-text-webpack-plugin v4.0.0-beta.0， That's the mistake.




------------------ 原始邮件 ------------------
发件人: "Bastien Lemaire"<notifications@github.com>;
发送时间: 2018年4月20日(星期五) 下午4:39
收件人: "webpack-contrib/extract-text-webpack-plugin"<extract-text-webpack-plugin@noreply.github.com>;
抄送: "Traveling Light"<1129565996@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [webpack-contrib/extract-text-webpack-plugin] Module buildfailed: Error: write EOFat exports._errnoException at WriteWrap.afterWrite(#779)




I believe you need to use extract-text-webpack-plugin v4.0.0-beta.0 if you want to use Webpack 4

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
