### ISSUE TITLE
include sub-page css in shared css

### ISSUE THREAD

**Issue by haf** [webpack-contrib/extract-text-webpack-plugin#78]
In a project like:

```
.
├── main.css
├── main.js
├── subpage.css
├── subpage.js
└── webpack-config.js

0 directories, 5 files
```

With these contents:

```
/* main.css */
body { background: black; }


// main.js
require('main.css') // this works


/* subpage.css */
.test { display: block; }


// subpage.js
require('subpage.css'); // this doesn't work

...

module.exports = SubPage;


// webpack-config.js
var ExtractTextPlugin = require("extract-text-webpack-plugin"),¬

// snip
//
    entry: {
      './js/main': './js/main', // start page
      // & one more
    }

//snip
//

    loaders: [
      { test: /\.css$/, loader: ExtractTextPlugin.extract("style-loader", "css-loader") },

// snip
//

  plugins: [
    new ExtractTextPlugin("./styles.css"),
    new webpack.optimize.CommonsChunkPlugin('./js/commons.js', ['main', 'one_more'])
  ]
```

It seems that styles.css only contains the contents from main.css, and not from subpage.css. Is this a bug?

This worked with webpack 1.9.10 & extract 0.8.1, but not with webpack 1.9.11 and 0.8.2. Extract 0.8.2 doesn't compile with webpack 1.9.10.

**Comment by sokra** [comment]
Try `new ExtractTextPlugin("[name].css")`. Because ExtractTextPlugin will emit multiple stylesheets. One for each entry and one for the commons chunk.

**Comment by haf** [comment]
That does include all text, however, it doesn't follow the naming standard. Instead of outputting `./main.css` it outputs `././js/main.css`... This is what my output config looks like:

```
  1     output: {¬
  2       path: path.resolve(__dirname, '..', '..', 'build'),
  3       filename: '[name].js',
  4       sourceMapFilename: '[file].map',
  5       chunkFilename: "[id].js"
  6     },¬
```

And output:

```
snip
                      ././js/main.css    12.6 kB    0, 2  [emitted]  ./js/main
                    ././js/one_more.css    12.5 kB    1, 2  [emitted]  ./js/one_more
                     ./js/main.js.map     559 kB    0, 2  [emitted]  ./js/main
snip
```

**Comment by sokra** [comment]
`[name]` is the key of the `entry` option key-value-pair. So `entry: { "./js/index": "..." }` is wrong. Use `entry: { "index": "..." }` with `output: { filename: "js/[name].js" }` instead.

**Comment by bebraw** [comment]
Answered. Closing.
