### ISSUE TITLE
Add some kind of deprecation notice for webpack >= 4

### ISSUE THREAD

**Issue by mnquintana** [webpack-contrib/extract-text-webpack-plugin#782]
I had to do some ~Googling~ digging to find: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/701#issuecomment-374551300

Since extract-text-webpack-plugin's been superseded by https://github.com/webpack-contrib/mini-css-extract-plugin, would you mind updating the readme with a deprecation notice pointing at the new plugin? I'd love to save future users the pain of finding out the hard way that this plugin won't be updated with webpack 4 support.

Thanks so much for all your hard work on these plugins, though! 💖

**Comment by Almo7aya** [comment]
Thanks, you saved me 😆

**Comment by PJCHENder** [comment]
Thanks, you saved me too 😆

**Comment by alexdevero** [comment]
There should be some info about depreciation in the readme. It's been a while since release of Webpack 4 and still nothing. There is even a PR for that.

**Comment by rodgerer** [comment]
It turns out so.

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
