### ISSUE TITLE
[4.0.0-beta.0] Module build failed: Error: Didn't get a result from child compile

### ISSUE THREAD

**Issue by vasivas** [webpack-contrib/extract-text-webpack-plugin#786]
> ERROR in ./app/app.css
> Module build failed: Error: Didn't get a result from child compiler
>     at childCompiler.runAsChild (/home/ivan/projects/extract-text-webpack-plugin-bug-demo/node_modules/extract-text-webpack-plugin/dist/loader.js:136:25)
>     at compile (/home/ivan/projects/extract-text-webpack-plugin-bug-demo/node_modules/webpack/lib/Compiler.js:242:11)
>     at hooks.afterCompile.callAsync.err (/home/ivan/projects/extract-text-webpack-plugin-bug-demo/node_modules/webpack/lib/Compiler.js:487:14)
>     at _err1 (eval at create (/home/ivan/projects/extract-text-webpack-plugin-bug-demo/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:29:1)
>     at /home/ivan/projects/extract-text-webpack-plugin-bug-demo/node_modules/awesome-typescript-loader/src/instance.ts:448:4
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/ivan/projects/extract-text-webpack-plugin-bug-demo/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:16:1)
>     at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/home/ivan/projects/extract-text-webpack-plugin-bug-demo/node_modules/tapable/lib/Hook.js:35:21)
>     at compilation.seal.err (/home/ivan/projects/extract-text-webpack-plugin-bug-demo/node_modules/webpack/lib/Compiler.js:484:30)
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/ivan/projects/extract-text-webpack-plugin-bug-demo/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
>     at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/home/ivan/projects/extract-text-webpack-plugin-bug-demo/node_modules/tapable/lib/Hook.js:35:21)
>  @ ./app/App.tsx 1:0-19
>  @ ./client/client.tsx
>  @ multi webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000&reload=false&quiet=false&noInfo=false react-hot-loader/patch ./client/client.tsx

https://github.com/vasivas/extract-text-webpack-plugin-bug-demo

**Comment by evilebottnawi** [comment]
@vasivas don't use `extract-text-webpack-plugin` for extract css, please use https://github.com/webpack-contrib/mini-css-extract-plugin

**Comment by vasivas** [comment]
@evilebottnawi there identical error https://github.com/webpack-contrib/mini-css-extract-plugin/issues/126

**Comment by evilebottnawi** [comment]
@vasivas will be solved in near future
