### ISSUE TITLE
Invalid CSS after "...load the styles": expected 1 selector or at-rule, was "var content = requi"

### ISSUE THREAD

**Issue by dvfgit** [webpack-contrib/extract-text-webpack-plugin#787]
Hi guys I' ve been trying to workout this issue for several times... each person has a different thing to say about it... but for some reason haven't found a simple understanding on what is the issue

```
ERROR in ./~/css-loader!./~/sass-loader/lib/loader.js!./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/style-loader!./~/css-loader!./~/sass-loader/lib/loader.js!./src/index.scss
Module build failed: 
.todoapp{
^
      Invalid CSS after "...load the styles": expected 1 selector or at-rule, was "var content = requi"
      in /Users/df/Documents/my_apps_yo/personal_page/src/index.scss (line 1, column 1)
 @ ./~/style-loader!./~/css-loader!./~/sass-loader/lib/loader.js!./src/index.scss 4:14-297
 @ ./src/index.js
```

My config is such as in the readme sass section in extractText pluggin
INFO:
"webpack": "^2.2.1",
"extract-text-webpack-plugin": "^2.0.0-rc.3",
I used the yeoman Foutain webapp to scaffold the app

Config in for webpac-dist is
`      {
        test: /\.(css|scss)$/,
        loaders: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: ['css-loader', 'sass-loader']
        })
      },`
Please any inputs

**Comment by swatigoel1991** [comment]
I am facing the same issue

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
