### ISSUE TITLE
loader is used without the corresponding plugin

### ISSUE THREAD

**Issue by zdrummond** [webpack-contrib/extract-text-webpack-plugin#789]
This is an issue between a project issue and support issue, so not sure if you want it here or StackOverflow. 

We are using;
`node 6.14`
`npm 3.9.3`
`extract-text-webpack-plugin 3.0.2`
`hard-source-webpack-plugin: 0.5.18`
`rails 4.2.2 with webpacker 3.0.2`
`storybook 3.3.15`

---
Ok, so as you can kind of see from above, we are using Rails with Webpacker and storybook. Webpacker uses extract-text-webpack, but so does Storybook. Here is where things get odd. 

If we install hard-source-webpack-plugin, if we do *not* explicitly add extract-text-webpack to package.json, then hard source will not recompile CSS on subsequent builds.

BUT 

If we include extract-text-webpack, then storybook will error with 

```Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example```

I know this is a lot of moving pieces, and I don't have a small project repro for you. However, I was hoping you could give me insight to the above error. If I jump into extract-text code, this is the line that is complaining 

https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/cc3ba946ef4066264410737ce5bd43d0c7d724f1/src/loader.js#L20

What does it mean by 
> // We already in child compiler, return empty bundle

and any ideas why Storybook would be causing it to get into this state?

Thanks!

**Comment by evilebottnawi** [comment]
@zdrummond what version of webpack you use?

**Comment by zdrummond** [comment]
I guess that was the one version I didn’t list :)

3.6.0

On May 25, 2018, 4:00 AM -0700, Evilebot Tnawi <notifications@github.com>, wrote:

@zdrummond<https://github.com/zdrummond> what version of webpack you use?

**Comment by evilebottnawi** [comment]
@zdrummond to be honestly, `extract-text-webpack-plugin` is bad for extract `css` and have a lot of problems :disappointed: Better upgrade you `webpack` to `4` version and use https://github.com/webpack-contrib/mini-css-extract-plugin.

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
