### ISSUE TITLE
Purify(CSS)!

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack-contrib/extract-text-webpack-plugin#79]
I'd like to propose an update to this module to run the output CSS through [PurifyCSS](https://github.com/purifycss/purifycss).

For that, the plugin's construction would take an additional parameter that represents the view files.

That way, we could "strip" the CSS of unused stuff! That, IMHO, would be very, very useful.

Kind regards, Ingwie.

**Comment by blainekasten** [comment]
That sounds like something that should be opted-in in user land via the webpack config. This plugin isn't necassarily tied to css. It's just extracting text.

**Comment by bebraw** [comment]
[purifycss-webpack](https://github.com/webpack-contrib/purifycss-webpack) works well after etwp. No need to have the functionality here.
