### ISSUE TITLE
in extract add url loader invaild 

### ISSUE THREAD

**Issue by gun321654** [webpack-contrib/extract-text-webpack-plugin#791]
I cant add relative path in  production environment ,  I need 

**
background:url(/images/xxx.jpg)
to
background:url:(../../static/images/xxx.jpg)
**
I tred many time  ,  change webpack setting  :css-loader ,  file-loader  ,url-loader ,but invaild  .

previous version  is  true  ，I don't understand what the new version brings

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
