### ISSUE TITLE
Unable to generate css bundle with LimitChunkCountPlugin maxLimit=1

### ISSUE THREAD

**Issue by sumanla13a** [webpack-contrib/extract-text-webpack-plugin#792]
`Node: 8.9.1`
`OS: Ubuntu`

I was using dynamic import in order to create multiple chunks for my javascripts but now I have to disable chunks for some time.
So I added `maxChunks` option to 1 for LimitChunkCountPlugin.

Now everytime I build, the app doesn't create the css bundle, created by extract-text-webpack-plugin.

With `maxChunks=2`, it creates the css bundle.
Am I doing something wrong?

Minimal reproduction is in the link below.
https://github.com/sumanla13a/extract-text-plugin-reproduction

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
