### ISSUE TITLE
Module parse failed:

### ISSUE THREAD

**Issue by AGunnels** [webpack-contrib/extract-text-webpack-plugin#793]
I am working on merging an old, but working react-redux project into a new project. The goal was to use what was already completed and build off of it in a group of 4 developers. I, for the life of me, cannot figure out the latest error message and how to fix it. The others are also stumped. Any help would be greatly, greatly appreciated 👍 Here is the error:                                                                                                                          
./node_modules/react-redux/src/components/connectAdvanced.js
Module parse failed: Unexpected token (242:29)
You may need an appropriate loader to handle this file type.
|         // instance. a singleton memoized selector would then be holding a reference to the
|         // instance, preventing the instance from being garbage collected, and that would be bad
|         const withExtras = { ...props }
|         if (withRef) withExtras.ref = this.setWrappedInstance
|         if (renderCountProp) withExtras[renderCountProp] = this.renderCount++

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
