### ISSUE TITLE
Write the CSS file but do not inject into the HTML

### ISSUE THREAD

**Issue by merolhack** [webpack-contrib/extract-text-webpack-plugin#795]
Versions:
- html-webpack-plugin: 2.28.0
- webpack: 2.6.1

I need to write the CSS file to the dist directory, but i do not want include them into the HTML file? How can i do that?

My application is growing up and i need to load the CSS files dynamically with Javascript.

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
