### ISSUE TITLE
ERROR in ./src/css/index.css (./node_modules/css-loader!./node_modules/extract-text-webpack-plugin/dist/loader.js??ref--6-0!./node_modules/style-loader!./node_modules/css-loader!./src/css/index.css) Module build failed (from ./node_modules/css-loader/index.js):

### ISSUE THREAD

**Issue by antiai1** [webpack-contrib/extract-text-webpack-plugin#796]
ERROR in ./src/css/index.css (./node_modules/css-loader!./node_modules/extract-text-webpack-plugin/dist/loader.js??ref--6-0!./node_modules/style-loader!./node_modules/css-loader!./src/css/index.css)
Module build failed (from ./node_modules/css-loader/index.js):
Unknown word (1:1)

> 1 | // removed by extract-text-webpack-plugin
    | ^

 @ ./src/css/index.css (./node_modules/css-loader!./node_modules/extract-text-webpack-plugin/dist/loader.js??ref--6-0!./node_modules/style-loader!./node_modules/css-loader!./src/css/index.css)

ERROR in ./src/css/index.css (./node_modules/css-loader!./node_modules/extract-text-webpack-plugin/dist/loader.js??ref--6-0!./node_modules/style-loader!./node_modules/css-loader!./src/css/index.css)
Module build failed (from ./node_modules/css-loader/index.js):
Unknown word (2:1)

  1 |
> 2 | var content = require("!!../../node_modules/css-loader/index.js!./index.css");
    | ^
  3 |
  4 | if(typeof content === 'string') content = [[module.id, content, '']];
  5 |

 @ ./src/css/index.css 2:14-229
 @ ./src/main.js

**Comment by antiai1** [comment]
what should i do？

**Comment by cyssxt** [comment]
I have the same error

**Comment by evilebottnawi** [comment]
Please use https://github.com/webpack-contrib/mini-css-extract-plugin/

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
