### ISSUE TITLE
 options['extractCSS'] is an invalid

### ISSUE THREAD

**Issue by Harismp** [webpack-contrib/extract-text-webpack-plugin#798]
ValidationError: Dll Reference Plugin Invalid Options  options['extractCSS'] is an invalid additional property `const path = require('path');
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
var OptimizeCSSPlugin = require('optimize-css-assets-webpack-plugin');
const bundleOutputDir = './wwwroot/dist';

module.exports = (env) => {
    const extractCSS = new ExtractTextPlugin('site.css');
    const isDevBuild = !(env && env.prod);
    return [{
        stats: { modules: false },
        entry: { 'main': './ClientApp/boot-app.js' },
        resolve: {
            extensions: ['.js', '.vue'],
            alias: {
                'vue$': 'vue/dist/vue',
                'components': path.resolve(__dirname, './ClientApp/components'),
                'views': path.resolve(__dirname, './ClientApp/views'),
                'utils': path.resolve(__dirname, './ClientApp/utils'),
                'api': path.resolve(__dirname, './ClientApp/store/api')
            }
        },
        output: {
            path: path.join(__dirname, bundleOutputDir),
            filename: '[name].js',
            publicPath: '/dist/'
        },
        module: {
              loaders: [
                    
                  { test: /\.vue$/, include: /ClientApp/, use: 'vue-loader' },
                  { test: /\.js$/, include: /ClientApp/, use: 'babel-loader' },
                  {
                    test: /\.css$/, use: ExtractTextPlugin.extract({
                      fallback: "style-loader",
                      load: "css-loader"
                    })
                  },
                  //{ test: /\.css$/, use: isDevBuild ? ['style-loader', 'css-loader'] : ExtractTextPlugin.extract({ use: 'css-loader' }) },
                  // { test: /\.css/,loader: ExtractTextPlugin.extract("css-loader") },
                  //{ test: /\.(png|jpg|jpeg|gif|svg)$/, use: 'url-loader?limit=25000' },
                  { test: /\.(png|jpg|jpeg|gif|svg|woff|woff2|eot|ttf|svg)(\?|$)/, use: 'url-loader?limit=100000' },                     
               ]   
        },
        plugins: [
            new webpack.DllReferencePlugin({
                context: __dirname,
                extractCSS,
                manifest: require('./wwwroot/dist/vendor-manifest.json')
            })
        ].concat(isDevBuild ? [
            // Plugins that apply in development builds only
            new webpack.SourceMapDevToolPlugin({
                filename: '[file].map', // Remove this line if you prefer inline source maps
                moduleFilenameTemplate: path.relative(bundleOutputDir, '[resourcePath]') // Point sourcemap entries to the original file locations on disk
            }),
            new webpack.ProvidePlugin({
                $: 'jquery',
                jquery: 'jquery',
                'window.jQuery': 'jquery',
                jQuery: 'jquery'
            }),
            new ExtractTextPlugin('site.css')

        ] : [
                // Plugins that apply in production builds only
                new webpack.ProvidePlugin({
                    $: 'jquery',
                    jquery: 'jquery',
                    'window.jQuery': 'jquery',
                    jQuery: 'jquery'
                }),
                new webpack.optimize.UglifyJsPlugin(),
                new ExtractTextPlugin('site.css')
            ])
    }];
};`

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
