### ISSUE TITLE
ERROR in Module build failed: TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by manojcena** [webpack-contrib/extract-text-webpack-plugin#799]
Hi ,

I am building a application using angular 6. Every things works fine and when i regenerate build using ng build every thing is fine But when i generate ng-build --prod --aot i am getting error. please look at attachemnet. 

![capture](https://user-images.githubusercontent.com/15008735/43672554-04a849dc-97ce-11e8-9f08-c1a070bdf673.PNG)

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
