### ISSUE TITLE
 Add custom css for "react dropdown tree select" all other css mashup

### ISSUE THREAD

**Issue by xporium** [webpack-contrib/extract-text-webpack-plugin#800]
in my project i has install dropdown tree select and use custom css for this. but if i add new rule in my webpack than this plugin working fine but other css mashup.

And if i remove rule than other css working fine but this dropdown tree select not working proper.

working like same

react dropdown tree select with country flag so in that case i have to add some custom css.

below is my webpack. so can you tell me which rule i have to add/remove in my webpack.

{ test: /.css$/, use: ExtractTextPlugin.extract({ fallback: 'style-loader', use: [ { loader: 'css-loader' } ] }), include: /node_modules[/\]react-dropdown-tree-select/ },

      // "postcss" loader applies autoprefixer to our CSS.
      // "css" loader resolves paths in CSS and adds assets as dependencies.
      // "style" loader turns CSS into JS modules that inject <style> tags.
      // In production, we use a plugin to extract that CSS to a file, but
      // in development "style" loader enables hot editing of CSS.
      {
        test: /\.css$/,
        use: [
          require.resolve('style-loader'),
          {
            loader: require.resolve('css-loader'),
            options: {
              importLoaders: 1,
              modules:true,
              localIdentName:'[Name]__[local]__[has:base64:5]'
            },
          },
          {
            loader: require.resolve('postcss-loader'),
            options: {
              // Necessary for external CSS imports to work
              // https://github.com/facebookincubator/create-react-app/issues/2677
              ident: 'postcss',
              plugins: () => [
                require('postcss-flexbugs-fixes'),
                autoprefixer({
                  browsers: [
                    '>1%',
                    'last 4 versions',
                    'Firefox ESR',
                    'not ie < 9', // React doesn't support IE8 anyway
                  ],
                  flexbox: 'no-2009',
                }),
              ],
            },
          },
        ],
      }, 
plugins: [ new ExtractTextPlugin("styles.css"),

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
