### ISSUE TITLE
remove neo-async

### ISSUE THREAD

**Issue by jimmywarting** [webpack-contrib/extract-text-webpack-plugin#803]
You only use one function from neo-async (async.forEach) at two places

https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/e1e65405c8c1dc2b4efb94f087d69f894afcfd35/src/index.js#L144-L148

It adds 37.7 kB to the bundled size
https://bundlephobia.com/result?p=neo-async@2.5.2

I'm sure you can think of any other way to solve it, maybe with Promise + Promise.all...

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
