### ISSUE TITLE
Newbie question. Sorry for my ignorance. How do I uninstall?

### ISSUE THREAD

**Issue by jcklpe** [webpack-contrib/extract-text-webpack-plugin#806]
I know this is a really basic question, I am new to webpack and I've tried searching this but I can't seem to find a straight forward answer to this problem. 

I try running `npm uninstall --save-dev extract-text-webpack-plugin` and I get this error:
```
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "extract-text-webpack-plugin@next": name can only contain URL-friendly characters

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/david/.npm/_logs/2018-09-17T21_50_12_998Z-debug.log
```

I installed the @next version after reading that it was necessary to run in Webpack 4. But after installing I encountered some errors and since the README indicates that I should use a different plugin, I figured that would be best. But in the interests of not having a bunch of code hanging around that's not being used I wanted to uninstall it. 

When I search this error and "uninstall" I get a bunch of people getting this error with npm init and with installs etc, but no uninstalls. 

I know this is a pretty broad question, and not specific to this plugin but I was hoping someone could help as I am new to webpack and npm and not sure where else to check. I looked at the npm uninstall documentation and didn't see any mention of how to deal with these kinds of issues. I'm guessing it's the "@" symbol that is considered not a proper url etc.

**Comment by lmenus** [comment]
Can you show the relevant line(s) from your `package.json`?

**Comment by jcklpe** [comment]
I don't remember how I fixed this issue but I ended up fixing it. Thanks anyway!
