### ISSUE TITLE
Sourcemaps are not linked

### ISSUE THREAD

**Issue by antpaw** [webpack-contrib/extract-text-webpack-plugin#808]
version:  "4.0.0-beta.0"

This setup will not append the `sourceMappingURL`

    devtool: 'source-map',
    module: {
      rules: [
        {test: /\.(sass|scss)$/, loader: cssExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            {
              loader: 'css-loader',
              options: {
                sourceMap: true,
              },
            },
            {
              loader: 'sass-loader',
              options: {
                sourceMap: true,
              },
            }
          ],
        })},

i did this workaround to get sourcemaps

    plugins: new webpack.SourceMapDevToolPlugin({}),
    devtool: false,
    module: {
      rules: [
        {test: /\.(sass|scss)$/, loader: cssExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            {
              loader: 'css-loader',
              options: {
                sourceMap: true,
              },
            },
            {
              loader: 'sass-loader',
              options: {
                sourceMap: true,
              },
            }
          ],
        })},

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
