### ISSUE TITLE
How to use this plugin and minify SCSS to CSS?

### ISSUE THREAD

**Issue by hrahimi270** [webpack-contrib/extract-text-webpack-plugin#809]
I'll be glad to help using this plugin and make my SCSS files to one minified CSS file. Thanks.

**Comment by evilebottnawi** [comment]
Please use https://github.com/intervolga/optimize-cssnano-plugin plugin, need documentation

**Comment by AlvMF1** [comment]
With https://github.com/webpack-contrib/sass-loader and...
```js
{
  test: /\.scss$/,
  use: ExtractTextPlugin.extract({
    use: [{
      loader: 'sass-loader',
      options: { minimize: true }
    }]
  })
}
```
...works pretty well for me.

**Comment by jayarjo** [comment]
@AlvMF1 are you sure that that's what minimizes it for you? `sass-loader` doesn't seem to have an option `minimize`.

**Comment by AlvMF1** [comment]
`sass-loader` does not. But `extract-text-webpack-plugin` does. No? All I know is that I get a minified CSS. 😄

**Comment by evilebottnawi** [comment]
@AlvMF1 `minimize` option for old `css-loader` and was remove in 2 version

**Comment by webdev20** [comment]
> 
> 
> `sass-loader` does not. But `extract-text-webpack-plugin` does. No? All I know is that I get a minified CSS. 😄

yes, it does!

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
