### ISSUE TITLE
CSS file not generated 

### ISSUE THREAD

**Issue by amit-kumar27** [webpack-contrib/extract-text-webpack-plugin#810]
With extract-text-webpack-plugin@3.0.2 and webpack@3.11.0, I have created an angular-5 and angular-cli based project, I am not able generate the required css. Also it's not showing any error and not able to understand what configuration I missed.
Already referred the previous similar issues, but couldn't resolve it.

Please refer the sample app I have created, which can reproduce the issue:-
[sample-app](https://github.com/amit-kumar27/sample_app_ng5)

**Comment by jiadabaihua** [comment]
I have the same question ~

**Comment by xyxuyao** [comment]
I have the same question ~

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
