### ISSUE TITLE
Stats/debug log could be improved

### ISSUE THREAD

**Issue by ericmuyser** [webpack-contrib/extract-text-webpack-plugin#817]
Hey guys,

Every once and a while I'll get a bug building for production and this plugin seems to be the culprit but I never get details about the error. Can you make it log stack traces or some relevant info?

For example this error:

```
(node:596) UnhandledPromiseRejectionWarning: CssSyntaxError: /ude/hb/projects/blockhub-delta/clients/web/static/css/app.dfaaff76999d6e821f1e.css:9:2: Unknown word
(node:596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:596) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

What file did it encounter an "unknown word" - I have no clue, I searched and searched, tried all sorts of verbosity settings, and still can't figure it out, so I'll have to go through the git commits until I find the offender.

Thoughts?

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
