### ISSUE TITLE
CSS is extracted from Dynamically loaded chunks, but not injected in page by the fallback loader

### ISSUE THREAD

**Issue by Abdelhady** [webpack-contrib/extract-text-webpack-plugin#818]
**webpack:** 3.12.0
**node:** 10.0.0
**OS:** Ubuntu 16.04
**Repo for showing the issue:** https://github.com/abdelhady/extract-text-webpack-plugin-dynamic-chunk-issue

For multiple entries, when a css file is being required in an entry, then being imported dynamically in a second entry (with setting the option `allChunks: false`), this second entry will not contain that css !

Further details are in the repo itself

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
