### ISSUE TITLE
Removes Required CSS

### ISSUE THREAD

**Issue by hdrabs** [webpack-contrib/extract-text-webpack-plugin#819]
[Removes needed css #670](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/670)

I have asked a question on this closed issue. I am having the same issue and also the plugin used there (PurifyCSS) is not used in my project. Can you please help me on this?

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
