### ISSUE TITLE
Not able to run karma getting errors related to ```extract-text-webpack-plugin```

### ISSUE THREAD

**Issue by sunilb0575** [webpack-contrib/extract-text-webpack-plugin#821]
please help me with this.
https://stackoverflow.com/questions/54524743/not-able-to-run-karma-getting-errors-related-to-extract-text-webpack-plugin

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
