### ISSUE TITLE
4.0.0-beta for a year+ - is this a dead project?

### ISSUE THREAD

**Issue by Muqluk** [webpack-contrib/extract-text-webpack-plugin#822]
as the subject line says, on the latest/beta for over a year now.  Is this project still maintained or should I seek another solution for production use?

**Comment by evilebottnawi** [comment]
Yes it is dead, please use mini css extract plugin

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
