### ISSUE TITLE
I've also got this issue: Module parse failed: Unexpected character '#' (17:0);

### ISSUE THREAD

**Issue by StellaYangF** [webpack-contrib/extract-text-webpack-plugin#823]

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin

**Comment by StellaYangF** [comment]
Thanks a lot. This issue was solved by revising the webpack.config.js. 
Here are the details:
const config = {
  module: {
    rules: [
      { 
	test: /\.styl/, 
	use: ExtractPlugin.extract({
	  fallback : 'style-loader',
	  use: [
	    'css-loader',
	    {
	      loader: 'postcss-loader',
	      options:{
		sourceMap : true,      
	      }
	    },
	    'stylus-loader'
	  ]
	})
       }
    ]
  }
};

module.exports = config;
