### ISSUE TITLE
Postprocess the output

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack-contrib/extract-text-webpack-plugin#85]
I just realized, that when using PostCSS-loader, I am not getting the expected results. I have initialized the postcss-loader with a "merge-rules" plugin. But my filesize is not changing, like, not a single byte. That only tells me that it is not yielding the expected results.

In general it would be great to run something over the finalized CSS as a "postprocessor". Could this be added?

**Comment by lepture** [comment]
+1

**Comment by IngwiePhoenix** [comment]
Bump! o.o

I have played around with PurifyCSS and I am getting unbelivable results. I would really like to use it with this plugin since the original PurifyCSS plugin doesn't cut it...

**Comment by kisenka** [comment]
+1

**Comment by micky2be** [comment]
+1
I really need to be able to postprocess the output

**Comment by oeeq** [comment]
+1
I don't see any way to pass modules into postcss-loader when using extract-text. Would be very usefull.

**Comment by mjpearson** [comment]
+1 I need to be able to append to the output

**Comment by kisenka** [comment]
How about [this](https://github.com/webpack/extract-text-webpack-plugin/issues/167#issuecomment-256752174)?

**Comment by fedeoo** [comment]
+1

**Comment by bebraw** [comment]
#167 covers how to achieve post-processing.

**Comment by derwaldgeist** [comment]
I'm also trying to postprocess a file. Have looked at #167, but still can't figure out how to do that. The link to the ExtractSVGPlugin is dead, and I couldn't find the right hint in the purify-webpack plugin.
