### ISSUE TITLE
Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by halt-hammerzeit** [webpack-contrib/extract-text-webpack-plugin#91]
```
ERROR in ./client/styles/style.scss
Module build failed: ModuleParseError: Module parse failed: G:\work\cinema\client\styles\style.scss Line 1: Unexpected t
oken ILLEGAL
You may need an appropriate loader to handle this file type.
| @font-face {
|       font-family: 'PT Sans';
|       font-weight: normal;
```

I was having this error when in webpack configuration I had `loaders: [ExtractTextPlugin.extract(...)]` and didn't have this error when it was temporarily changed to `loader: ExtractTextPlugin.extract(...)`.
Seems to be a bug: loaders[] and loader should be interchangeable.

**Comment by tupy** [comment]
I got the same error. Please, fix this!

**Comment by caesarsol** [comment]
same here!

**Comment by kevindqc** [comment]
Had the same problem.

Was using the new 
```
module: {
   rules: {
      {
         test: ...,
         use: ...
      }
   }
}
``` 

syntax from webpack 2 instead of 

```
module: {
   loaders: {
      {
         test: ...,
         loader: ...
      }
   }
}
```

So I had, inside my rules:

```
{
    test: /\.css$/,
    use: ExtractTextPlugin.extract({fallbackLoader: 'style-loader', loader: 'css-loader'})
}

```


I changed `use` to `loader` and now I don't get the unexpected tokens
```
{
    test: /\.css$/,
    loader: ExtractTextPlugin.extract({fallbackLoader: 'style-loader', loader: 'css-loader'})
}
```

**Comment by jussch** [comment]
Thanks @kevindqc! Changing `use` to `loader` worked for me.

**Comment by oieduardorabelo** [comment]
many thanks @kevindqc! Changing from `use` to `loader` fixed my CI.

is it a bug?

**Comment by bebraw** [comment]
`use` is supported since rc0. In fact, using `loader` is illegal now.
