### ISSUE TITLE
Give a nice warning if options isn't an object

### ISSUE THREAD

**Issue by bebraw** [webpack-contrib/extract-text-webpack-plugin#94]
It would be cool to give nice warnings if people are trying to use the plugin wrong. Example:

``` javascript
ExtractTextPlugin.extract('style','css','less')
```

yields a strange `Object.keys` error.

**Comment by WishCow** [comment]
What's the correct usage? Because what you wrote is exactly what the README says.

**Comment by bebraw** [comment]
The docs give a signature such as

> ExtractTextPlugin.extract([notExtractLoader], loader, [options])

Apparently doing

> ExtractTextPlugin.extract('style','css!less')

was the right thing as that maps to `loader`.

I probably should set up a test case for this. :+1:

**Comment by bebraw** [comment]
Here's [the example](https://github.com/bebraw/extract-text-warning) as promised.

1. `npm i`
2. `npm run gh-pages` -> Nasty error

I would probably change the interface to accept an arbitrary amount of strings (optional object at the end). This is backwards compatible. Better UX.

**Comment by legend80s** [comment]
Has someone made a pull request？0.8.2 still has this problem，and it took me much effort to find out the reason

**Comment by bebraw** [comment]
This should be fixed now.
