### ISSUE TITLE
Support exclude

### ISSUE THREAD

**Issue by beckend** [webpack-contrib/extract-text-webpack-plugin#95]
I got this as a result from the compiler when using extract plugin:

```
./~/css-loader?minimize!./~/autoprefixer-loader?{browsers:["last 2 versions", "ie >= 8", "android >= 2.3", "opera >= 12", "> 5%"]}!./~/stylus-loader!./src/app/app.l.styl
```

the loader is:

```
test: /\.(styl)(\?.*)?$/i,
exclude: /\.l\.(styl)(\?.*)?$/i,
loader: '/pathToProject/node_modules/extract-text-webpack-plugin/loader.js?{"remove":true}!css?minimize!autoprefixer?{browsers:["last 2 versions", "ie >= 8", "android >= 2.3", "opera >= 12", "> 5%"]}!stylus'
```

Which states that the ".l.style" files should be excluded, and is properly excluded when not using extract plugin.

Using without extract plugin yields:

```
./~/css-loader?modules&localIdentName=[name]__[local]___[hash:base64:5]!./~/autoprefixer-loader?{browsers:["last 2 versions", "ie >= 8", "android >= 2.3", "opera >= 12", "> 5%"]}!./~/stylus-loader!./src/app/app.l.styl
```

In both cases, this loader is present:

```
test: /\.l\.(styl)(\?.*)?$/i,
loader: '/pathToProject/node_modules/extract-text-webpack-plugin/loader.js?{"remove":true}!css?minimize!autoprefixer?{browsers:["last 2 versions", "ie >= 8", "android >= 2.3", "opera >= 12", "> 5%"]}!stylus'
```

This is a great way of using a global scoped css file and a local one,

**Comment by beckend** [comment]
I manually solved it by generating the correct loader string, so it seems like the extract function might have parsing issues.

**Comment by schickling** [comment]
Any progress on this?

**Comment by bebraw** [comment]
Can someone try with webpack 2?

**Comment by beckend** [comment]
Since it was my issue, and i deem that this is no longer valid for the latest version as of writing - `2.0.0-rc.3`. Since this version does not really care about exclude since in webpack 2 has the new `loader.use` and it's working fine with exclude.
