### ISSUE TITLE
Log Spam

### ISSUE THREAD

**Issue by igl** [webpack-contrib/extract-text-webpack-plugin#97]
For every file this plugin extracts, it prints a meaningless message into the stdout.
I just started on a project with this integrated and i already have a wall of:

```
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
...
```

 Is there a way to silence this plugin?

**Comment by matt-dease** [comment]
From #35, this worked for me:
``` javascript
module.exports = {
    stats: { children: false },
   // other settings
}
```

**Comment by adamvleggett** [comment]
Please reopen this bug. It is not adequate to just hide stats from all children. If a config is sent as an array, there will be no output at all then.

**Comment by vdh** [comment]
@d3viant0ne Hey, this *is* still a bug. As already mentioned, the workaround is not adequate.

**Comment by le0nik** [comment]
Here's a simple webpack plugin I use that does the job of cleaning up the log spam. But I agree that it should be configurable within `extract-text-webpack-plugin` itself.

```js
class CleanUpStatsPlugin {
  /**
   * @param {Object} child
   * @param {string} child.name
   * @returns {boolean}
   */
  shouldPickStatChild(child) {
    return child.name.indexOf('extract-text-webpack-plugin') !== 0;
  }

  apply(compiler) {
    compiler.plugin('done', stats => {
      if (Array.isArray(stats.compilation.children)) {
        stats.compilation.children = stats.compilation.children.filter(child => this.shouldPickStatChild(child));
      }
    });
  }
}

module.exports = CleanUpStatsPlugin;
```

**Comment by antialias** [comment]
@le0nik I hope you don't mind that I published your code in an npm package: https://www.npmjs.com/package/clean-up-extract-text-plugin-output

**Comment by pietrofxq** [comment]
You can also call `webpack` with the `--hide-modules` flag.

**Comment by und3fined** [comment]
Please set `stats` to `devServer`.
Not set to `webpack.config.js`

Example:

```
devServer: {
        host: '0.0.0.0',
        port: config.webpack.HMR_PORT,

        // respond to 404s with index.html
        historyApiFallback: true,

        // enable HMR on the server
        hot: true,
        publicPath: '/',
        noInfo: false,
        inline: true,
        disableHostCheck: true,
        stats: {
            children: false,
            chunks: false,
            chunkModules: false,
            modules: false,
            reasons: false,
            usedExports: false,
        },
    },
```
