### ISSUE TITLE
Multiple extractors

### ISSUE THREAD

**Issue by malykhinvi** [webpack-contrib/extract-text-webpack-plugin#99]
It is mentioned in the Readme that 

> There is also a extract function on the instance. You should use this if you have more than one ExtractTextPlugin.

But I didn't found any example. I've tried to do the following, but plugin generates only one file.

``` javascript
var vendorJSextractor  = new ExtractTextPlugin('vendor-js.js'),
    vendorCSSextractor = new ExtractTextPlugin('vendor-css.css');
```

Then in config use instances' `.extract` method.

``` javascript
module: {
            loaders: [{
                test: /app\/external\/\.*.js$/,
                loader: vendorJSextractor.extract('raw')
            }, {
                test: /\.less$/,
                loader: vendorCSSextractor.extract('style-loader', 'css-loader!less-loader')
            }, {
                test: /\.css$/,
                loader: vendorCSSextractor.extract('style-loader', 'raw-loader')
            }]
        },
```

And then add both plugins:

``` javascript
 plugins: [
            vendorCSSextractor,
            vendorJSextractor
]
```

The idea is to concat all **minified** vendor files into one, and add this file to the body via `<script>` tag.

**Comment by Daniel15** [comment]
You can use code splitting to pull vendor files into a separate script file: http://webpack.github.io/docs/code-splitting.html#split-app-and-vendor-code

**Comment by bebraw** [comment]
Closing as this was answered. Please use SO for support. 👍
